xLib: xl::debug::ErrorReport Class Reference
xl::debug::ErrorReport Class Reference final
debug report
#include "ErrorReport.h"
Inherits xl::interface_::IStr.
Public Types
enum class Type {
Unknown ,
Stdout ,
Log ,
StdoutLog ,
Exception
}
type
Public Member Functions
Type type () const
report type
ctors, dtor
ErrorReport (cType type, culong_t nativeError, const SourceInfo &sourceInfo, std::ctstring_t &stackTrace, std::ctstring_t &comment)
ErrorReport (culong_t nativeError, const SourceInfo &sourceInfo, std::ctstring_t &stackTrace, std::ctstring_t &comment)
virtual ~ErrorReport ()=default
xNO_DEFAULT_CTOR (ErrorReport)
xNO_COPY_ASSIGN (ErrorReport)
Overrides
std::tstring_t str () const final
report message
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
Detailed Description
debug report
Member Enumeration Documentation
Type
enum class xl::debug::ErrorReport::Type strong
type
Enumerator
Unknown
unknown
Stdout
to std::cout
Log
to log
StdoutLog
to std::cout and log
Exception
to exception
    {
        Unknown,   ///< unknown
        Stdout,    ///< to std::cout
        Log,       ///< to log
        StdoutLog, ///< to std::cout and log
        Exception  ///< to exception
    };
Constructor & Destructor Documentation
ErrorReport() [1/2]
xl::debug::ErrorReport::ErrorReport (cType type, culong_t nativeError, const SourceInfo & sourceInfo, std::ctstring_t & stackTrace, std::ctstring_t & comment)
  :
    _type       {a_type},
    _nativeError{a_nativeError},
    _sourceInfo (a_sourceInfo),
    _stackTrace (a_stackTrace),
    _comment    (a_comment)
{
    _program        = Path::exe().brief(::reportWidthMax).toUnix(false).str();
#if   xENV_WIN
    _processId      = ::GetCurrentProcessId();
#elif xENV_UNIX
    _processId      = static_cast<ulong_t>( ::getpid() );
#endif
    _threadId       = (ulong_t)ThreadCurrent::id();
    _nativeErrorStr = NativeError(_nativeError).str();
    _currentDate    = DateTime::currentLocal().format(xT("%Y-%m-%d %H:%M:%S"));
}
References xl::fs::Path::brief(), xl::core::DateTime::currentLocal(), xl::fs::Path::exe(), xl::core::DateTime::format(), xl::sync::ThreadCurrent::id(), xl::interface_::IError< CodeT >::str(), xl::fs::Path::str(), xl::fs::Path::toUnix(), and xT.
ErrorReport() [2/2]
xl::debug::ErrorReport::ErrorReport (culong_t nativeError, const SourceInfo & sourceInfo, std::ctstring_t & stackTrace, std::ctstring_t & comment)
  :
    ErrorReport(Type::StdoutLog, a_nativeError, a_sourceInfo, a_stackTrace, a_comment)
{
}
~ErrorReport()
virtual xl::debug::ErrorReport::~ErrorReport () virtual default
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::debug::ErrorReport::xNO_DEFAULT_CTOR (ErrorReport)
xNO_COPY_ASSIGN()
xl::debug::ErrorReport::xNO_COPY_ASSIGN (ErrorReport)
str()
std::tstring_t xl::debug::ErrorReport::str () const final virtual
report message
Implements xl::interface_::IStr.
{
    switch (_type) {
    case Type::Stdout:
    case Type::Log:
    case Type::StdoutLog:
    case Type::Exception:
        return _initPlain();
        break;
    case Type::Unknown:
        break;
    }
    return {};
}
References Exception, Log, Stdout, StdoutLog, and Unknown.
Referenced by xl::debug::Debugger::reportMake().
type()
ErrorReport::Type xl::debug::ErrorReport::type () const
report type
{
    return _type;
}
Referenced by xl::debug::Debugger::reportMake().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Debug/ErrorReport.h
/home/runner/work/xLib/xLib/Include/xLib/Debug/ErrorReport.cpp