xLib: xl::fs::Dir Class Reference
xl::fs::Dir Class Reference final
directory
#include "Dir.h"
Inherits xl::interface_::IPrinter< std::tostream_t >, and xl::interface_::IStrConstRef.
Public Member Functions
bool_t isExists () const
check for existence
bool_t isEmpty (std::ctstring_t &shellFilter=Const::maskAll()) const
is empty
bool_t isRoot () const
is root
void_t create () const
create
void_t pathCreate () const
creation of all directories that not exists in path
void_t copy (std::ctstring_t &dirPathTo, cbool_t failIfExists) const
copy
void_t move (std::ctstring_t &dirPathTo, cbool_t failIfExists) const
move
void_t createSymlink (std::ctstring_t &dirPathTo) const
create symlink
void_t remove () const
deletion dir which empty
void_t tryRemove (std::csize_t attempts, culong_t timeoutMsec) const
try deleting, max 100 attempts
void_t pathClear () const
deletion all content of dir
void_t pathDelete () const
deletion dir find all content of it
Overrides
void_t print (std::tostream_t &stream) const final
std::ctstring_t & str () const final
Get as string.
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
Public Member Functions inherited from xl::interface_::IStrConstRef
IStrConstRef ()=default
virtual ~IStrConstRef ()=default
Static Public Member Functions
static void_t setCurrent (std::ctstring_t &dirPath)
set current
ctors, dtor
Dir (std::ctstring_t &dirPath)
virtual ~Dir ()=default
xNO_DEFAULT_CONSTRUCT (Dir)
xNO_COPY_ASSIGN (Dir)
static Dir current ()
static Dir temp ()
Detailed Description
directory
Constructor & Destructor Documentation
Dir()
xl::fs::Dir::Dir (std::ctstring_t & dirPath) explicit
  :
    _dirPath(a_dirPath)
{
    xTEST(!a_dirPath.empty());
}
References xTEST.
~Dir()
virtual xl::fs::Dir::~Dir () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::Dir::xNO_DEFAULT_CONSTRUCT (Dir)
xNO_COPY_ASSIGN()
xl::fs::Dir::xNO_COPY_ASSIGN (Dir)
current()
Dir xl::fs::Dir::current () static
{
    std::ctstring_t &currentDir = _current_impl();
    xTEST(Dir(currentDir).isExists());
    return Dir(currentDir);
}
References isExists(), and xTEST.
Referenced by xl::package::Application::dirPath(), and xl::package::GitClient::trackedFiles().
temp()
Dir xl::fs::Dir::temp () static
{
    std::ctstring_t &tempDir = _temp_impl();
    xTEST(Dir(tempDir).isExists());
    return Dir(tempDir);
}
References isExists(), and xTEST.
print()
void_t xl::fs::Dir::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
str()
std::ctstring_t & xl::fs::Dir::str () const final virtual
Get as string.
Implements xl::interface_::IStrConstRef.
{
    return _dirPath;
}
Referenced by xl::package::Application::dirPath(), xl::fs::Backup::fileExec(), xl::test::Unit::run(), and xl::package::GitClient::trackedFiles().
isExists()
bool_t xl::fs::Dir::isExists () const
check for existence
{
    xCHECK_RET(_dirPath.empty(), false);
    FileType type(_dirPath);
    xCHECK_RET(type.get() == static_cast<FileType::types_t>(FileType::Type::Unknown), false);
#if xENV_UNIX
    if (type.get() == static_cast<FileType::types_t>(FileType::Type::SymbolicLink)) {
        std::ctstring_t &symLinkPathTo = Path::readSymLink(_dirPath);
        FileType symLinkType(symLinkPathTo);
        bool_t bRv = symLinkType.isExists(FileType::Type::Directory);
        xCHECK_RET(!bRv, false);
        return true;
    }
#endif
    bool_t bRv = type.isExists(FileType::Type::Directory);
    xCHECK_RET(!bRv, false);
    return true;
}
References xl::fs::FileType::Directory, xl::fs::FileType::get(), xl::fs::FileType::isExists(), xl::fs::Path::readSymLink(), xl::fs::FileType::SymbolicLink, xl::fs::FileType::Unknown, and xCHECK_RET.
Referenced by copy(), create(), current(), xl::fs::Backup::fileExec(), move(), pathClear(), pathCreate(), pathDelete(), remove(), xl::fs::Volume::space(), temp(), and tryRemove().
isEmpty()
bool_t xl::fs::Dir::isEmpty (std::ctstring_t & shellFilter = Const::maskAll()) const
is empty
{
    xTEST(!a_shellFilter.empty());
    bool_t bRv {true};
    Finder finder(_dirPath, a_shellFilter);
    for ( ; ; ) {
        xCHECK_DO(!finder.moveNext(), break);
        xCHECK_DO(finder.entryName() == Const::dot(),  continue);
        xCHECK_DO(finder.entryName() == Const::dot2(), continue);
        bRv = false;
        break;
    }
    return bRv;
}
References xl::core::Const::dot(), xl::core::Const::dot2(), xl::fs::Finder::entryName(), xl::fs::Finder::moveNext(), xCHECK_DO, and xTEST.
Referenced by xl::fs::Volume::isEmpty(), and pathClear().
isRoot()
bool_t xl::fs::Dir::isRoot () const
is root
{
    return _isRoot_impl();
}
create()
void_t xl::fs::Dir::create () const
create
{
    bool_t bRv = isExists();
    xCHECK_DO(bRv, return);
    _create_impl();
    xTEST(isExists());
}
References isExists(), xCHECK_DO, and xTEST.
Referenced by pathCreate().
pathCreate()
void_t xl::fs::Dir::pathCreate () const
creation of all directories that not exists in path
{
    // split dirPath into parts
    std::vec_tstring_t pathParts;
    Path(_dirPath).toNative(false).split(&pathParts);
    // create dirs by steps
    std::tstring_t buildPath;
    for (const auto &it : pathParts) {
        buildPath.append(it).append(Const::slash());
        Dir(buildPath).create();
    }
    xTEST(isExists());
}
References create(), isExists(), xl::core::Const::slash(), xl::fs::Path::split(), xl::fs::Path::toNative(), and xTEST.
Referenced by copy(), xl::fs::DirTemp::create(), xl::package::Archive::dirCompress(), xl::package::Application::dirsCreate(), xl::package::Archive::fileCompress(), xl::fs::Backup::fileExec(), xl::package::Archive::fileUncompress(), and xl::fs::FileIO::open().
copy()
void_t xl::fs::Dir::copy (std::ctstring_t & dirPathTo, cbool_t failIfExists) const
copy
{
    xTEST(isExists());
    xTEST(!a_dirPathTo.empty());
    xTEST_NA(a_failIfExists);
    // sets attribute "normal"
    bool_t bRv = Dir(a_dirPathTo).isExists();
    if (bRv) {
        FileType(a_dirPathTo).clear();
    }
    FileType(_dirPath).clear();
    // get lists of files
    std::vec_tstring_t filePaths;
    filePaths.clear();
    Finder::files(_dirPath, Const::maskAll(), true, &filePaths);
    // copy
    xFOR_EACH_R_CONST(std::vec_tstring_t, it, filePaths) {
        std::tstring_t filePathTo = *it;
        size_t posBegin = filePathTo.find(_dirPath);
        xTEST_DIFF(posBegin, std::tstring_t::npos);
        filePathTo.replace(posBegin, posBegin + _dirPath.size(), a_dirPathTo);
        Dir( Path(filePathTo).dir() ).pathCreate();
        File(*it).copy(filePathTo, a_failIfExists);
    }
    // TODO: [skynowa] rollback copy
}
References xl::fs::FileType::clear(), xl::fs::File::copy(), xl::fs::Finder::files(), isExists(), xl::core::Const::maskAll(), pathCreate(), xFOR_EACH_R_CONST, xTEST, xTEST_DIFF, and xTEST_NA.
Referenced by move().
move()
void_t xl::fs::Dir::move (std::ctstring_t & dirPathTo, cbool_t failIfExists) const
move
{
    xTEST(isExists());
    xTEST(!a_dirPathTo.empty());
    xTEST_NA(a_failIfExists);
    Dir dir(_dirPath);
    dir.copy(a_dirPathTo, a_failIfExists);
    dir.pathDelete();
}
References copy(), isExists(), pathDelete(), xTEST, and xTEST_NA.
createSymlink()
void_t xl::fs::Dir::createSymlink (std::ctstring_t & dirPathTo) const
create symlink
{
    _createSymlink_impl(a_dirPathTo);
}
remove()
void_t xl::fs::Dir::remove () const
deletion dir which empty
{
    bool_t bRv = isExists();
    xCHECK_DO(!bRv, return);
    FileType(_dirPath).clear();
    _remove_impl();
    xTEST(!isExists());
}
References xl::fs::FileType::clear(), isExists(), xCHECK_DO, and xTEST.
Referenced by pathClear(), and pathDelete().
tryRemove()
void_t xl::fs::Dir::tryRemove (std::csize_t attempts, culong_t timeoutMsec) const
try deleting, max 100 attempts
{
    xTEST_DIFF(a_attempts, size_t(0U));
    std::csize_t maxAttempts  = 100;  // MAGIC_NUMBER: maxAttempts
    std::csize_t realAttempts = (maxAttempts < a_attempts) ? maxAttempts : a_attempts;
    for (size_t i = 0; i < realAttempts; ++ i) {
        bool_t bRv = isExists();
        xCHECK_DO(!bRv, break);
        FileType(_dirPath).clear();
        bRv = _tryRemove_impl();
        xCHECK_DO(bRv, break);
        Thread::currentSleep(a_timeoutMsec);
    }
    xTEST(!isExists());
}
References xl::fs::FileType::clear(), xl::sync::Thread::currentSleep(), isExists(), xCHECK_DO, xTEST, and xTEST_DIFF.
pathClear()
void_t xl::fs::Dir::pathClear () const
deletion all content of dir
{
    xTEST(isExists());
    // checks
    bool_t bRv = isEmpty(Const::maskAll());
    xCHECK_DO(bRv, return);
    // delete files
    {
        std::vec_tstring_t filePaths;
        filePaths.clear();
        Finder::files(_dirPath, Const::maskAll(), true, &filePaths);
        xFOR_EACH_R(std::vec_tstring_t, it, filePaths) {
            File(*it).remove();
        }
    }
    // delete subdirs
    {
        std::vec_tstring_t dirPaths;
        dirPaths.clear();
        Finder::dirs(_dirPath, Const::maskAll(), true, &dirPaths);
        xFOR_EACH_R(std::vec_tstring_t, it, dirPaths) {
            Dir(*it).remove();
        }
    }
    xTEST(isEmpty());
}
References xl::fs::Finder::dirs(), xl::fs::Finder::files(), isEmpty(), isExists(), xl::core::Const::maskAll(), remove(), xl::fs::File::remove(), xCHECK_DO, xFOR_EACH_R, and xTEST.
Referenced by pathDelete().
pathDelete()
void_t xl::fs::Dir::pathDelete () const
deletion dir find all content of it
{
    bool_t bRv = isExists();
    xCHECK_DO(!bRv, return);
    pathClear();
    remove();
    xTEST(!isExists());
}
References isExists(), pathClear(), remove(), xCHECK_DO, and xTEST.
Referenced by xl::package::Archive::dirCompress(), xl::package::Archive::fileCompress(), move(), and xl::fs::DirTemp::~DirTemp().
setCurrent()
void_t xl::fs::Dir::setCurrent (std::ctstring_t & dirPath) static
set current
{
    _setCurrent_impl(a_dirPath);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Dir.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Dir.cpp