xLib: xl::package::curl::SmtpClient Class Reference
xl::package::curl::SmtpClient Class Reference
SMTP client.
#include "SmtpClient.h"
Inherits xl::package::curl::Client.
Public Member Functions
void_t request ()
send request
ctors, dtor
SmtpClient (cbool_t isDebug, std::ctstring_t &url, std::ctstring_t &caPath, std::ctstring_t &userName, std::ctstring_t &password, std::ctstring_t &from, std::ctstring_t &to, std::ctstring_t &cc, std::ctstring_t &subject, std::ctstring_t &body)
virtual ~SmtpClient ()=default
xNO_DEFAULT_CONSTRUCT (SmtpClient)
xNO_COPY_ASSIGN (SmtpClient)
Public Member Functions inherited from xl::package::curl::Client
HandleCurl & get ()
void_t reset ()
template<typename T >
void_t setOption (cCURLoption option, const T &value)
void_t perform ()
void_t pause (cint_t bitMask)
template<typename T >
void_t info (cCURLINFO info, const T &value)
void_t receive (void_t *buff, std::csize_t buffSize, std::size_t *items)
void_t send (cvoid_t *buff, std::csize_t buffSize, std::size_t *items)
std::tstring_t escape (std::ctstring_t &str) const
std::tstring_t unescape (std::ctstring_t &str) const
Client (cbool_t isDebug)
virtual ~Client ()
xNO_DEFAULT_CONSTRUCT (Client)
xNO_COPY_ASSIGN (Client)
Additional Inherited Members
Static Public Member Functions inherited from xl::package::curl::Client
static std::tstring_t escapeUrl (std::ctstring_t &str)
static std::tstring_t unescapeUrl (std::ctstring_t &str)
static std::size_t onWriteHeader (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onWriteData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onReadData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
Protected Types inherited from xl::package::curl::Client
using slist_unique_ptr_t = std::unique_ptr< curl_slist, SlistDeleter >
Protected Attributes inherited from xl::package::curl::Client
cbool_t _isDebug {}
HandleCurl _handle
ReadData _readData {}
slist_unique_ptr_t _headers
Detailed Description
SMTP client.
Constructor & Destructor Documentation
SmtpClient()
xl::package::curl::SmtpClient::SmtpClient (cbool_t isDebug, std::ctstring_t & url, std::ctstring_t & caPath, std::ctstring_t & userName, std::ctstring_t & password, std::ctstring_t & from, std::ctstring_t & to, std::ctstring_t & cc, std::ctstring_t & subject, std::ctstring_t & body)
  :
    Client   (a_isDebug),
    _url     {a_url},
    _caPath  {a_caPath},
    _userName{a_userName},
    _password{a_password},
    _from    {a_from},
    _to      {a_to},
    _cc      {a_cc},
    _subject {a_subject},
    _body    {a_body}
{
}
~SmtpClient()
virtual xl::package::curl::SmtpClient::~SmtpClient () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::curl::SmtpClient::xNO_DEFAULT_CONSTRUCT (SmtpClient)
xNO_COPY_ASSIGN()
xl::package::curl::SmtpClient::xNO_COPY_ASSIGN (SmtpClient)
request()
void_t xl::package::curl::SmtpClient::request ()
send request
This is the URL for your mailserver. Note the use of port 587 here, instead of the normal SMTP port (25). Port 587 is commonly used for secure mail submission (see RFC4403), but you should use whatever matches your server configuration.
In this example, we'll start with a plain text connection, and upgrade to Transport Layer Security (TLS) using the STARTTLS command. Be careful of using CURLUSESSL_TRY here, because if TLS upgrade fails, the transfer will continue anyway - see the security discussion in the libcurl tutorial for more details.
If your server doesn't have a valid certificate, then you can disable part of the Transport Layer Security protection by setting the CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST options to 0 (false). curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L); curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
That is, in general, a bad idea. It is still better than sending your authentication details in plain text though. Instead, you should get the issuer certificate (or the host certificate if the certificate is self-signed) and add it to the set of certificates that are known to libcurl using CURLOPT_CAINFO and/or CURLOPT_CAPATH. See docs/SSLCERTS for more information.
Set username and password
Note that this option isn't strictly required, omitting it will result in libcurl sending the MAIL FROM command with empty sender data. All autoresponses should have an empty reverse-path, and should be directed to the address in the reverse-path which triggered them. Otherwise, they could cause an endless loop. See RFC 5321 Section 4.5.5 for more details.
Add two recipients, in this particular case they correspond to the To: and Cc: addressees in the header, but they could be any kind of recipient
{
#if 0
    Cout()
        << xTRACE_VAR(_url)      << "\n"
        << xTRACE_VAR(_caPath)   << "\n"
        << xTRACE_VAR(_userName) << "\n"
        << xTRACE_VAR(_password) << "\n"
        << xTRACE_VAR(_from)     << "\n"
        << xTRACE_VAR(_to)       << "\n"
        << xTRACE_VAR(_cc)       << "\n"
        << xTRACE_VAR(_subject)  << "\n"
        << xTRACE_VAR(_body);
#endif
    setOption(CURLOPT_PROTOCOLS, CURLPROTO_SMTP);
   /**
    * This is the URL for your mailserver. Note the use of port 587 here,
    * instead of the normal SMTP port (25). Port 587 is commonly used for
    * secure mail submission (see RFC4403), but you should use whatever
    * matches your server configuration.
    */
    setOption(CURLOPT_URL, _url.c_str());
   /**
    * In this example, we'll start with a plain text connection, and upgrade
    * to Transport Layer Security (TLS) using the STARTTLS command. Be careful
    * of using CURLUSESSL_TRY here, because if TLS upgrade fails, the transfer
    * will continue anyway - see the security discussion in the libcurl
    * tutorial for more details.
    */
    setOption(CURLOPT_USE_SSL, static_cast<long_t>(CURLUSESSL_ALL));
   /**
    * If your server doesn't have a valid certificate, then you can disable
    * part of the Transport Layer Security protection by setting the
    * CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST options to 0 (false).
    *   curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
    *   curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
    *
    * That is, in general, a bad idea. It is still better than sending your
    * authentication details in plain text though.  Instead, you should get
    * the issuer certificate (or the host certificate if the certificate is
    * self-signed) and add it to the set of certificates that are known to
    * libcurl using CURLOPT_CAINFO and/or CURLOPT_CAPATH. See docs/SSLCERTS
    * for more information.
    */
    if ( !_caPath.empty() ) {
        setOption(CURLOPT_CAINFO, _caPath.c_str());
    }
   /**
    * Set username and password
    */
    setOption(CURLOPT_USERNAME, _userName.c_str());
    setOption(CURLOPT_PASSWORD, _password.c_str());
   /**
    * Note that this option isn't strictly required, omitting it will result
    * in libcurl sending the MAIL FROM command with empty sender data. All
    * autoresponses should have an empty reverse-path, and should be directed
    * to the address in the reverse-path which triggered them. Otherwise,
    * they could cause an endless loop. See RFC 5321 Section 4.5.5 for more
    * details.
    */
    setOption(CURLOPT_MAIL_FROM, _from.c_str());
    // _recipients
    {
       /**
        * Add two recipients, in this particular case they correspond to the
        * To: and Cc: addressees in the header, but they could be any kind of recipient
        */
        struct curl_slist *recipients {};
        recipients = ::curl_slist_append(recipients, _to.c_str());
        recipients = ::curl_slist_append(recipients, _cc.c_str());
        // [out]
        _recipients.reset(recipients);
    }
    setOption(CURLOPT_MAIL_RCPT, _recipients.get());
    setOption(CURLOPT_UPLOAD, 1L);
    std::ctstring_t mimeMsg = Format::str(
        "To: {}\r\n"
        "From: {}\r\n"
        "Subject: {}\r\n"
        "\r\n"
        "{}\r\n"
        "\r\n",
        _to,
        _from,
        _subject,
        _body);
    Cout()
        << "mimeMsg:\n"
        << "--------------------------------------------------\n"
        << mimeMsg
        << "--------------------------------------------------\n";
    // Upload data
    {
        _readData.buff = mimeMsg;
        setOption(CURLOPT_READDATA,     &_readData);
        setOption(CURLOPT_READFUNCTION,  onReadData);
    }
    perform();
    int_t responseCode {};
    info(CURLINFO_RESPONSE_CODE, &responseCode);
    xTEST(Algos::isInBounds(responseCode, 200, 299));
}
References xl::package::curl::Client::_readData, xl::package::curl::Client::ReadData::buff, xl::package::curl::Client::info(), xl::algos::Algos::isInBounds(), xl::package::curl::Client::onReadData(), xl::package::curl::Client::perform(), xl::package::curl::Client::setOption(), xl::core::FormatT< StreamT >::str(), xTEST, and xTRACE_VAR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/SmtpClient.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/SmtpClient.cpp