xLib: xl::core::OStream Class Reference
xl::core::OStream Class Reference
print string
#include "OStream.h"
Inherits xl::interface_::IStr.
Inherited by xl::core::Cout.
Classes
struct TuplePrint
Public Member Functions
void_t str (std::ctstring_t &value)
void_t clear ()
OStream & operator<< (const bool value)
OStream & operator<< (const char value)
OStream & operator<< (const wchar_t value)
OStream & operator<< (const unsigned char value)
OStream & operator<< (const short value)
OStream & operator<< (const unsigned short value)
OStream & operator<< (const int value)
OStream & operator<< (const unsigned int value)
OStream & operator<< (const long value)
OStream & operator<< (const unsigned long value)
OStream & operator<< (const long long value)
OStream & operator<< (const unsigned long long value)
OStream & operator<< (const float value)
OStream & operator<< (const double value)
OStream & operator<< (const long double value)
OStream & operator<< (const void *value)
OStream & operator<< (const char *value)
OStream & operator<< (const wchar_t *value)
OStream & operator<< (const std::wstring &value)
OStream & operator<< (const std::string &value)
OStream & operator<< (const std::ustring_t &value)
template<typename T1 , typename T2 >
OStream & operator<< (const std::pair< T1, T2 > &value)
template<typename T >
OStream & operator<< (const std::vector< T > &value)
template<typename T >
OStream & operator<< (const std::list< T > &value)
template<typename T >
OStream & operator<< (const std::set< T > &value)
template<typename T >
OStream & operator<< (const std::multiset< T > &value)
template<typename T >
OStream & operator<< (const std::deque< T > &value)
template<typename T >
OStream & operator<< (const std::queue< T > &value)
template<typename T >
OStream & operator<< (const std::priority_queue< T > &value)
template<typename T >
OStream & operator<< (const std::stack< T > &value)
template<typename T1 , typename T2 >
OStream & operator<< (const std::map< T1, T2 > &value)
template<typename T1 , typename T2 >
OStream & operator<< (const std::multimap< T1, T2 > &value)
OStream & operator<< (const std::nullptr_t value)
template<typename T , std::size_t N>
OStream & operator<< (const std::array< T, N > &value)
template<typename T >
OStream & operator<< (const std::forward_list< T > &value)
template<typename T1 , typename T2 >
OStream & operator<< (const std::unordered_map< T1, T2 > &value)
template<typename T1 , typename T2 >
OStream & operator<< (const std::unordered_multimap< T1, T2 > &value)
template<typename T >
OStream & operator<< (const std::unordered_set< T > &value)
template<typename T >
OStream & operator<< (const std::unordered_multiset< T > &value)
template<typename... Args>
OStream & operator<< (const std::tuple< Args... > &value)
OStream & operator<< (std::tostream_t &(*a_os)(std::tostream_t &))
print std::endl
template<typename T >
OStream & operator<< (const Float< T > &value)
ctors, dtor
OStream ()=default
virtual ~OStream ()=default
xNO_COPY_ASSIGN (OStream)
Overrides
std::tstring_t str () const final
Get as string.
LibC
OStream & operator<< (const std::tm &value)
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
Protected Member Functions
template<typename T >
void_t _printContainerTitle (const T &a_value)
template<typename T >
void_t _printValue (const T &value)
template<typename IteratorT >
void_t _printString (IteratorT first, IteratorT last)
template<typename IteratorT >
void_t _printRange (IteratorT first, IteratorT last)
template<typename IteratorT >
void_t _printRangeMap (IteratorT first, IteratorT last)
template<typename T >
void_t _printContainer (const T &value)
template<typename T >
void_t _printMap (const T &value)
template<typename T >
void_t _printFloat (const T value)
Static Protected Member Functions
static std::ctstring_t & _bracketOpen ()
open bracket
static std::ctstring_t & _bracketClose ()
close bracket
static std::ctstring_t & _delimiter ()
_delimiter
Protected Attributes
std::tstringstream_t _os
Detailed Description
print string
Constructor & Destructor Documentation
OStream()
xl::core::OStream::OStream () default
~OStream()
virtual xl::core::OStream::~OStream () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::core::OStream::xNO_COPY_ASSIGN (OStream)
str() [1/2]
std::tstring_t xl::core::OStream::str () const final virtual
Get as string.
Implements xl::interface_::IStr.
{
    return _os.str();
}
References _os.
Referenced by xl::core::Cout::operator<<().
str() [2/2]
void_t xl::core::OStream::str (std::ctstring_t & value)
{
    _os.str(a_value);
}
References _os.
clear()
void_t xl::core::OStream::clear ()
{
    _os.clear();
}
References _os.
Referenced by xl::core::Cout::operator<<().
operator<<() [1/43]
OStream & xl::core::OStream::operator<< (const bool a_value)
Parameters
a_value value
{
    _os << (a_value ? xT("true") : xT("false"));
    return *this;
}
References _os, and xT.
Referenced by _printValue(), and xl::core::Cout::operator<<().
operator<<() [2/43]
OStream & xl::core::OStream::operator<< (const char a_value)
Parameters
a_value value
{
#if xANSI
    _os << a_value;
#else
    _os << static_cast<wchar_t>(a_value);
#endif
    return *this;
}
References _os.
operator<<() [3/43]
OStream & xl::core::OStream::operator<< (const wchar_t a_value)
Parameters
a_value value
{
    if ( ::iswprint(  static_cast<wint_t>(a_value) ) ) {
        _os << static_cast<tchar_t>(a_value);
    } else {
        _os << CharW(a_value).symbol();
    }
    return *this;
}
References _os.
operator<<() [4/43]
OStream & xl::core::OStream::operator<< (const unsigned char a_value)
Parameters
a_value value
{
    if ( ::isprint(a_value) ) {
        _os << a_value;
    } else {
        _os << CharU(a_value).symbol();
    }
    return *this;
}
References _os.
operator<<() [5/43]
OStream & xl::core::OStream::operator<< (const short a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [6/43]
OStream & xl::core::OStream::operator<< (const unsigned short a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [7/43]
OStream & xl::core::OStream::operator<< (const int a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [8/43]
OStream & xl::core::OStream::operator<< (const unsigned int a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [9/43]
OStream & xl::core::OStream::operator<< (const long a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [10/43]
OStream & xl::core::OStream::operator<< (const unsigned long a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [11/43]
OStream & xl::core::OStream::operator<< (const long long a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [12/43]
OStream & xl::core::OStream::operator<< (const unsigned long long a_value)
Parameters
a_value value
{
    _os << a_value;
    return *this;
}
References _os.
operator<<() [13/43]
OStream & xl::core::OStream::operator<< (const float a_value)
Parameters
a_value value
{
    _printFloat(a_value);
    return *this;
}
References _printFloat().
operator<<() [14/43]
OStream & xl::core::OStream::operator<< (const double a_value)
Parameters
a_value value
{
    _printFloat(a_value);
    return *this;
}
References _printFloat().
operator<<() [15/43]
OStream & xl::core::OStream::operator<< (const long double a_value)
Parameters
a_value value
{
    _printFloat(a_value);
    return *this;
}
References _printFloat().
operator<<() [16/43]
OStream & xl::core::OStream::operator<< (const void * a_value)
Parameters
a_value value
{
    if (a_value == nullptr) {
        _os << xT("null");
    } else {
        _os << a_value;
    }
    return *this;
}
References _os, and xT.
operator<<() [17/43]
OStream & xl::core::OStream::operator<< (const char * a_value)
Parameters
a_value value
{
    if (a_value == nullptr) {
        _os << xT("null");
    } else {
        _os << std::string(a_value);
    }
    return *this;
}
References _os, and xT.
operator<<() [18/43]
OStream & xl::core::OStream::operator<< (const wchar_t * a_value)
Parameters
a_value value
{
    if (a_value == nullptr) {
        _os << xT("null");
    } else {
        _printValue( std::wstring(a_value) );
    }
    return *this;
}
References _os, _printValue(), and xT.
operator<<() [19/43]
OStream & xl::core::OStream::operator<< (const std::wstring & a_value)
Parameters
a_value value
{
    std::tstring_t sRv;
    sRv.reserve( a_value.size() );
    for (size_t i = 0; i < a_value.size(); ++ i) {
        if ( ::iswprint( static_cast<wint_t>(a_value[i])) ) {
            sRv += static_cast<tchar_t>( a_value[i] );
        } else {
            sRv += CharW( a_value[i] ).symbol();
        }
    }
    _os << sRv;
    return *this;
}
References _os.
operator<<() [20/43]
OStream & xl::core::OStream::operator<< (const std::string & a_value)
Parameters
a_value value
{
#if xANSI
    _os << a_value;
#else
    _os << std::wstring(a_value.cbegin(), a_value.cend());
#endif
    return *this;
}
References _os.
operator<<() [21/43]
OStream & xl::core::OStream::operator<< (const std::ustring_t & a_value)
Parameters
a_value value
{
    _printString(a_value.cbegin(), a_value.cend());
    return *this;
}
References _printString().
operator<<() [22/43]
template<typename T1 , typename T2 > OStream & xl::core::OStream::operator<< (const std::pair< T1, T2 > & a_value) inline
Parameters
a_value value
{
    _os << _bracketOpen();
    _printValue(a_value.first);
    _os << _delimiter();
    _printValue(a_value.second);
    _os << _bracketClose();
    return *this;
}
References _bracketClose(), _bracketOpen(), _delimiter(), _os, and _printValue().
operator<<() [23/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::vector< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [24/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::list< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [25/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::set< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [26/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::multiset< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [27/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::deque< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [28/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::queue< T > & a_value) inline
Parameters
a_value value
{
    using const_iterator = const T *;
    const_iterator begin = &a_value.front();
    const_iterator end   = &a_value.back() + 1;
    _printRange(begin, end);
    return *this;
}
References _printRange().
operator<<() [29/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::priority_queue< T > & a_value) inline
Parameters
a_value value
{
    using const_iterator = const T *;
    const_iterator begin = &a_value.top();
    const_iterator end   = &a_value.top() + a_value.size();
    _printRange(begin, end);
    return *this;
}
References _printRange().
operator<<() [30/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::stack< T > & a_value) inline
Parameters
a_value value
{
    using const_iterator = const T *;
    const_iterator begin = &a_value.top() - a_value.size() + 1;
    const_iterator end   = &a_value.top() + 1;
    _printRange(begin, end);
    return *this;
}
References _printRange().
operator<<() [31/43]
template<typename T1 , typename T2 > OStream & xl::core::OStream::operator<< (const std::map< T1, T2 > & a_value) inline
Parameters
a_value value
{
    _printMap(a_value);
    return *this;
}
References _printMap().
operator<<() [32/43]
template<typename T1 , typename T2 > OStream & xl::core::OStream::operator<< (const std::multimap< T1, T2 > & a_value) inline
Parameters
a_value value
{
    _printMap(a_value);
    return *this;
}
References _printMap().
operator<<() [33/43]
OStream & xl::core::OStream::operator<< (const std::nullptr_t a_value)
Parameters
a_value value
{
    xUNUSED(a_value);
    _os << xT("nullptr");
    return *this;
}
References _os, xT, and xUNUSED.
operator<<() [34/43]
template<typename T , std::size_t N> OStream & xl::core::OStream::operator<< (const std::array< T, N > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [35/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::forward_list< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [36/43]
template<typename T1 , typename T2 > OStream & xl::core::OStream::operator<< (const std::unordered_map< T1, T2 > & a_value) inline
Parameters
a_value value
{
    _printMap(a_value);
    return *this;
}
References _printMap().
operator<<() [37/43]
template<typename T1 , typename T2 > OStream & xl::core::OStream::operator<< (const std::unordered_multimap< T1, T2 > & a_value) inline
Parameters
a_value value
{
    _printMap(a_value);
    return *this;
}
References _printMap().
operator<<() [38/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::unordered_set< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [39/43]
template<typename T > OStream & xl::core::OStream::operator<< (const std::unordered_multiset< T > & a_value) inline
Parameters
a_value value
{
    _printContainer(a_value);
    return *this;
}
References _printContainer().
operator<<() [40/43]
template<typename... Args> OStream & xl::core::OStream::operator<< (const std::tuple< Args... > & a_value) inline
Parameters
a_value value
{
    _os << _bracketOpen();
    TuplePrint<decltype(a_value), sizeof...(Args)>::print(_os, a_value);
    _os << _bracketClose();
    return *this;
}
References _bracketClose(), _bracketOpen(), and _os.
operator<<() [41/43]
OStream & xl::core::OStream::operator<< (const std::tm & a_value)
Parameters
a_value value
{
    _os
        << "std::tm (sizeof=" << sizeof(a_value) << xT("):") << "\n"
        << xT("    tm_sec:   ") << a_value.tm_sec            << "\n"
        << xT("    tm_min:   ") << a_value.tm_min            << "\n"
        << xT("    tm_hour:  ") << a_value.tm_hour           << "\n"
        << xT("    tm_mday:  ") << a_value.tm_mday           << "\n"
        << xT("    tm_mon:   ") << (a_value.tm_mon  + 1)     << "\n"
        << xT("    tm_year:  ") << (a_value.tm_year + 1900)  << "\n"
        << xT("    tm_wday:  ") << a_value.tm_wday           << "\n"
        << xT("    tm_yday:  ") << a_value.tm_yday           << "\n"
        << xT("    tm_isdst: ") << a_value.tm_isdst;
    return *this;
}
References _os, and xT.
operator<<() [42/43]
OStream & xl::core::OStream::operator<< (std::tostream_t &(*)(std::tostream_t &) a_os) inline
print std::endl
References _os.
operator<<() [43/43]
template<typename T > OStream & xl::core::OStream::operator<< (const Float< T > & a_value) inline
Parameters
a_value value
{
    _printFloat( a_value.get() );
    return *this;
}
References _printFloat(), and xl::core::Float< T >::get().
_bracketOpen()
std::ctstring_t & xl::core::OStream::_bracketOpen () static protected
open bracket
{
    static std::ctstring_t sRv(xT("{"));
    return sRv;
}
References xT.
Referenced by _printRange(), _printRangeMap(), operator<<(), and operator<<().
_bracketClose()
std::ctstring_t & xl::core::OStream::_bracketClose () static protected
close bracket
{
    static std::ctstring_t sRv(xT("}"));
    return sRv;
}
References xT.
Referenced by _printRange(), _printRangeMap(), operator<<(), and operator<<().
_delimiter()
std::ctstring_t & xl::core::OStream::_delimiter () static protected
_delimiter
{
    static std::ctstring_t sRv(xT(", "));
    return sRv;
}
References xT.
Referenced by _printRange(), operator<<(), and xl::core::OStream::TuplePrint< T, N >::print().
_printContainerTitle()
template<typename T > void_t xl::core::OStream::_printContainerTitle (const T & a_value) inline protected
_os << TypeName<T>::get() << xT(" (size=") /*<< a_value.size()*‍/ << xT("):") << std::endl;
Parameters
a_value value
{
    // TODO: std::forward_list - max_size()
    xUNUSED(a_value);
    /// _os << TypeName<T>::get() << xT(" (size=") /*<< a_value.size()*/ << xT("):") << std::endl;
}
References xUNUSED.
Referenced by _printContainer(), and _printMap().
_printValue()
template<typename T > void_t xl::core::OStream::_printValue (const T & a_value) inline protected
Parameters
a_value value
{
    OStream::operator << (a_value);
}
References operator<<().
Referenced by _printRange(), _printRangeMap(), _printString(), operator<<(), and operator<<().
_printString()
template<typename IteratorT > void_t xl::core::OStream::_printString (IteratorT a_first, IteratorT a_last) inline protected
Parameters
a_first first iterator
a_last last iterator
{
    for (; a_first != a_last; ++ a_first) {
        _printValue(*a_first);
    }
}
References _printValue().
Referenced by operator<<().
_printRange()
template<typename IteratorT > void_t xl::core::OStream::_printRange (IteratorT a_first, IteratorT a_last) inline protected
Parameters
a_first first iterator
a_last last iterator
{
    if (a_first == a_last) {
        _os << _bracketOpen();
        _os << _bracketClose();
        return;
    }
    _os << _bracketOpen();
    _printValue(*a_first);
    for (++ a_first; a_first != a_last; ++ a_first) {
        _os << _delimiter();
        _printValue(*a_first);
    }
    _os << _bracketClose();
}
References _bracketClose(), _bracketOpen(), _delimiter(), _os, and _printValue().
Referenced by _printContainer(), operator<<(), operator<<(), and operator<<().
_printRangeMap()
template<typename IteratorT > void_t xl::core::OStream::_printRangeMap (IteratorT a_first, IteratorT a_last) inline protected
Parameters
a_first first iterator
a_last last iterator
{
    if (a_first == a_last) {
        _os << _bracketOpen();
        _os << _bracketClose();
        return;
    }
    _os << _bracketOpen();
    _printValue(*a_first);
    for (++ a_first; a_first != a_last; ++ a_first) {
        _os << Const::nl();
        _printValue(*a_first);
    }
    _os << _bracketClose();
}
References _bracketClose(), _bracketOpen(), _os, _printValue(), and xl::core::Const::nl().
Referenced by _printMap().
_printContainer()
template<typename T > void_t xl::core::OStream::_printContainer (const T & a_value) inline protected
Parameters
a_value value
{
    _printContainerTitle(a_value);
    _printRange(a_value.cbegin(), a_value.cend());
}
References _printContainerTitle(), and _printRange().
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), and operator<<().
_printMap()
template<typename T > void_t xl::core::OStream::_printMap (const T & a_value) inline protected
Parameters
a_value value
{
    _printContainerTitle(a_value);
    _printRangeMap(a_value.cbegin(), a_value.cend());
}
References _printContainerTitle(), and _printRangeMap().
Referenced by operator<<(), operator<<(), operator<<(), and operator<<().
_printFloat()
template<typename T > void_t xl::core::OStream::_printFloat (const T value) inline protected
Skip extras '0' from end:
15.000 -> 15.0
12.99000 -> 12.99
{
    std::tstring_t value = std::to_string(a_value);
   /**
    * Skip extras '0' from end:
    *
    * - 15.000   -> 15.0
    * - 12.99000 -> 12.99
    */
    std::size_t pos = value.find_last_not_of(xT('0'));
    if (pos != std::tstring_t::npos &&
        pos != value.size() - 1)
    {
        if (value[pos] == xT('.')) {
            ++ pos;
        }
        value = value.substr(0, pos + 1);
    }
    _os << value;
}
References _os, and xT.
Referenced by operator<<(), operator<<(), operator<<(), and operator<<().
Member Data Documentation
_os
std::tstringstream_t xl::core::OStream::_os protected
Referenced by _printFloat(), _printRange(), _printRangeMap(), clear(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), str(), and str().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/OStream.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/OStream.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/OStream.inl