xLib: xl::fs::FsName Class Reference
xl::fs::FsName Class Reference final
File system name (file, directory name)
#include "FsName.h"
Inherits xl::interface_::IValid, xl::interface_::IStrConstRef, and xl::interface_::IPrinter< std::tostream_t >.
Public Member Functions
FsName normalize () const
fix name
ctors, dtor
FsName (std::ctstring_t &name)
virtual ~FsName ()
xNO_DEFAULT_CTOR (FsName)
xNO_COPY_ASSIGN (FsName)
Overrides
bool_t isOk () const final
Result is success.
std::ctstring_t & str () const final
Get as string.
void_t print (std::tostream_t &stream) const final
Public Member Functions inherited from xl::interface_::IValid
bool_t isError () const
Result is error.
operator bool_t () const
Result is success / error.
IValid ()=default
virtual ~IValid ()=default
Public Member Functions inherited from xl::interface_::IStrConstRef
IStrConstRef ()=default
virtual ~IStrConstRef ()=default
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
Static Public Member Functions
static std::size_t maxSize ()
get max name length in symbols
Detailed Description
File system name (file, directory name)
Constructor & Destructor Documentation
FsName()
xl::fs::FsName::FsName (std::ctstring_t & a_name) explicit
Parameters
a_name fs name
  :
    _name(a_name)
{
}
~FsName()
xl::fs::FsName::~FsName () virtual
{
}
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::fs::FsName::xNO_DEFAULT_CTOR (FsName)
xNO_COPY_ASSIGN()
xl::fs::FsName::xNO_COPY_ASSIGN (FsName)
isOk()
bool_t xl::fs::FsName::isOk () const final virtual
Result is success.
Implements xl::interface_::IValid.
{
    cbool_t isLog {false};
    if ( _name.empty() ) {
        LogCout(isLog) << xT("[FsName] empty name");
        return false;
    }
    if (_name.size() > maxSize()) {
        LogCout(isLog) << xT("[FsName] name size");
        return false;
    }
    if ( _isSpaceDot_impl() ) {
        LogCout(isLog) << xT("[FsName] space, dot");
        return false;
    }
    if ( _isBadChars_impl() ) {
        LogCout(isLog) << xT("[FsName] bad chars");
        return false;
    }
    if ( _isControlChars_impl() ) {
        LogCout(isLog) << xT("[FsName] control chars");
        return false;
    }
    if ( _isBadName_impl() ) {
        LogCout(isLog) << xT("[FsName] bad names");
        return false;
    }
    return true;
}
References maxSize(), and xT.
Referenced by xl::fs::Path::isValid().
str()
std::ctstring_t & xl::fs::FsName::str () const final virtual
Get as string.
Implements xl::interface_::IStrConstRef.
{
    return _name;
}
Referenced by xl::fs::Path::isValid().
print()
void_t xl::fs::FsName::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
normalize()
FsName xl::fs::FsName::normalize () const
fix name
{
    std::tstring_t name = _name;
    if ( name.empty() ) {
        return FsName(name);
    }
    // Fixes
    _fixSpaceDot_impl(name);
    _fixBadChars_impl(name);
    _fixControlChars_impl(name);
    _fixBadName_impl(name);
    // Fix: name size
    std::csize_t maxSize_ = maxSize();
    if (name.size() > maxSize_) {
        name.resize(maxSize_);
    }
    return FsName(name);
}
References maxSize().
Referenced by xl::fs::Path::isValid().
maxSize()
std::size_t xl::fs::FsName::maxSize () static
get max name length in symbols
{
    return _maxSize_impl();
}
Referenced by xl::sync::IpcMutex::create(), isOk(), and normalize().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Fs/FsName.h
/home/runner/work/xLib/xLib/Include/xLib/Fs/FsName.cpp