xLib: xl::system::Environment Class Reference
xl::system::Environment Class Reference
system environment variable
#include "Environment.h"
Inherits xl::interface_::IStr.
Public Member Functions
bool_t isExists () const
check for existence
std::tstring_t value () const
get value
std::vec_tstring_t values () const
convert value to container
void_t setValue (std::ctstring_t &value) const
set or change value
void_t remove () const
delete var
Overrides
std::tstring_t str () const final
variable with value (DESKTOP_SESSION=xfce)
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
ctors, dtor
Environment (std::ctstring_t &name)
virtual ~Environment ()=default
xNO_DEFAULT_CONSTRUCT (Environment)
xNO_COPY_ASSIGN (Environment)
static Environment path ()
get PATH values (/usr/bin ... pathes) with separator
Detailed Description
system environment variable
Definition at line 15 of file Environment.h.
Constructor & Destructor Documentation
Environment()
xl::system::Environment::Environment (std::ctstring_t & name) explicit
Definition at line 34 of file Environment.cpp.
  :
    _name{a_name}
{
    xTEST(_isNameValid());
}
References xTEST.
~Environment()
virtual xl::system::Environment::~Environment () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::system::Environment::xNO_DEFAULT_CONSTRUCT (Environment)
xNO_COPY_ASSIGN()
xl::system::Environment::xNO_COPY_ASSIGN (Environment)
path()
Environment xl::system::Environment::path () static
get PATH values (/usr/bin ... pathes) with separator
Definition at line 44 of file Environment.cpp.
{
    std::ctstring_t name =
    #if   xENV_WIN
        xT("Path");
    #elif xENV_UNIX
        xT("PATH");
    #endif
    return Environment(name);
}
References xT.
Referenced by xl::fs::Finder::fileInEnvPath().
str()
std::tstring_t xl::system::Environment::str () const final virtual
variable with value (DESKTOP_SESSION=xfce)
Implements xl::interface_::IStr.
Definition at line 57 of file Environment.cpp.
{
    return _name + Const::equal() + value();
}
References xl::core::Const::equal(), and value().
isExists()
bool_t xl::system::Environment::isExists () const
check for existence
Definition at line 63 of file Environment.cpp.
{
    xCHECK_RET(_name.empty(), false);
    return _isExists_impl();
}
References xCHECK_RET.
Referenced by xl::system::Environments::findFirstOf(), xl::test::Unit::isGithubCI(), remove(), value(), and values().
value()
std::tstring_t xl::system::Environment::value () const
get value
Definition at line 71 of file Environment.cpp.
{
    xCHECK_RET(!isExists(), std::tstring_t());
    return _value_impl();
}
References isExists(), and xCHECK_RET.
Referenced by xl::system::Environments::expandVars(), xl::system::Environments::findFirstOf(), str(), and values().
values()
std::vec_tstring_t xl::system::Environment::values () const
convert value to container
Definition at line 79 of file Environment.cpp.
{
    xCHECK_RET(!isExists(), std::vec_tstring_t{});
    std::vec_tstring_t items;
    String::split(value(), _envsSeparator(), &items);
    return std::move(items);
}
References isExists(), xl::core::String::split(), value(), and xCHECK_RET.
Referenced by xl::fs::Finder::fileInEnvPath().
setValue()
void_t xl::system::Environment::setValue (std::ctstring_t & value) const
set or change value
Definition at line 90 of file Environment.cpp.
{
    xTEST(_isValueValid(a_value));
    _setValue_impl(a_value);
}
References xTEST.
Referenced by xl::system::Environments::setVars().
remove()
void_t xl::system::Environment::remove () const
delete var
Definition at line 100 of file Environment.cpp.
{
    xCHECK_DO(!isExists(), return);
    _remove_impl();
}
References isExists(), and xCHECK_DO.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Environment.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Environment.cpp