xLib: xl::package::CsvWriter Class Reference
xl::package::CsvWriter Class Reference final
CSV writer.
#include "Csv.h"
Inherits xl::package::ICsv.
Public Member Functions
void_t saveFile (crow_t &header, crows_t &rows, std::ctstring_t &filePath)
void_t saveString (crow_t &header, crows_t &rows, std::tstring_t *rawString)
ctors, dtor
CsvWriter (cCsvOption &option)
virtual ~CsvWriter ()=delete
xNO_COPY_ASSIGN (CsvWriter)
Additional Inherited Members
Public Types inherited from xl::package::ICsv
using row_t = std::vec_tstring_t
using rows_t {}
Detailed Description
CSV writer.
Constructor & Destructor Documentation
CsvWriter()
xl::package::CsvWriter::CsvWriter (cCsvOption & option) explicit
  :
    _option(a_option)
{
}
~CsvWriter()
virtual xl::package::CsvWriter::~CsvWriter () virtual delete
Member Function Documentation
xNO_COPY_ASSIGN()
xl::package::CsvWriter::xNO_COPY_ASSIGN (CsvWriter)
saveFile()
void_t xl::package::CsvWriter::saveFile (crow_t & header, crows_t & rows, std::ctstring_t & filePath)
{
    // a_header
    {
        std::ctstring_t &header = String::join(a_header, _option.delimiter);
        FileText(a_filePath).write(header + Const::nl(), FileIO::OpenMode::ReadWrite);
    }
    // a_rows
    for (const auto &it_row : a_rows)
    {
        std::ctstring_t &row = String::join(it_row, _option.delimiter);
        FileText(a_filePath).write(row + Const::nl(), FileIO::OpenMode::Append);
    }
}
References xl::core::String::join(), xl::core::Const::nl(), and xl::fs::FileText::write().
saveString()
void_t xl::package::CsvWriter::saveString (crow_t & header, crows_t & rows, std::tstring_t * rawString)
{
    out_rawString->clear();
    // a_header
    {
        std::ctstring_t &header = String::join(a_header, _option.delimiter);
        *out_rawString += header + Const::nl();
    }
    // a_rows
    for (const auto &it_row : a_rows)
    {
        std::ctstring_t &row = String::join(it_row, _option.delimiter);
        *out_rawString += row + Const::nl();
    }
}
References xl::core::String::join(), and xl::core::Const::nl().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Csv.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Csv.cpp