xLib: xl::log::FileLog Class Reference
xl::log::FileLog Class Reference final
logging to file
#include "FileLog.h"
Public Types
enum class LogSizes : std::size_t { lsDefaultMb = xMB(20) , lsDefaultMaxMb = xMB(50) }
Public Types inherited from xl::log::ILog
enum class Level {
Off = 0 , Trace = 1 , Debug = 2 , Info = 3 ,
Warning = 4 , Error = 5 , Fatal = 6
}
log level
Public Member Functions
void_t setFilePath (std::ctstring_t &filePath)
set log path
std::tstring_t filePath () const
get log path
void_t clear () const
clear content
void_t remove () const
delete
ctors, dtor
FileLog (cLogSizes fileSizeMaxBytes)
FileLog (std::csize_t fileSizeMaxBytes)
operators
template<typename T >
FileLog & operator<< (const T &valueT)
Overrides
void_t write (cptr_ctchar_t format,...) const final
write to log
void_t write (cLevel level, cptr_ctchar_t format,...) const final
write to log
Public Member Functions inherited from xl::log::ILog
void_t setEnabled (cbool_t flag)
set enabled
bool_t isEnabled () const
set enabled
xNO_COPY_ASSIGN (ILog)
Additional Inherited Members
Protected Member Functions inherited from xl::log::ILog
std::tstring_t _levelString (cLevel level) const
Protected Attributes inherited from xl::log::ILog
std::tostringstream_t _oss
string stream
Detailed Description
logging to file
Definition at line 17 of file FileLog.h.
Member Enumeration Documentation
LogSizes
enum class xl::log::FileLog::LogSizes : std::size_t strong
Definition at line 22 of file FileLog.h.
    {
        lsDefaultMb    = xMB(20),
        lsDefaultMaxMb = xMB(50)
    };
Constructor & Destructor Documentation
FileLog() [1/3]
xl::log::FileLog::FileLog ()
Definition at line 32 of file FileLog.cpp.
                 :
    _fileSizeMaxBytes( static_cast<std::size_t>(LogSizes::lsDefaultMb) )
{
    xTEST(_filePath.empty());
}
FileLog() [2/3]
xl::log::FileLog::FileLog (cLogSizes fileSizeMaxBytes) explicit
Definition at line 38 of file FileLog.cpp.
  :
    _fileSizeMaxBytes( static_cast<std::size_t>(a_fileSizeMaxBytes) )
{
    xTEST(_filePath.empty());
}
FileLog() [3/3]
xl::log::FileLog::FileLog (std::csize_t fileSizeMaxBytes) explicit
Definition at line 46 of file FileLog.cpp.
  :
    _fileSizeMaxBytes(a_fileSizeMaxBytes)
{
    xTEST(_filePath.empty());
}
~FileLog()
xl::log::FileLog::~FileLog () virtual
Definition at line 55 of file FileLog.cpp.
{
    write(xT("%s"), _oss.str().c_str());
}
Member Function Documentation
clear()
void_t xl::log::FileLog::clear () const
clear content
Definition at line 138 of file FileLog.cpp.
{
    FileIO file(filePath());
    file.open(FileIO::OpenMode::Write);
    file.clear();
}
References xl::fs::FileIO::clear(), filePath(), and xl::fs::FileIO::open().
filePath()
std::tstring_t xl::log::FileLog::filePath () const
get log path
Definition at line 75 of file FileLog.cpp.
{
    return _filePath;
}
Referenced by clear(), xl::debug::Profiler::logPath(), remove(), xl::debug::Profiler::restart(), xl::debug::Profiler::stop(), write(), and write().
operator<<()
template<typename T > FileLog & xl::log::FileLog::operator<< (const T & valueT)
Definition at line 17 of file FileLog.inl.
{
    _oss << valueT;
    return *this;
}
remove()
void_t xl::log::FileLog::remove () const
delete
Definition at line 146 of file FileLog.cpp.
{
    File(filePath()).remove();
}
References filePath(), and xl::fs::File::remove().
setFilePath()
void_t xl::log::FileLog::setFilePath (std::ctstring_t & a_filePath)
set log path
Parameters
a_filePath full path or name
Definition at line 61 of file FileLog.cpp.
{
    xTEST(!a_filePath.empty());
    if (a_filePath.find( Const::slash() ) == std::tstring_t::npos) {
        _filePath = Path::exe().dir() + Const::slash() + a_filePath;
    } else {
        _filePath = a_filePath;
    }
}
References xl::fs::Path::dir(), and xl::fs::Path::exe().
Referenced by xl::debug::Profiler::setLogPath().
write() [1/2]
void_t xl::log::FileLog::write (cLevel level, cptr_ctchar_t format, ...) const final virtual
write to log
Implements xl::log::ILog.
Definition at line 102 of file FileLog.cpp.
{
    xCHECK_DO(!isEnabled(),       return);
    xCHECK_DO(filePath().empty(), return);
    _removeIfFull();
    // datetime
    std::tstring_t time;
    time = DateTime::current().format(xT("%Y-%m-%d %H:%M:%S"));
    std::tstring_t msg;
    {
        va_list args;
        xVA_START(args, a_format);
        msg = FormatC::strV(a_format, args);
        xVA_END(args);
        if (a_level != Level::Trace) {
            msg = _levelString(a_level) + xT(": ") + msg;
        }
    }
    // write
    {
        FileIO file(filePath());
        file.open(FileIO::OpenMode::Append, false);
        int_t iRv = file.write(xT("[%s] %s\n"), time.c_str(), msg.c_str());
        xTEST_DIFF(iRv, - 1);
    }
}
References xl::core::DateTime::current(), filePath(), xl::core::DateTime::format(), xl::log::ILog::isEnabled(), xl::fs::FileIO::open(), xl::core::FormatC::strV(), xl::fs::FileIO::write(), xCHECK_DO, and xT.
write() [2/2]
void_t xl::log::FileLog::write (cptr_ctchar_t format, ...) const final virtual
write to log
Implements xl::log::ILog.
Definition at line 82 of file FileLog.cpp.
{
    xCHECK_DO(!isEnabled(),        return);
    xCHECK_DO(a_format == nullptr, return);
    xCHECK_DO(filePath().empty(),  return);
    std::tstring_t msg;
    va_list args;
    xVA_START(args, a_format);
    msg = FormatC::strV(a_format, args);
    xVA_END(args);
    write(Level::Trace, xT("%s"), msg.c_str());
}
References filePath(), xl::log::ILog::isEnabled(), xl::core::FormatC::strV(), write(), xCHECK_DO, and xT.
Referenced by xl::debug::Profiler::stop(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/FileLog.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/FileLog.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/FileLog.inl