xLib: xl::sync::Sleeper Class Reference
xl::sync::Sleeper Class Reference
sleeper
#include "Sleeper.h"
Public Member Functions
void_t sleep (culong_t &timeoutMsec)
sleep
void_t wakeUp ()
wake up
bool_t isSleeping () const
check for sleeping
ctors, dtor
Sleeper ()
virtual ~Sleeper ()=default
xNO_COPY_ASSIGN (Sleeper)
Detailed Description
sleeper
Constructor & Destructor Documentation
Sleeper()
xl::sync::Sleeper::Sleeper ()
                 :
    _event(false, false)
{
    _event.create();
}
References xl::sync::Event::create().
~Sleeper()
virtual xl::sync::Sleeper::~Sleeper () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::Sleeper::xNO_COPY_ASSIGN (Sleeper)
sleep()
void_t xl::sync::Sleeper::sleep (culong_t & a_timeoutMsec)
sleep
Parameters
a_timeoutMsec in milliseconds
{
    // n/a
    Event::ObjectState osRv = _event.wait(a_timeoutMsec);
    xTEST(osRv == Event::ObjectState::osSignaled || osRv == Event::ObjectState::osTimeout);
}
References xl::sync::Event::osSignaled, xl::sync::Event::osTimeout, xl::sync::Event::wait(), and xTEST.
wakeUp()
void_t xl::sync::Sleeper::wakeUp ()
wake up
{
    // n/a
    _event.set();
}
References xl::sync::Event::set().
isSleeping()
bool_t xl::sync::Sleeper::isSleeping () const
check for sleeping
{
    // n/a
    return _event.isSignaled();
}
References xl::sync::Event::isSignaled().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Sleeper.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Sleeper.cpp