xLib: xl::fs::Finder Class Reference
xl::fs::Finder Class Reference
Filesystem finder.
#include "Finder.h"
Public Member Functions
std::ctstring_t & rootDirPath () const
root directory path
std::ctstring_t & shellFilter () const
shell wild card filter
std::tstring_t entryName () const
entry name
bool_t isDot () const
check entry is dot ("." or "..")
std::tstring_t entryPath () const
entry path
FileType::types_t fileTypes () const
file attributes
bool_t moveNext ()
move next entry
void_t close ()
close search
ctors, dtor
Finder (std::ctstring_t &rootDirPath, std::ctstring_t &shellFilter)
virtual ~Finder ()
xNO_DEFAULT_CONSTRUCT (Finder)
xNO_COPY_ASSIGN (Finder)
Static Public Member Functions
static void_t dirs (std::ctstring_t &rootDirPath, std::ctstring_t &shellFilter, cbool_t isRecursively, std::vec_tstring_t *dirPaths)
search subdirectories
static void_t files (std::ctstring_t &rootDirPath, std::ctstring_t &shellFilter, cbool_t isRecursively, std::vec_tstring_t *filePaths)
search files
static std::tstring_t file (std::cvec_tstring_t &rootDirPaths, std::ctstring_t &shellFilter, cbool_t isRecursively)
search file in directories (by priority)
static std::tstring_t fileInEnvPath (std::ctstring_t &shellFilter, cbool_t isRecursively)
search file in directories from environment variable $PATH
Detailed Description
Filesystem finder.
Constructor & Destructor Documentation
Finder()
xl::fs::Finder::Finder (std::ctstring_t & a_rootDirPath, std::ctstring_t & a_shellFilter)
Parameters
a_rootDirPath target root dir
a_shellFilter shell wildcard pattern
  :
    _rootDirPath( Path(a_rootDirPath).toNative(false).str() ),
    _shellFilter(a_shellFilter)
{
    xTEST(!_entry.handle.isValid());
    xTEST(!a_rootDirPath.empty());
    xTEST(!a_shellFilter.empty());
}
References xTEST.
~Finder()
xl::fs::Finder::~Finder () virtual
{
    close();
}
References close().
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::Finder::xNO_DEFAULT_CONSTRUCT (Finder)
xNO_COPY_ASSIGN()
xl::fs::Finder::xNO_COPY_ASSIGN (Finder)
rootDirPath()
std::ctstring_t & xl::fs::Finder::rootDirPath () const
root directory path
{
    xTEST(!_rootDirPath.empty());
    return _rootDirPath;
}
References xTEST.
Referenced by entryPath().
shellFilter()
std::ctstring_t & xl::fs::Finder::shellFilter () const
shell wild card filter
{
    xTEST(!_shellFilter.empty());
    return _shellFilter;
}
References xTEST.
entryName()
std::tstring_t xl::fs::Finder::entryName () const
entry name
{
    xTEST(_entry.handle.isValid());
    std::ctstring_t sRv = _entryName_impl();
    xTEST(!sRv.empty());
    return sRv;
}
References xTEST.
Referenced by entryPath(), isDot(), and xl::fs::Dir::isEmpty().
isDot()
bool_t xl::fs::Finder::isDot () const
check entry is dot ("." or "..")
{
    std::ctstring_t &name = entryName();
    if (name == Const::dot() ||
        name == Const::dot2())
    {
        return true;
    }
    return false;
}
References xl::core::Const::dot(), xl::core::Const::dot2(), and entryName().
entryPath()
std::tstring_t xl::fs::Finder::entryPath () const
entry path
{
    xTEST(_entry.handle.isValid());
    std::tstring_t sRv;
    sRv = Path(rootDirPath()).slashAppend().str() + entryName();
    return sRv;
}
References entryName(), rootDirPath(), xl::fs::Path::slashAppend(), xl::fs::Path::str(), and xTEST.
fileTypes()
FileType::types_t xl::fs::Finder::fileTypes () const
file attributes
{
    xTEST(_entry.handle.isValid());
    return _fileTypes_impl();
}
References xTEST.
moveNext()
bool_t xl::fs::Finder::moveNext ()
move next entry
{
    bool_t bRv {};
    if (_isMoveFirst) {
        bRv = _moveFirst();
        xCHECK_RET(!bRv, false);
    } else {
        xTEST(_entry.handle.isValid());
        bRv = _moveNext_impl();
        xCHECK_RET(!bRv, false);
    }
    return true;
}
References xCHECK_RET, and xTEST.
Referenced by dirs(), files(), and xl::fs::Dir::isEmpty().
close()
void_t xl::fs::Finder::close ()
close search
{
    _isMoveFirst = true;
    xCHECK_DO(!_entry.handle.isValid(), return);
    _close_impl();
}
References xCHECK_DO.
Referenced by ~Finder().
dirs()
void_t xl::fs::Finder::dirs (std::ctstring_t & a_rootDirPath, std::ctstring_t & a_shellFilter, cbool_t a_isRecursively, std::vec_tstring_t * a_dirPaths) static
search subdirectories
Parameters
a_rootDirPath target root dir
a_shellFilter shell wildcard pattern
a_isRecursively is recursive search
a_dirPaths result dir paths
{
    xTEST(!a_rootDirPath.empty());
    xTEST(!a_shellFilter.empty());
    xTEST_NA(a_isRecursively);
    xTEST_PTR(a_dirPaths);
    if ( !Dir(a_rootDirPath).isExists() ) {
        return;
    }
    for (Finder finder(a_rootDirPath, a_shellFilter); finder.moveNext(); ) {
        xCHECK_DO(finder.isDot(), continue);
        // set filter for dirs
        if ( !(static_cast<FileType::types_t>(FileType::Type::Directory) & finder.fileTypes()) ) {
            continue;
        }
        a_dirPaths->push_back( finder.entryPath() );
        // is search in subdirs
        if (a_isRecursively) {
            Finder::dirs(finder.entryPath(), a_shellFilter, true, a_dirPaths);
        }
    }
}
References xl::fs::FileType::Directory, dirs(), moveNext(), xCHECK_DO, xTEST, xTEST_NA, and xTEST_PTR.
Referenced by dirs(), files(), and xl::fs::Dir::pathClear().
files()
void_t xl::fs::Finder::files (std::ctstring_t & a_rootDirPath, std::ctstring_t & a_shellFilter, cbool_t a_isRecursively, std::vec_tstring_t * a_filePaths) static
search files
Parameters
a_rootDirPath target root dir
a_shellFilter shell wildcard pattern
a_isRecursively is recursive search
a_filePaths result file paths
{
    xTEST(!a_rootDirPath.empty());
    xTEST(!a_shellFilter.empty());
    xTEST_NA(a_isRecursively);
    xTEST_PTR(a_filePaths);
    if (!a_isRecursively) {
        for (Finder finder(a_rootDirPath, a_shellFilter); finder.moveNext(); ) {
            xCHECK_DO(finder.isDot(), continue);
            // set filter for files
            if (static_cast<FileType::types_t>(FileType::Type::Directory) & finder.fileTypes()) {
                continue;
            }
            a_filePaths->push_back(finder.entryPath());
        }
    } else {
        // subdirs
        std::vec_tstring_t dirPaths;
        dirs(a_rootDirPath, Const::maskAll(), true, &dirPaths);
        // files in root dir and each subdir
        files(a_rootDirPath, a_shellFilter, false, a_filePaths);
        for (const auto &it : dirPaths) {
            files(it, a_shellFilter, false, a_filePaths);
        }
    }
}
References xl::fs::FileType::Directory, dirs(), files(), xl::core::Const::maskAll(), moveNext(), xCHECK_DO, xTEST, xTEST_NA, and xTEST_PTR.
Referenced by xl::fs::Dir::copy(), xl::package::Archive::dirUncompress(), file(), files(), xl::fs::FsWatcher::openDirs(), and xl::fs::Dir::pathClear().
file()
std::tstring_t xl::fs::Finder::file (std::cvec_tstring_t & rootDirPaths, std::ctstring_t & shellFilter, cbool_t isRecursively) static
search file in directories (by priority)
{
    for (const auto &it_rootDirPath : a_rootDirPaths) {
        std::vec_tstring_t outFles;
        files(it_rootDirPath, a_shellFilter, a_isRecursively, &outFles);
        if ( outFles.empty() ) {
            continue;
        }
        return outFles.front();
    }
    return {};
}
References files().
Referenced by fileInEnvPath().
fileInEnvPath()
std::tstring_t xl::fs::Finder::fileInEnvPath (std::ctstring_t & shellFilter, cbool_t isRecursively) static
search file in directories from environment variable $PATH
{
    const Env env = Env::path();
    return file(env.values(), a_shellFilter, a_isRecursively);
}
References file(), xl::system::Env::path(), and xl::system::Env::values().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Finder.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Finder.cpp