xLib: xl::system::Color Class Reference
xl::system::Color Class Reference
Shell console color.
#include "Color.h"
Public Types
enum class FG {
Default = 0 ,
Black = 1 ,
Red = 2 ,
Green = 3 ,
Yellow = 4 ,
Blue = 5 ,
Magenta = 6 ,
Cyan = 7 ,
White = 8 ,
Gray = 9
}
foreground (text) color
enum class BG {
Default = 0 ,
Black = 1 ,
Red = 2 ,
Green = 3 ,
Yellow = 4 ,
Blue = 5 ,
Magenta = 6 ,
Cyan = 7 ,
White = 8 ,
Gray = 9
}
background color
enum class Attr {
Unknown = 0 ,
Reset = 1 << 0 ,
Bold = 1 << 1 ,
Dim = 1 << 2 ,
Underline = 1 << 3 ,
Blink = 1 << 4 ,
Reverse = 1 << 5 ,
Hidden = 1 << 6
}
text attribute
Public Member Functions
std::tstring_t set () const
set text color
std::tstring_t clear () const
reset text color to default
std::tstring_t setText (std::ctstring_t &str) const
set text color, text, reset text color to default
ctors, dtor
constexpr Color ()
constexpr Color (cFG a_fg, cBG a_bg, cAttr a_attrs)
~Color ()=default
xNO_COPY_ASSIGN (Color)
Detailed Description
Shell console color.
Member Enumeration Documentation
FG
enum class xl::system::Color::FG strong
foreground (text) color
Enumerator
Default
Black
Red
Green
Yellow
Blue
Magenta
Cyan
White
Gray
    {
        Default  = 0,
        Black    = 1,
        Red      = 2,
        Green    = 3,
        Yellow   = 4,
        Blue     = 5,
        Magenta  = 6,
        Cyan     = 7,
        White    = 8,
        Gray     = 9
    };
BG
enum class xl::system::Color::BG strong
background color
Enumerator
Default
Black
Red
Green
Yellow
Blue
Magenta
Cyan
White
Gray
    {
        Default  = 0,
        Black    = 1,
        Red      = 2,
        Green    = 3,
        Yellow   = 4,
        Blue     = 5,
        Magenta  = 6,
        Cyan     = 7,
        White    = 8,
        Gray     = 9
    };
Attr
enum class xl::system::Color::Attr strong
text attribute
Enumerator
Unknown
Unknown.
Reset
Reset all attributes.
Bold
Bold/Bright.
Dim
Dim.
Underline
Underlined.
Blink
Blink (not work with most of the terminal emulators)
Reverse
Invert the foreground and background colors.
Hidden
Hidden (useful for passwords)
    {
        Unknown    = 0,      ///< Unknown
        Reset      = 1 << 0, ///< Reset all attributes
        Bold       = 1 << 1, ///< Bold/Bright
        Dim        = 1 << 2, ///< Dim
        Underline  = 1 << 3, ///< Underlined
        Blink      = 1 << 4, ///< Blink (not work with most of the terminal emulators)
        Reverse    = 1 << 5, ///< Invert the foreground and background colors
        Hidden     = 1 << 6  ///< Hidden (useful for passwords)
    };
Constructor & Destructor Documentation
Color() [1/2]
constexpr xl::system::Color::Color () inline constexpr
                      :
        Color(FG::Default, BG::Default, Attr::Reset)
    {
    };
Color() [2/2]
constexpr xl::system::Color::Color (cFG a_fg, cBG a_bg, cAttr a_attrs) inline constexpr
Parameters
a_fg foreground color
a_bg background color
a_attrs text attributes
      :
        _fg   {a_fg},
        _bg   {a_bg},
        _attrs{a_attrs}
    {
    }
~Color()
xl::system::Color::~Color () default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::Color::xNO_COPY_ASSIGN (Color)
set()
std::tstring_t xl::system::Color::set () const
set text color
Colors and formatting (ANSI/VT100 Control sequences)
https://misc.flogisoft.com/bash/tip_colors_and_formatting
{
    xCHECK_RET(!_isColorSupport, xT(""));
    _enableAnsiColors();
    std::tstring_t sRv;
    FG fgColor {};
    {
        int_t iRv {};
        switch (_fg) {
        case FG::Default: iRv = 39; break;
        case FG::Black:   iRv = 30; break;
        case FG::Red:     iRv = 31; break;
        case FG::Green:   iRv = 32; break;
        case FG::Yellow:  iRv = 33; break;
        case FG::Blue:    iRv = 34; break;
        case FG::Magenta: iRv = 35; break;
        case FG::Cyan:    iRv = 36; break;
        case FG::White:   iRv = 37; break;
        case FG::Gray:    iRv = 90; break;
        }
        fgColor = static_cast<FG>(iRv);
    }
    BG bgColor {};
    {
        int_t iRv {};
        switch (_bg) {
        case BG::Default: iRv = 49;  break;
        case BG::Black:   iRv = 40;  break;
        case BG::Red:     iRv = 41;  break;
        case BG::Green:   iRv = 42;  break;
        case BG::Yellow:  iRv = 43;  break;
        case BG::Blue:    iRv = 44;  break;
        case BG::Magenta: iRv = 45;  break;
        case BG::Cyan:    iRv = 46;  break;
        case BG::White:   iRv = 47;  break;
        case BG::Gray:    iRv = 100; break;
        }
        bgColor = static_cast<BG>(iRv);
    }
    std::tstring_t attrs;
    {
        // Terminals allow attribute combinations.
        // The attributes must be separated by a semicolon (“;”).
        std::vec_tstring_t values;
        Bitset bits( static_cast<int_t>(_attrs) );
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Reset)),     values.emplace_back(xT("0")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Bold)),      values.emplace_back(xT("1")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Dim)),       values.emplace_back(xT("2")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Underline)), values.emplace_back(xT("4")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Blink)),     values.emplace_back(xT("5")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Reverse)),   values.emplace_back(xT("7")));
        xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attr::Hidden)),    values.emplace_back(xT("8")));
        attrs = String::join(values, xT(';'));
    }
    // TODO: [skynowa] StdStreamV2
    sRv = Format::str(xT("\033[{};{};{}m"), attrs, static_cast<int>(fgColor), static_cast<int>(bgColor));
    return sRv;
}
References Black, Blink, Blue, Bold, Cyan, Default, Dim, Gray, Green, Hidden, xl::core::Bitset< T >::isSetBit(), xl::core::String::join(), Magenta, Red, Reset, Reverse, xl::core::FormatT< StreamT >::str(), Underline, White, xCHECK_DO, xCHECK_RET, xT, and Yellow.
Referenced by setText(), and xl::system::Console::write().
clear()
std::tstring_t xl::system::Color::clear () const
reset text color to default
{
    xCHECK_RET(!_isColorSupport, xT(""));
    return xT("\033[0m");
}
References xCHECK_RET, and xT.
Referenced by setText(), and xl::system::Console::write().
setText()
std::tstring_t xl::system::Color::setText (std::ctstring_t & str) const
set text color, text, reset text color to default
{
    return set() + a_str + clear();
}
References clear(), and set().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/System/Color.h
/home/runner/work/xLib/xLib/Include/xLib/System/Color.cpp