xLib: xl::fs::Path Class Reference
xl::fs::Path Class Reference final
file system path
#include "Path.h"
Inherits xl::interface_::IPrinter< std::tostream_t >, and xl::interface_::IStrConstRef.
Public Types
enum class FileExt {
Exe ,
Dll ,
Lib ,
Obj ,
Shell ,
Config ,
Log ,
Db ,
Dat ,
Backup ,
Temp ,
Text
}
file extension
Public Member Functions
bool_t isAbsolute () const
is absolute
bool_t isRelative () const
is relative
std::tstring_t volume () const
get drive
std::tstring_t dir () const
get dir path, without a trailing backslash '\'
std::tstring_t dirName () const
get dir name
std::tstring_t fileName () const
get name.extension
std::tstring_t fileBaseName () const
get name without extension
std::tstring_t ext () const
get extension
void_t split (std::vec_tstring_t *values) const
split into parts by slashes
Path setVolume (std::ctstring_t &volumePath) const
set volume
Path setDir (std::ctstring_t &dirPath) const
set dir
Path setFileName (std::ctstring_t &fullName) const
set full name
Path setFileBaseName (std::ctstring_t &name) const
set name
Path setExt (std::ctstring_t &ext) const
set extension
Path removeExt () const
remove extension
Path removeExtIf (std::ctstring_t &ext) const
remove extension if it equal some string
Path toWin (cbool_t isSlashAtEnd) const
convert slashes to Windows style
Path toUnix (cbool_t isSlashAtEnd) const
convert slashes to Nix style
Path toNative (cbool_t isSlashAtEnd) const
convert slashes to native style
Path absolute () const
get absolute path
Path brief (std::csize_t maxSize) const
get short path
Path brief (std::csize_t leftDirsNum, std::csize_t rightDirsNum) const
get short path (hide dirs as dots)
Path briefName (std::csize_t maxSize) const
get short name
Path homeAsBrief () const
replace home dir with "~"
Path slashAppend () const
append slash
Path slashRemove () const
remove slash
Overrides
void_t print (std::tostream_t &stream) const final
std::ctstring_t & str () const final
file path
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
Public Member Functions inherited from xl::interface_::IStrConstRef
IStrConstRef ()=default
virtual ~IStrConstRef ()=default
Static Public Member Functions
static std::tstring_t fileExt (cFileExt fileExt)
get standard extension
static std::tstring_t fileDotExt (cFileExt fileExt)
get standard extension with dot (if needed, for "exe" - n/n)
static bool_t isValid (std::ctstring_t &filePath, std::tstring_t *filePathValid)
path validation
static bool_t isNameValid (std::ctstring_t &fileName, std::tstring_t *fileNameValid)
name validation
static size_t maxSize ()
get max path length in symbols
static size_t nameMaxSize ()
get max name length in symbols
Proc file
static std::tstring_t proc (std::ctstring_t &procPath, std::function< bool_t(std::ctstring_t &line)> cond, std::function< std::tstring_t(std::ctstring_t &line)> op)
get file lines from UNIX proc file
static std::tstring_t procValue (std::ctstring_t &procPath, std::ctstring_t &key)
get value by data from UNIX proc file
static std::tstring_t readSymLink (std::ctstring_t &symLinkPath)
read symlink content
ctors, dtor
Path (std::ctstring_t &filePath)
virtual ~Path ()
xNO_DEFAULT_CONSTRUCT (Path)
xNO_COPY_ASSIGN (Path)
static Path exe ()
static Path dll ()
static Path shell ()
static Path homeDir ()
static Path trashDir ()
Detailed Description
file system path
Member Enumeration Documentation
FileExt
enum class xl::fs::Path::FileExt strong
file extension
Enumerator
Exe
execute module
Dll
dynamically linked shared library
Lib
static library
Obj
object file
Shell
shell script file
Config
config file
Log
log file
Db
database file
Dat
data file
Backup
backup file
Temp
temprary file
Text
text file
    {
        Exe,    ///< execute module
        Dll,    ///< dynamically linked shared library
        Lib,    ///< static library
        Obj,    ///< object file
        Shell,  ///< shell script file
        Config, ///< config file
        Log,    ///< log file
        Db,     ///< database file
        Dat,    ///< data file
        Backup, ///< backup file
        Temp,   ///< temprary file
        Text    ///< text file
    };
Constructor & Destructor Documentation
Path()
xl::fs::Path::Path (std::ctstring_t & filePath) explicit
xTEST(!_filePath.empty());
  :
    _filePath(a_filePath)
{
    // TODO: PathDll - test
    /// xTEST(!_filePath.empty());
    xSTD_VERIFY(!a_filePath.empty());
}
References xSTD_VERIFY.
~Path()
xl::fs::Path::~Path () virtual
std::cout << "Path: dtor" << std::endl;
{
    /// std::cout << "Path: dtor" << std::endl;
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::Path::xNO_DEFAULT_CONSTRUCT (Path)
xNO_COPY_ASSIGN()
xl::fs::Path::xNO_COPY_ASSIGN (Path)
exe()
Path xl::fs::Path::exe () static
{
    std::ctstring_t &exePath = _exe_impl();
    xTEST(FileInfo(exePath).isExists());
    return Path(exePath);
}
References xTEST.
Referenced by xl::package::Application::dirPath(), xl::package::Application::filePath(), xl::test::Unit::run(), xl::log::FileLog::setFilePath(), xl::fs::Volume::space(), and xl::log::SystemLog::SystemLog().
dll()
Path xl::fs::Path::dll () static
{
    std::ctstring_t &dllPath = _dll_impl();
#if (cmOPTION_PROJECT_LIB_SHARE || cmOPTION_PROJECT_LIB_MODULE)
    xTEST(FileInfo(dllPath).isExists());
#endif
    return Path(dllPath);
}
References xTEST.
shell()
Path xl::fs::Path::shell () static
{
    std::ctstring_t &path = _shell_impl();
    return Path(path);
}
homeDir()
Path xl::fs::Path::homeDir () static
{
    std::ctstring_t &path = _homeDir_impl();
    return Path(path);
}
Referenced by xl::test::Unit::cfg(), and homeAsBrief().
trashDir()
Path xl::fs::Path::trashDir () static
Libraries:
https://github.com/KDE/kio/blob/master/src/ioslaves/trash/trashimpl.h
https://bugreports.qt.io/browse/QTBUG-47703?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true
https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html
{
    std::ctstring_t &path = _trashDir_impl();
    return Path(path);
}
print()
void_t xl::fs::Path::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
str()
std::ctstring_t & xl::fs::Path::str () const final virtual
file path
Implements xl::interface_::IStrConstRef.
{
    return _filePath;
}
Referenced by xl::test::Unit::cfg(), xl::fs::Finder::entryPath(), xl::fs::Backup::fileExec(), xl::package::Application::filePath(), homeAsBrief(), setDir(), setExt(), toNative(), toUnix(), and toWin().
isAbsolute()
bool_t xl::fs::Path::isAbsolute () const
is absolute
{
    xCHECK_RET(_filePath.empty(),                       false);
    xCHECK_RET(_filePath.at(0) == Const::slash().at(0), true);
    return _isAbsolute_impl();
}
References xl::core::Const::slash(), and xCHECK_RET.
Referenced by absolute(), and isRelative().
isRelative()
bool_t xl::fs::Path::isRelative () const
is relative
{
    return !isAbsolute();
}
References isAbsolute().
volume()
std::tstring_t xl::fs::Path::volume () const
get drive
{
    return _volume_impl();
}
Referenced by setVolume().
dir()
std::tstring_t xl::fs::Path::dir () const
get dir path, without a trailing backslash '\'
{
    std::csize_t slashPos = _filePath.rfind(Const::slash(), _filePath.size());
    xCHECK_RET(slashPos == std::tstring_t::npos, std::tstring_t());
    return _filePath.substr(0, slashPos);
}
References xl::core::Const::slash(), and xCHECK_RET.
Referenced by xl::package::Archive::dirCompress(), xl::package::Application::dirPath(), xl::package::Archive::fileCompress(), xl::test::Unit::run(), setDir(), xl::log::FileLog::setFilePath(), xl::fs::Volume::space(), and xl::fs::File::wipe().
dirName()
std::tstring_t xl::fs::Path::dirName () const
get dir name
{
    std::csize_t slashPos2 = _filePath.rfind(Const::slash());
    xCHECK_RET(slashPos2 == std::tstring_t::npos, std::tstring_t());
    std::csize_t slashPos1 = _filePath.rfind(Const::slash(), slashPos2 - 1);
    if (slashPos1 == std::tstring_t::npos) {
        return _filePath.substr(0, slashPos2);
    }
    return _filePath.substr(slashPos1 + 1, slashPos2 - slashPos1 - 1);
}
References xl::core::Const::slash(), and xCHECK_RET.
fileName()
std::tstring_t xl::fs::Path::fileName () const
get name.extension
{
    std::csize_t slashPos = _filePath.rfind(Const::slash(), _filePath.size());
    xCHECK_RET(slashPos == std::tstring_t::npos, _filePath);
    return _filePath.substr(slashPos + Const::slash().size());
}
References xl::core::Const::slash(), and xCHECK_RET.
Referenced by briefName(), xl::fs::Backup::fileExec(), isValid(), xl::debug::BuildInfo::libs(), and setFileName().
fileBaseName()
std::tstring_t xl::fs::Path::fileBaseName () const
get name without extension
{
    std::csize_t slashPos = _filePath.rfind(Const::slash(), _filePath.size());
    std::csize_t dotPos   = _filePath.rfind(Const::dot(),   _filePath.size());
    return String::cut(_filePath, slashPos + Const::slash().size(), dotPos);
}
References xl::core::String::cut(), xl::core::Const::dot(), and xl::core::Const::slash().
Referenced by xl::package::Application::configPath(), xl::package::Application::dbPath(), xl::package::Application::logPath(), and setFileBaseName().
ext()
std::tstring_t xl::fs::Path::ext () const
get extension
{
    std::csize_t dotPos = _filePath.rfind(Const::dot(), _filePath.size());
    xCHECK_RET(dotPos == std::tstring_t::npos, std::tstring_t());
    std::csize_t slashPos = _filePath.rfind(Const::slash(), _filePath.size());
    // if dot after slash - extension not exists
    xCHECK_RET(dotPos < slashPos && slashPos != std::tstring_t::npos, std::tstring_t());
    return _filePath.substr(dotPos + Const::dot().size());
}
References xl::core::Const::dot(), xl::core::Const::slash(), and xCHECK_RET.
Referenced by briefName(), xl::package::GitClient::modifiedFiles(), and xl::package::GitClient::trackedFiles().
split()
void_t xl::fs::Path::split (std::vec_tstring_t * values) const
split into parts by slashes
{
    xTEST_PTR(out_values);
    String::split(_filePath, Const::slash(), out_values);
}
References xl::core::Const::slash(), xl::core::String::split(), and xTEST_PTR.
Referenced by brief(), and xl::fs::Dir::pathCreate().
setVolume()
Path xl::fs::Path::setVolume (std::ctstring_t & volumePath) const
set volume
{
    std::tstring_t sRv(_filePath);
    std::tstring_t driveStr = Path(sRv).volume();
    xTEST(!driveStr.empty());
    std::csize_t pos = sRv.find(driveStr);
    xTEST_DIFF(pos, std::tstring_t::npos);
    return Path( sRv.replace(pos, driveStr.size(), a_volumePath) );
}
References volume(), xTEST, and xTEST_DIFF.
setDir()
Path xl::fs::Path::setDir (std::ctstring_t & dirPath) const
set dir
{
    std::tstring_t sRv(_filePath);
    std::tstring_t dirStr = Path(sRv).dir();
    xTEST(!dirStr.empty());
    std::csize_t pos = sRv.find(dirStr);
    xTEST_DIFF(pos, std::tstring_t::npos);
    return Path( sRv.replace(pos, dirStr.size(), Path(a_dirPath).slashRemove().str()) );
}
References dir(), slashRemove(), str(), xTEST, and xTEST_DIFF.
setFileName()
Path xl::fs::Path::setFileName (std::ctstring_t & fullName) const
set full name
{
    std::tstring_t sRv(_filePath);
    std::tstring_t fullName = Path(sRv).fileName();
    xTEST(!fullName.empty());
    std::csize_t pos = sRv.rfind(fullName);
    xTEST_DIFF(pos, std::tstring_t::npos);
    return Path( sRv.replace(pos, fullName.size(), a_fullName) );
}
References fileName(), xTEST, and xTEST_DIFF.
setFileBaseName()
Path xl::fs::Path::setFileBaseName (std::ctstring_t & name) const
set name
{
    std::tstring_t sRv(_filePath);
    std::tstring_t name = Path(sRv).fileBaseName();
    xTEST(!name.empty());
    std::csize_t pos = sRv.rfind(name);
    xTEST_DIFF(pos, std::tstring_t::npos);
    return Path( sRv.replace(pos, name.size(), a_name) );
}
References fileBaseName(), xTEST, and xTEST_DIFF.
setExt()
Path xl::fs::Path::setExt (std::ctstring_t & ext) const
set extension
{
    xTEST_NA(a_ext);
    return Path(removeExt().str() + Const::dot() + a_ext);
}
References xl::core::Const::dot(), removeExt(), str(), and xTEST_NA.
removeExt()
Path xl::fs::Path::removeExt () const
remove extension
{
    std::csize_t dotPos = _filePath.rfind( Const::dot() );
    return Path( _filePath.substr(0, dotPos) );
}
References xl::core::Const::dot().
Referenced by setExt().
removeExtIf()
Path xl::fs::Path::removeExtIf (std::ctstring_t & ext) const
remove extension if it equal some string
{
    std::csize_t extPos = _filePath.rfind(Const::dot() + a_ext);
    xCHECK_RET(extPos == std::tstring_t::npos, Path(_filePath));
    std::csize_t dotPos = _filePath.rfind(Const::dot());
    xTEST_DIFF(dotPos, std::tstring_t::npos);
    return Path( _filePath.substr(0, dotPos) );
}
References xl::core::Const::dot(), xCHECK_RET, and xTEST_DIFF.
toWin()
Path xl::fs::Path::toWin (cbool_t isSlashAtEnd) const
convert slashes to Windows style
{
    xTEST_NA(a_isSlashAtEnd);
    std::tstring_t sRv;
    sRv = a_isSlashAtEnd ? slashAppend().str() : slashRemove().str();
    sRv = String::replaceAll(sRv, Const::unixSlash(), Const::winSlash());
    return Path(sRv);
}
References xl::core::String::replaceAll(), slashAppend(), slashRemove(), str(), xl::core::Const::unixSlash(), xl::core::Const::winSlash(), and xTEST_NA.
toUnix()
Path xl::fs::Path::toUnix (cbool_t isSlashAtEnd) const
convert slashes to Nix style
{
    xTEST_NA(a_isSlashAtEnd);
    std::tstring_t sRv;
    sRv = a_isSlashAtEnd ? slashAppend().str() : slashRemove().str();
    sRv = String::replaceAll(sRv, Const::winSlash(), Const::unixSlash());
    return Path(sRv);
}
References xl::core::String::replaceAll(), slashAppend(), slashRemove(), str(), xl::core::Const::unixSlash(), xl::core::Const::winSlash(), and xTEST_NA.
toNative()
Path xl::fs::Path::toNative (cbool_t isSlashAtEnd) const
convert slashes to native style
{
    xTEST_NA(a_isSlashAtEnd);
    std::tstring_t sRv;
    sRv = a_isSlashAtEnd ? slashAppend().str() : slashRemove().str();
    _toNative_impl(&sRv);
    return Path(sRv);
}
References slashAppend(), slashRemove(), str(), and xTEST_NA.
Referenced by brief(), and xl::fs::Dir::pathCreate().
absolute()
Path xl::fs::Path::absolute () const
get absolute path
{
    std::ctstring_t sRv( _absolute_impl() );
    xTEST(Path(sRv).isAbsolute());
    return Path(sRv);
}
References isAbsolute(), and xTEST.
brief() [1/2]
Path xl::fs::Path::brief (std::csize_t maxSize) const
get short path
{
    xTEST_DIFF(a_maxSize, std::size_t(0));
    // util function
    struct _Functor
    {
        static void_t
        slashesMake(
            std::tstring_t *a_str,
            size_t         *a_num
        )
        {
            size_t index {};
            for ( ; ; ) {
                std::csize_t pos = a_str->find_first_of(Const::winSlash() + Const::unixSlash());
                xCHECK_DO(pos == std::tstring_t::npos, break);
                a_str->erase(0, pos + Const::slash().size());
                ++ index;
                xCHECK_DO(*a_num == index && *a_num != 0, break);
            }
            *a_num = index;
        }
    };
    std::tstring_t sRv  = _filePath;
    std::tstring_t path = _filePath;
    size_t         num  {};
    _Functor::slashesMake(&path, &num);
    while (sRv.size() > a_maxSize && num > 2) {
        path = sRv;
        std::size_t numNew = num / 2;
        _Functor::slashesMake(&path, &numNew);
        sRv.erase(sRv.find(path), path.size());
        numNew = 2;
        _Functor::slashesMake(&path, &numNew);
        sRv.append(Const::dot3() + Const::slash() + path);
        -- num;
    }
    return Path(sRv).toNative(false);
}
References xl::core::Const::dot3(), num, xl::core::Const::slash(), toNative(), xl::core::Const::unixSlash(), xl::core::Const::winSlash(), xCHECK_DO, and xTEST_DIFF.
brief() [2/2]
Path xl::fs::Path::brief (std::csize_t leftDirsNum, std::csize_t rightDirsNum) const
get short path (hide dirs as dots)
{
    std::vec_tstring_t values;
    split(&values);
    std::csize_t showDirsNum  = a_leftDirsNum + a_rightDirsNum;
    if (showDirsNum >= values.size()) {
        // n/a dots - return full path
        return Path(_filePath);
    }
    std::csize_t hideDirsNum = values.size() - showDirsNum;
    // rm hide dirs
    {
        const auto it_cbegin = values.cbegin() + static_cast<ptrdiff_t>(a_leftDirsNum);
        values.erase(it_cbegin, it_cbegin + static_cast<ptrdiff_t>(hideDirsNum - 1 /* dots */));
    }
    // set dot(s) == hide dirs number
    {
        std::ctstring_t dots(hideDirsNum, Const::dot()[0]);
        values.at(a_leftDirsNum) = dots;
    }
    return Path( String::join(values, Const::slash()) );
}
References xl::core::Const::dot(), xl::core::String::join(), xl::core::Const::slash(), and split().
briefName()
Path xl::fs::Path::briefName (std::csize_t maxSize) const
get short name
{
    xTEST_DIFF(a_maxSize, size_t(0));
    std::tstring_t tildaDotExt;
    {
        std::ctstring_t &_ext = ext();
        if ( _ext.empty() ) {
            tildaDotExt = xT("~");
        } else {
            tildaDotExt = xT("~") + Const::dot() + _ext;
        }
    }
    std::tstring_t sRv;
    {
        std::ctstring_t &_fileName = fileName();
        if (_fileName.size() > a_maxSize) {
            if (a_maxSize < tildaDotExt.size()) {
                sRv = _fileName.substr(0, a_maxSize);
            } else {
                sRv = _fileName.substr(0, a_maxSize - tildaDotExt.size()) + tildaDotExt;
            }
        } else {
            sRv = _fileName;
        }
    }
    return Path(sRv);
}
References xl::core::Const::dot(), ext(), fileName(), xT, and xTEST_DIFF.
homeAsBrief()
Path xl::fs::Path::homeAsBrief () const
replace home dir with "~"
{
    return Path( String::replaceAll(_filePath, homeDir().str(), xT("~")) );
}
References homeDir(), xl::core::String::replaceAll(), str(), and xT.
slashAppend()
Path xl::fs::Path::slashAppend () const
append slash
{
    return Path( String::trimRightChars(_filePath, Const::slash()).append(Const::slash()) );
}
References xl::core::Const::slash(), and xl::core::String::trimRightChars().
Referenced by xl::fs::Finder::entryPath(), xl::fs::Backup::fileExec(), toNative(), toUnix(), and toWin().
slashRemove()
Path xl::fs::Path::slashRemove () const
remove slash
{
#if xENV_UNIX
    if (_filePath == Const::unixSlash()) {
        return Path(_filePath);
    }
#endif
    return Path( String::trimRightChars(_filePath, Const::slash()) );
}
References xl::core::Const::slash(), xl::core::String::trimRightChars(), and xl::core::Const::unixSlash().
Referenced by setDir(), toNative(), toUnix(), and toWin().
fileExt()
std::tstring_t xl::fs::Path::fileExt (cFileExt fileExt) static
get standard extension
{
    std::tstring_t sRv;
    switch (a_fileExt) {
    case FileExt::Config:
        sRv = xT("cfg");
        break;
    case FileExt::Log:
        sRv = xT("log");
        break;
    case FileExt::Db:
        sRv = xT("db");
        break;
    case FileExt::Dat:
        sRv = xT("dat");
        break;
    case FileExt::Backup:
        sRv = xT("bak");
        break;
    case FileExt::Temp:
        sRv = xT("tmp");
        break;
    case FileExt::Text:
        sRv = xT("txt");
        break;
    default:
        sRv = _fileExt_impl(a_fileExt);
        break;
    }
    return sRv;
}
References Backup, Config, Dat, Db, Log, Temp, Text, and xT.
Referenced by fileDotExt().
fileDotExt()
std::tstring_t xl::fs::Path::fileDotExt (cFileExt fileExt) static
get standard extension with dot (if needed, for "exe" - n/n)
{
    std::ctstring_t &exeExt = fileExt(a_fileExt);
    xCHECK_RET(exeExt.empty(), std::tstring_t());
    return Const::dot() + exeExt;
}
References xl::core::Const::dot(), fileExt(), and xCHECK_RET.
Referenced by xl::package::Application::configPath(), xl::package::Application::dbPath(), xl::fs::Backup::fileExec(), and xl::package::Application::logPath().
isValid()
bool_t xl::fs::Path::isValid (std::ctstring_t & a_filePath, std::tstring_t * a_filePathValid) static
path validation
Parameters
a_filePath file, directory path
[out] a_filePathValid normalized path
{
    xTEST_NA(a_filePath);
    xTEST_NA(a_filePathValid);
    // is empty
    xCHECK_RET(a_filePath.empty(), false);
    // check for size
    xCHECK_RET(a_filePath.size() > maxSize(), false);
    // TODO: [skynowa] Path::isValid() - more checks
    // name
    {
        std::ctstring_t &fileName = Path(a_filePath).fileName();
        xCHECK_RET(!isNameValid(fileName, a_filePathValid), false);
    }
    return true;
}
References fileName(), isNameValid(), maxSize(), xCHECK_RET, and xTEST_NA.
isNameValid()
bool_t xl::fs::Path::isNameValid (std::ctstring_t & a_fileName, std::tstring_t * a_fileNameValid) static
name validation
Parameters
a_fileName file, directory name
[out] a_fileNameValid normalized name
{
    xTEST_NA(a_fileName);
    xTEST_NA(a_fileNameValid);
    std::tstring_t sRv(a_fileName);
    // check: empty name
    if ( sRv.empty() ) {
        xCHECK_RET(a_fileNameValid == nullptr, false);
        a_fileNameValid->clear();
        return true;
    }
    // check: name size
    std::csize_t _nameMaxSize = nameMaxSize();
    if (sRv.size() > _nameMaxSize) {
        xCHECK_RET(a_fileNameValid == nullptr, false);
        sRv.resize(_nameMaxSize);
    }
    return _isNameValid_impl(sRv, a_fileNameValid);
}
References nameMaxSize(), xCHECK_RET, and xTEST_NA.
Referenced by isValid().
maxSize()
size_t xl::fs::Path::maxSize () static
get max path length in symbols
{
    std::csize_t uiRv = _maxSize_impl();
    xTEST_DIFF(uiRv, std::size_t(0));
    return uiRv;
}
References xTEST_DIFF.
Referenced by xl::sync::IpcSemaphore::create(), and isValid().
nameMaxSize()
size_t xl::fs::Path::nameMaxSize () static
get max name length in symbols
{
    std::csize_t uiRv = _nameMaxSize_impl();
    xTEST_DIFF(uiRv, std::size_t(0));
    return uiRv;
}
References xTEST_DIFF.
Referenced by xl::sync::IpcMutex::create(), and isNameValid().
proc()
static std::tstring_t xl::fs::Path::proc (std::ctstring_t & procPath, std::function< bool_t(std::ctstring_t &line)> cond, std::function< std::tstring_t(std::ctstring_t &line)> op) static
get file lines from UNIX proc file
procValue()
static std::tstring_t xl::fs::Path::procValue (std::ctstring_t & procPath, std::ctstring_t & key) static
get value by data from UNIX proc file
readSymLink()
static std::tstring_t xl::fs::Path::readSymLink (std::ctstring_t & symLinkPath) static
read symlink content
Referenced by xl::fs::Dir::isExists().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Path.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Path.cpp