xLib: xl::log::ILog Class Reference
xl::log::ILog Class Reference abstract
logging
#include "ILog.h"
Inherited by xl::log::Cout, xl::log::FileLog, and xl::log::SystemLog.
Public Types
enum class Level {
Trace = 0 ,
Debug = 1 ,
Info = 2 ,
Warn = 3 ,
Error = 4 ,
Fatal = 5
}
log level
Public Member Functions
void_t setEnabled (cbool_t flag)
set enabled
template<typename... Args>
void_t trace (cptr_ctchar_t fmt, Args &&... args) const
template<typename... Args>
void_t debug (cptr_ctchar_t fmt, Args &&... args) const
template<typename... Args>
void_t info (cptr_ctchar_t fmt, Args &&... args) const
template<typename... Args>
void_t warn (cptr_ctchar_t fmt, Args &&... args) const
template<typename... Args>
void_t error (cptr_ctchar_t fmt, Args &&... args) const
template<typename... Args>
void_t fatal (cptr_ctchar_t fmt, Args &&... args) const
ctors, dtor
ILog ()=default
virtual ~ILog ()=0
xNO_COPY_ASSIGN (ILog)
Protected Member Functions
virtual void_t write (cLevel level, std::ctstring_t &msg) const =0
write to log (with EOL)
Level views (choose any you like)
std::tstring_t _levelString (cLevel level) const
std::tstring_t _levelIcon (cLevel level) const
std::tstring_t _ts () const
Protected Attributes
bool_t _isEnable {true}
is enabled
Detailed Description
logging
Member Enumeration Documentation
Level
enum class xl::log::ILog::Level strong
log level
Enumerator
Trace
Debug
Info
Warn
Error
Fatal
    {
        Trace = 0,
        Debug = 1,
        Info  = 2,
        Warn  = 3,
        Error = 4,
        Fatal = 5
    };
Constructor & Destructor Documentation
ILog()
xl::log::ILog::ILog () default
~ILog()
xl::log::ILog::~ILog () pure virtual
{
}
Member Function Documentation
xNO_COPY_ASSIGN()
xl::log::ILog::xNO_COPY_ASSIGN (ILog)
References debug(), and info().
setEnabled()
void_t xl::log::ILog::setEnabled (cbool_t flag)
set enabled
{
    _isEnable = a_flag;
}
References _isEnable.
trace()
template<typename... Args> void_t xl::log::ILog::trace (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Trace, msg);
}
References _isEnable, xl::core::FormatC::str(), Trace, write(), and xCHECK_DO.
debug()
template<typename... Args> void_t xl::log::ILog::debug (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Debug, msg);
}
References _isEnable, Debug, xl::core::FormatC::str(), write(), and xCHECK_DO.
Referenced by xNO_COPY_ASSIGN().
info()
template<typename... Args> void_t xl::log::ILog::info (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Info, msg);
}
References _isEnable, Info, xl::core::FormatC::str(), write(), and xCHECK_DO.
Referenced by xNO_COPY_ASSIGN().
warn()
template<typename... Args> void_t xl::log::ILog::warn (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Warn, msg);
}
References _isEnable, xl::core::FormatC::str(), Warn, write(), and xCHECK_DO.
error()
template<typename... Args> void_t xl::log::ILog::error (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Error, msg);
}
References _isEnable, Error, xl::core::FormatC::str(), write(), and xCHECK_DO.
fatal()
template<typename... Args> void_t xl::log::ILog::fatal (cptr_ctchar_t fmt, Args &&... args) const inline
{
    xCHECK_DO(!_isEnable, return);
    std::ctstring_t msg = FormatC::str(a_fmt, std::forward<Args>(a_args)...);
    write(Level::Fatal, msg);
}
References _isEnable, Fatal, xl::core::FormatC::str(), write(), and xCHECK_DO.
write()
virtual void_t xl::log::ILog::write (cLevel level, std::ctstring_t & msg) const protected pure virtual
write to log (with EOL)
Implemented in xl::log::Cout, xl::log::FileLog, and xl::log::SystemLog.
Referenced by debug(), error(), fatal(), info(), trace(), and warn().
_levelString()
std::tstring_t xl::log::ILog::_levelString (cLevel level) const protected
{
    switch (a_level) {
    xSWITCH_CASE_RET(Level::Trace, xT("TRACE"));
    xSWITCH_CASE_RET(Level::Debug, xT("DEBUG"));
    xSWITCH_CASE_RET(Level::Info,  xT("INFO"));
    xSWITCH_CASE_RET(Level::Warn,  xT("WARN"));
    xSWITCH_CASE_RET(Level::Error, xT("ERROR"));
    xSWITCH_CASE_RET(Level::Fatal, xT("FATAL"));
    }
    return {};
}
References Debug, Error, Fatal, Info, Trace, Warn, xSWITCH_CASE_RET, and xT.
_levelIcon()
std::tstring_t xl::log::ILog::_levelIcon (cLevel level) const protected
{
    switch (a_level) {
    xSWITCH_CASE_RET(Level::Trace, xT("🔍 "));
    xSWITCH_CASE_RET(Level::Debug, xT("🛠️ "));
    xSWITCH_CASE_RET(Level::Info,  xT("ℹ️ "));
    xSWITCH_CASE_RET(Level::Warn,  xT("⚠️ "));
    xSWITCH_CASE_RET(Level::Error, xT("❌"));
    xSWITCH_CASE_RET(Level::Fatal, xT("❗"));
    }
    return {};
}
References Debug, Error, Fatal, Info, Trace, Warn, xSWITCH_CASE_RET, and xT.
_ts()
std::tstring_t xl::log::ILog::_ts () const protected
{
    return DateTime::currentLocal().format(xT("%Y-%m-%d %H:%M:%S"));
}
References xl::core::DateTime::currentLocal(), xl::core::DateTime::format(), and xT.
Member Data Documentation
_isEnable
bool_t xl::log::ILog::_isEnable {true} protected
is enabled
{true};  ///< is enabled
Referenced by debug(), error(), fatal(), info(), setEnabled(), trace(), and warn().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Log/ILog.h
/home/runner/work/xLib/xLib/Include/xLib/Log/ILog.cpp
/home/runner/work/xLib/xLib/Include/xLib/Log/ILog.inl