xLib: xl::interface_::ICompare< T > Class Template Reference
xl::interface_::ICompare< T > Class Template Reference abstract
Comparable.
#include "ICompare.h"
Inherited by xl::core::Float< T >.
Public Member Functions
ctors, dtor
ICompare ()=default
virtual ~ICompare ()=default
operators
bool_t operator== (const T &a_value) const
Returns true if "value" is equal to this object.
bool_t operator!= (const T &a_value) const
Returns true if "value" is not equal to this object.
bool_t operator< (const T &a_value) const
Returns true if "value" is less than this object.
bool_t operator<= (const T &a_value) const
Returns true if "value" is less than or equal to this object.
bool_t operator> (const T &a_value) const
Returns true if "value" is greater than this object.
bool_t operator>= (const T &a_value) const
Returns true if "value" is greater than or equal to this object.
Protected Member Functions
virtual int_t compare (const T &value) const =0
Compare this object to another of the same type.
Detailed Description
template<typename T>
class xl::interface_::ICompare< T >
Comparable.
Constructor & Destructor Documentation
ICompare()
template<typename T > xl::interface_::ICompare< T >::ICompare () default
~ICompare()
template<typename T > virtual xl::interface_::ICompare< T >::~ICompare () virtual default
Member Function Documentation
operator==()
template<typename T > bool_t xl::interface_::ICompare< T >::operator== (const T & a_value) const inline
Returns true if "value" is equal to this object.
References xl::interface_::ICompare< T >::compare().
operator!=()
template<typename T > bool_t xl::interface_::ICompare< T >::operator!= (const T & a_value) const inline
Returns true if "value" is not equal to this object.
References xl::interface_::ICompare< T >::compare().
operator<()
template<typename T > bool_t xl::interface_::ICompare< T >::operator< (const T & a_value) const inline
Returns true if "value" is less than this object.
References xl::interface_::ICompare< T >::compare().
operator<=()
template<typename T > bool_t xl::interface_::ICompare< T >::operator<= (const T & a_value) const inline
Returns true if "value" is less than or equal to this object.
References xl::interface_::ICompare< T >::compare().
operator>()
template<typename T > bool_t xl::interface_::ICompare< T >::operator> (const T & a_value) const inline
Returns true if "value" is greater than this object.
References xl::interface_::ICompare< T >::compare().
operator>=()
template<typename T > bool_t xl::interface_::ICompare< T >::operator>= (const T & a_value) const inline
Returns true if "value" is greater than or equal to this object.
References xl::interface_::ICompare< T >::compare().
compare()
template<typename T > virtual int_t xl::interface_::ICompare< T >::compare (const T & value) const protected pure virtual
Compare this object to another of the same type.
Returns
"< 0" - if this object is "before" the value "0" - of they are equal "> 0" - if this object is "after" the value
Implemented in xl::core::Float< T >.
Referenced by xl::interface_::ICompare< T >::operator!=(), xl::interface_::ICompare< T >::operator<(), xl::interface_::ICompare< T >::operator<=(), xl::interface_::ICompare< T >::operator==(), xl::interface_::ICompare< T >::operator>(), and xl::interface_::ICompare< T >::operator>=().
The documentation for this class was generated from the following file:
/home/runner/work/xLib/xLib/Include/xLib/Interface/ICompare.h