xLib: xl::package::Archive Class Reference
xl::package::Archive Class Reference
Compress/unpack archives.
#include "Archive.h"
Public Types
enum class Type {
Unknown = 0 ,
Zip = 1 ,
zip7 = 2 ,
Rar = 3 ,
Gz = 4 ,
TarBz2 = 5
}
archive type
Public Member Functions
bool_t fileCompress (std::ctstring_t &sourceFilePath, std::ctstring_t &destFilePath, cbool_t isRemoveSourceFile)
bool_t dirCompress (std::ctstring_t &sourceDirPath, std::ctstring_t &destFilePath, cbool_t isRemoveSourceDir)
bool_t fileUncompress (std::ctstring_t &sourceFilePath, std::ctstring_t &destDirPath, cbool_t isRemoveSourceFile, cbool_t isAutoDetectType)
bool_t dirUncompress (std::ctstring_t &sourceDirPath, std::ctstring_t &fileShellFilter, std::ctstring_t &destDirPath, cbool_t isRemoveSourceFiles, cbool_t isAutoDetectType)
ctors, dtor
Archive (const Type type)
~Archive ()=default
xNO_DEFAULT_CONSTRUCT (Archive)
xNO_COPY_ASSIGN (Archive)
Detailed Description
Compress/unpack archives.
Member Enumeration Documentation
Type
enum class xl::package::Archive::Type strong
archive type
Enumerator
Unknown
Zip
zip7
Rar
Gz
TarBz2
    {
        Unknown = 0,
        Zip     = 1,
        zip7    = 2,
        Rar     = 3,
        Gz      = 4,
        TarBz2  = 5
    };
Constructor & Destructor Documentation
Archive()
xl::package::Archive::Archive (const Type type) explicit
  :
    _type{a_type}
{
}
~Archive()
xl::package::Archive::~Archive () default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::Archive::xNO_DEFAULT_CONSTRUCT (Archive)
xNO_COPY_ASSIGN()
xl::package::Archive::xNO_COPY_ASSIGN (Archive)
fileCompress()
bool_t xl::package::Archive::fileCompress (std::ctstring_t & a_sourceFilePath, std::ctstring_t & a_destFilePath, cbool_t a_isRemoveSourceFile)
Parameters
a_sourceFilePath source path
a_destFilePath destination archive path
a_isRemoveSourceFile is remove source dir
{
    xTEST_DIFF((int_t)_type, (int_t)Type::Unknown);
    xTEST(!a_sourceFilePath.empty());
    xTEST(!a_destFilePath.empty());
    xTEST_NA(a_isRemoveSourceFile);
    std::ctstring_t destDir = Path(a_destFilePath).dir();
    Dir(destDir).pathCreate();
    std::tstring_t     binPath;
    std::vec_tstring_t params;
    {
        switch (_type) {
        case Type::Zip:
            binPath = ::zipPath;
            params  = {"-9", "-Dj", a_destFilePath, a_sourceFilePath};
            break;
        case Type::zip7:
            // TODO: Type::zip7
            return false;
            break;
        case Type::Rar:
            // TODO: Type::Rar
            return false;
            break;
        case Type::Gz:
            // TODO: Type::Gz
            return false;
            break;
        case Type::TarBz2:
            // TODO: Type::TarBz2
            return false;
            break;
        case Type::Unknown:
        default:
            xTEST(false);
            return false;
            break;
        }
    }
    Process::execute(binPath, params, {}, xTIMEOUT_INFINITE, nullptr, nullptr);
    // remove source dir
    if (a_isRemoveSourceFile) {
        Dir(a_sourceFilePath).pathDelete();
    }
    return true;
}
References xl::fs::Path::dir(), xl::sync::Process::execute(), Gz, xl::fs::Dir::pathCreate(), xl::fs::Dir::pathDelete(), Rar, TarBz2, Unknown, xTEST, xTEST_DIFF, xTEST_NA, xTIMEOUT_INFINITE, Zip, and zip7.
dirCompress()
bool_t xl::package::Archive::dirCompress (std::ctstring_t & a_sourceDirPath, std::ctstring_t & a_destFilePath, cbool_t a_isRemoveSourceDir)
Parameters
a_sourceDirPath source path
a_destFilePath destination archive path
a_isRemoveSourceDir is remove source dir
{
    xTEST_DIFF((int_t)_type, (int_t)Type::Unknown);
    xTEST(Dir(a_sourceDirPath).isExists());
    xTEST(!a_destFilePath.empty());
    xTEST_NA(a_isRemoveSourceDir);
    std::ctstring_t destDir = Path(a_destFilePath).dir();
    Dir(destDir).pathCreate();
    std::tstring_t     binPath;
    std::vec_tstring_t params;
    {
        switch (_type) {
        case Type::Zip:
            binPath = ::zipPath;
            params  = {"-9", "-r", "-Dj", a_destFilePath, a_sourceDirPath};
            break;
        case Type::zip7:
            // TODO: Type::zip7
            return false;
            break;
        case Type::Rar:
            // TODO: Type::Rar
            return false;
            break;
        case Type::Gz:
            // TODO: Type::Gz
            return false;
            break;
        case Type::TarBz2:
            // TODO: Type::TarBz2
            return false;
            break;
        case Type::Unknown:
        default:
            xTEST(false);
            return false;
            break;
        }
    }
    Process::execute(binPath, params, {}, xTIMEOUT_INFINITE, nullptr, nullptr);
    // remove source dir
    if (a_isRemoveSourceDir) {
        Dir(a_sourceDirPath).pathDelete();
    }
    return true;
}
References xl::fs::Path::dir(), xl::sync::Process::execute(), Gz, xl::fs::Dir::pathCreate(), xl::fs::Dir::pathDelete(), Rar, TarBz2, Unknown, xTEST, xTEST_DIFF, xTEST_NA, xTIMEOUT_INFINITE, Zip, and zip7.
fileUncompress()
bool_t xl::package::Archive::fileUncompress (std::ctstring_t & a_sourceFilePath, std::ctstring_t & a_destDirPath, cbool_t a_isRemoveSourceFile, cbool_t a_isAutoDetectType)
Parameters
a_sourceFilePath file path
a_destDirPath destination dir
a_isRemoveSourceFile is remove source archive file
a_isAutoDetectType is auto detect archive type by file extention
{
    if ( !a_isAutoDetectType ) {
        xTEST_DIFF((int_t)_type, (int_t)Type::Unknown);
    }
    xTEST(!a_sourceFilePath.empty());
    xTEST(!a_destDirPath.empty());
    xTEST_NA(a_isRemoveSourceFile);
    Dir(a_destDirPath).pathCreate();
    const auto type = a_isAutoDetectType ? _detectType(a_sourceFilePath) : _type;
    std::tstring_t     binPath;
    std::vec_tstring_t params;
    {
        switch (type) {
        case Type::Zip:
            binPath = ::unzipPath;
            params  = {a_sourceFilePath, "-d", a_destDirPath};
            break;
        case Type::zip7:
            binPath = ::zip7Path;
            params  = {"x", a_sourceFilePath, "-o", a_destDirPath};
            break;
        case Type::Rar:
            binPath = ::unrarPath;
            params  = {"x", a_sourceFilePath, a_destDirPath};
            break;
        case Type::Gz:
            xUNUSED(a_isRemoveSourceFile);
            binPath = ::gunzipPath;
            params  = {a_sourceFilePath};
            break;
        case Type::TarBz2:
            binPath = ::tarPath;
            params  = {"xvjf", a_sourceFilePath, "-C", a_destDirPath};
            break;
        case Type::Unknown:
        default:
            xTEST(false);
            return false;
            break;
        }
    }
    Process::execute(binPath, params, {}, xTIMEOUT_INFINITE, nullptr, nullptr);
    // remove zip file
    if (a_isRemoveSourceFile) {
        if (type == Type::Gz) {
            // n/a
        } else {
            File(a_sourceFilePath).remove();
        }
    }
    // fix unzip bug - chmod for dest dir
    if (type == Type::Zip &&
        !Dir(a_destDirPath).isExists())
    {
        std::ctstring_t     binPathFixed = ::chmodPath;
        std::cvec_tstring_t paramsFixed  = {xT("-R"), xT("0777"), a_destDirPath};
        Process::execute(binPathFixed, paramsFixed, {}, xTIMEOUT_INFINITE, nullptr, nullptr);
    }
    return true;
}
References xl::sync::Process::execute(), Gz, xl::fs::Dir::pathCreate(), Rar, xl::fs::File::remove(), TarBz2, Unknown, xT, xTEST, xTEST_DIFF, xTEST_NA, xTIMEOUT_INFINITE, xUNUSED, Zip, and zip7.
Referenced by dirUncompress().
dirUncompress()
bool_t xl::package::Archive::dirUncompress (std::ctstring_t & a_sourceDirPath, std::ctstring_t & a_fileShellFilter, std::ctstring_t & a_destDirPath, cbool_t a_isRemoveSourceFiles, cbool_t a_isAutoDetectType)
Parameters
a_sourceDirPath dir path
a_fileShellFilter shell wildcard pattern
a_destDirPath destination dir
a_isRemoveSourceFiles is remove source archive files
a_isAutoDetectType is auto detect archive type by file extention
{
    bool_t bRv {};
    std::vec_tstring_t archive_files;
    Finder::files(a_sourceDirPath, a_fileShellFilter, true, &archive_files);
    if ( archive_files.empty() ) {
        xTEST(false);
        return false;
    }
    for (const auto &it_archive_file : archive_files) {
        bRv = fileUncompress(it_archive_file, a_destDirPath, a_isRemoveSourceFiles,
            a_isAutoDetectType);
        if (!bRv) {
            xTEST(false);
            return false;
        }
    }
    return true;
}
References xl::fs::Finder::files(), fileUncompress(), and xTEST.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Archive.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Archive.cpp