xLib: xl::sync::Pipe Class Reference
xl::sync::Pipe Class Reference final
Pipe is a section of shared memory that processes use for communication.
#include "Pipe.h"
Inherits xl::interface_::ISync< HandleNative >.
Public Member Functions
cint_t handleRead () const
cint_t handleWrite () const
std::tstring_t readAll () const
void_t closeRead ()
void_t closeWrite ()
ctors, dtor
Pipe ()
virtual ~Pipe ()
xNO_COPY_ASSIGN (Pipe)
Overrides
cHandleNative & handle () const final
get handle
void_t create () final
create
void_t close () final
close
Public Member Functions inherited from xl::interface_::ISync< HandleNative >
ISync ()=default
virtual ~ISync ()=default
Detailed Description
Pipe is a section of shared memory that processes use for communication.
Constructor & Destructor Documentation
Pipe()
xl::sync::Pipe::Pipe ()
{
}
~Pipe()
xl::sync::Pipe::~Pipe () virtual
{
    close();
}
References close().
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::Pipe::xNO_COPY_ASSIGN (Pipe)
handle()
cHandleNative & xl::sync::Pipe::handle () const final virtual
get handle
Implements xl::interface_::ISync< HandleNative >.
{
    return _handle;
}
create()
void_t xl::sync::Pipe::create () final virtual
create
Implements xl::interface_::ISync< HandleNative >.
{
    _create_impl();
}
close()
void_t xl::sync::Pipe::close () final virtual
close
Implements xl::interface_::ISync< HandleNative >.
{
    _close_impl(CloseMode::All);
}
Referenced by ~Pipe().
handleRead()
cint_t xl::sync::Pipe::handleRead () const
{
    return _handles[FdIndex::Read];
}
Referenced by readAll().
handleWrite()
cint_t xl::sync::Pipe::handleWrite () const
{
    return _handles[FdIndex::Write];
}
readAll()
std::tstring_t xl::sync::Pipe::readAll () const
{
    std::tstring_t sRv;
    constexpr std::size_t buffSize {1024 * 10};
    for (std::ssize_t readSize = 1; readSize > 0; ) {
        // Cout() << "ParentOk - Start read: " << a_pipeRead;
        char buff[buffSize + 1] {};
        readSize = _read_impl(handleRead(), buff, buffSize);
        // Cout() << "ParentOk - Stop read, " << xTRACE_VAR(readSize);
        if (readSize == - 1L) {
            xTEST_FAIL;
            break;
        }
        // [out]
        sRv.append(buff, static_cast<std::size_t>(readSize));
    } // for
    return sRv;
}
References handleRead(), and xTEST_FAIL.
closeRead()
void_t xl::sync::Pipe::closeRead ()
{
    _close_impl(CloseMode::Read);
}
closeWrite()
void_t xl::sync::Pipe::closeWrite ()
{
    _close_impl(CloseMode::Write);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Pipe.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Pipe.cpp