xLib: xl::fs::File Class Reference
xl::fs::File Class Reference
File.
#include "File.h"
Public Member Functions
ctors, dtor
File (std::ctstring_t &filePath)
File (const FileInfo &fileInfo)
virtual ~File ()
xNO_DEFAULT_CONSTRUCT (File)
xNO_COPY_ASSIGN (File)
actions
enum class CopyError {
Ok = 0 ,
DestFileExists = 1 ,
CopyFail = 2 ,
FilesDiffrent = 3 ,
Unknown = 4
}
errors codes
void_t clear () const
void_t remove () const
void_t tryRemove (std::csize_t attempts, culong_t timeoutMsec) const
void_t wipe (std::csize_t passes) const
void_t unlink () const
void_t rename (std::ctstring_t &filePathNew) const
void_t move (std::ctstring_t &dirPath) const
CopyError copy (std::ctstring_t &filePathTo, cbool_t isFailIfExists) const
void_t createSymlink (std::ctstring_t &filePathTo) const
Detailed Description
File.
Member Enumeration Documentation
CopyError
enum class xl::fs::File::CopyError strong
errors codes
Enumerator
Ok
Success.
DestFileExists
Destination file is exists.
CopyFail
Copy fail.
FilesDiffrent
Files are diffrent.
Unknown
Unknown.
    {
        Ok             = 0, ///< Success
        DestFileExists = 1, ///< Destination file is exists
        CopyFail       = 2, ///< Copy fail
        FilesDiffrent  = 3, ///< Files are diffrent
        Unknown        = 4  ///< Unknown
    };
Constructor & Destructor Documentation
File() [1/2]
xl::fs::File::File (std::ctstring_t & filePath) explicit
  :
    _filePath(a_filePath)
{
}
File() [2/2]
xl::fs::File::File (const FileInfo & fileInfo) explicit
  :
    _filePath( a_fileInfo.path() )
{
}
~File()
xl::fs::File::~File () virtual
{
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::File::xNO_DEFAULT_CONSTRUCT (File)
xNO_COPY_ASSIGN()
xl::fs::File::xNO_COPY_ASSIGN (File)
clear()
void_t xl::fs::File::clear () const
{
    FileInfo info(_filePath);
    xCHECK_DO(!info.isExists(), return);
    // Write, clear
    {
        FileIO file(_filePath);
        file.open(FileIO::OpenMode::Write);
        file.clear();
    }
}
References xl::fs::FileIO::clear(), xl::fs::FileInfo::isExists(), xl::fs::FileIO::open(), xl::fs::FileIO::Write, and xCHECK_DO.
Referenced by xl::fs::Config::clear().
remove()
void_t xl::fs::File::remove () const
TODO: [skynowa] maybe not work ???!!!
{
    FileInfo info(_filePath);
    xCHECK_DO(!info.isExists(), return);
    /// TODO: [skynowa] maybe not work ???!!!
    info.chmod(FileInfo::PermissionMode::Write);
    int_t iRv = xTREMOVE(_filePath.c_str());
    xTEST_DIFF(iRv, - 1);
    xTEST(!info.isExists());
}
References xl::fs::FileInfo::chmod(), xl::fs::FileInfo::isExists(), xl::fs::FileInfo::Write, xCHECK_DO, xTEST, and xTEST_DIFF.
Referenced by copy(), xl::package::Archive::fileUncompress(), xl::fs::Dir::pathClear(), xl::fs::Config::remove(), xl::log::FileLog::remove(), tryRemove(), and wipe().
tryRemove()
void_t xl::fs::File::tryRemove (std::csize_t attempts, culong_t timeoutMsec) const
{
    xTEST_GR(a_attempts, size_t(0U));
    xTEST_NA(a_timeoutMsec);
    std::csize_t attemptsMax  {100};  // MAGIC_NUMBER: attemptsMax
    std::csize_t attemptsReal = (std::min)(a_attempts, attemptsMax);
    for (size_t i = 0; i < attemptsReal; ++ i) {
        xTRY {
            remove();
            xCHECK_DO(!FileInfo(_filePath).isExists(), break);
        }
        xCATCH_ALL
        Thread::currentSleep(a_timeoutMsec);
    }
}
References xl::sync::Thread::currentSleep(), remove(), xCATCH_ALL, xCHECK_DO, xTEST_GR, xTEST_NA, and xTRY.
wipe()
void_t xl::fs::File::wipe (std::csize_t passes) const
{
    xTEST_NA(a_passes);
    FileInfo info(_filePath);
    xCHECK_DO(!info.isExists(), return);
    // attributes - reset
    {
        FileType(_filePath).clear();
    }
    // content - reset
    if ( !info.isEmpty() ) {
        FileIO file(_filePath);
        file.open(FileIO::OpenMode::BinReadWrite);
        clonglong_t fileSize = file.size();
        if (fileSize > 0LL) {
            for (size_t p {}; p < a_passes; ++ p) {
                auto writer = [&](cuchar_t a_byte) -> void
                {
                    file.setPosition(0L, FileIO::PointerPosition::Begin);
                    for (longlong_t i {}; i < fileSize; ++ i) {
                        std::csize_t uiRv = std::fwrite(&a_byte, 1, sizeof(a_byte), file.get().get());
                        xTEST_EQ(uiRv, sizeof(a_byte));
                    }
                    file.flush();
                };
                // fill by 0x55 (01010101), 0xAA (10101010), random char
                cuchar_t bytes[] {0x55, 0xAA, NativeRandom().nextChar<uchar_t>()};
                for (const auto it_byte : bytes) {
                    writer(it_byte);
                }
            } // for (p)
            // truncate
            file.clear();
        } // if (fileSize)
    }
    // file time - reset
    info.resetTime();
    // file name - randomize
    std::tstring_t randFilePath;
    {
        std::tstring_t randFileName = String::cast( DateTime().current().toMsec() );
        std::random_device randDevice;
        std::mt19937       gen( randDevice() );
        std::shuffle(randFileName.begin(), randFileName.end(), gen);
        randFilePath = Path(_filePath).dir() + Const::slash() + randFileName;
        rename(randFilePath);
    }
    remove();
}
References xl::fs::FileIO::Begin, xl::fs::FileIO::BinReadWrite, xl::core::String::cast(), xl::fs::FileIO::clear(), xl::fs::FileType::clear(), xl::fs::Path::dir(), xl::fs::FileIO::flush(), xl::fs::FileIO::get(), xl::core::Handle< T, typeT >::get(), xl::fs::FileInfo::isEmpty(), xl::fs::FileInfo::isExists(), xl::fs::FileIO::open(), remove(), rename(), xl::fs::FileInfo::resetTime(), xl::fs::FileIO::setPosition(), xl::fs::FileIO::size(), xl::core::Const::slash(), xCHECK_DO, xTEST_EQ, and xTEST_NA.
unlink()
void_t xl::fs::File::unlink () const
{
    int_t iRv = xTUNLINK(_filePath.c_str());
    xTEST_DIFF(iRv, - 1);
}
References xTEST_DIFF.
rename()
void_t xl::fs::File::rename (std::ctstring_t & filePathNew) const
{
    xTEST(!a_filePathNew.empty());
    int_t iRv = xTRENAME(_filePath.c_str(), a_filePathNew.c_str());
    xTEST_DIFF(iRv, - 1);
}
References xTEST, and xTEST_DIFF.
Referenced by move(), and wipe().
move()
void_t xl::fs::File::move (std::ctstring_t & dirPath) const
{
    xTEST(!a_dirPath.empty());
    rename(Path(a_dirPath).slashAppend().str() + Path(_filePath).fileName());
}
References rename(), and xTEST.
copy()
File::CopyError xl::fs::File::copy (std::ctstring_t & filePathTo, cbool_t isFailIfExists) const
{
    xTEST(!a_filePathTo.empty());
    xTEST_NA(a_isFailIfExists);
    bool_t isCopyOk {true};
    // errors
    std::ctstring_t errorDestFileExists = xT("File - Destination file is exists");
    std::ctstring_t errorCopyFail       = xT("File - Copy fail");
    std::ctstring_t errorFilesDiffrent  = xT("File - Files are diffrent");
    xCHECK_RET(a_isFailIfExists && FileInfo(a_filePathTo).isExists(), CopyError::DestFileExists);
    // copy
    {
        FileIO fileFrom(_filePath);
        fileFrom.open(FileIO::OpenMode::BinReadOnly);
        FileIO fileTo(a_filePathTo);
        fileTo.open(FileIO::OpenMode::BinWrite);
        constexpr std::size_t buffSize       {1024};
        uchar_t               buff[buffSize] {};
        for ( ; !fileFrom.isEof(); ) {
            std::csize_t readed  = fileFrom.read(buff, buffSize);
            xCHECK_DO(0 >= readed, break);
            std::csize_t written = fileTo.write(buff, readed);
            xCHECK_DO(readed != written, isCopyOk = false; break);
        }
    }
    // checks
    {
        if (!isCopyOk) {
            File(a_filePathTo).remove();
            return CopyError::CopyFail;
        }
        if (FileInfo(_filePath).size() != FileInfo(a_filePathTo).size()) {
            File(a_filePathTo).remove();
            return CopyError::FilesDiffrent;
        }
    }
    return CopyError::Ok;
}
References xl::fs::FileIO::BinReadOnly, xl::fs::FileIO::BinWrite, CopyFail, DestFileExists, FilesDiffrent, xl::fs::FileIO::isEof(), Ok, xl::fs::FileIO::open(), xl::fs::FileIO::read(), remove(), xl::fs::FileIO::write(), xCHECK_DO, xCHECK_RET, xT, xTEST, and xTEST_NA.
Referenced by xl::fs::Dir::copy(), and xl::fs::Backup::fileExec().
createSymlink()
void_t xl::fs::File::createSymlink (std::ctstring_t & filePathTo) const
{
    _createSymlink_impl(a_filePathTo);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/File.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/File.cpp