xLib: xl::package::Ssh2Client Class Reference
xl::package::Ssh2Client Class Reference
#include "Ssh2Client.h"
Public Types
enum class UserAuth {
uaUnknown = 0 ,
uaPassword = 1 ,
uaKeyboardInteractive = 2
}
Public Member Functions
bool_t isAlive ()
bool_t connect ()
void_t authPassword (cUserAuth userAuth)
void_t authPublicKey (std::ctstring_t &keyDirPath)
bool_t channelExec (std::ctstring_t &cmd, cbool_t isBlockingMode)
bool_t channelReadLine (std::tstring_t *stdOut, std::tstring_t *stdErr)
void_t channelClose ()
void_t disconnect ()
int lastError ()
std::tstring_t lastErrorFormat ()
ctors, dtor
Ssh2Client (cSsh2ClientOption &option)
virtual ~Ssh2Client ()
xNO_DEFAULT_CONSTRUCT (Ssh2Client)
xNO_COPY_ASSIGN (Ssh2Client)
Member Enumeration Documentation
UserAuth
enum class xl::package::Ssh2Client::UserAuth strong
Enumerator
uaUnknown
uaPassword
uaKeyboardInteractive
    {
        uaUnknown             = 0,
        uaPassword            = 1,
        uaKeyboardInteractive = 2,
    };
Constructor & Destructor Documentation
Ssh2Client()
xl::package::Ssh2Client::Ssh2Client (cSsh2ClientOption & option) explicit
  :
    _option(a_option)
{
    userPassword = a_option.password;
    int iRv = ::libssh2_init(0);
    xTEST_EQ(iRv, 0);
}
References xTEST_EQ.
~Ssh2Client()
xl::package::Ssh2Client::~Ssh2Client () virtual
{
    (void_t)::libssh2_exit();
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::Ssh2Client::xNO_DEFAULT_CONSTRUCT (Ssh2Client)
xNO_COPY_ASSIGN()
xl::package::Ssh2Client::xNO_COPY_ASSIGN (Ssh2Client)
isAlive()
bool_t xl::package::Ssh2Client::isAlive ()
{
    std::tstring_t hostAddr;
    if (DnsClient::isAddressIpv4(_option.hostName) ||
        DnsClient::isAddressIpv6(_option.hostName))
    {
        hostAddr = _option.hostName;
    } else {
        DnsClient::hostAddrByName(_option.hostName, &hostAddr);
    }
    return TcpClient::isServerAlive(hostAddr, _option.port);
}
References xl::net::DnsClient::hostAddrByName(), xl::net::DnsClient::isAddressIpv4(), xl::net::DnsClient::isAddressIpv6(), and xl::net::TcpClient::isServerAlive().
connect()
bool_t xl::package::Ssh2Client::connect ()
{
    int_t iRv = 0;
    std::tstring_t hostAddr;
    if (DnsClient::isAddressIpv4(_option.hostName) ||
        DnsClient::isAddressIpv6(_option.hostName))
    {
        hostAddr = _option.hostName;
    } else {
        DnsClient::hostAddrByName(_option.hostName, &hostAddr);
    }
    _tcpClient.create(ISocket::AddressFamily::afInet, ISocket::Type::tpStream, ISocket::Protocol::ptIp);
    _tcpClient.connect(hostAddr, _option.port);
    _session = ::libssh2_session_init();
    xTEST_PTR(_session);
    // \see [Win] UINT_PTR - _wait()
    while ((iRv = ::libssh2_session_startup(_session, static_cast<int_t>( _tcpClient.handle().get() ))) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, 0);
    return true;
}
References xl::net::TcpClient::connect(), xl::net::ISocket::create(), xl::core::Handle< T, typeT >::get(), xl::net::ISocket::handle(), xl::net::DnsClient::hostAddrByName(), xl::net::DnsClient::isAddressIpv4(), xl::net::DnsClient::isAddressIpv6(), xTEST_EQ, and xTEST_PTR.
authPassword()
void_t xl::package::Ssh2Client::authPassword (cUserAuth userAuth)
– xTEST_DIFF(a_userAuth, uaUnknown);
{
    xTEST_PTR(_session);
    // TODO: [skynowa] StdStreamV2
    ///-- xTEST_DIFF(a_userAuth, uaUnknown);
    int iRv = - 1;
    switch (a_userAuth) {
    case UserAuth::uaPassword:
        while ((iRv = ::libssh2_userauth_password(_session, xT2A(_option.userName).c_str(),
            xT2A(_option.password).c_str())) == LIBSSH2_ERROR_EAGAIN)
        {
            _wait(waitTimeoutSec);
        }
        break;
    case UserAuth::uaKeyboardInteractive:
        while ((iRv = ::libssh2_userauth_keyboard_interactive(_session, xT2A(_option.userName).c_str(),
            &_authPassword_OnKeyboardInteractive)) == LIBSSH2_ERROR_EAGAIN)
        {
            _wait(waitTimeoutSec);
        }
        break;
    case UserAuth::uaUnknown:
    default:
        iRv = - 1;
        break;
    }
    xTEST_EQ_MSG(iRv, 0, lastErrorFormat());
}
References lastErrorFormat(), uaKeyboardInteractive, uaPassword, uaUnknown, xT2A, xTEST_EQ_MSG, and xTEST_PTR.
authPublicKey()
void_t xl::package::Ssh2Client::authPublicKey (std::ctstring_t & keyDirPath)
{
    xTEST_PTR(_session);
    int iRv = - 1;
    std::ctstring_t privateKey = a_keyDirPath + xT("/id_rsa");
    std::ctstring_t publicKey  = a_keyDirPath + xT("/id_rsa.pub");
    while ((iRv = ::libssh2_userauth_publickey_fromfile(_session, xT2A(_option.userName).c_str(),
        xT2A(publicKey).c_str(), xT2A(privateKey).c_str(),
        xT2A(_option.password).c_str())) == LIBSSH2_ERROR_EAGAIN)
    {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, 0);
}
References xT, xT2A, xTEST_EQ, and xTEST_PTR.
channelExec()
bool_t xl::package::Ssh2Client::channelExec (std::ctstring_t & cmd, cbool_t isBlockingMode)
{
    xTEST_PTR(_session);
    xTEST_PTR_FAIL(_channel);
    xTEST(!a_cmd.empty());
    xTEST_NA(a_isBlockingMode);
    ssize_t iRv = - 1;
    _channel = ::libssh2_channel_open_session(_session);
    xTEST_PTR(_channel);
    (void_t)::libssh2_channel_set_blocking(_channel, static_cast<int>(a_isBlockingMode));
#if 0
    while ((iRv = ::libssh2_channel_exec(_channel, xT2A(a_cmd).c_str())) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, (ssize_t)0);
#else
    // % echo $0
    std::cstring_t shellName = "zsh";
    while ((iRv = ::libssh2_channel_request_pty(_channel, shellName.c_str())) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, (ssize_t)0);
    while ((iRv = ::libssh2_channel_shell(_channel)) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, (ssize_t)0);
    while ((iRv = ::libssh2_channel_write(_channel, xT2A(a_cmd).c_str(), a_cmd.size())) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, (ssize_t)a_cmd.size());
#endif
    return true;
}
References xT2A, xTEST, xTEST_EQ, xTEST_NA, xTEST_PTR, and xTEST_PTR_FAIL.
channelReadLine()
bool_t xl::package::Ssh2Client::channelReadLine (std::tstring_t * stdOut, std::tstring_t * stdErr)
{
    xTEST_PTR(_session);
    xTEST_PTR(_channel);
    xTEST_PTR(a_stdOut);
    xTEST_PTR(a_stdErr);
    xCHECK_RET(a_stdOut == nullptr, false);
    xCHECK_RET(a_stdErr == nullptr, false);
    std::tstring_t stdOut;
    bool_t         isStdOutChannelEof = false;
    _channelStdStreamReadLine(true, &stdOut, &isStdOutChannelEof);
    std::tstring_t stdErr;
    bool_t         isStdErrChannelEof = false;
    _channelStdStreamReadLine(false, &stdErr, &isStdErrChannelEof);
    if (isStdOutChannelEof && stdOut.empty() /* && isStdErrChannelEof && stdErr.empty() */) {
        a_stdOut->clear();
        a_stdErr->clear();
        return false;
    }
    // data format
    switch (_option.stdFormat) {
    case Ssh2ClientOption::StdFormat::sfRaw:
        // skip
        break;
    case Ssh2ClientOption::StdFormat::sfText:
        // TODO: [skynowa] sfText
        break;
    case Ssh2ClientOption::StdFormat::sfHtml:
        if ( !stdErr.empty() ) {
            Trace() << "\n" << stdErr;
            FileLog log;
            log.setFilePath("./log.log");
            log << "\n" << stdErr << "\n";
        }
        _convertStdToHtml(&stdOut);
        _convertStdToHtml(&stdErr);
        if ( !stdErr.empty() ) {
            Trace() << "\n" << stdErr;
            FileLog log;
            log.setFilePath("./log.log");
            log << "\n" << stdErr << "\n\n\n";
        }
        break;
    case Ssh2ClientOption::StdFormat::sfUnknown:
    default:
        xTEST(false);
        break;
    }
    // out
    std::swap(stdOut, *a_stdOut);
    std::swap(stdErr, *a_stdErr);
    return true;
}
References xl::log::FileLog::setFilePath(), xl::package::Ssh2ClientOption::sfHtml, xl::package::Ssh2ClientOption::sfRaw, xl::package::Ssh2ClientOption::sfText, xl::package::Ssh2ClientOption::sfUnknown, xCHECK_RET, xTEST, and xTEST_PTR.
channelClose()
void_t xl::package::Ssh2Client::channelClose ()
{
    xTEST_PTR(_channel);
    int iRv = - 1;
    while ((iRv = ::libssh2_channel_close(_channel)) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, 0);
    while ((iRv = ::libssh2_channel_free(_channel)) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    _channel = nullptr;
    xTEST_EQ(iRv, 0);
}
References xTEST_EQ, and xTEST_PTR.
disconnect()
void_t xl::package::Ssh2Client::disconnect ()
{
    xTEST_PTR(_session);
    int iRv = - 1;
    while ((iRv = ::libssh2_session_disconnect(_session, "Ssh2Client disconnected.")) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    xTEST_EQ(iRv, 0);
    _tcpClient.close();
    while ((iRv = ::libssh2_session_free(_session)) == LIBSSH2_ERROR_EAGAIN) {
        _wait(waitTimeoutSec);
    }
    _session = nullptr;
    xTEST_EQ(iRv, 0);
}
References xl::net::ISocket::close(), xTEST_EQ, and xTEST_PTR.
lastError()
int xl::package::Ssh2Client::lastError ()
{
    return ::libssh2_session_last_errno(_session);
}
lastErrorFormat()
std::tstring_t xl::package::Ssh2Client::lastErrorFormat ()
{
    std::string asRv;
    char *error     = nullptr;
    int   errorSize = 0;
    int_t iRv = ::libssh2_session_last_error(_session, &error, &errorSize, 0);
    xUNUSED(iRv);
    if (error == nullptr) {
        asRv = "[Unknown]";
    } else {
        asRv.assign(error, static_cast<std::size_t>( errorSize ));
    }
    return xA2T(asRv);
}
References xA2T, and xUNUSED.
Referenced by authPassword().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Ssh2Client.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Ssh2Client.cpp