xLib: xl::debug::SourceInfo Class Reference
xl::debug::SourceInfo Class Reference
Source info.
#include "SourceInfo.h"
Public Member Functions
cSourceInfoOption & option () const
option
std::tstring_t format () const
format data
std::tstring_t at () const
format as file and line
std::tstring_t expr () const
format as expression
std::tstring_t exprValues () const
format as expression
ctors, dtor
SourceInfo (cSourceInfoOption &option)
SourceInfo (std::ctstring_t &filePath, culong_t lineNum, std::ctstring_t &funcName, culong_t counter)
virtual ~SourceInfo ()=default
xNO_DEFAULT_CTOR (SourceInfo)
xNO_COPY_ASSIGN (SourceInfo)
Detailed Description
Source info.
Constructor & Destructor Documentation
SourceInfo() [1/2]
xl::debug::SourceInfo::SourceInfo (cSourceInfoOption & option) explicit
  :
    _option(a_option)
{
}
SourceInfo() [2/2]
xl::debug::SourceInfo::SourceInfo (std::ctstring_t & filePath, culong_t lineNum, std::ctstring_t & funcName, culong_t counter)
  :
    _option{a_filePath, a_lineNum, a_funcName, a_counter, {}, {}, {}, {}, {}}
{
}
~SourceInfo()
virtual xl::debug::SourceInfo::~SourceInfo () virtual default
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::debug::SourceInfo::xNO_DEFAULT_CTOR (SourceInfo)
xNO_COPY_ASSIGN()
xl::debug::SourceInfo::xNO_COPY_ASSIGN (SourceInfo)
option()
cSourceInfoOption & xl::debug::SourceInfo::option () const
option
{
    return _option;
}
format()
std::tstring_t xl::debug::SourceInfo::format () const
format data
{
    return Format::str(xT("#{} in {}, func: {}"), _option.counter, at(), _option.funcName);
}
References xl::core::FormatT< StreamT >::str(), and xT.
at()
std::tstring_t xl::debug::SourceInfo::at () const
format as file and line
{
    return Format::str(xT("{}:{}"), _option.filePath, _option.lineNum);
}
References xl::core::FormatT< StreamT >::str(), and xT.
expr()
std::tstring_t xl::debug::SourceInfo::expr () const
format as expression
{
    return Format::str(xT("{} {} {}"), _option.exprVar1, _option.exprOp, _option.exprVar2);
}
References xl::core::FormatT< StreamT >::str(), and xT.
exprValues()
std::tstring_t xl::debug::SourceInfo::exprValues () const
format as expression
{
    return Format::str(xT("{} {} {}"), _option.exprValue1, _option.exprOp, _option.exprValue2);
}
References xl::core::FormatT< StreamT >::str(), and xT.
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Debug/SourceInfo.h
/home/runner/work/xLib/xLib/Include/xLib/Debug/SourceInfo.cpp