xLib: xl::package::xml::Error Class Reference
xl::package::xml::Error Class Reference final
#include "Error.h"
Inherits xl::interface_::IError< int_t >.
Public Member Functions
ctors, dtor
Error (const xmlErrorPtr error)
virtual ~Error ()=default
xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN (Error)
Overrides
int_t code () const final
Code.
bool_t isOk () const final
Check for success.
std::tstring_t category () const final
Category (type)
std::tstring_t message () const final
Detail message.
Public Member Functions inherited from xl::interface_::IError< int_t >
bool_t isFail () const
Check for error.
std::tstring_t str () const
Formatted message.
IError ()=default
virtual ~IError ()=default
Constructor & Destructor Documentation
Error()
xl::package::xml::Error::Error (const xmlErrorPtr a_error) explicit
Parameters
a_error XML error
  :
    _error{a_error}
{
    xTEST_PTR(a_error);
}
References xTEST_PTR.
~Error()
virtual xl::package::xml::Error::~Error () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::xml::Error::xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN()
xl::package::xml::Error::xNO_COPY_ASSIGN (Error)
code()
int_t xl::package::xml::Error::code () const final virtual
Code.
Implements xl::interface_::IError< int_t >.
{
    return _error->code;
}
Referenced by isOk(), and message().
isOk()
bool_t xl::package::xml::Error::isOk () const final virtual
Check for success.
Implements xl::interface_::IError< int_t >.
{
    return (code() == XML_ERR_OK);
}
References code().
category()
std::tstring_t xl::package::xml::Error::category () const final virtual
Category (type)
Implements xl::interface_::IError< int_t >.
{
    return xT("xl::package::xml::Error");
}
References xT.
message()
std::tstring_t xl::package::xml::Error::message () const final virtual
Detail message.
Implements xl::interface_::IError< int_t >.
{
    if (_error->code == XML_ERR_OK) {
        return {};
    }
    cint_t domain = _error->domain;
    cint_t code   = _error->code;
    std::tstring_t level;
    {
        const std::map<xmlErrorLevel, cptr_ctchar_t> levels
        {
            {XML_ERR_NONE,    xT("")},
            {XML_ERR_WARNING, xT("Warning")},
            {XML_ERR_ERROR,   xT("Error")},
            {XML_ERR_FATAL,   xT("Fatal")}
        };
        auto it = levels.find(_error->level);
        if (it != levels.cend()) {
            level = it->second;
        } else {
            level = xT("Unknown");
        }
    }
    std::tstring_t file;
    {
        if (_error->file != nullptr) {
            file = _error->file;
        }
    }
    int_t line {};
    int_t column {};
    {
        if (_error->domain == XML_FROM_PARSER) {
            line   = _error->line;
            column = _error->int2;
        }
    }
    std::tstring_t element;
    {
        if (_error->node != nullptr) {
            if (((xmlNodePtr)_error->node)->type == XML_ELEMENT_NODE) {
                auto node_name = (cptr_ctchar_t)((xmlNodePtr)_error->node)->name;
                element = node_name;
            }
        }
    }
    std::ctstring_t msg = String::trimSpace(_error->message);
    std::tstring_t msgExtra1;
    std::tstring_t msgExtra2;
    std::tstring_t msgExtra3;
    {
        if (_error->domain == XML_FROM_XPATH) {
            if (_error->str1 != nullptr) {
                msgExtra1 = _error->str1;
            }
            if (_error->str2 != nullptr) {
                msgExtra2 = _error->str2;
            }
            if (_error->str3 != nullptr) {
                msgExtra3 = _error->str3;
            }
        }
    }
    std::ctstring_t sRv = Format::str(
        xT("LibXML2 ver:    {}\n")
        xT("domain:         {}\n")
        xT("code:           {}\n")
        xT("level:          {}\n")
        xT("file:           {}\n")
        xT("line:           {}\n")
        xT("column:         {}\n")
        xT("element:        {}\n")
        xT("message:        {}\n")
        xT("message extra1: {}\n")
        xT("message extra2: {}\n")
        xT("message extra3: {}\n"),
        LIBXML_VERSION, domain, code, level, file, line, column, element,
            msg, msgExtra1, msgExtra2, msgExtra3);
    return sRv;
}
References code(), xl::core::FormatT< StreamT >::str(), xl::core::String::trimSpace(), and xT.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Error.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Error.cpp