xLib: xl::package::xml::Doc Class Reference
xl::package::xml::Doc Class Reference
#include "Doc.h"
Inherits xl::interface_::IValid, xl::interface_::IStr, and xl::interface_::IPrinter< std::tostream_t >.
Public Member Functions
void parse (std::ctstring_t &str, cbool_t isNss, Node &root)
void parseFile (std::ctstring_t &filePath, Node &root)
void saveToFile (std::ctstring_t &filePath) const
std::tstring_t format (std::ctstring_t &toCharset) const
ctors, dtor
Doc (std::ctstring_t &charset)
virtual ~Doc ()=default
xNO_DEFAULT_CONSTRUCT (Doc)
xNO_COPY_ASSIGN (Doc)
void setNss (std::cmap_tstring_t &nss)
Overrides
bool_t isOk () const final
Result is success.
void_t print (std::tostream_t &stream) const final
std::tstring_t str () const final
Get as string.
Public Member Functions inherited from xl::interface_::IValid
bool_t isError () const
Result is error.
operator bool_t () const
Result is success / error.
IValid ()=default
virtual ~IValid ()=default
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
Static Public Member Functions
static bool_t isValidLight (std::ctstring_t &str)
quick check string if XML document
Friends
class Node
Constructor & Destructor Documentation
Doc()
xl::package::xml::Doc::Doc (std::ctstring_t & charset) explicit
  :
    _doc  (nullptr, nullptr),
    _iconv(a_charset, ::charsetDefault.c_str(), 1024, false, true) // TODO: Iconv::isForceEncoding = false
{
    // FAQ: https://adobkin.com/2011/10/08/956/
    (void)::xmlSetStructuredErrorFunc(nullptr, reinterpret_cast<xmlStructuredErrorFunc>(_onError));
}
~Doc()
virtual xl::package::xml::Doc::~Doc () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::xml::Doc::xNO_DEFAULT_CONSTRUCT (Doc)
xNO_COPY_ASSIGN()
xl::package::xml::Doc::xNO_COPY_ASSIGN (Doc)
setNss()
void xl::package::xml::Doc::setNss (std::cmap_tstring_t & a_nss)
Parameters
a_nss prefix to namespase
{
    _nss = a_nss;
}
isOk()
bool_t xl::package::xml::Doc::isOk () const final virtual
Result is success.
Implements xl::interface_::IValid.
{
    return static_cast<bool_t>(_doc);
}
print()
void_t xl::package::xml::Doc::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
str()
std::tstring_t xl::package::xml::Doc::str () const final virtual
Get as string.
Implements xl::interface_::IStr.
{
    return format(::charsetDefault);
}
References format().
Referenced by isValidLight(), and parse().
parse()
void xl::package::xml::Doc::parse (std::ctstring_t & a_str, cbool_t a_isNss, Node & out_root)
Parameters
a_str XML string
a_isNss if need nss
[out] out_root
{
    if (!a_isNss) {
        std::tstring_t str = a_str;
        _stringNoNs(&str);
        _doc = {::xmlParseDoc( (const xmlChar *)str.data() ), ::xmlFreeDoc};
    } else {
        _doc = {::xmlParseDoc( (const xmlChar *)a_str.data() ), ::xmlFreeDoc};
    }
    xTEST(static_cast<bool_t>(_doc));
    // [out]
    _rootNode(out_root);
}
References str(), and xTEST.
parseFile()
void xl::package::xml::Doc::parseFile (std::ctstring_t & a_filePath, Node & out_root)
Parameters
a_filePath file path
[out] out_root root node
{
    _doc = {::xmlParseFile( a_filePath.c_str() ), ::xmlFreeDoc};
    xTEST(static_cast<bool_t>(_doc));
    // [out]
    _rootNode(out_root);
}
References xTEST.
saveToFile()
void xl::package::xml::Doc::saveToFile (std::ctstring_t & filePath) const
{
    cptr_cchar_t encoding {};
    xmlSaveCtxtPtr saveCtxt = ::xmlSaveToFilename(a_filePath.c_str(), encoding, XML_SAVE_FORMAT);
    xTEST_PTR(saveCtxt);
    long_t liRv = ::xmlSaveDoc(saveCtxt, _doc.get());
    xTEST_EQ(liRv, 0L);
    int_t iRv = ::xmlSaveClose(saveCtxt);
    xTEST_EQ(iRv, 0);
}
References xTEST_EQ, and xTEST_PTR.
format()
std::tstring_t xl::package::xml::Doc::format (std::ctstring_t & a_toCharset) const
Parameters
a_toCharset character encoding to use when generating XML (sample: "UTF-8")
{
    if ( a_toCharset.empty() ) {
        return {};
    }
    std::tstring_t  sRv;
    int_t           iRv {};
    xmlChar        *buff {};
    int             buff_size {};
    iRv = ::xmlKeepBlanksDefault(0);
    xTEST_EQ(iRv, 0);
    ::xmlDocDumpFormatMemoryEnc(_doc.get(), &buff, &buff_size, a_toCharset.c_str(), 1);
    xTEST_PTR(buff);
    xTEST_GR(buff_size, 0);
    sRv.assign(reinterpret_cast<cptr_ctchar_t>(buff), static_cast<size_t>(buff_size));
    Utils::freeT(buff, ::xmlFree, nullptr);
    return sRv;
}
References xl::core::Utils::freeT(), xTEST_EQ, xTEST_GR, and xTEST_PTR.
Referenced by str().
isValidLight()
bool_t xl::package::xml::Doc::isValidLight (std::ctstring_t & str) static
quick check string if XML document
🔗 See also:
https://xmlwriter.net/xml_guide/xml_declaration.shtml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
{
    xCHECK_RET(a_str.empty(), false);
   /**
    * \see https://xmlwriter.net/xml_guide/xml_declaration.shtml
    *
    * \code{.xml}
    * <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
    * \endcode
    */
    constexpr std::ctstring_view_t xmlDeclBegin = xT("<?xml ");
    if (a_str.size() <= xmlDeclBegin.size()) {
        return false;
    }
    std::ctstring_t &str = a_str.substr(0, xmlDeclBegin.size());
    if (str != xmlDeclBegin) {
        return false;
    }
    return true;
}
References str(), xCHECK_RET, and xT.
Friends And Related Symbol Documentation
Node
friend class Node friend
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Doc.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Doc.cpp