xLib: xl::algos::Algos Class Reference
xl::algos::Algos Class Reference
Algorithms.
#include "Algos.h"
Public Member Functions
template<typename T >
void listUnique (std::list< T > &a_cont)
ctors, dtor
xNO_DEFAULT_CONSTRUCT (Algos)
xNO_COPY_ASSIGN (Algos)
Static Public Member Functions
Common
template<typename ContT , typename ValueT >
static bool_t isContains (const ContT &cont, const ValueT &value)
check value existence
template<typename ContT , typename UnaryPredicateT >
static bool_t findIfAll (const ContT &cont, ContT &out, UnaryPredicateT pred)
Find all elements in container.
template<typename T >
static bool_t isInBounds (const T &value, const T &low, const T &high)
check value bounds
template<typename T , typename R , typename ComparatorT >
static bool_t isInBounds (const T &value, const R &low, const R &high, ComparatorT comp)
check value bounds (with custom comparator)
template<typename ContT >
static void_t deleteAll (ContT &cont)
delete all values
static bool_t isStartsWith (std::ctstring_t &value, std::ctstring_t &prefix)
starts with
static bool_t isEndsWith (std::ctstring_t &value, std::ctstring_t &suffix)
ends with
static bool_t contains (std::ctstring_t &value, std::ctstring_t &infix)
contains
template<typename T >
static bool_t isUnique (T first, T last)
determining if sorted container has all unique elements
template<typename ContT >
static bool_t isUniqueAll (const ContT &cont)
determining if sorted container has all unique elements
std::vector
template<typename T >
static void_t vectorUnique (std::vector< T > &cont)
unique std::vector
template<typename T >
static void_t vectorRemove (std::vector< T > &vec, const T &item)
remove item from std::vector
std::list
template<typename T >
static void_t listUnique (std::list< T > &cont)
unique std::list
std::map
template<typename T1 , typename T2 >
static T1 mapFindByValue (const std::map< T1, T2 > &cont, const T2 &value)
find find key by value
Detailed Description
Algorithms.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::algos::Algos::xNO_DEFAULT_CONSTRUCT (Algos)
xNO_COPY_ASSIGN()
xl::algos::Algos::xNO_COPY_ASSIGN (Algos)
isContains()
template<typename ContT , typename ValueT > bool_t xl::algos::Algos::isContains (const ContT & a_cont, const ValueT & a_value) inline static
check value existence
Parameters
a_cont container
a_value search value
{
    return std::find(a_cont.cbegin(), a_cont.cend(), a_value) != a_cont.cend();
}
Referenced by xl::sync::Process::isRunning(), xl::package::GitClient::modifiedFiles(), and xl::package::GitClient::trackedFiles().
findIfAll()
template<typename ContT , typename UnaryPredicateT > bool_t xl::algos::Algos::findIfAll (const ContT & a_cont, ContT & a_out, UnaryPredicateT a_pred) inline static
Find all elements in container.
Parameters
a_cont container
[out] a_out
a_pred predicate
{
    for (typename ContT::const_iterator it = std::find_if(a_cont.cbegin(), a_cont.cend(), a_pred);
        it != a_cont.cend();
        it = std::find_if(++ it, a_cont.cend(), a_pred))
    {
        a_out.push_back(*it);
    }
    return !a_out.empty();
}
isInBounds() [1/2]
template<typename T > bool_t xl::algos::Algos::isInBounds (const T & value, const T & low, const T & high) inline static
check value bounds
{
    return !(a_value < a_low) && !(a_high < a_value);
}
Referenced by xl::package::curl::HttpClient::httpCode(), and xl::package::curl::SmtpClient::request().
isInBounds() [2/2]
template<typename T , typename R , typename ComparatorT > bool_t xl::algos::Algos::isInBounds (const T & value, const R & low, const R & high, ComparatorT comp) inline static
check value bounds (with custom comparator)
{
    return !a_comp(a_value, a_low) && a_comp(a_value, a_high);
}
deleteAll()
template<typename ContT > void_t xl::algos::Algos::deleteAll (ContT & cont) inline static
delete all values
{
    for (const auto &it : a_cont) {
        Utils::ptrDeleteT(it);
    }
}
References xl::core::Utils::ptrDeleteT().
isStartsWith()
bool_t xl::algos::Algos::isStartsWith (std::ctstring_t & value, std::ctstring_t & prefix) static
starts with
{
    return a_value.size() >= a_prefix.size() && a_value.substr(0, a_prefix.size()) == a_prefix;
}
isEndsWith()
bool_t xl::algos::Algos::isEndsWith (std::ctstring_t & value, std::ctstring_t & suffix) static
ends with
{
    return a_value.size() >= a_suffix.size() &&
        a_value.substr(a_value.size() - a_suffix.size(), a_suffix.size()) == a_suffix;
}
contains()
bool_t xl::algos::Algos::contains (std::ctstring_t & value, std::ctstring_t & infix) static
contains
{
    return a_value.find(a_infix) != std::tstring_t::npos;
}
isUnique()
template<typename T > bool_t xl::algos::Algos::isUnique (T first, T last) inline static
determining if sorted container has all unique elements
{
    return (std::adjacent_find(a_first, a_last) == a_last);
}
Referenced by isUniqueAll().
isUniqueAll()
template<typename ContT > bool_t xl::algos::Algos::isUniqueAll (const ContT & cont) inline static
determining if sorted container has all unique elements
{
    return isUnique(a_cont.cbegin(), a_cont.cend());
}
References isUnique().
vectorUnique()
template<typename T > void_t xl::algos::Algos::vectorUnique (std::vector< T > & a_cont) inline static
unique std::vector
Parameters
[in,out] a_cont container
{
    std::sort(a_cont.begin(), a_cont.end());
    a_cont.erase(std::unique(a_cont.begin(), a_cont.end()), a_cont.end());
}
vectorRemove()
template<typename T > void_t xl::algos::Algos::vectorRemove (std::vector< T > & vec, const T & item) inline static
remove item from std::vector
{
    a_vec.erase(std::remove(a_vec.begin(), a_vec.end(), a_value), a_vec.cend());
}
listUnique() [1/2]
template<typename T > static void_t xl::algos::Algos::listUnique (std::list< T > & cont) static
unique std::list
mapFindByValue()
template<typename T1 , typename T2 > T1 xl::algos::Algos::mapFindByValue (const std::map< T1, T2 > & a_cont, const T2 & a_value) inline static
find find key by value
Parameters
a_cont container
a_value search value
{
    auto pred = [&](const typename std::map<T1, T2>::value_type &a_it) -> bool
    {
        return (a_it.second == a_value);
    };
    auto it = std::find_if(a_cont.cbegin(), a_cont.cend(), pred);
    if (it != a_cont.end()) {
        return it->first;
    }
    return {};
}
listUnique() [2/2]
template<typename T > void xl::algos::Algos::listUnique (std::list< T > & a_cont) inline
Parameters
[in,out] a_cont container
{
    a_cont.sort();
    a_cont.unique();
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Algo/Algos.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Algo/Algos.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Algo/Algos.inl