xLib: xl::db::mysql::Query Class Reference
xl::db::mysql::Query Class Reference
MySql query.
#include "Query.h"
Public Member Functions
ctors, dtor
Query (const Connection &conn, std::ctstring_t &sql)
virtual ~Query ()=default
xNO_DEFAULT_CONSTRUCT (Query)
xNO_COPY_ASSIGN (Query)
Executes the SQL statement
void_t exec () const
StoreResult store () const
UseResult use () const
Detailed Description
MySql query.
Constructor & Destructor Documentation
Query()
xl::db::mysql::Query::Query (const Connection & conn, std::ctstring_t & sql)
  :
    _conn{a_conn},
    _sql {a_sql}
{
    xTEST(_conn.get().isValid());
}
References xl::db::mysql::Connection::get(), and xTEST.
~Query()
virtual xl::db::mysql::Query::~Query () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::Query::xNO_DEFAULT_CONSTRUCT (Query)
xNO_COPY_ASSIGN()
xl::db::mysql::Query::xNO_COPY_ASSIGN (Query)
exec()
void_t xl::db::mysql::Query::exec () const
{
    xTEST(_conn.get().isValid());
    std::cstring_t &asSql = xT2A(_sql);
    int_t iRv = ::mysql_real_query(_conn.get().get(), asSql.data(),
        static_cast<ulong_t>( asSql.size() ));
    xTEST_EQ_MSG(iRv, 0, Error(_conn, _sql).str());
}
References xl::db::mysql::Connection::get(), xT2A, xTEST, and xTEST_EQ_MSG.
Referenced by xl::db::mysql::Db::create(), xl::db::mysql::Db::drop(), store(), and use().
store()
StoreResult xl::db::mysql::Query::store () const
{
    exec();
    return StoreResult(_conn);
}
References exec().
Referenced by xl::db::mysql::Db::isExists(), and xl::db::mysql::Db::show().
use()
UseResult xl::db::mysql::Query::use () const
{
    exec();
    return UseResult(_conn);
}
References exec().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Query.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Query.cpp