xLib: xl::sync::ThreadStorage Class Reference
xl::sync::ThreadStorage Class Reference
thread local storage
#include "ThreadStorage.h"
Public Member Functions
bool_t isValid () const
is valid
bool_t isSet () const
is set value
void_t * value () const
get the value
void_t setValue (void_t **value) const
set value
ctors, dtor
xNO_COPY_ASSIGN (ThreadStorage)
Detailed Description
thread local storage
Definition at line 14 of file ThreadStorage.h.
Constructor & Destructor Documentation
ThreadStorage()
xl::sync::ThreadStorage::ThreadStorage ()
Definition at line 34 of file ThreadStorage.cpp.
{
    xTEST(!isValid());
    _construct_impl();
    xTEST(isValid());
}
~ThreadStorage()
xl::sync::ThreadStorage::~ThreadStorage () virtual
Definition at line 44 of file ThreadStorage.cpp.
{
    xTEST(isValid());
    _destruct_impl();
    xTEST(!isValid());
}
Member Function Documentation
isSet()
bool_t xl::sync::ThreadStorage::isSet () const
is set value
Definition at line 60 of file ThreadStorage.cpp.
{
    return _isSet_impl();
}
isValid()
bool_t xl::sync::ThreadStorage::isValid () const
is valid
Definition at line 54 of file ThreadStorage.cpp.
{
    return (_index != _indexInvalid_impl());
}
Referenced by setValue(), and value().
setValue()
void_t xl::sync::ThreadStorage::setValue (void_t ** value) const
set value
Definition at line 74 of file ThreadStorage.cpp.
{
    xTEST_PTR(a_value);
    xTEST_PTR(*a_value);
    xTEST(isValid());
    _setValue_impl(a_value);
}
References isValid().
value()
void_t * xl::sync::ThreadStorage::value () const
get the value
Definition at line 66 of file ThreadStorage.cpp.
{
    xTEST(isValid());
    return _value_impl();
}
References isValid().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/ThreadStorage.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/ThreadStorage.cpp