xLib: xl::core::Char< T > Class Template Reference
xl::core::Char< T > Class Template Reference final
character
#include "Char.h"
Public Member Functions
bool_t isAlphaNum () const
Check is alphanumeric.
bool_t isAlpha () const
Check is alphabetic.
bool_t isControl () const
Check is a control ch.
bool_t isDigitDec () const
Check is decimal digit.
bool_t isDigitHex () const
Check is hexadecimal digit.
bool_t isGraph () const
Check has graphical representation.
bool_t isPrint () const
Check is printable.
bool_t isPunct () const
Check is a punctuation.
bool_t isSpace () const
Check is a white-space.
bool_t isLower () const
Check is lowercase letter.
bool_t isUpper () const
Check is uppercase letter.
Char< T > toLower () const
Convert to lowercase.
Char< T > toUpper () const
Convert to uppercase.
std::tstring_t symbol () const
char as symbol, unprintable chars with braces "<>"
ctors, dtor
Char (const T ch)
Char (const T ch, const xTLOCALE &locale)
xNO_DEFAULT_CONSTRUCT (Char)
xNO_COPY_ASSIGN (Char)
Overrides
const T & get () const final
getter
ctors, dtor
Detailed Description
template<typename T>
class xl::core::Char< T >
character
Definition at line 16 of file Char.h.
Constructor & Destructor Documentation
Char() [1/2]
template<typename T > xl::core::Char< T >::Char (const T ch) inline explicit
Definition at line 22 of file Char.inl.
  :
    _char(a_ch)
{
}
Char() [2/2]
template<typename T > xl::core::Char< T >::Char (const T ch, const xTLOCALE & locale) inline
Definition at line 31 of file Char.inl.
  :
    _char  (a_ch),
    _locale(a_locale)
{
}
Member Function Documentation
get()
template<typename T > const T & xl::core::Char< T >::get () const inline final virtual
getter
Implements xl::interface_::IGetConstRef< T >.
Definition at line 42 of file Char.inl.
{
    return _char;
}
isAlpha()
template<typename T > bool_t xl::core::Char< T >::isAlpha () const inline
Check is alphabetic.
Definition at line 56 of file Char.inl.
{
    return static_cast<bool_t>( xTISALPHA_L(_char, _locale) );
}
isAlphaNum()
template<typename T > bool_t xl::core::Char< T >::isAlphaNum () const inline
Check is alphanumeric.
Definition at line 49 of file Char.inl.
{
    return static_cast<bool_t>( xTISALNUM_L(_char, _locale) );
}
isControl()
template<typename T > bool_t xl::core::Char< T >::isControl () const inline
Check is a control ch.
Definition at line 63 of file Char.inl.
{
    return static_cast<bool_t>( xTISCNTRL_L(_char, _locale) );
}
isDigitDec()
template<typename T > bool_t xl::core::Char< T >::isDigitDec () const inline
Check is decimal digit.
Definition at line 70 of file Char.inl.
{
    return static_cast<bool_t>( xTISDIGIT_L(_char, _locale) );
}
isDigitHex()
template<typename T > bool_t xl::core::Char< T >::isDigitHex () const inline
Check is hexadecimal digit.
Definition at line 77 of file Char.inl.
{
    return static_cast<bool_t>( xTISXDIGIT_L(_char, _locale) );
}
isGraph()
template<typename T > bool_t xl::core::Char< T >::isGraph () const inline
Check has graphical representation.
Definition at line 84 of file Char.inl.
{
    return static_cast<bool_t>( xTISGRAPH_L(_char, _locale) );
}
isLower()
template<typename T > bool_t xl::core::Char< T >::isLower () const inline
Check is lowercase letter.
Definition at line 112 of file Char.inl.
{
    return static_cast<bool_t>( xTISLOWER_L(_char, _locale) );
}
isPrint()
template<typename T > bool_t xl::core::Char< T >::isPrint () const inline
Check is printable.
Definition at line 91 of file Char.inl.
{
    return static_cast<bool_t>( xTISPRINT_L(_char, _locale) );
}
isPunct()
template<typename T > bool_t xl::core::Char< T >::isPunct () const inline
Check is a punctuation.
Definition at line 98 of file Char.inl.
{
    return static_cast<bool_t>( xTISPUNCT_L(_char, _locale) );
}
isSpace()
template<typename T > bool_t xl::core::Char< T >::isSpace () const inline
Check is a white-space.
Definition at line 105 of file Char.inl.
{
    return static_cast<bool_t>( xTISSPACE_L(_char, _locale) );
}
isUpper()
template<typename T > bool_t xl::core::Char< T >::isUpper () const inline
Check is uppercase letter.
Definition at line 119 of file Char.inl.
{
    return static_cast<bool_t>( xTISUPPER_L(_char, _locale) );
}
symbol()
template<typename T > std::tstring_t xl::core::Char< T >::symbol () const inline
char as symbol, unprintable chars with braces "<>"
FAQ: C documentation for isprint
+---------+---------------------------+-------------------+
| ASCII   | Characters                | isprint, iswprint |
+---------+---------------------------+-------------------+
| 0 - 8   | control codes (NUL, etc.) | -                 |
| 9       | tab (\t)                  | -                 |
| 10 - 13 | whitespaces (\n,\v,\f,\r) | -                 |
| 14 - 31 | control codes             | -                 |
| 32      | space                     | +                 |
| 33 - 47 | !"#$%&'()*+,-./           | +                 |
| 48 - 57 | 123456789                 | +                 |
| 58 - 64 | :;<=>?@                   | +                 |
| 65 - 70 | ABCDEF                    | +                 |
| 71 - 90 | GHIJKLMNOPQRSTUVWXYZ      | +                 |
| 91 - 96 | [\]^_`                    | +                 |
| 97 -102 | abcdef                    | +                 |
| 103-122 | ghijklmnopqrstuvwxyz      | +                 |
| 123-126 | {|}~                      | +                 |
| 127     | backspace character (DEL) | -                 |
+-------------------------------------+-------------------+
TODO: Unused
TODO: symbol() - impl
Definition at line 144 of file Char.inl.
{
    if ( Algos::isInBounds<T>(_char, 0, 31) ) {
        struct CharData
        {
            int_t          decCode;
            std::tstring_t symbol;
            std::tstring_t htmlCode;
        };
        static const CharData data[31 + 1] =
        {
            {0,  xT("NUL"), xT("&#000;")}, // Null char
            {1,  xT("SOH"), xT("&#001;")}, // Start of Heading
            {2,  xT("STX"), xT("&#002;")}, // Start of Text
            {3,  xT("ETX"), xT("&#003;")}, // End of Text
            {4,  xT("EOT"), xT("&#004;")}, // End of Transmission
            {5,  xT("ENQ"), xT("&#005;")}, // Enquiry
            {6,  xT("ACK"), xT("&#006;")}, // Acknowledgment
            {7,  xT("BEL"), xT("&#007;")}, // Bell
            {8,  xT("BS"),  xT("&#008;")}, // Back Space
            {9,  xT("HT"),  xT("&#009;")}, // Horizontal Tab
            {10, xT("LF"),  xT("&#010;")}, // Line Feed
            {11, xT("VT"),  xT("&#011;")}, // Vertical Tab
            {12, xT("FF"),  xT("&#012;")}, // Form Feed
            {13, xT("CR"),  xT("&#013;")}, // Carriage Return
            {14, xT("SO"),  xT("&#014;")}, // Shift Out / X-On
            {15, xT("SI"),  xT("&#015;")}, // Shift In / X-Off
            {16, xT("DLE"), xT("&#016;")}, // Data Line Escape
            {17, xT("DC1"), xT("&#017;")}, // Device Control 1 (oft. XON)
            {18, xT("DC2"), xT("&#018;")}, // Device Control 2
            {19, xT("DC3"), xT("&#019;")}, // Device Control 3 (oft. XOFF)
            {20, xT("DC4"), xT("&#020;")}, // Device Control 4
            {21, xT("NAK"), xT("&#021;")}, // Negative Acknowledgement
            {22, xT("SYN"), xT("&#022;")}, // Synchronous Idle
            {23, xT("ETB"), xT("&#023;")}, // End of Transmit Block
            {24, xT("CAN"), xT("&#024;")}, // Cancel
            {25, xT("EM"),  xT("&#025;")}, // End of Medium
            {26, xT("SUB"), xT("&#026;")}, // Substitute
            {27, xT("ESC"), xT("&#027;")}, // Escape
            {28, xT("FS"),  xT("&#028;")}, // File Separator
            {29, xT("GS"),  xT("&#029;")}, // Group Separator
            {30, xT("RS"),  xT("&#030;")}, // Record Separator
            {31, xT("US"),  xT("&#031;")}  // Unit Separator
        };
        return xT("<") + data[_char].symbol + xT(">");
    }
    else if ( Algos::isInBounds<T>(_char, 32, 126) ) {
        return std::tstring_t(1, static_cast<tchar_t>(_char));
    }
    else if ( Algos::isInBounds<T>(_char, 127, 255) ) {
        return xT("<?>");
    }
    return xT("<?>");
}
References xT.
Referenced by xl::core::OStream::operator<<(), xl::core::OStream::operator<<(), and xl::core::OStream::operator<<().
toLower()
template<typename T > Char< T > xl::core::Char< T >::toLower () const inline
Convert to lowercase.
Definition at line 126 of file Char.inl.
{
    const auto ch = xTTOLOWER_L(_char, _locale);
    return Char(ch, _locale);
}
Referenced by xl::system::ConsoleUI::msgBox().
toUpper()
template<typename T > Char< T > xl::core::Char< T >::toUpper () const inline
Convert to uppercase.
Definition at line 135 of file Char.inl.
{
    const auto ch = xTTOUPPER_L(_char, _locale);
    return Char(ch, _locale);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Char.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Char.inl