xLib: xl::package::curl::Error Class Reference
xl::package::curl::Error Class Reference final
CURL error.
#include "Error.h"
Inherits xl::interface_::IError< CURLcode >.
Public Member Functions
ctors, dtor
Error (cCURLcode code)
virtual ~Error ()=default
xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN (Error)
Overrides
CURLcode code () const final
Code.
bool_t isOk () const final
Check for success.
std::tstring_t category () const final
Category (type)
std::tstring_t message () const final
Detail message.
Public Member Functions inherited from xl::interface_::IError< CURLcode >
bool_t isFail () const
Check for error.
std::tstring_t str () const
Formatted message.
IError ()=default
virtual ~IError ()=default
Detailed Description
CURL error.
Constructor & Destructor Documentation
Error()
xl::package::curl::Error::Error (cCURLcode code)
  :
    _code{a_code}
{
}
~Error()
virtual xl::package::curl::Error::~Error () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::curl::Error::xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN()
xl::package::curl::Error::xNO_COPY_ASSIGN (Error)
code()
CURLcode xl::package::curl::Error::code () const final virtual
Code.
Implements xl::interface_::IError< CURLcode >.
{
    return _code;
}
Referenced by isOk(), and message().
isOk()
bool_t xl::package::curl::Error::isOk () const final virtual
Check for success.
Implements xl::interface_::IError< CURLcode >.
{
    return (code() == CURLE_OK);
}
References code().
Referenced by xl::package::curl::Client::Client(), xl::package::curl::Client::info(), message(), xl::package::curl::Client::pause(), xl::package::curl::Client::perform(), xl::package::curl::Client::receive(), xl::package::curl::Client::send(), and xl::package::curl::Client::setOption().
category()
std::tstring_t xl::package::curl::Error::category () const final virtual
Category (type)
Implements xl::interface_::IError< CURLcode >.
{
    return xT("xl::package::curl::Error");
}
References xT.
message()
std::tstring_t xl::package::curl::Error::message () const final virtual
Detail message.
Implements xl::interface_::IError< CURLcode >.
{
    if ( isOk() ) {
        return {};
    }
    cptr_cchar_t pszRv = ::curl_easy_strerror( code() );
    if (pszRv == nullptr) {
        return Const::strUnknown();
    }
    return pszRv;
}
References code(), isOk(), and xl::core::Const::strUnknown().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Error.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Error.cpp