xLib: xl::package::CsvReader Class Reference
xl::package::CsvReader Class Reference final
CSV reader.
#include "Csv.h"
Inherits xl::package::ICsv.
Public Member Functions
bool_t loadFile (std::ctstring_t &filePath)
bool_t loadString (std::ctstring_t &rawString)
bool_t loadVector (std::cvec_tstring_t &rawVector)
row_t headers () const
std::tstring_t header (std::csize_t column) const
std::size_t columns () const
std::size_t rows () const
std::tstring_t cell (std::csize_t row, std::csize_t column) const
ctors, dtor
CsvReader (cCsvOption &option)
virtual ~CsvReader ()=default
xNO_DEFAULT_CTOR (CsvReader)
xNO_COPY_ASSIGN (CsvReader)
Additional Inherited Members
Public Types inherited from xl::package::ICsv
using row_t = std::vec_tstring_t
using rows_t {}
Detailed Description
CSV reader.
Constructor & Destructor Documentation
CsvReader()
xl::package::CsvReader::CsvReader (cCsvOption & option) explicit
  :
    _option(a_option)
{
}
~CsvReader()
virtual xl::package::CsvReader::~CsvReader () virtual default
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::package::CsvReader::xNO_DEFAULT_CTOR (CsvReader)
xNO_COPY_ASSIGN()
xl::package::CsvReader::xNO_COPY_ASSIGN (CsvReader)
loadFile()
bool_t xl::package::CsvReader::loadFile (std::ctstring_t & filePath)
{
    FileText file(a_filePath);
    std::tstring_t content;
    file.read(&content);
    return loadString(content);
}
References loadString(), and xl::fs::FileText::read().
loadString()
bool_t xl::package::CsvReader::loadString (std::ctstring_t & rawString)
{
    std::vec_tstring_t lines;
    String::split(a_rawString, _option.eol, &lines);
    // Last empty line - rm
    if (!lines.empty() &&
        lines.back().empty())
    {
        lines.pop_back();
    }
    return loadVector(lines);
}
References loadVector(), and xl::core::String::split().
Referenced by loadFile().
loadVector()
bool_t xl::package::CsvReader::loadVector (std::cvec_tstring_t & rawVector)
{
    _rows.clear();
    std::ctstring_t delimiter(1, _option.delimiter);
    for (const auto &it_line : a_rawVector) {
        row_t row;
        String::split(it_line, delimiter, &row);
        _rows.push_back(std::move(row));
    }
    return _isValid();
}
References xl::core::String::split().
Referenced by loadString().
headers()
ICsv::row_t xl::package::CsvReader::headers () const
{
    return _rows.at(0);
}
Referenced by columns(), and header().
header()
std::tstring_t xl::package::CsvReader::header (std::csize_t column) const
{
    return headers().at(a_column);
}
References headers().
columns()
std::size_t xl::package::CsvReader::columns () const
{
    return headers().size();
}
References headers().
rows()
std::size_t xl::package::CsvReader::rows () const
{
    return _rows.size();
}
cell()
std::tstring_t xl::package::CsvReader::cell (std::csize_t a_row, std::csize_t a_column) const
Parameters
a_row row
a_column column
{
    return _rows.at(a_row).at(a_column);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Csv.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Csv.cpp