xLib: xl::interface_::IContainer< T > Class Template Reference
xl::interface_::IContainer< T > Class Template Reference abstract
Container.
#include "IContainer.h"
Public Types
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using pointer = T *
using const_pointer = const T *
using iterator = value_type *
using const_iterator = const value_type *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
virtual iterator begin ()=0
virtual const_iterator cbegin () const =0
virtual iterator end ()=0
virtual const_iterator cend () const =0
virtual size_type size () const =0
virtual pointer data ()=0
bool empty () const
reverse_iterator rbegin ()
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator crend () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
const_pointer data () const
ctors, dtor
IContainer ()=default
virtual ~IContainer ()=default
Detailed Description
template<typename T>
class xl::interface_::IContainer< T >
Container.
Member Typedef Documentation
value_type
template<typename T > using xl::interface_::IContainer< T >::value_type = T
size_type
template<typename T > using xl::interface_::IContainer< T >::size_type = std::size_t
difference_type
template<typename T > using xl::interface_::IContainer< T >::difference_type = std::ptrdiff_t
reference
template<typename T > using xl::interface_::IContainer< T >::reference = value_type &
const_reference
template<typename T > using xl::interface_::IContainer< T >::const_reference = const value_type &
pointer
template<typename T > using xl::interface_::IContainer< T >::pointer = T *
const_pointer
template<typename T > using xl::interface_::IContainer< T >::const_pointer = const T *
iterator
template<typename T > using xl::interface_::IContainer< T >::iterator = value_type *
const_iterator
template<typename T > using xl::interface_::IContainer< T >::const_iterator = const value_type *
reverse_iterator
template<typename T > using xl::interface_::IContainer< T >::reverse_iterator = std::reverse_iterator<iterator>
const_reverse_iterator
template<typename T > using xl::interface_::IContainer< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Constructor & Destructor Documentation
IContainer()
template<typename T > xl::interface_::IContainer< T >::IContainer () default
~IContainer()
template<typename T > virtual xl::interface_::IContainer< T >::~IContainer () virtual default
Member Function Documentation
begin()
template<typename T > virtual iterator xl::interface_::IContainer< T >::begin () pure virtual
Referenced by xl::interface_::IContainer< T >::crend(), xl::interface_::IContainer< T >::front(), xl::interface_::IContainer< T >::front(), and xl::interface_::IContainer< T >::rend().
cbegin()
template<typename T > virtual const_iterator xl::interface_::IContainer< T >::cbegin () const pure virtual
end()
template<typename T > virtual iterator xl::interface_::IContainer< T >::end () pure virtual
Referenced by xl::interface_::IContainer< T >::back(), xl::interface_::IContainer< T >::crbegin(), and xl::interface_::IContainer< T >::rbegin().
cend()
template<typename T > virtual const_iterator xl::interface_::IContainer< T >::cend () const pure virtual
size()
template<typename T > virtual size_type xl::interface_::IContainer< T >::size () const pure virtual
Referenced by xl::interface_::IContainer< T >::back(), and xl::interface_::IContainer< T >::empty().
data() [1/2]
template<typename T > virtual pointer xl::interface_::IContainer< T >::data () pure virtual
Referenced by xl::interface_::IContainer< T >::data().
empty()
template<typename T > bool xl::interface_::IContainer< T >::empty () const inline
    {
        return (size() == 0);
    }
References xl::interface_::IContainer< T >::size().
rbegin()
template<typename T > reverse_iterator xl::interface_::IContainer< T >::rbegin () inline
    {
        return reverse_iterator( end() );
    }
References xl::interface_::IContainer< T >::end().
crbegin()
template<typename T > const_reverse_iterator xl::interface_::IContainer< T >::crbegin () const inline
    {
        return const_reverse_iterator( end() );
    }
References xl::interface_::IContainer< T >::end().
rend()
template<typename T > reverse_iterator xl::interface_::IContainer< T >::rend () inline
    {
        return reverse_iterator( begin() );
    }
References xl::interface_::IContainer< T >::begin().
crend()
template<typename T > const_reverse_iterator xl::interface_::IContainer< T >::crend () const inline
    {
        return const_reverse_iterator( begin() );
    }
References xl::interface_::IContainer< T >::begin().
front() [1/2]
template<typename T > reference xl::interface_::IContainer< T >::front () inline
    {
        return *begin();
    }
References xl::interface_::IContainer< T >::begin().
front() [2/2]
template<typename T > const_reference xl::interface_::IContainer< T >::front () const inline
    {
        return *begin();
    }
References xl::interface_::IContainer< T >::begin().
back() [1/2]
template<typename T > reference xl::interface_::IContainer< T >::back () inline
    {
        return size() ? *(end() - 1) : *end();
    }
References xl::interface_::IContainer< T >::end(), and xl::interface_::IContainer< T >::size().
Referenced by xl::interface_::IContainer< T >::back().
back() [2/2]
template<typename T > const_reference xl::interface_::IContainer< T >::back () const inline
    {
        return back();
    }
References xl::interface_::IContainer< T >::back().
data() [2/2]
template<typename T > const_pointer xl::interface_::IContainer< T >::data () const inline
    {
        return data();
    }
References xl::interface_::IContainer< T >::data().
The documentation for this class was generated from the following file:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Interface/IContainer.h