xLib: xl::debug::Exception Class Reference
xl::debug::Exception Class Reference
exception
#include "Exception.h"
Public Member Functions
std::ctstring_t & what () const
get message
ctors, dtor
Exception ()=default
virtual ~Exception ()=default
operators
template<typename T >
Exception & operator<< (const T &msgT)
Detailed Description
exception
Constructor & Destructor Documentation
Exception()
xl::debug::Exception::Exception () default
~Exception()
virtual xl::debug::Exception::~Exception () virtual default
Member Function Documentation
operator<<()
template<typename T > Exception & xl::debug::Exception::operator<< (const T & msgT)
{
    _msgT.append( Format::str(xT("{}"), a_msgT) );
    return *this;
}
References xl::core::FormatT< StreamT >::str(), and xT.
what()
std::ctstring_t & xl::debug::Exception::what () const
get message
{
    return _msgT;
}
Referenced by xl::package::Application::run(), and xl::test::Unit::run().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Exception.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Exception.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Exception.inl