xLib: xl::sync::Event Class Reference
xl::sync::Event Class Reference
event
#include "Event.h"
Public Types
enum class ObjectState : ulong_t
Public Member Functions
void_t create ()
create
void_t set ()
signal the event for the waiting thread (!!! unlock !!!)
void_t reset ()
once signaled, the event class must be "reset" before responding to a new signal
ObjectState wait (culong_t &timeoutMs=xTIMEOUT_INFINITE)
bool_t isSignaled () const
is signaled
ctors, dtor
Event (cbool_t isAutoReset, cbool_t isSignaled)
virtual ~Event ()
Private Member Functions
const handle_t & _handle_impl () const
void_t _create_impl ()
void_t _set_impl ()
void_t _reset_impl ()
ObjectState _wait_impl (culong_t &timeoutMs=xTIMEOUT_INFINITE)
bool_t _isSignaled_impl () const
Private Attributes
cbool_t _isAutoReset {}
auto-reset flag
cbool_t _initState {}
initial state
xPLATFORM_IMPL __pad0__: void_t _dectruct_impl()
Detailed Description
event
Definition at line 15 of file Event.h.
Constructor & Destructor Documentation
Event()
xl::sync::Event::Event (cbool_t a_isAutoReset, cbool_t a_isSignaled)
Parameters
a_isAutoReset is auto reset
a_isSignaled is signaled (false - wait, lock)
Definition at line 26 of file Event.cpp.
   :
 #if   xENV_WIN
     // n/a
 #elif xENV_UNIX
     _isSignaled (a_isSignaled),
 #endif
     _isAutoReset(a_isAutoReset),
     _initState  (a_isSignaled)
 {
 }
Member Function Documentation
_wait_impl()
Event::ObjectState xl::sync::Event::_wait_impl (culong_t & a_timeoutMs = xTIMEOUT_INFINITE) private
Parameters
a_timeoutMs in milliseconds
Definition at line 89 of file Event_unix.inl.
 {
     ObjectState osRv = ObjectState::osFailed;
     int_t iRv = - 1;
     iRv = ::pthread_mutex_lock(&_mutex);
     xTEST_EQ_MSG(iRv, 0, NativeError::format( static_cast<ulong_t>(iRv) ));
     {
         // if (!_isSignaled) {
             timespec timeoutMsec {};
             if (a_timeoutMs != xTIMEOUT_INFINITE) {
                 timeval timeNow  = {0, 0};
                 iRv = ::gettimeofday(&timeNow, nullptr);
                 xTEST_DIFF(iRv, - 1);
                 timeoutMsec.tv_sec  = timeNow.tv_sec + static_cast<time_t>(a_timeoutMs) / 1000;
                 timeoutMsec.tv_nsec = timeNow.tv_usec * 1000 + (static_cast<time_t>(a_timeoutMs) % 1000) * 1000000;
                 // handle overflow
                 if (timeoutMsec.tv_nsec >= 1000000000) {
                     Trace() << xT("::: xLib: Event::osWait - handle overflow :::");
                     ++ timeoutMsec.tv_sec;
                     timeoutMsec.tv_nsec -= 1000000000;
                 }
             }
             // wait until condition thread returns control
             do {
                 if (a_timeoutMs == xTIMEOUT_INFINITE) {
                     iRv = ::pthread_cond_wait     (&_cond, &_mutex);
                 } else {
                     iRv = ::pthread_cond_timedwait(&_cond, &_mutex, &timeoutMsec);
                 }
             }
             while (!iRv && !_isSignaled);
         // } else {
         //    iRv = 0;
         // }
         Trace() << xTRACE_VAR(iRv);
         // adjust signaled member
         switch (iRv) {
         case 0:
             if (_isAutoReset) {
                 _isSignaled = false;
             }
             osRv = ObjectState::osSignaled;
             break;
         case ETIMEDOUT:
             osRv = ObjectState::osTimeout;
             if (_isAutoReset) {
                 _isSignaled = false;
             } else {
                 osRv = _initState ? ObjectState::osSignaled : ObjectState::osTimeout;
                 _isSignaled = _initState;
             }
             break;
         }
     }
     iRv = ::pthread_mutex_unlock(&_mutex);
     xTEST_EQ_MSG(iRv, 0, NativeError::format( static_cast<ulong_t>(iRv) ));
     return osRv;
 }
Referenced by wait().
wait()
Event::ObjectState xl::sync::Event::wait (culong_t & a_timeoutMs = xTIMEOUT_INFINITE)
wait either for the Event to be signaled by another thread or for the specified timeout duration
Parameters
a_timeoutMs timeout (msec)
Definition at line 71 of file Event.cpp.
 {
     xTEST_NA(a_timeoutMs);
     ObjectState osRv = _wait_impl(a_timeoutMs);
     xTEST_EQ_MSG((osRv == ObjectState::osSignaled) || (osRv == ObjectState::osTimeout), true,
         NativeError::format( static_cast<ulong_t>(osRv) ));
     return osRv;
 }
References _wait_impl(), and xTEST_NA.
Referenced by xl::sync::Thread::_waitResumption().
The documentation for this class was generated from the following files:
/home/skynowa/Projects/xLib/Include/xLib/Sync/Event.h
/home/skynowa/Projects/xLib/Include/xLib/Sync/Event.cpp
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Unix/Event_unix.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Win/Event_win.inl