xLib: xl::package::JsonReader Class Reference
xl::package::JsonReader Class Reference
#include "JsonReader.h"
Public Member Functions
const json & get () const
get nlohmann::json object
std::tstring_t str () const
most compact representation
std::tstring_t plain (std::ctstring_t &indent) const
plain text
std::tstring_t plain (std::clist_tstring_t &json_ptrs, std::ctstring_t &indent) const
plain text
std::tstring_t format () const
pretty-printed with indent level, newlines
void print (std::tostream_t &out_os) const
implement std::ostream operator <<
ctors, dtor
JsonReader ()=default
JsonReader (ctchar_t *json_cstr)
JsonReader (std::ctstring_t &json_str)
JsonReader (const json &json_object)
JsonReader (const std::filesystem::path &json_path)
~JsonReader ()=default
xNO_COPY_ASSIGN (JsonReader)
void loadCString (ctchar_t *json_cstr)
void loadString (std::ctstring_t &json_str)
void loadJson (const json &json_object)
void loadFile (const std::filesystem::path &json_path)
bool isValid () const
operator bool () const
Getters by JSON pointer
std::tstring_t getContentStr (std::ctstring_t &json_ptr) const
std::tstring_t getContentStr (std::clist_tstring_t &json_ptrs) const
void getContentList (std::ctstring_t &json_ptr, std::list< JsonReader > &nodes) const
void getContentList (std::clist_tstring_t &json_ptrs, std::list< JsonReader > &nodes) const
void getContentList (std::ctstring_t &json_ptr, std::ctstring_t &key, std::list_tstring_t &values) const
bool getContent (std::ctstring_t &json_ptr, JsonReader &node) const
bool findContent (std::clist_tstring_t &json_ptrs, JsonReader &node) const
Constructor & Destructor Documentation
JsonReader() [1/5]
xl::package::JsonReader::JsonReader () default
JsonReader() [2/5]
xl::package::JsonReader::JsonReader (ctchar_t * a_json_cstr) explicit
Parameters
a_json_cstr JSON string
{
    loadCString(a_json_cstr);
}
References loadCString().
JsonReader() [3/5]
xl::package::JsonReader::JsonReader (std::ctstring_t & a_json_str) explicit
Parameters
a_json_str JSON string
{
    loadString(a_json_str);
}
References loadString().
JsonReader() [4/5]
xl::package::JsonReader::JsonReader (const json & a_json_object) explicit
Parameters
a_json_object JSON object
{
    loadJson(a_json_object);
}
References loadJson().
JsonReader() [5/5]
xl::package::JsonReader::JsonReader (const std::filesystem::path & a_json_path) explicit
Parameters
a_json_path JSON file path
{
    loadFile(a_json_path);
}
References loadFile().
~JsonReader()
xl::package::JsonReader::~JsonReader () default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::package::JsonReader::xNO_COPY_ASSIGN (JsonReader)
loadCString()
void xl::package::JsonReader::loadCString (ctchar_t * a_json_cstr)
Parameters
a_json_cstr JSON C-string
{
    xTEST(a_json_cstr != nullptr);
    if ( !json::accept(a_json_cstr) ) {
        return;
    }
    const_cast<json &>(_json_object) = json::parse(a_json_cstr, parse_cb,
        parse_allow_exceptions, parse_ignore_comments);
}
References xl::package::parse_allow_exceptions, xl::package::parse_cb, xl::package::parse_ignore_comments, and xTEST.
Referenced by JsonReader().
loadString()
void xl::package::JsonReader::loadString (std::ctstring_t & a_json_str)
Parameters
a_json_str JSON string
{
    xTEST(!a_json_str.empty());
    if ( !json::accept(a_json_str) ) {
        return;
    }
    const_cast<json &>(_json_object) = json::parse(a_json_str, parse_cb,
        parse_allow_exceptions, parse_ignore_comments);
}
References xl::package::parse_allow_exceptions, xl::package::parse_cb, xl::package::parse_ignore_comments, and xTEST.
Referenced by JsonReader().
loadJson()
void xl::package::JsonReader::loadJson (const json & a_json_object)
Parameters
a_json_object JSON object
{
    xTEST(!a_json_object.empty());
    const_cast<json &>(_json_object) = a_json_object;
}
References xTEST.
Referenced by getContent(), and JsonReader().
loadFile()
void xl::package::JsonReader::loadFile (const std::filesystem::path & a_json_path)
Parameters
a_json_path JSON file path
{
    xTEST(!a_json_path.empty());
    xTEST(std::filesystem::exists(a_json_path));
    std::ifstream ifs(a_json_path);
    if ( !ifs.is_open() ) {
        return;
    }
    if ( !json::accept(ifs) ) {
        return;
    }
    // Need after json::accept
    ifs.clear();                 // Reset eof state
    ifs.seekg(0, std::ios::beg); // Seek to the begin of the file
    const_cast<json &>(_json_object) = json::parse(ifs, parse_cb,
        parse_allow_exceptions, parse_ignore_comments);
}
References xl::package::parse_allow_exceptions, xl::package::parse_cb, xl::package::parse_ignore_comments, and xTEST.
Referenced by JsonReader().
isValid()
bool xl::package::JsonReader::isValid () const
{
    if ( _json_object.is_null() ) {
    #if xJSON_READER_LOG
        LogCout() << "[JsonReader] " << xTRACE_VAR_2(_json_object, _json_object.is_null());
    #endif
        return false;
    }
    if ( _json_object.empty() ) {
    #if xJSON_READER_LOG
        LogCout() << "[JsonReader] " << xTRACE_VAR_2(_json_object, _json_object.empty());
    #endif
        return false;
    }
    if ( _json_object.is_discarded() ) {
    #if xJSON_READER_LOG
        LogCout() << "[JsonReader] " << xTRACE_VAR_2(_json_object, _json_object.is_discarded());
    #endif
        return false;
    }
    if ( !_json_object.is_structured() ) {
    #if xJSON_READER_LOG
        LogCout()
            << "[JsonReader] "
            << xTRACE_VAR_5(_json_object, _json_object.empty(), _json_object.is_object(),
                _json_object.is_array(), _json_object.is_structured())
            << " - is_structured";
    #endif
        return false;
    }
    return true;
}
References xTRACE_VAR_2, and xTRACE_VAR_5.
operator bool()
xl::package::JsonReader::operator bool () const explicit
{
    return isValid();
}
getContentStr() [1/2]
std::tstring_t xl::package::JsonReader::getContentStr (std::ctstring_t & a_json_ptr) const
Parameters
a_json_ptr json_pointer as string
{
    if ( !_isJsonPtrValid(a_json_ptr) ) {
        return {};
    }
    const json::json_pointer json_ptr(a_json_ptr);
    if ( !_json_object.contains(json_ptr) ) {
        return {};
    }
    if ( _json_object[json_ptr].is_null() ) {
        return {};
    }
    if ( _json_object[json_ptr].is_string() ) {
        return _json_object[json_ptr].get<std::tstring_t>();
    }
    return _json_object[json_ptr].dump();
}
Referenced by getContentStr().
getContentStr() [2/2]
std::tstring_t xl::package::JsonReader::getContentStr (std::clist_tstring_t & a_json_ptrs) const
Parameters
a_json_ptrs alternative json_pointers as strings
{
    for (const auto &it_json_ptr : a_json_ptrs) {
        std::ctstring_t &result = getContentStr(it_json_ptr);
        if ( !result.empty() ) {
            return result;
        }
    }
    return {};
}
References getContentStr().
getContentList() [1/3]
void xl::package::JsonReader::getContentList (std::ctstring_t & a_json_ptr, std::list< JsonReader > & out_nodes) const
Parameters
a_json_ptr json_pointer as string
[out] out_nodes
{
    out_nodes.clear();
    if ( !_isJsonPtrValid(a_json_ptr) ) {
        return;
    }
    const json::json_pointer json_ptr(a_json_ptr);
    if ( !_json_object.contains(json_ptr) ) {
        return;
    }
    if ( _json_object[json_ptr].is_null() ) {
        return;
    }
    if ( !_json_object[json_ptr].is_array() ) {
        return;
    }
    const auto &nodes = _json_object[json_ptr].get<std::list<json>>();
    for (const auto &it_node : nodes) {
        out_nodes.emplace_back(it_node);
    }
}
Referenced by getContentList().
getContentList() [2/3]
void xl::package::JsonReader::getContentList (std::clist_tstring_t & a_json_ptrs, std::list< JsonReader > & out_nodes) const
Parameters
a_json_ptrs json_pointers as string
[out] out_nodes
{
    out_nodes.clear();
    for (const auto &it_json_ptr : a_json_ptrs) {
        JsonReader node;
        getContent(it_json_ptr, node);
        if (!node) {
            continue;
        }
        // [out]
        out_nodes.emplace_back( node.get() );
    }
}
References get(), and getContent().
getContentList() [3/3]
void xl::package::JsonReader::getContentList (std::ctstring_t & a_json_ptr, std::ctstring_t & a_key, std::list_tstring_t & out_values) const
Parameters
a_json_ptr json_pointer as string
a_key JSON field key (without "/")
[out] out_values
{
    out_values.clear();
    if ( a_key.empty() ) {
        return;
    }
    std::list<JsonReader> results;
    getContentList(a_json_ptr, results);
    for (const auto &it_result : results) {
    #if 0
        if ( it_result.contains(a_key) ) {
            out_values.emplace_back( it_result[a_key] );
        }
    #elif 0
        if ( it_result.get().contains(a_key) ) {
            out_values.emplace_back( it_result.get()[a_key] );
        }
    #else
        std::ctstring_t value = it_result.getContentStr("/" + a_key);
        if ( !value.empty() ) {
            out_values.emplace_back(value);
        }
    #endif
    }
}
References getContentList().
getContent()
bool xl::package::JsonReader::getContent (std::ctstring_t & a_json_ptr, JsonReader & out_node) const
out_node.clear();
Parameters
a_json_ptr json_pointer as string
[out] out_node
{
    /// out_node.clear();
    if ( !_isJsonPtrValid(a_json_ptr) ) {
        return false;
    }
    const json::json_pointer json_ptr(a_json_ptr);
    if ( !_json_object.contains(json_ptr) ) {
        return false;
    }
    if ( _json_object[json_ptr].is_null() ) {
        return false;
    }
    if ( !_json_object[json_ptr].is_structured() ) {
        return false;
    }
    const auto &node = _json_object[json_ptr].get<json>();
    out_node.loadJson(node);
    return true;
}
References loadJson().
Referenced by findContent(), getContentList(), and plain().
findContent()
bool xl::package::JsonReader::findContent (std::clist_tstring_t & a_json_ptrs, JsonReader & out_node) const
out_node.clear();
Parameters
a_json_ptrs json_pointer(s) as string
[out] out_node
{
    /// out_node.clear();
    for (std::ctstring_t &it_json_ptr : a_json_ptrs) {
        bool brv = getContent(it_json_ptr, out_node);
        if (brv) {
            return true;
        }
    }
    return false;
}
References getContent().
get()
const json & xl::package::JsonReader::get () const
get nlohmann::json object
{
    return _json_object;
}
Referenced by getContentList().
str()
std::tstring_t xl::package::JsonReader::str () const
most compact representation
{
    return _json_object.dump();
}
plain() [1/2]
std::tstring_t xl::package::JsonReader::plain (std::ctstring_t & a_indent) const
plain text
Parameters
a_indent [default] ""
{
    return _toPlain(_json_object, a_indent);
}
Referenced by plain().
plain() [2/2]
std::tstring_t xl::package::JsonReader::plain (std::clist_tstring_t & a_json_ptrs, std::ctstring_t & a_indent) const
plain text
Parameters
a_json_ptrs json_pointers as string
a_indent [default] ""
{
    std::tstring_t srv;
    std::ctstring_t colon = xT(":");
    std::ctstring_t nl    = xT("\n");
    for (const auto &it_json_ptr : a_json_ptrs) {
        JsonReader node;
        getContent(it_json_ptr, node);
        if (!node) {
            continue;
        }
        // [out]
        srv += a_indent + _getParentKey(it_json_ptr) + colon + nl;
        srv += a_indent + node.plain(a_indent) + nl;
    }
    srv = String::trimSpace(srv);
    return srv;
}
References getContent(), plain(), xl::core::String::trimSpace(), and xT.
format()
std::tstring_t xl::package::JsonReader::format () const
pretty-printed with indent level, newlines
{
    std::tstring_t srv;
    cint_t   json_indent       = 4;
    ctchar_t json_indent_char  = xT(' ');
    cbool_t  json_ensure_ascii = false;
#if defined(JSON_NOEXCEPTION)
    srv = _json_object.dump(json_indent, json_indent_char, json_ensure_ascii);
#else
    std::tstring_t error_msg;
    try {
        srv = _json_object.dump(json_indent, json_indent_char, json_ensure_ascii);
    }
    catch (const json::parse_error &a_e) {
        error_msg = a_e.what();
    }
    catch (const json::exception &a_e) {
        error_msg = a_e.what();
    }
    catch (const std::exception &a_e) {
        error_msg = a_e.what();
    }
    catch (...) {
        error_msg = xT("unknown");
    }
    STD_TEST_DO(error_msg.empty(), std::cout << STD_TRACE_VAR(error_msg) << std::endl);
#endif
    return srv;
}
References xT.
Referenced by print().
print()
void xl::package::JsonReader::print (std::tostream_t & out_os) const
implement std::ostream operator <<
Parameters
[in,out] out_os
{
    out_os << format();
}
References format().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Package/Json/JsonReader.h
/home/runner/work/xLib/xLib/Include/xLib/Package/Json/JsonReader.cpp