xLib: xl::core::DtUtils Class Reference
xl::core::DtUtils Class Reference final
#include "DtUtils.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CTOR (DtUtils)
xNO_COPY_ASSIGN (DtUtils)
Static Public Member Functions
static std::tuple< std::tm, int_t > currentTm (cbool_t isUtc)
Build both parts from one captured now value to keep DateTime internally coherent.
static std::tuple< std::time_t, int_t > totalMsecToTime_t (const int64_t totalMsec)
msec -> std::tuple
static std::time_t tmToPosixUtc (const std::tm &tm)
UTC std::tm -> POSIX seconds.
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::core::DtUtils::xNO_DEFAULT_CTOR (DtUtils)
xNO_COPY_ASSIGN()
xl::core::DtUtils::xNO_COPY_ASSIGN (DtUtils)
currentTm()
std::tuple< std::tm, int_t > xl::core::DtUtils::currentTm (cbool_t isUtc) static
Build both parts from one captured now value to keep DateTime internally coherent.
{
    // POSIX time (seconds since 1970-01-01 00:00:00 UTC (GMT))
    const auto        now    = std::chrono::system_clock::now();
    const std::time_t nowSec = std::chrono::system_clock::to_time_t(now);
    const std::tm     t      = a_isUtc ? *std::gmtime(&nowSec) : *std::localtime(&nowSec);
    const auto        msPart = std::chrono::duration_cast<std::chrono::milliseconds>(
        now.time_since_epoch()) % 1000;
    return {t, static_cast<int>(msPart.count())};
}
Referenced by xl::core::Date::currentLocal(), xl::core::DateTime::currentLocal(), xl::core::Time::currentLocal(), xl::core::Date::currentUTC(), xl::core::DateTime::currentUTC(), and xl::core::Time::currentUTC().
totalMsecToTime_t()
std::tuple< std::time_t, int_t > xl::core::DtUtils::totalMsecToTime_t (const int64_t totalMsec) static
msec -> std::tuple
{
    const int64_t sec    = a_totalmsec / 1000;
    const int64_t msPart = a_totalmsec % 1000;
    if (msPart < 0) {
        return {sec - 1, msPart + 1000};
    }
    return {sec, msPart};
}
Referenced by xl::core::Date::fromTotalMsec(), and xl::core::Time::fromTotalMsec().
tmToPosixUtc()
std::time_t xl::core::DtUtils::tmToPosixUtc (const std::tm & tm) static
UTC std::tm -> POSIX seconds.
{
    std::tm tm = a_tm;
#if xENV_WIN
    return ::_mkgmtime(&tm);
#else
    return ::timegm(&tm);
#endif
}
Referenced by xl::core::Date::toPosixTime(), xl::core::DateTime::toPosixTime(), and xl::core::Date::toTotalMsec().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/DtUtils.h
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/DtUtils.cpp