xLib: xl::fs::DirTemp Class Reference
xl::fs::DirTemp Class Reference
Temporary directory.
#include "DirTemp.h"
Public Member Functions
const Dir & dir () const
dir path (with unique postfix)
void_t create () const
create temporary dir
ctors, dtor
DirTemp (std::ctstring_t &dirPath, cbool_t isRandomPostfix, cbool_t isAutoDelete)
virtual ~DirTemp ()
xNO_DEFAULT_CONSTRUCT (DirTemp)
xNO_COPY_ASSIGN (DirTemp)
Detailed Description
Temporary directory.
Constructor & Destructor Documentation
DirTemp()
xl::fs::DirTemp::DirTemp (std::ctstring_t & dirPath, cbool_t isRandomPostfix, cbool_t isAutoDelete) explicit
  :
    _dir         (a_dirPath + (a_isRandomPostfix ? (xT("_") + Guid().str()) : xT(""))),
    _isAutoDelete(a_isAutoDelete)
{
    xTEST(!a_dirPath.empty());
}
References xTEST.
~DirTemp()
xl::fs::DirTemp::~DirTemp () virtual
{
    if (_isAutoDelete) {
        _dir.pathDelete();
    }
}
References xl::fs::Dir::pathDelete().
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::DirTemp::xNO_DEFAULT_CONSTRUCT (DirTemp)
xNO_COPY_ASSIGN()
xl::fs::DirTemp::xNO_COPY_ASSIGN (DirTemp)
dir()
const Dir & xl::fs::DirTemp::dir () const
dir path (with unique postfix)
{
    return _dir;
}
Referenced by xl::test::Unit::run().
create()
void_t xl::fs::DirTemp::create () const
create temporary dir
{
    _dir.pathCreate();
}
References xl::fs::Dir::pathCreate().
Referenced by xl::test::Unit::run().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/DirTemp.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/DirTemp.cpp