xLib: xl::sync::AutoMutex Class Reference
xl::sync::AutoMutex Class Reference
auto critical section
#include "AutoMutex.h"
Public Member Functions
ctors, dtor
AutoMutex (Mutex *mutex)
virtual ~AutoMutex ()
xNO_COPY_ASSIGN (AutoMutex)
Detailed Description
auto critical section
Constructor & Destructor Documentation
AutoMutex()
xl::sync::AutoMutex::AutoMutex (Mutex * mutex) explicit
  :
    _mutex(a_mutex)
{
    _mutex->create();
    _mutex->lock();
}
References xl::sync::Mutex::create(), and xl::sync::Mutex::lock().
~AutoMutex()
xl::sync::AutoMutex::~AutoMutex () virtual
{
    _mutex->unlock();
}
References xl::sync::Mutex::unlock().
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::AutoMutex::xNO_COPY_ASSIGN (AutoMutex)
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AutoMutex.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AutoMutex.cpp