xLib: xl::debug::Profiler Class Reference
xl::debug::Profiler Class Reference
code profiling
#include "Profiler.h"
Public Member Functions
void_t setLogPath (std::ctstring_t &logPath)
set log path
std::tstring_t logPath () const
get log path
void_t start ()
start measurement
size_t stop (cptr_ctchar_t comment,...)
stop measurement
size_t restart (cptr_ctchar_t comment,...)
stop, start measurement
ctors, dtor
Profiler ()
virtual ~Profiler ()
xNO_COPY_ASSIGN (Profiler)
Detailed Description
code profiling
Constructor & Destructor Documentation
Profiler()
xl::debug::Profiler::Profiler ()
{
    _reset();
}
~Profiler()
xl::debug::Profiler::~Profiler () virtual
{
    if ( !_log.filePath().empty() ) {
        _log.write(xT("----------------------------------------"));
    }
}
References xl::log::FileLog::filePath(), xl::log::FileLog::write(), and xT.
Member Function Documentation
xNO_COPY_ASSIGN()
xl::debug::Profiler::xNO_COPY_ASSIGN (Profiler)
setLogPath()
void_t xl::debug::Profiler::setLogPath (std::ctstring_t & logPath)
set log path
{
    _log.setFilePath(a_logPath);
}
References xl::log::FileLog::setFilePath().
Referenced by xl::debug::AutoProfiler::AutoProfiler().
logPath()
std::tstring_t xl::debug::Profiler::logPath () const
get log path
{
    return _log.filePath();
}
References xl::log::FileLog::filePath().
start()
void_t xl::debug::Profiler::start ()
start measurement
{
    xTEST(!_isStarted);
    _reset();
    // TODO: [skynowa] set highest thread priority
    {
    }
    _start = std::clock();
    xTEST_DIFF(static_cast<clock_t>( - 1 ), _start);
    _isStarted = true;
}
References xTEST, and xTEST_DIFF.
Referenced by xl::debug::AutoProfiler::AutoProfiler(), and restart().
stop()
size_t xl::debug::Profiler::stop (cptr_ctchar_t comment, ...)
stop measurement
{
    xTEST(_isStarted);
    // stop, get duration
    {
        _stop = std::clock();
        xTEST_DIFF(static_cast<clock_t>( - 1 ), _stop);
        _duration = _stop - _start;
        xTEST_LESS_EQ(static_cast<clock_t>( 0 ), _duration);
    }
    cdouble_t   durationMsec1 = (static_cast<double>( _duration ) /
        static_cast<double>( CLOCKS_PER_SEC )) * 1000.0;  // 1 sec = 1000 msec
    std::size_t durationMsec2 = Utils::roundIntT<std::size_t>( durationMsec1 );
    // write to log
    if ( !_log.filePath().empty() ) {
        std::tstring_t  sRv;
        std::ctstring_t durationTime = DateTime(durationMsec2).format(xT("%H:%M:%S"));
        va_list args;
        xVA_START(args, a_comment);
        sRv = FormatC::strV(a_comment, args);
        xVA_END(args);
        _log.write(xT("%s: %s"), durationTime.c_str(), sRv.c_str());
    }
    _isStarted = false;
    return durationMsec2;
}
References xl::log::FileLog::filePath(), xl::core::DateTime::format(), xl::core::FormatC::strV(), xl::log::FileLog::write(), xT, xTEST, xTEST_DIFF, and xTEST_LESS_EQ.
Referenced by restart(), and xl::debug::AutoProfiler::~AutoProfiler().
restart()
size_t xl::debug::Profiler::restart (cptr_ctchar_t comment, ...)
stop, start measurement
{
    size_t uiRV = 0;
    // format comment
    std::tstring_t sRv;
    if ( !_log.filePath().empty() ) {
        va_list args;
        xVA_START(args, a_comment);
        sRv = FormatC::strV(a_comment, args);
        xVA_END(args);
    }
    // stop, start
    uiRV = stop(xT("%s"), sRv.c_str());
    start();
    return uiRV;
}
References xl::log::FileLog::filePath(), start(), stop(), xl::core::FormatC::strV(), and xT.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Profiler.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Profiler.cpp