xLib: xl::core::Date Class Reference
xl::core::Date Class Reference
Date impl.
#include "Date.h"
Inherits xl::interface_::ICompare< Date >, xl::interface_::IStr, and xl::interface_::IPrinter< std::tostream_t >.
Public Member Functions
Overrides
int_t compare (const Date &value) const final
std::tstring_t str () const final
Get as string.
void_t print (std::tostream_t &stream) const final
Ops
Date operator+ (const Duration &delta) const
Date operator- (const Duration &delta) const
Converters
int64_t toTotalMsec () const
std::time_t toPosixTime () const
Format
std::tstring_t format (std::ctstring_t &format) const
Public Member Functions inherited from xl::interface_::ICompare< Date >
ICompare ()=default
virtual ~ICompare ()=default
bool_t operator== (const Date &a_value) const
Returns true if "value" is equal to this object.
bool_t operator!= (const Date &a_value) const
Returns true if "value" is not equal to this object.
bool_t operator< (const Date &a_value) const
Returns true if "value" is less than this object.
bool_t operator<= (const Date &a_value) const
Returns true if "value" is less than or equal to this object.
bool_t operator> (const Date &a_value) const
Returns true if "value" is greater than this object.
bool_t operator>= (const Date &a_value) const
Returns true if "value" is greater than or equal to this object.
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
ctors, dtor
Date ()
Date (cint_t year, cint_t month, cint_t day)
Date (const std::tm &t)
virtual ~Date ()
xDEF_COPY_ASSIGN (Date)
int_t year () const
int_t month () const
int_t day () const
static Date currentLocal ()
🕓 local
static Date currentUTC ()
🌍 UTC
static Date fromTotalMsec (const int64_t totalMsec)
🌍 UTC
static Date fromPosix (const std::time_t posixTime)
🌍 UTC
Additional Inherited Members
Protected Member Functions inherited from xl::interface_::ICompare< Date >
virtual int_t compare (const Date &value) const=0
Compare this object to another of the same type.
Detailed Description
Date impl.
Constructor & Destructor Documentation
Date() [1/3]
xl::core::Date::Date ()
{
}
Referenced by currentLocal(), currentUTC(), fromPosix(), and fromTotalMsec().
Date() [2/3]
xl::core::Date::Date (cint_t year, cint_t month, cint_t day)
  :
    _year (a_year),
    _month(a_month),
    _day  (a_day)
{
}
Date() [3/3]
xl::core::Date::Date (const std::tm & t)
  :
    Date(a_t.tm_year + 1900, a_t.tm_mon + 1, a_t.tm_mday)
{
}
~Date()
xl::core::Date::~Date () virtual
{
}
Member Function Documentation
xDEF_COPY_ASSIGN()
xl::core::Date::xDEF_COPY_ASSIGN (Date)
currentLocal()
Date xl::core::Date::currentLocal () static
🕓 local
{
    const auto &[t, msec] = DtUtils::currentTm(false);
    xUNUSED(msec);
    return Date(t);
}
References xl::core::DtUtils::currentTm(), Date(), and xUNUSED.
currentUTC()
Date xl::core::Date::currentUTC () static
🌍 UTC
{
    const auto &[t, msec] = DtUtils::currentTm(true);
    xUNUSED (msec);
    return Date(t);
}
References xl::core::DtUtils::currentTm(), Date(), and xUNUSED.
fromTotalMsec()
Date xl::core::Date::fromTotalMsec (const int64_t totalMsec) static
🌍 UTC
{
    const auto [sec, msec] = DtUtils::totalMsecToTime_t(a_totalMsec);
    xUNUSED(msec);
    std::tm t {};
#if xENV_WIN
    if (::gmtime_s(&t, &sec) != 0) {
        return {};
    }
#else
    if (::gmtime_r(&sec, &t) == nullptr) {
        return {};
    }
#endif
    return Date(t);
}
References Date(), xl::core::DtUtils::totalMsecToTime_t(), and xUNUSED.
Referenced by operator+().
fromPosix()
Date xl::core::Date::fromPosix (const std::time_t posixTime) static
🌍 UTC
{
    const std::tm t = *std::gmtime(&a_posixTime);
    return Date(t);
}
References Date().
year()
int_t xl::core::Date::year () const
{
    return _year;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
month()
int_t xl::core::Date::month () const
{
    return _month;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
day()
int_t xl::core::Date::day () const
{
    return _day;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
compare()
int_t xl::core::Date::compare (const Date & value) const final
TODO: C++20
{
    /// TODO: C++20
    if (_year < a_value._year) return -1;
    if (_year > a_value._year) return 1;
    if (_month < a_value._month) return -1;
    if (_month > a_value._month) return 1;
    if (_day < a_value._day) return -1;
    if (_day > a_value._day) return 1;
    return 0;
}
str()
std::tstring_t xl::core::Date::str () const final virtual
Get as string.
Implements xl::interface_::IStr.
{
    std::ctstring_t fmt =
    #if xENV_APPLE
        xT("%d-%m-%Y");
    #else
        xT("%d-%m-%4Y");
    #endif
    return format(fmt);
}
References format(), and xT.
print()
void_t xl::core::Date::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
operator+()
Date xl::core::Date::operator+ (const Duration & delta) const
{
    const int64_t totalMsec = this->toTotalMsec() + a_delta.totalMsecs();
    return Date::fromTotalMsec(totalMsec);
}
References fromTotalMsec(), xl::core::Duration::totalMsecs(), and toTotalMsec().
operator-()
Date xl::core::Date::operator- (const Duration & delta) const
{
    return *this + Duration(- a_delta.totalMsecs());
}
References xl::core::Duration::totalMsecs().
toTotalMsec()
int64_t xl::core::Date::toTotalMsec () const
{
    std::tm tm {};
    tm.tm_year = _year  - 1900;
    tm.tm_mon  = _month - 1;
    tm.tm_mday = _day;
    // UTC
    std::time_t seconds = DtUtils::tmToPosixUtc(tm);
    return static_cast<int64_t>(seconds) * 1000;
}
References xl::core::DtUtils::tmToPosixUtc().
Referenced by operator+(), and xl::core::DateTime::toMsec().
toPosixTime()
std::time_t xl::core::Date::toPosixTime () const
{
    std::tm t {};
    t.tm_year = _year  - 1900;
    t.tm_mon  = _month - 1;
    t.tm_mday = _day;
    return DtUtils::tmToPosixUtc(t);
}
References xl::core::DtUtils::tmToPosixUtc().
format()
std::tstring_t xl::core::Date::format (std::ctstring_t & a_format) const
Parameters
a_format date format
{
    std::tstring_t sRv;
    std::tm date {};
    date.tm_year  = _year  - 1900;
    date.tm_mon   = _month - 1;
    date.tm_mday  = _day;
    date.tm_hour  = {};
    date.tm_min   = {};
    date.tm_sec   = {};
    date.tm_wday  = {};
    date.tm_yday  = {};
    date.tm_isdst = {};
    // LogCout() << date;
    tchar_t buff[80 + 1] {};
    std::csize_t buffSize = xSTRFTIME(&buff[0], sizeof(buff) - 1, a_format.c_str(), &date);
    xCHECK_RET(buffSize == 0, std::tstring_t());
    sRv.assign(&buff[0], buffSize);
    return sRv;
}
References xCHECK_RET.
Referenced by xl::core::DateTime::format2(), and str().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Date.h
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Date.cpp