xLib: xl::sync::Process Class Reference
xl::sync::Process Class Reference
process
#include "Process.h"
Public Types
enum class WaitStatus : ulong_t
Public Member Functions
xUSING_CONST (WaitStatus)
void_t kill (culong_t &timeoutMsec)
kills the calling process and all of its threads
handle_t handle () const
get handle
id_t id () const
get ID
std::tstring_t name () const
get name
void_t setName (std::ctstring_t &name) const
set name
bool_t isValid () const
check for the handles, IDs validness
bool_t isExists () const
check for the existence of a process ID or process group ID, see isRunning()
bool_t isCurrent () const
is current
ulong_t exitStatus () const
get termination status
ctors, dtor
Process ()
virtual ~Process ()
Static Public Member Functions
static handle_t handleById (const id_t &id)
get handle by ID
static id_t idByName (std::ctstring_t &processName)
get ID by name
static bool_t isRunning (const id_t &id)
is process running by name (with extension)
static void_t ids (std::vector< Process::id_t > *ids)
get all IDs of current processes
Current process
static bool_t isCurrent (const Process::id_t &id)
is current id
static id_t currentId ()
process ID of the calling process
static id_t currentParentId ()
process ID of the parent of the calling process
static handle_t currentHandle ()
get pseudo handle for the calling process
static void_t currentExit (cuint_t &exitCode)
ends the calling process and all its threads
static void_t currenQuicktExit (cuint_t &exitCode)
Causes normal program termination to occur without completely cleaning the resources.
Execute
static void_t execute (std::ctstring_t &filePath, std::cvec_tstring_t &params, const std::set< std::pair_tstring_t > &envs, culong_t waitTimeoutMsec, std::tstring_t *stdOut, std::tstring_t *stdError)
create, wait process
static void_t execute (std::ctstring_t &filePath, std::cvec_tstring_t &params, std::tstring_t *stdOut, std::tstring_t *stdError)
create, wait process (Without envs, with infinite wait timeout)
static void_t shellExecute (std::ctstring_t &filePathOrURL, std::cvec_tstring_t &params)
opens a file or URL in the user's preferred application
Public Attributes
xPUBLIC_STATIC __pad0__: static id_t idByHandle(const handle_t &handle)
get ID by handle
Private Member Functions
void_t _create_impl (std::ctstring_t &filePath, std::cvec_tstring_t &params, const std::set< std::pair_tstring_t > &envs, std::tstring_t *stdOut, std::tstring_t *stdError)
WaitStatus _wait_impl (culong_t &timeoutMsec)
void_t _kill_impl (culong_t &timeoutMsec)
std::tstring_t _name_impl () const
void_t _setName_impl (std::ctstring_t &name) const
bool_t _isExists_impl () const
ulong_t _exitStatus_impl () const
Static Private Member Functions
static id_t _idByHandle_impl (const handle_t &handle)
static handle_t _handleById_impl (const id_t &id)
static id_t _idByName_impl (std::ctstring_t &processName)
static void_t _ids_impl (std::vector< Process::id_t > *ids)
static bool_t _isCurrent_impl (const Process::id_t &a_id)
static id_t _currentId_impl ()
static id_t _currentParentId_impl ()
static handle_t _currentHandle_impl ()
static void_t _currentExit_impl (cuint_t &exitCode)
static void_t _shellExecute_impl (std::ctstring_t &filePathOrURL, std::ctstring_t &params)
static bool_t _isUrlFull (std::ctstring_t &url)
Private Attributes
handle_t _handle {}
id_t _pid {}
uint_t _exitStatus {}
exit code
xPLATFORM_IMPL __pad1__: void_t _destruct_impl()
Detailed Description
process
Definition at line 28 of file Process.h.
Member Function Documentation
_create_impl()
void_t xl::sync::Process::_create_impl (std::ctstring_t & filePath, std::cvec_tstring_t & params, const std::set< std::pair_tstring_t > & envs, std::tstring_t * out_stdOut, std::tstring_t * out_stdError) private
For GUI app
It probably can't find the X Display. Try adding DISPLAY=:0 to the environment
See also
https://stackoverflow.com/questions/646930/cannot-connect-to-x-server-0-0-with-a-qt-application
Parameters
[out] out_stdOut std::cout (maybe as nullptr)
[out] out_stdError std::cerr (maybe as nullptr)
Definition at line 29 of file Process_unix.inl.
 {
     if (out_stdOut != nullptr) {
         out_stdOut->clear();
     }
     if (out_stdError != nullptr) {
         out_stdError->clear();
     }
     int_t iRv {};
     // Create pipes
     Pipe pipeIn;
     pipeIn.create();
     Pipe pipeOut;
     pipeOut.create();
     Pipe pipeErr;
     pipeErr.create();
     // Create process
     const pid_t pid = ::fork();
     if      (pid == -1) {
         // Cout() << "\n::::: ChildError :::::";
         xTEST(false);
         std::exit(EXIT_FAILURE);
     }
     // Child
     else if (pid == 0) {
         // Cout() << "\n::::: ChildOk :::::";
         std::vector<char *> cmds;
         {
             cmds.push_back( const_cast<char *>(xT2A(a_filePath).c_str()) );
             for (const auto &it_param : a_params) {
                 cmds.push_back( const_cast<char *>(xT2A(it_param).c_str()) );
             }
             if ( !cmds.empty() ) {
                 cmds.push_back(nullptr);
             }
         }
         std::vector<char *> envs;
         {
             for (const auto &[it_var, it_value] : a_envs) {
                 std::ctstring_t &envVarValue = it_var + Const::equal() + it_value;
                 const auto str = const_cast<char *>(xT2A(envVarValue).c_str());
                 envs.push_back(str);
             }
             if (Environment env(xT("DISPLAY"));
                 env.isExists())
             {
                 const auto str = const_cast<char *>( xT2A(env.str()).c_str() );
                 envs.push_back(str);
             }
             if ( !envs.empty() ) {
                 envs.push_back(nullptr);
             }
         }
         if (out_stdOut != nullptr) {
             // close all other inherited descriptors child doesn't need
             ::dup2(pipeIn.handleRead(),   STDIN_FILENO);
             ::dup2(pipeOut.handleWrite(), STDOUT_FILENO);
             ::dup2(pipeErr.handleWrite(), STDERR_FILENO);
             // TODO: close all other inherited descriptors child doesn't need ?????????
             pipeIn.closeRead();
             pipeOut.closeWrite();
             pipeErr.closeWrite();
         }
         char *const *cmd = cmds.empty() ? nullptr : cmds.data();
         xTEST_PTR(cmd);
         char *const *env = envs.empty() ? nullptr : envs.data();
         cint_t status = ::execve(xT2A(a_filePath).c_str(), cmd, env);
         xTEST_DIFF(status, - 1);
         // Cout() << "\n::::: ChildOk - Finished :::::";
         (void_t)::_exit(status);  // not std::exit()
     }
     // Parent
     else if (pid > 0) {
         // Cout() << "\n::::: ParentOk :::::";
         // printf("[PARENT] PID: %lld, parent PID: %d\n", getpid(), pid);
         // read
         if (out_stdOut != nullptr) {
             // binds streams to pipes
             {
                 // pipeOut - for read
                 pipeOut.closeWrite();
                 iRv = ::dup2(pipeOut.handleRead(), STDIN_FILENO);
                 xTEST_DIFF(iRv, - 1);
                 // pipeErr - for read
                 pipeErr.closeWrite();
                 iRv = ::dup2(pipeErr.handleRead(), STDIN_FILENO);
                 xTEST_DIFF(iRv, - 1);
             }
             // reads
             *out_stdOut   += pipeOut.readAll();
             *out_stdError += pipeErr.readAll();
             // wait
             {
                 // ::waitpid(pid, nullptr, 0);
                 pipeOut.closeRead();
                 pipeErr.closeRead();
             }
         }
     }
     _handle = pid;
     _pid    = pid;
     // Cout() << "\n::::: Finished :::::";
 }
References xl::sync::Pipe::create().
_handleById_impl()
Process::handle_t xl::sync::Process::_handleById_impl (const id_t & a_id) static private
Parameters
a_id ID
Definition at line 365 of file Process_unix.inl.
 {
     handle_t hRv = static_cast<handle_t>( a_id );
     return hRv;
 }
Referenced by handleById().
_idByHandle_impl()
Process::id_t xl::sync::Process::_idByHandle_impl (const handle_t & a_handle) static private
Parameters
a_handle handle
Definition at line 355 of file Process_unix.inl.
 {
     id_t ulRv = static_cast<id_t>( a_handle );
     return ulRv;
 }
_isUrlFull()
bool_t xl::sync::Process::_isUrlFull (std::ctstring_t & a_url) static private
Parameters
a_url URL
Definition at line 350 of file Process.cpp.
 {
     // List of known URL schemes
     constexpr std::ctstring_view_t schemes[] =
     {
         xT("http://"), xT("https://"), xT("ftp://"), xT("ftps://"), xT("sftp://"),
         xT("mailto:"), xT("www."), xT("file://")
     };
     // Check if the URL starts with any of the known schemes
     for (const auto &it_scheme : schemes) {
         if (a_url.compare(0, it_scheme.size(), it_scheme) == 0) {
             return true;
         }
     }
     return false;
 }
_kill_impl()
void_t xl::sync::Process::_kill_impl (culong_t & timeoutMsec) private
TODO: [skynowa] Process::_kill_impl()
I would attempt to close a (Process with) Window(s) in the following order:
WM_CLOSE
WM_QUIT
WM_DESTROY
TerminateProcess()
Definition at line 257 of file Process_unix.inl.
 {
     int_t iRv = ::kill(_pid, SIGKILL);
     xTEST_DIFF(iRv, - 1);
     Thread::currentSleep(a_timeoutMsec);
     _exitStatus = 0U;
 }
References kill().
_shellExecute_impl()
void_t xl::sync::Process::_shellExecute_impl (std::ctstring_t & a_filePathOrURL, std::ctstring_t & a_params) static private
TODO: QProcess::startDetached() TODO: Process::create() - use ?
Parameters
a_filePathOrURL full file path or URL
a_params command line params
Definition at line 420 of file Process_unix.inl.
 {
     std::tstring_t cmdLine;
     if (FileType type(a_filePathOrURL); type.isExecutable()) {
         cmdLine = Format::str(xT("{} {}"), String::quoted(a_filePathOrURL), a_params);
     } else {
         std::tstring_t appPath;
         {
         #if   xENV_LINUX
             appPath = xT("xdg-open");
         #elif xENV_BSD
             appPath = xT("open");
         #elif xENV_APPLE
             appPath = xT("open");
         #endif
         }
         cmdLine = Format::str(xT("{} {} {}"), appPath, String::quoted(a_filePathOrURL), a_params);
     }
     cint_t iRv = std::system(cmdLine.c_str());
     xTEST_EQ(iRv, 0);
 }
References xl::fs::FileType::isExecutable().
_wait_impl()
Process::WaitStatus xl::sync::Process::_wait_impl (culong_t & a_timeoutMsec) private
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.bpxbd00/rtwaip.htm https://linux.die.net/man/2/waitpid
If unsuccessful, waitpid() returns -1 and sets errno to one of the following values:
ECHILD - The process specified by pid does not exist or is not a child of the calling process, or the process group specified by pid does not exist or does not have any member process that is a child of the calling process EINTR - waitpid() was interrupted by a signal. The value of *status_ptr is undefined EINVAL - The value of options is incorrect
If WNOHANG was given, and if there is at least one process (usually a child) whose status information is not available, waitpid() returns 0
If successful, waitpid() returns a value of the process (usually a child) whose status information has been obtained
Definition at line 177 of file Process_unix.inl.
 {
     xUNUSED(a_timeoutMsec);
     WaitStatus waitStatus = WaitStatus::Failed;
     // TODO: [skynowa] Process::_wait_impl() - a_timeoutMsec
     // Thread::currentSleep(a_timeoutMsec);
     pid_t iRv {-1};
     do {
         int_t status {};
         iRv = ::waitpid(_pid, &status, WUNTRACED | WCONTINUED /* or WNOHANG */ );
         if      (iRv == -1) {
             Cout() << "wait() - error";
             _exitStatus = static_cast<uint_t>( NativeError::get() );
             waitStatus  = WaitStatus::Failed;
         }
         else if (iRv == 0) {
             // Cout() << "Child - running";
         }
         else {
             xTEST_EQ(iRv, _pid);
             xTEST_GR(iRv, 0);
             if      ( WIFEXITED(status) ) {
                 // Cout() << "Child - exited status: " << WEXITSTATUS(status) << " (" << status << ")";
                 // WEXITSTATUS - macro should be employed only if WIFEXITED returned true
                 _exitStatus = static_cast<uint_t>( WEXITSTATUS(status) );
                 waitStatus  = WaitStatus::Ok;
             }
             else if ( WIFSIGNALED(status) ) {
                 Cout() << "Child - killed by signal " << WTERMSIG(status);
             }
             else if ( WIFSTOPPED(status) ) {
                 Cout() << "Child - stopped by signal " << WSTOPSIG(status);
             }
             else if ( WIFCONTINUED(status) ) {
                 Cout() << "Child - continued";
             }
             else {
                 Cout() << "Child - did not exit successfully";
                 _exitStatus = static_cast<uint_t>( NativeError::get() );
                 waitStatus  = WaitStatus::Abandoned;
             }
         }
     }
     while (iRv == 0);
     return waitStatus;
 }
References _exitStatus, and xUNUSED.
currenQuicktExit()
void_t xl::sync::Process::currenQuicktExit (cuint_t & exitCode) static
Causes normal program termination to occur without completely cleaning the resources.
TOOD: [xENV_APPLE] currenQuicktExit
Definition at line 271 of file Process.cpp.
 {
 #if xENV_APPLE
     std::exit( static_cast<int_t>(a_exitCode) );
 #else
     std::quick_exit( static_cast<int_t>(a_exitCode) );
 #endif
 }
execute() [1/2]
void_t xl::sync::Process::execute (std::ctstring_t & a_filePath, std::cvec_tstring_t & a_params, const std::set< std::pair_tstring_t > & a_envs, culong_t a_waitTimeoutMsec, std::tstring_t * out_stdOut, std::tstring_t * out_stdError) static
create, wait process
Parameters
a_filePath binary file path
a_params command line params
a_envs evironments ({"HOME=/usr/home", "LOGNAME=home"})
a_waitTimeoutMsec waiting timeout
[out] out_stdOut std::cout (maybe as nullptr)
[out] out_stdError std::cerr (maybe as nullptr)
Definition at line 293 of file Process.cpp.
 {
     Process proc;
     proc.create(a_filePath, a_params, a_envs, out_stdOut, out_stdError);
     xCHECK_DO(!proc.isValid(), return);
     cWaitStatus wrRes = proc.wait(a_waitTimeoutMsec);
     xTEST_EQ((int)wrRes,   (int)Process::WaitStatus::Ok);
     xTEST_DIFF((int)wrRes, (int)Process::WaitStatus::Abandoned);
 }
References isValid(), and xCHECK_DO.
Referenced by execute().
execute() [2/2]
void_t xl::sync::Process::execute (std::ctstring_t & a_filePath, std::cvec_tstring_t & a_params, std::tstring_t * out_stdOut, std::tstring_t * out_stdError) static
create, wait process (Without envs, with infinite wait timeout)
Parameters
a_filePath binary file path
a_params command line params
[out] out_stdOut std::cout (maybe as nullptr)
[out] out_stdError std::cerr (maybe as nullptr)
Definition at line 313 of file Process.cpp.
 {
     const std::set<std::pair_tstring_t> envs;
     culong_t                            waitTimeoutMsec {xTIMEOUT_INFINITE};
     execute(a_filePath, a_params, envs, waitTimeoutMsec, out_stdOut, out_stdError);
 }
References execute().
handleById()
Process::handle_t xl::sync::Process::handleById (const id_t & a_id) static
get handle by ID
Parameters
a_id ID
Definition at line 187 of file Process.cpp.
 {
     return _handleById_impl(a_id);
 }
References _handleById_impl().
kill()
void_t xl::sync::Process::kill (culong_t & a_timeoutMsec)
kills the calling process and all of its threads
Parameters
a_timeoutMsec waiting timeout
Definition at line 94 of file Process.cpp.
 {
     if ( !isExists() ) {
         return;
     }
     if (exitStatus() == EXIT_SUCCESS) {
         return;
     }
     Cout() << xT("Kill: ") << xTRACE_VAR(_pid) << std::endl;
     _kill_impl(a_timeoutMsec);
 }
References exitStatus(), and isExists().
Referenced by _kill_impl().
shellExecute()
void_t xl::sync::Process::shellExecute (std::ctstring_t & a_filePathOrURL, std::cvec_tstring_t & a_params) static
opens a file or URL in the user's preferred application
Parameters
a_filePathOrURL full file path or URL
a_params command line params
Definition at line 328 of file Process.cpp.
 {
     xTEST(Path(a_filePathOrURL).isAbsolute() || _isUrlFull(a_filePathOrURL));
     std::ctstring_t params = String::join(a_params, Const::space());
     _shellExecute_impl(a_filePathOrURL, params);
 }
The documentation for this class was generated from the following files:
/home/skynowa/Projects/xLib/Include/xLib/Sync/Process.h
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Apple/Process_apple.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Bsd/Process_bsd.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Linux/Process_linux.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Unix/Process_unix.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Platform/Win/Process_win.inl
/home/skynowa/Projects/xLib/Include/xLib/Sync/Process.cpp