xLib: xl::fs::FileInfo Class Reference
xl::fs::FileInfo Class Reference
File information.
#include "FileInfo.h"
Public Types
enum class AccessMode { Existence = 0 , Write = 2 , Read = 4 , ReadWrite = 6 }
access mode
enum class PermissionMode {
Read = S_IRUSR , Write = S_IWUSR , ReadWrite = (S_IRUSR | S_IWUSR) , SetUserId = S_ISUID ,
SetGroupId = S_ISGID , StickyBit = S_ISVTX , ExecSearch = S_IXUSR , GroupRead = S_IRGRP ,
GroupWrite = S_IWGRP , GroupExecSearch = S_IXGRP , OthersRead = S_IROTH , OthersWrite = S_IWOTH ,
OthersExecSearch = S_IXOTH
}
permission mode
Public Member Functions
std::tstring_t path () const
path
longlong_t size () const
get size
bool_t isEmpty () const
is empty
ulonglong_t lines () const
get number of lines
void_t time (time_t *create, time_t *access, time_t *modified) const
get time
void_t setTime (const time_t create, const time_t access, const time_t modified) const
set time
void_t resetTime () const
reset time
bool_t isExists () const
check for existence
std::tstring_t isExistsEx () const
check for existence, if exists - generate new file name (file path), which not exists
bool_t checkAccess (cAccessMode mode) const
determine file-access permission
void_t chmod (cPermissionMode mode) const
change the file-permission settings
ctors, dtor
FileInfo (std::ctstring_t &filePath)
FileInfo (const Path &path)
FileInfo (const FileIO &file)
xNO_DEFAULT_CONSTRUCT (FileInfo)
xNO_COPY_ASSIGN (FileInfo)
Detailed Description
File information.
Definition at line 17 of file FileInfo.h.
Member Enumeration Documentation
AccessMode
enum class xl::fs::FileInfo::AccessMode strong
access mode
Definition at line 21 of file FileInfo.h.
    {
        Existence = 0,
        Write     = 2,
        Read      = 4,
        ReadWrite = 6
    };
PermissionMode
enum class xl::fs::FileInfo::PermissionMode strong
permission mode
Definition at line 31 of file FileInfo.h.
    {
    #if xENV_WIN
        Read             = _S_IREAD,
        Write            = _S_IWRITE,
        ReadWrite        = (_S_IREAD | _S_IWRITE)
    #else
        Read             = S_IRUSR,
        Write            = S_IWUSR,
        ReadWrite        = (S_IRUSR | S_IWUSR),
        SetUserId        = S_ISUID,
        SetGroupId       = S_ISGID,
        StickyBit        = S_ISVTX,
        ExecSearch       = S_IXUSR,
        GroupRead        = S_IRGRP,
        GroupWrite       = S_IWGRP,
        GroupExecSearch  = S_IXGRP,
        OthersRead       = S_IROTH,
        OthersWrite      = S_IWOTH,
        OthersExecSearch = S_IXOTH
    #endif
    };
Constructor & Destructor Documentation
FileInfo() [1/3]
xl::fs::FileInfo::FileInfo (std::ctstring_t & filePath) explicit
Definition at line 33 of file FileInfo.cpp.
  :
    _filePath(a_filePath)
{
    xTEST(!_filePath.empty());
}
FileInfo() [2/3]
xl::fs::FileInfo::FileInfo (const Path & path) explicit
Definition at line 41 of file FileInfo.cpp.
  :
    FileInfo( a_path.str() )
{
}
FileInfo() [3/3]
xl::fs::FileInfo::FileInfo (const FileIO & file) explicit
Definition at line 49 of file FileInfo.cpp.
  :
    FileInfo( a_file.path() )
{
}
~FileInfo()
xl::fs::FileInfo::~FileInfo () virtual
Definition at line 56 of file FileInfo.cpp.
{
}
Member Function Documentation
checkAccess()
bool_t xl::fs::FileInfo::checkAccess (cAccessMode mode) const
determine file-access permission
Definition at line 176 of file FileInfo.cpp.
{
    xTEST_NA(a_mode);
    int_t iRv = xTACCESS(_filePath.c_str(), static_cast<int_t>(a_mode));
    xCHECK_RET(iRv == - 1, false);
    return true;
}
chmod()
void_t xl::fs::FileInfo::chmod (cPermissionMode mode) const
change the file-permission settings
Definition at line 189 of file FileInfo.cpp.
{
    xTEST_NA(a_mode);
#if   xENV_WIN
    using _mode_t = cint_t;
#elif xENV_UNIX
    using _mode_t = const mode_t;
#endif
    int_t iRv = xTCHMOD(_filePath.c_str(), static_cast<_mode_t>(a_mode));
    xTEST_DIFF(iRv, - 1);
}
Referenced by xl::fs::File::remove().
isEmpty()
bool_t xl::fs::FileInfo::isEmpty () const
is empty
Definition at line 79 of file FileInfo.cpp.
{
    return (size() == 0LL);
}
References size().
isExists()
bool_t xl::fs::FileInfo::isExists () const
check for existence
Definition at line 143 of file FileInfo.cpp.
{
    xCHECK_RET(!FileType(_filePath).isFile(), false);
    int_t iRv = xTACCESS(_filePath.c_str(), static_cast<int_t>(AccessMode::Existence));
    xCHECK_RET(iRv == - 1 && NativeError::get() == ENOENT, false);
    return true;
}
References xl::debug::NativeError::get().
Referenced by xl::fs::Backup::fileExec(), isExistsEx(), lines(), xl::fs::Config::read(), and xl::fs::File::remove().
isExistsEx()
std::tstring_t xl::fs::FileInfo::isExistsEx () const
check for existence, if exists - generate new file name (file path), which not exists
Definition at line 154 of file FileInfo.cpp.
{
    std::tstring_t sRv;
    Path path(_filePath);
    std::ctstring_t &fileDir  = path.dir();
    std::ctstring_t &fileName = path.fileBaseName();
    std::tstring_t   fileExt  = path.ext();
    xCHECK_DO(!fileExt.empty(), fileExt.insert(0, Const::dot()));
    for (ulong_t existsIndex = 1; ; ++ existsIndex) {
        sRv = Format::str(xT("{}{}{} ({}){}"), fileDir, Const::slash(), fileName, existsIndex,
            fileExt);
        xCHECK_DO(!FileInfo(sRv).isExists(), break);
    }
    return sRv;
}
References isExists(), path(), xl::core::FormatT< StreamT >::str(), xCHECK_DO, and xT.
lines()
ulonglong_t xl::fs::FileInfo::lines () const
get number of lines
Definition at line 86 of file FileInfo.cpp.
{
    xTEST(isExists());
    std::locale::global( std::locale() );
    ulonglong_t ullRv {};
    std::tifstream_t ifs(_filePath, std::ios::in);
    xCHECK_RET(!ifs,           0LL);
    xCHECK_RET(ifs.fail(),     0LL);
    xCHECK_RET(!ifs.good(),    0LL);
    xCHECK_RET(!ifs.is_open(), 0LL);
    xCHECK_RET(ifs.eof(),      0LL);
    for (tchar_t chChar {}; ifs.get(chChar); ) {
        xCHECK_DO(chChar == xT('\n'), ++ ullRv);
    }
    return ullRv;
}
References isExists(), xCHECK_DO, and xT.
path()
std::tstring_t xl::fs::FileInfo::path () const
path
Definition at line 61 of file FileInfo.cpp.
{
    return _filePath;
}
Referenced by isExistsEx().
resetTime()
void_t xl::fs::FileInfo::resetTime () const
reset time
Definition at line 137 of file FileInfo.cpp.
{
    setTime({}, {}, {});
}
References setTime().
setTime()
void_t xl::fs::FileInfo::setTime (const time_t create, const time_t access, const time_t modified) const
set time
Definition at line 123 of file FileInfo.cpp.
{
    xTEST_NA(a_create);
    xTEST_NA(a_access);
    xTEST_NA(a_modified);
    _setTime_impl(a_create, a_access, a_modified);
}
Referenced by resetTime().
size()
longlong_t xl::fs::FileInfo::size () const
get size
Definition at line 68 of file FileInfo.cpp.
{
    FileIO file(_filePath);
    file.open(FileIO::OpenMode::ReadOnly);
    clonglong_t llRv = file.size();
    return llRv;
}
References xl::fs::FileIO::open(), xl::fs::FileIO::ReadOnly, and xl::fs::FileIO::size().
Referenced by xl::fs::Backup::fileExec(), and isEmpty().
time()
void_t xl::fs::FileInfo::time (time_t * a_create, time_t * a_access, time_t * a_modified) const
get time
Parameters
[out] a_create
[out] a_access
[out] a_modified
Definition at line 109 of file FileInfo.cpp.
{
    xTEST_NA(a_create);
    xTEST_NA(a_access);
    xTEST_NA(a_modified);
    _time_impl(a_create, a_access, a_modified);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileInfo.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileInfo.cpp