xLib: xl::package::curl::HttpClient Class Reference
xl::package::curl::HttpClient Class Reference
HTTP client.
#include "HttpClient.h"
Public Types
enum class HttpCode {
Unknown = 0 , Info = 1 , Success = 2 , Redirection = 3 ,
ClientError = 4 , ServerError = 5
}
HTTP response code.
Public Member Functions
xUSING_CONST (HttpCode)
ctors, dtor
HttpClient (cbool_t isDebug)
virtual ~HttpClient ()=default
HTTP result
HttpCode httpCode (cOptionOut &optionOut) const
bool_t isSuccess (cOptionOut &optionOut) const
Public Member Functions inherited from xl::package::curl::Client
void_t reset ()
template<typename T >
void_t setOption (cCURLoption option, const T &value)
void_t perform ()
void_t pause (cint_t bitMask)
template<typename T >
void_t info (cCURLINFO info, const T &value)
void_t receive (void_t *buff, std::csize_t buffSize, std::size_t *items)
void_t send (cvoid_t *buff, std::csize_t buffSize, std::size_t *items)
std::tstring_t escape (std::ctstring_t &str) const
std::tstring_t unescape (std::ctstring_t &str) const
Client (cbool_t isDebug)
virtual ~Client ()
Protected Member Functions
void_t setOptionsDefault (OptionIn *optionIn, std::ctstring_t &buffRead, std::tstring_t *buffHeader, std::tstring_t *buffData)
set options in
void_t getInfos (OptionOut *optionOut)
get options out
Private Types
enum class Request {
Unknown = 0 , Get = 1 , Head = 2 , Post = 3 ,
Put = 4 , Delete = 5 , Connect = 6 , Options = 7 ,
Trace = 8
}
Private Member Functions
xUSING_CONST (Request)
bool_t _request (cRequest type, OptionIn &optionIn, OptionOut *optionOut)
send request
Requests
OptionOut * optionOut
bool_t head (OptionIn &optionIn, OptionOut *optionOut)
bool_t post (OptionIn &optionIn, OptionOut *optionOut)
bool_t put (OptionIn &optionIn, OptionOut *optionOut)
bool_t del (OptionIn &optionIn, OptionOut *optionOut)
bool_t connect (OptionIn &optionIn, OptionOut *optionOut)
bool_t options (OptionIn &optionIn, OptionOut *optionOut)
bool_t trace (OptionIn &optionIn, OptionOut *optionOut)
Additional Inherited Members
Static Public Member Functions inherited from xl::package::curl::Client
static std::tstring_t unescapeUrl (std::ctstring_t &str)
static std::size_t onWriteHeader (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onWriteData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onReadData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
Public Attributes inherited from xl::package::curl::Client
xPUBLIC_STATIC __pad0__: static std::tstring_t escapeUrl(std::ctstring_t &str)
Protected Types inherited from xl::package::curl::Client
using slist_unique_ptr_t = std::unique_ptr< curl_slist, SlistDeleter >
Protected Attributes inherited from xl::package::curl::Client
cbool_t _isDebug {}
HandleCurl _handle
ReadData _readData {}
slist_unique_ptr_t _headers
Detailed Description
HTTP client.
Definition at line 90 of file HttpClient.h.
Member Enumeration Documentation
HttpCode
enum xl::package::curl::HttpClient::HttpCode strong
HTTP response code.
Enumerator
Unknown
Unknown.
Info
1xx - Transient code, a new one follows
Success
2xx - Things are OK
Redirection
3xx - The content is somewhere else
ClientError
4xx - Failed because of a client problem
ServerError
5xx - Failed because of a server problem
Definition at line 95 of file HttpClient.h.
     {
         Unknown     = 0,
         Info        = 1,
         Success     = 2,
         Redirection = 3,
         ClientError = 4,
         ServerError = 5
     };
Member Function Documentation
_request()
bool_t xl::package::curl::HttpClient::_request (cRequest type, OptionIn & a_optionIn, OptionOut * out_optionOut) private
send request
Retrieve information from the given server using a given URI. Requests using GET should only retrieve data and should have no other effect on the data
Same as GET, but transfers the status line and header section only
Send data to the server, for example, customer information, file upload, etc. using HTML forms
Replaces all current representations of the target resource with uploaded content
Removes all current representations of the target resource given by a URI
Establishes a tunnel to the server identified by a given URI
Describes the communication options for the target resource
Performs a message loop-back test along the path to the target resource
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 447 of file HttpClient.cpp.
 {
     xTEST_DIFF((int)a_type, (int)Request::Unknown);
     xTEST_PTR(out_optionOut);
     out_optionOut->headers.clear();
     out_optionOut->body.clear();
     setOption(CURLOPT_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS);
     switch (a_type) {
     case Request::Get:
         {
             a_optionIn.url += xT("?") + a_optionIn.request;
             if (!a_optionIn.isCacheControl) {
                 std::ctstring_t sessId = std::to_string( DateTime().current().toMsec() );
                 a_optionIn.url += "&SessId=" + escape(sessId);
             }
             setOption(CURLOPT_POST,   0L);
             setOption(CURLOPT_NOBODY, 0L);
         }
         break;
     case Request::Head:
         {
             setOption(CURLOPT_NOBODY, 1L);
         }
         break;
     case Request::Post:
         {
             setOption(CURLOPT_POST,          1L);
             setOption(CURLOPT_POSTFIELDS,    a_optionIn.request.data());
             setOption(CURLOPT_POSTFIELDSIZE, a_optionIn.request.size());
         }
         break;
     case Request::Put:
         {
             // TODO: Request::Put
             setOption(CURLOPT_UPLOAD, 1L);
         }
         break;
     case Request::Delete:
         {
             setOption(CURLOPT_CUSTOMREQUEST, xT("DELETE"));
         }
         break;
     case Request::Connect:
         {
             // TODO: Request::Connect
         }
         break;
     case Request::Options:
         {
             // TODO: Request::Options
         }
         break;
     case Request::Trace:
         {
             // TODO: Request::Trace
         }
         break;
     case Request::Unknown:
         xTEST(false);
         return false;
         break;
     }
     std::tstring_t buffRead;
     std::tstring_t buffHeaderOut;
     std::tstring_t buffOptionOut;
     setOptionsDefault(&a_optionIn, buffRead, &buffHeaderOut, &buffOptionOut);
     perform();
     getInfos(out_optionOut);
     // [out]
     String::split(buffHeaderOut, Const::crNl(), xT(": "), &out_optionOut->headers);
     out_optionOut->body = buffOptionOut;
     return true;
 }
Referenced by connect(), del(), head(), options(), post(), put(), and trace().
connect()
bool_t xl::package::curl::HttpClient::connect (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 144 of file HttpClient.cpp.
 {
     return _request(Request::Connect, a_optionIn, out_optionOut);
 }
References _request().
del()
bool_t xl::package::curl::HttpClient::del (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 135 of file HttpClient.cpp.
 {
     return _request(Request::Delete, a_optionIn, out_optionOut);
 }
References _request().
getInfos()
void_t xl::package::curl::HttpClient::getInfos (OptionOut * out_optionOut) protected
get options out
Parameters
[out] out_optionOut
Definition at line 403 of file HttpClient.cpp.
 {
     xTEST(_handle.isValid());
     {
         tchar_t *contentType {};
         info(CURLINFO_CONTENT_TYPE, &contentType);
         out_optionOut->contentType = (contentType == nullptr ? xT("") : contentType);
     }
     {
         tchar_t *effectiveUrl {};
         info(CURLINFO_EFFECTIVE_URL, &effectiveUrl);
         out_optionOut->effectiveUrl = (effectiveUrl == nullptr ? xT("") : effectiveUrl);
     }
     {
         int_t responseCode {};
         info(CURLINFO_RESPONSE_CODE, &responseCode);
         out_optionOut->responseCode = responseCode;
     }
     {
         double_t totalTimeSec {};
         info(CURLINFO_TOTAL_TIME, &totalTimeSec);
         out_optionOut->totalTimeSec = totalTimeSec;
     }
 }
head()
bool_t xl::package::curl::HttpClient::head (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 108 of file HttpClient.cpp.
 {
     return _request(Request::Head, a_optionIn, out_optionOut);
 }
References _request().
httpCode()
HttpClient::HttpCode xl::package::curl::HttpClient::httpCode (cOptionOut & a_optionOut) const
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes https://restfulapi.net/http-status-codes/
Definition at line 175 of file HttpClient.cpp.
 {
     static const std::map<std::pair<int, int>, HttpCode> httpCodes
     {
         {{100, 199}, HttpCode::Info       },
         {{200, 299}, HttpCode::Success    },
         {{300, 399}, HttpCode::Redirection},
         {{400, 499}, HttpCode::ClientError},
         {{500, 599}, HttpCode::ServerError}
     };
     for (const auto &[it_range, it_code] : httpCodes) {
         const auto &[it_low, it_high] = it_range;
         if ( Algos::isInBounds(a_optionOut.responseCode, it_low, it_high) ) {
             return it_code;
         }
     }
     return HttpCode::Unknown;
 }
References ClientError, Info, Redirection, ServerError, Success, and Unknown.
options()
bool_t xl::package::curl::HttpClient::options (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 153 of file HttpClient.cpp.
 {
     return _request(Request::Options, a_optionIn, out_optionOut);
 }
References _request().
post()
bool_t xl::package::curl::HttpClient::post (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 117 of file HttpClient.cpp.
 {
     return _request(Request::Post, a_optionIn, out_optionOut);
 }
References _request().
put()
bool_t xl::package::curl::HttpClient::put (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 126 of file HttpClient.cpp.
 {
     return _request(Request::Put, a_optionIn, out_optionOut);
 }
References _request().
setOptionsDefault()
void_t xl::package::curl::HttpClient::setOptionsDefault (OptionIn * a_optionIn, std::ctstring_t & buffRead, std::tstring_t * out_buffHeader, std::tstring_t * out_buffData) protected
set options in
Parameters
[in,out] a_optionIn
[out] out_buffHeader
[out] out_buffData
Definition at line 216 of file HttpClient.cpp.
 {
     xTEST(_handle.isValid());
     xTEST_PTR(a_optionIn);
     xTEST_NA(a_buffRead);
     xTEST_PTR(out_buffHeader);
     xTEST_PTR(out_buffData);
     out_buffHeader->clear();
     out_buffData->clear();
     setOption(CURLOPT_URL, a_optionIn->url.c_str());
     // Download data
     {
         setOption(CURLOPT_WRITEHEADER,    out_buffHeader);
         setOption(CURLOPT_HEADERFUNCTION, onWriteHeader);
         setOption(CURLOPT_WRITEDATA,      out_buffData);
         setOption(CURLOPT_WRITEFUNCTION,  onWriteData);
     }
     // Upload data
     {
         _readData.buff = a_buffRead;
         setOption(CURLOPT_READDATA,     &_readData);
         setOption(CURLOPT_READFUNCTION,  onReadData);
     }
     setOption(CURLOPT_HEADER, static_cast<long_t>(a_optionIn->isUseHeader));
     //  CURLOPT_SSL...
     {
         setOption(CURLOPT_SSL_VERIFYPEER, static_cast<long_t>(a_optionIn->isSslVerifyPeer));
         setOption(CURLOPT_SSL_VERIFYHOST, a_optionIn->isSslVerifyHost ? 2L : 0L);
         setOption(CURLOPT_SSLVERSION,     a_optionIn->sslVersion);
         if ( !a_optionIn->sslCert.empty() ) {
             setOption(CURLOPT_SSLCERT,       a_optionIn->sslCert.c_str());
             setOption(CURLOPT_SSLCERTPASSWD, a_optionIn->sslCertPass.c_str());
         }
     }
     setOption(CURLOPT_HTTP_VERSION, a_optionIn->httpVersion);
     // CURLOPT_COOKIE...
     {
         if ( !a_optionIn->cookieFile.empty() ) {
             setOption(CURLOPT_COOKIESESSION, 0L);
             setOption(CURLOPT_COOKIEFILE,    a_optionIn->cookieFile.c_str());
             setOption(CURLOPT_COOKIEJAR,     a_optionIn->cookieFile.c_str());
         }
         if ( !a_optionIn->addCookie.empty() ) {
             setOption(CURLOPT_COOKIE, a_optionIn->addCookie.c_str());
         }
     }
     if ( !a_optionIn->encodingParam.empty() ) {
         setOption(CURLOPT_ACCEPT_ENCODING, a_optionIn->encodingParam.c_str());
     }
     if ( !a_optionIn->ciphers.empty() ) {
         setOption(CURLOPT_SSL_CIPHER_LIST, a_optionIn->ciphers.c_str());
     }
     // FTP
     {
         curl_slist *quotes {};
         setOption(CURLOPT_QUOTE, quotes);
         curl_slist *postQuotes {};
         setOption(CURLOPT_POSTQUOTE, postQuotes);
     }
     // CURLOPT_TIMEOUT...
     {
         if (a_optionIn->timeoutMs > 0) {
             if (a_optionIn->timeoutMs >= 1000) {
                 setOption(CURLOPT_TIMEOUT_MS,        0L);
                 setOption(CURLOPT_CONNECTTIMEOUT_MS, 0L);
                 setOption(CURLOPT_TIMEOUT,           a_optionIn->timeoutMs / 1000);
                 setOption(CURLOPT_CONNECTTIMEOUT ,   a_optionIn->timeoutMs / 1000);
             } else {
                 setOption(CURLOPT_TIMEOUT,           0L);
                 setOption(CURLOPT_CONNECTTIMEOUT,    0L);
                 setOption(CURLOPT_TIMEOUT_MS,        a_optionIn->timeoutMs);
                 setOption(CURLOPT_CONNECTTIMEOUT_MS, a_optionIn->timeoutMs);
             }
         }
         else if (a_optionIn->timeoutSec > 0) {
             setOption(CURLOPT_TIMEOUT_MS,        0L);
             setOption(CURLOPT_CONNECTTIMEOUT_MS, 0L);
             setOption(CURLOPT_TIMEOUT,           a_optionIn->timeoutSec);
             setOption(CURLOPT_CONNECTTIMEOUT,    a_optionIn->timeoutSec);
         }
         if (a_optionIn->continueTimeoutMs > 0) {
             setOption(CURLOPT_EXPECT_100_TIMEOUT_MS, a_optionIn->continueTimeoutMs);
         }
     }
     // CURLOPT_PROXY
     if ( !a_optionIn->proxy.empty() ) {
         setOption(CURLOPT_PROXY,     a_optionIn->proxy.c_str());
         setOption(CURLOPT_PROXYTYPE, a_optionIn->proxyType);
         if ( !a_optionIn->proxyUserPass.empty() ) {
             setOption(CURLOPT_PROXYUSERPWD, a_optionIn->proxyUserPass.c_str());
         }
     }
     if ( !a_optionIn->userPass.empty() ) {
         setOption(CURLOPT_USERPWD, a_optionIn->userPass.c_str());
     }
     // CURLOPT_HTTPHEADER
     {
         // _headers
         {
             curl_slist *headers {};
             if ( !a_optionIn->accept.empty() ) {
                 std::ctstring_t &value = xT("Accept: ") + a_optionIn->accept;
                 headers = ::curl_slist_append(headers, value.c_str());
             }
             if ( !a_optionIn->acceptLanguage.empty() ) {
                 std::ctstring_t &value = xT("Accept-Language: ") + a_optionIn->acceptLanguage;
                 headers = ::curl_slist_append(headers, value.c_str());
             }
             if ( !a_optionIn->acceptCharset.empty() ) {
                 std::ctstring_t &value = xT("Accept-Charset: ") + a_optionIn->acceptCharset;
                 headers = ::curl_slist_append(headers, value.c_str());
             }
             if (a_optionIn->isCacheControl) {
                 // use cache
             } else {
                 // no cache
                 headers = ::curl_slist_append(headers, xT("Cache-Control: no-cache"));
                 // SEE: also set in HttpClient::request()
             }
             for (const auto &[param, value] : a_optionIn->addHeaders) {
                 std::ctstring_t &value_ = param + xT(": ") + value;
                 headers = ::curl_slist_append(headers, value_.c_str());
             }
             // [out]
             _headers.reset(headers);
         }
         // set list
         setOption(CURLOPT_HTTPHEADER, _headers.get());
     }
     if ( !a_optionIn->referer.empty() ) {
         setOption(CURLOPT_REFERER, a_optionIn->referer.c_str());
     }
     if ( !a_optionIn->acceptEncoding.empty() ) {
         setOption(CURLOPT_ACCEPT_ENCODING, a_optionIn->acceptEncoding.c_str());
     }
     if ( !a_optionIn->userAgent.empty() ) {
         setOption(CURLOPT_USERAGENT, a_optionIn->userAgent.c_str());
     }
     // curl_easy_setopt(curl, CURLOPT_AUTOREFERER, 1);
     setOption(CURLOPT_FOLLOWLOCATION, static_cast<long_t>(a_optionIn->isFollowLocation));
     setOption(CURLOPT_MAXREDIRS,      a_optionIn->maxRedirects);
 }
trace()
bool_t xl::package::curl::HttpClient::trace (OptionIn & a_optionIn, OptionOut * out_optionOut)
Parameters
[in,out] a_optionIn
[out] out_optionOut
Definition at line 162 of file HttpClient.cpp.
 {
     return _request(Request::Trace, a_optionIn, out_optionOut);
 }
References _request().
The documentation for this class was generated from the following files:
/home/skynowa/Projects/xLib/Include/xLib/Package/Curl/HttpClient.h
/home/skynowa/Projects/xLib/Include/xLib/Package/Curl/HttpClient.cpp