xLib: xl::sync::Thread Class Reference
xl::sync::Thread Class Reference
thread
#include "Thread.h"
Public Types
enum class Priority {
tpError = - 1 , tpIdle , tpLowest = 10 , tpBelowNormal ,
tpNormal , tpAboveNormal , tpHighest , tpTimeCritical
}
priotity
using handle_t = pthread_t
handle
using id_t = pthread_t
ID.
Public Member Functions
void_t setTag (culong_t tag)
set data tag
ulong_t tag () const
get data tag
void_t create (cbool_t isPaused, cuint_t stackSizeBytes, void_t *param)
start
void_t resume ()
resume
void_t pause ()
pause
void_t exit ()
exit (set flag "exit")
void_t kill (culong_t timeoutMsec)
kill
void_t wait (culong_t timeoutMsec) const
wait
bool_t isCreated () const
is created
bool_t isRunning () const
is running
bool_t isPaused ()
is paused
bool_t isExited ()
is exited (is set flag "exit")
void_t setPriority (cPriority priority) const
set priority (under Linux must use admin privilege)
Priority priority () const
get priority
void_t priorityUp () const
increase priority on one level
void_t priorityDown () const
decrease priority on one level
bool_t isPriorityBoost () const
get priority boost control state
void_t setPriorityBoost (cbool_t isEnabled) const
disables/enables the ability of the system to temporarily boost the priority of a thread
void_t setCpuAffinity (cint_t procNum) const
set processor affinity
void_t setCpuIdeal (culong_t idealCpu) const
sets preferred processor for a thread
ulong_t cpuIdeal () const
get current ideal processor without changing it
bool_t isHandleValid () const
bool_t isIdValid () const
handle_t handle () const
get handle
id_t id () const
get ID
bool_t isCurrent () const
is current
ulong_t exitStatus () const
get termination status
void_t setDebugName (std::ctstring_t &name) const
set name your threads in the debugger thread list
ctors, dtor
Thread (cbool_t isAutoDelete)
xNO_COPY_ASSIGN (Thread)
Static Public Member Functions
static ulong_t cpuCount ()
get CPU count on machine
static bool_t isHandleValid (chandle_t handle)
static bool_t isIdValid (cid_t id)
static handle_t open (culong_t access, cbool_t isInheritHandle, cid_t &id)
opens an existing thread object
static bool_t isCurrent (cid_t id)
is current id
static id_t currentId ()
get the thread identifier of the calling thread
static handle_t currentHandle ()
get pseudo handle for the calling thread
static void_t currentYield ()
yield
static void_t currentSleep (culong_t timeoutMsec)
sleep
Protected Member Functions
virtual uint_t onRun (void_t *param)
work thread function, must be override
bool_t isTimeToExit ()
is need to exit from work thread function
Detailed Description
thread
Definition at line 16 of file Thread.h.
Member Typedef Documentation
handle_t
using xl::sync::Thread::handle_t = pthread_t
handle
Definition at line 24 of file Thread.h.
id_t
using xl::sync::Thread::id_t = pthread_t
ID.
Definition at line 25 of file Thread.h.
Member Enumeration Documentation
Priority
enum class xl::sync::Thread::Priority strong
priotity
Definition at line 30 of file Thread.h.
    {
    #if   xENV_WIN
        tpError        = THREAD_PRIORITY_ERROR_RETURN,
        tpIdle         = THREAD_PRIORITY_IDLE,
        tpLowest       = THREAD_PRIORITY_LOWEST,
        tpBelowNormal  = THREAD_PRIORITY_BELOW_NORMAL,
        tpNormal       = THREAD_PRIORITY_NORMAL,
        tpAboveNormal  = THREAD_PRIORITY_ABOVE_NORMAL,
        tpHighest      = THREAD_PRIORITY_HIGHEST,
        tpTimeCritical = THREAD_PRIORITY_TIME_CRITICAL
    #elif xENV_UNIX
        tpError        = - 1,
        tpIdle         ,
        tpLowest       = 10,
        tpBelowNormal  ,
        tpNormal       ,
        tpAboveNormal  ,
        tpHighest      ,
        tpTimeCritical
    #endif
    };
Constructor & Destructor Documentation
Thread()
xl::sync::Thread::Thread (cbool_t isAutoDelete) explicit
Definition at line 31 of file Thread.cpp.
  :
    _isAutoDelete(a_isAutoDelete)
{
}
~Thread()
xl::sync::Thread::~Thread () virtual
Definition at line 39 of file Thread.cpp.
{
    // close thread, if it still running
    bool_t bRv = isRunning();
    if (bRv) {
        exit();
        // TODO: [skynowa] Thread::~Thread()
    #if xTODO
        kill(_s_exitTimeoutMsec);
    #endif
    }
    _clear(0U);
}
Member Function Documentation
cpuCount()
ulong_t xl::sync::Thread::cpuCount () static
get CPU count on machine
Definition at line 371 of file Thread.cpp.
{
    ulong_t ulRv = info::Cpu().num();
    xCHECK_RET(ulRv < 1UL || ulRv > 32UL, 1UL);
    // TODO: [skynowa] Thread::cpuCount() - make constant 32UL
    return ulRv;
}
References xl::system::info::Cpu::num().
cpuIdeal()
ulong_t xl::sync::Thread::cpuIdeal () const
get current ideal processor without changing it
Definition at line 362 of file Thread.cpp.
{
    xTEST(isHandleValid());
    return _cpuIdeal_impl();
}
create()
void_t xl::sync::Thread::create (cbool_t isPaused, cuint_t stackSizeBytes, void_t * param)
start
Definition at line 78 of file Thread.cpp.
{
    xTEST(!isHandleValid());
    xTEST_NA(a_isPaused);
    xTEST_NA(a_stackSizeBytes);
    xTEST_NA(a_param);
    _param = a_param;
    // events
    cbool_t isAutoReset {true};
    cbool_t isSignaled  {false};
    _eventStarter = new Event(isAutoReset, isSignaled);
    _eventStarter->create();
    _eventPause.create();
    _eventExit.create();
    // start
    _create_impl(a_stackSizeBytes);
    xTEST(!isCurrent(_id));
    // states
    {
        _state.isCreated = true;
        _state.isRunning = true;
        if (a_isPaused) {
            pause();
        } else {
            resume();
        }
    }
    // construction is complete, start job entry
    _eventStarter->set();
}
References xl::sync::Event::create(), isCurrent(), pause(), resume(), and xl::sync::Event::set().
currentHandle()
Thread::handle_t xl::sync::Thread::currentHandle () static
get pseudo handle for the calling thread
Definition at line 544 of file Thread.cpp.
{
    // n/a
    return _currentHandle_impl();
}
currentId()
Thread::id_t xl::sync::Thread::currentId () static
get the thread identifier of the calling thread
Definition at line 536 of file Thread.cpp.
{
    // n/a
    return _currentId_impl();
}
Referenced by isCurrent().
currentSleep()
void_t xl::sync::Thread::currentSleep (culong_t timeoutMsec) static
sleep
Definition at line 560 of file Thread.cpp.
{
    // n/a
    xCHECK_DO(a_timeoutMsec == 0UL, return);
    _currentSleep_impl(a_timeoutMsec);
}
References xCHECK_DO.
Referenced by xl::sync::ThreadPool< T >::onRun(), xl::system::Console::pause(), and xl::fs::Dir::tryRemove().
currentYield()
void_t xl::sync::Thread::currentYield () static
yield
Definition at line 552 of file Thread.cpp.
{
    // n/a
    _currentYield_impl();
}
exit()
void_t xl::sync::Thread::exit ()
exit (set flag "exit")
Definition at line 149 of file Thread.cpp.
{
    xTEST(isHandleValid());
    _eventExit.set();
    // states
    {
        // _state.isCreated - n/a
        // _state.isRunning - n/a
        xCHECK_DO(isPaused(), resume());
    }
}
References isPaused(), resume(), xl::sync::Event::set(), and xCHECK_DO.
exitStatus()
ulong_t xl::sync::Thread::exitStatus () const
get termination status
Definition at line 472 of file Thread.cpp.
{
    return _exitStatus_impl();
}
handle()
Thread::handle_t xl::sync::Thread::handle () const
get handle
Definition at line 452 of file Thread.cpp.
{
    return _handle_impl();
}
id()
Thread::id_t xl::sync::Thread::id () const
get ID
Definition at line 458 of file Thread.cpp.
{
    xTEST(isHandleValid());
    return _id;
}
isCreated()
bool_t xl::sync::Thread::isCreated () const
is created
Definition at line 190 of file Thread.cpp.
{
    // _handle - n/a
    return _isCreated_impl();
}
isCurrent() [1/2]
bool_t xl::sync::Thread::isCurrent () const
is current
Definition at line 466 of file Thread.cpp.
{
    return isCurrent( currentId() );
}
References currentId(), and isCurrent().
Referenced by create(), and isCurrent().
isCurrent() [2/2]
bool_t xl::sync::Thread::isCurrent (cid_t id) static
is current id
Definition at line 528 of file Thread.cpp.
{
    return _isCurrent_impl(a_id);
}
isExited()
bool_t xl::sync::Thread::isExited ()
is exited (is set flag "exit")
Definition at line 214 of file Thread.cpp.
{
    // _handle - n/a
    return _isExited_impl();
}
Referenced by isTimeToExit().
isHandleValid() [1/2]
bool_t xl::sync::Thread::isHandleValid () const
Definition at line 390 of file Thread.cpp.
{
    return isHandleValid(_handle);
}
isHandleValid() [2/2]
bool_t xl::sync::Thread::isHandleValid (chandle_t handle) static
Definition at line 403 of file Thread.cpp.
{
    bool_t bRv {};
#if   xENV_WIN
    bRv = (a_handle != xNATIVE_HANDLE_NULL);
#elif xENV_UNIX
    #if xENV_APPLE
        bRv = (a_handle != nullptr);
    #else
        bRv = (a_handle > 0);
    #endif
#endif
    return bRv;
}
isIdValid() [1/2]
bool_t xl::sync::Thread::isIdValid () const
Definition at line 396 of file Thread.cpp.
{
    return isIdValid(_id);
}
isIdValid() [2/2]
bool_t xl::sync::Thread::isIdValid (cid_t id) static
Definition at line 424 of file Thread.cpp.
{
    bool_t bRv {};
#if   xENV_WIN
    bRv = (a_id > 0UL);
#elif xENV_UNIX
    #if xENV_APPLE
        bRv = (a_id != nullptr);
    #else
        bRv = (a_id > 0);
    #endif
#endif
    return bRv;
}
isPaused()
bool_t xl::sync::Thread::isPaused ()
is paused
Definition at line 206 of file Thread.cpp.
{
    // _handle - n/a
    return _isPaused_impl();
}
Referenced by exit(), and isTimeToExit().
isPriorityBoost()
bool_t xl::sync::Thread::isPriorityBoost () const
get priority boost control state
Definition at line 324 of file Thread.cpp.
{
    return _isPriorityBoost_impl();
}
isRunning()
bool_t xl::sync::Thread::isRunning () const
is running
Definition at line 198 of file Thread.cpp.
{
    // _handle - n/a
    return _isRunning_impl();
}
isTimeToExit()
bool_t xl::sync::Thread::isTimeToExit () protected
is need to exit from work thread function
Definition at line 612 of file Thread.cpp.
{
    // n/a
    bool_t bRv {};
    // exit
    bRv = isExited();
    xCHECK_RET(bRv, true);
    // pause / resume
    bRv = isPaused();
    xCHECK_RET(bRv, !_waitResumption());
    // states
    // n/a
    return false;
}
References isExited(), and isPaused().
Referenced by onRun().
kill()
void_t xl::sync::Thread::kill (culong_t timeoutMsec)
kill
Definition at line 165 of file Thread.cpp.
{
    _kill_impl(a_timeoutMsec);
    _clear(0U);
}
onRun()
uint_t xl::sync::Thread::onRun (void_t * param) protected virtual
work thread function, must be override
Reimplemented in xl::sync::ThreadPool< T >.
Definition at line 581 of file Thread.cpp.
{
    xUNUSED(a_param);
    xTEST_FAIL_MSG(xT("It's virtual method"));
    uint_t uiRv {};
#if xTEMP_DISABLED
    for ( ; ; ) {
        bool_t bRv = isTimeToExit();
        xCHECK_DO(bRv, break);
        //...
    }
#endif
    return uiRv;
}
References isTimeToExit(), xCHECK_DO, xT, and xUNUSED.
open()
Thread::handle_t xl::sync::Thread::open (culong_t access, cbool_t isInheritHandle, cid_t & id) static
opens an existing thread object
Definition at line 506 of file Thread.cpp.
{
    xTEST_NA(a_access);
    xTEST_NA(a_isInheritHandle);
    xTEST(isIdValid(a_id));
    return _open_impl(a_access, a_isInheritHandle, a_id);
}
pause()
void_t xl::sync::Thread::pause ()
pause
Definition at line 135 of file Thread.cpp.
{
    xTEST(isHandleValid());
    _eventPause.reset();
    // states
    {
        // _state.isCreated - n/a
        // _state.isRunning - n/a
    }
}
References xl::sync::Event::reset().
Referenced by create().
priority()
Thread::Priority xl::sync::Thread::priority () const
get priority
Definition at line 238 of file Thread.cpp.
{
    xTEST(isHandleValid());
    return _priority_impl();
}
Referenced by priorityDown(), and priorityUp().
priorityDown()
void_t xl::sync::Thread::priorityDown () const
decrease priority on one level
Definition at line 285 of file Thread.cpp.
{
    xTEST(isHandleValid());
    Priority tpOldLevel  = Priority::tpError;
    Priority tpiNewLevel = Priority::tpError;
    tpOldLevel = priority();
    switch (tpOldLevel) {
    case Priority::tpIdle:
        return;
        break;
    case Priority::tpLowest:
        tpiNewLevel = Priority::tpIdle;
        break;
    case Priority::tpBelowNormal:
        tpiNewLevel = Priority::tpLowest;
        break;
    case Priority::tpNormal:
        tpiNewLevel = Priority::tpBelowNormal;
        break;
    case Priority::tpAboveNormal:
        tpiNewLevel = Priority::tpNormal;
        break;
    case Priority::tpHighest:
        tpiNewLevel = Priority::tpAboveNormal;
        break;
    case Priority::tpTimeCritical:
        tpiNewLevel =Priority::tpHighest;
        break;
    default:
        xTEST_FAIL;
        break;
    }
    setPriority(tpiNewLevel);
}
References priority(), and setPriority().
priorityUp()
void_t xl::sync::Thread::priorityUp () const
increase priority on one level
Definition at line 246 of file Thread.cpp.
{
    xTEST(isHandleValid());
    Priority tpOldLevel  = Priority::tpError;
    Priority tpiNewLevel = Priority::tpError;
    tpOldLevel = priority();
    switch (tpOldLevel) {
    case Priority::tpIdle:
        tpiNewLevel = Priority::tpLowest;
        break;
    case Priority::tpLowest:
        tpiNewLevel = Priority::tpBelowNormal;
        break;
    case Priority::tpBelowNormal:
        tpiNewLevel = Priority::tpNormal;
        break;
    case Priority::tpNormal:
        tpiNewLevel = Priority::tpAboveNormal;
        break;
    case Priority::tpAboveNormal:
        tpiNewLevel = Priority::tpHighest;
        break;
    case Priority::tpHighest:
        tpiNewLevel = Priority::tpTimeCritical;
        break;
    case Priority::tpTimeCritical:
        return;
        break;
    default:
        xTEST_FAIL;
        break;
    }
    setPriority(tpiNewLevel);
}
References priority(), and setPriority().
resume()
void_t xl::sync::Thread::resume ()
resume
Definition at line 121 of file Thread.cpp.
{
    xTEST(isHandleValid());
    _eventPause.set();
    // states
    {
        // _state.isCreated - n/a
        // _state.isRunning - n/a
    }
}
References xl::sync::Event::set().
Referenced by create(), and exit().
setCpuAffinity()
void_t xl::sync::Thread::setCpuAffinity (cint_t procNum) const
set processor affinity
Definition at line 346 of file Thread.cpp.
{
    _setCpuAffinity_impl(a_procNum);
}
setCpuIdeal()
void_t xl::sync::Thread::setCpuIdeal (culong_t a_idealCpu) const
sets preferred processor for a thread
Parameters
a_idealCpu value is zero-based
Definition at line 354 of file Thread.cpp.
{
    _setCpuIdeal_impl(a_idealCpu);
}
setDebugName()
void_t xl::sync::Thread::setDebugName (std::ctstring_t & name) const
set name your threads in the debugger thread list
Definition at line 478 of file Thread.cpp.
{
    xTEST(isIdValid());
    xTEST_LESS_EQ(a_name.size(), xTHREAD_NAME_LENGTH_MAX);
    std::tstring_t name = a_name;
    if (name.size() > xTHREAD_NAME_LENGTH_MAX) {
        name.resize(xTHREAD_NAME_LENGTH_MAX);
    }
    // TODO: [skynowa] Thread::setDebugName() - xCHECK_RET(!Debugger().isActive(), true);
    _setDebugName_impl(name);
}
References xTHREAD_NAME_LENGTH_MAX.
setPriority()
void_t xl::sync::Thread::setPriority (cPriority priority) const
set priority (under Linux must use admin privilege)
Definition at line 230 of file Thread.cpp.
{
    _setPriority_impl(a_priority);
}
Referenced by priorityDown(), and priorityUp().
setPriorityBoost()
void_t xl::sync::Thread::setPriorityBoost (cbool_t isEnabled) const
disables/enables the ability of the system to temporarily boost the priority of a thread
Definition at line 330 of file Thread.cpp.
{
    _setPriorityBoost_impl(a_isEnabled);
}
setTag()
void_t xl::sync::Thread::setTag (culong_t tag)
set data tag
Definition at line 64 of file Thread.cpp.
{
    _tag = a_tag;
}
tag()
ulong_t xl::sync::Thread::tag () const
get data tag
Definition at line 72 of file Thread.cpp.
{
    return _tag;
}
wait()
void_t xl::sync::Thread::wait (culong_t timeoutMsec) const
wait
Definition at line 174 of file Thread.cpp.
{
    _wait_impl(a_timeoutMsec);
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Thread.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Thread.cpp