xLib: xl::system::Env Class Reference
xl::system::Env Class Reference
system environment variable
#include "Env.h"
Inherits xl::interface_::IStr.
Public Member Functions
bool_t isExists () const
check for existence
std::tstring_t value () const
get value
std::vec_tstring_t values () const
convert value to container
void_t setValue (std::ctstring_t &value) const
set or change value
void_t remove () const
delete var
Overrides
std::tstring_t str () const final
variable with value (DESKTOP_SESSION=xfce)
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
ctors, dtor
Env (std::ctstring_t &name)
Env (std::ctstring_t &prefix, std::ctstring_t &name)
virtual ~Env ()=default
xNO_DEFAULT_CONSTRUCT (Env)
xNO_COPY_ASSIGN (Env)
static Env path ()
get PATH values (/usr/bin ... pathes) with separator
Detailed Description
system environment variable
Constructor & Destructor Documentation
Env() [1/2]
xl::system::Env::Env (std::ctstring_t & a_name) explicit
Parameters
a_name Like a "namespace" prefix
  :
    Env{{}, a_name}
{
}
Env() [2/2]
xl::system::Env::Env (std::ctstring_t & a_prefix, std::ctstring_t & a_name) explicit
Parameters
a_prefix Like a "namespace" prefix
a_name variable name
  :
    _prefix{a_prefix + a_name}
{
    xTEST(_isNameValid());
}
References xTEST.
~Env()
virtual xl::system::Env::~Env () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::system::Env::xNO_DEFAULT_CONSTRUCT (Env)
xNO_COPY_ASSIGN()
xl::system::Env::xNO_COPY_ASSIGN (Env)
path()
Env xl::system::Env::path () static
get PATH values (/usr/bin ... pathes) with separator
{
    std::ctstring_t name =
    #if   xENV_WIN
        xT("Path");
    #elif xENV_UNIX
        xT("PATH");
    #endif
    return Env(name);
}
References xT.
Referenced by xl::fs::Finder::fileInEnvPath().
str()
std::tstring_t xl::system::Env::str () const final virtual
variable with value (DESKTOP_SESSION=xfce)
Implements xl::interface_::IStr.
{
    return _prefix + Const::equal() + value();
}
References xl::core::Const::equal(), and value().
isExists()
bool_t xl::system::Env::isExists () const
check for existence
{
    xCHECK_RET(_prefix.empty(), false);
    return _isExists_impl();
}
References xCHECK_RET.
Referenced by xl::system::Envs::findFirstOf(), xl::test::Unit::isGithubCI(), remove(), value(), and values().
value()
std::tstring_t xl::system::Env::value () const
get value
{
    xCHECK_RET(!isExists(), std::tstring_t());
    return _value_impl();
}
References isExists(), and xCHECK_RET.
Referenced by xl::system::Envs::expandVars(), xl::system::Envs::findFirstOf(), xl::system::Envs::operator[](), str(), and values().
values()
std::vec_tstring_t xl::system::Env::values () const
convert value to container
{
    xCHECK_RET(!isExists(), std::vec_tstring_t{});
    std::vec_tstring_t items;
    String::split(value(), _envsSeparator(), &items);
    return std::move(items);
}
References isExists(), xl::core::String::split(), value(), and xCHECK_RET.
Referenced by xl::fs::Finder::fileInEnvPath().
setValue()
void_t xl::system::Env::setValue (std::ctstring_t & value) const
set or change value
{
    xTEST(_isValueValid(a_value));
    _setValue_impl(a_value);
}
References xTEST.
Referenced by xl::system::Envs::setVars(), and xl::system::Envs::setVars().
remove()
void_t xl::system::Env::remove () const
delete var
{
    xCHECK_DO(!isExists(), return);
    _remove_impl();
}
References isExists(), and xCHECK_DO.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Env.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Env.cpp