xLib: /home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Functions.h File Reference
Functions.h File Reference
function macroses
#include "Platform/Functions_ansi.h"
#include <string>
Macros
#define xDUP2 ::dup2
#define xLOCKING ::locking
#define xCHSIZE ::chsize
#define xIOCTLSOCKET ::ioctl
#define xADDR_INFO_GET ::getaddrinfo
#define xADDR_INFO_FREE ::freeaddrinfo
#define xNAME_INFO_GET ::getnameinfo
#define xSTATVFS ::statfs64
Filesystem statfs - struct and function.
#define xISATTY ::isatty
#define xFILENO ::fileno
Functions
std::string xl::demangleName (const char *nameRaw)
Demangling names.
Detailed Description
function macroses
Definition in file Functions.h.
Macro Definition Documentation
xADDR_INFO_FREE
#define xADDR_INFO_FREE ::freeaddrinfo
Definition at line 85 of file Functions.h.
xADDR_INFO_GET
#define xADDR_INFO_GET ::getaddrinfo
Definition at line 72 of file Functions.h.
xCHSIZE
#define xCHSIZE ::chsize
Definition at line 46 of file Functions.h.
xDUP2
#define xDUP2 ::dup2
Definition at line 20 of file Functions.h.
xFILENO
#define xFILENO ::fileno
Definition at line 142 of file Functions.h.
xIOCTLSOCKET
#define xIOCTLSOCKET ::ioctl
Definition at line 55 of file Functions.h.
xISATTY
#define xISATTY ::isatty
Definition at line 133 of file Functions.h.
xLOCKING
#define xLOCKING ::locking
Definition at line 33 of file Functions.h.
xNAME_INFO_GET
#define xNAME_INFO_GET ::getnameinfo
Definition at line 102 of file Functions.h.
xSTATVFS
#define xSTATVFS ::statfs64
Filesystem statfs - struct and function.
Definition at line 118 of file Functions.h.
Function Documentation
demangleName()
std::string xl::demangleName (const char * a_nameRaw)
Demangling names.
Definition at line 53 of file Functions.cpp.
{
    if (a_nameRaw == nullptr) {
        return {};
    }
    std::string sRv;
#if   xCOMPILER_MS
    constexpr DWORD buffSize {1024};
    char            buff[buffSize + 1] {};
    const     DWORD flags {UNDNAME_COMPLETE}; // Enable full undecoration
    DWORD dwRv = ::UnDecorateSymbolName(a_nameRaw, buff, buffSize, flags);
    sRv = (dwRv != 0UL) ? a_nameRaw : buff;
#elif xCOMPILER_MINGW || xCOMPILER_GNUC
    int status {- 1};
    char *buff = abi::__cxa_demangle(a_nameRaw, nullptr, nullptr, &status);
    sRv = (buff == nullptr || status != 0) ? a_nameRaw : buff;
    if (buff != nullptr) {
        std::free(buff); buff = nullptr;
    }
#else
    sRv = a_nameRaw;
#endif
    return sRv;
}
References xl::demangleName().
Referenced by xl::demangleName(), and xl::core::Type< T >::nameDemangle().