xLib: xl::fs::FileBin Class Reference
xl::fs::FileBin Class Reference
Binary file.
#include "FileBin.h"
Public Member Functions
void_t read (std::ustring_t *content) const
void_t write (std::custring_t &content, FileIO::cOpenMode mode) const
ctors, dtor
FileBin (std::ctstring_t &filePath)
virtual ~FileBin ()=default
xNO_DEFAULT_CONSTRUCT (FileBin)
xNO_COPY_ASSIGN (FileBin)
Detailed Description
Binary file.
Constructor & Destructor Documentation
FileBin()
xl::fs::FileBin::FileBin (std::ctstring_t & filePath) explicit
  :
    _filePath(a_filePath)
{
}
~FileBin()
virtual xl::fs::FileBin::~FileBin () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::FileBin::xNO_DEFAULT_CONSTRUCT (FileBin)
xNO_COPY_ASSIGN()
xl::fs::FileBin::xNO_COPY_ASSIGN (FileBin)
read()
void_t xl::fs::FileBin::read (std::ustring_t * content) const
{
    xTEST_PTR(a_content);
    a_content->clear();
    FileIO file(_filePath);
    file.open(FileIO::OpenMode::BinReadOnly);
    clonglong_t fileSize = file.size();
    xTEST_DIFF(fileSize, static_cast<longlong_t>(FileIO::PointerPosition::Error));
    xCHECK_DO(fileSize == 0LL, return);
    std::ustring_t usRv;
    usRv.resize( static_cast<size_t>(fileSize) );
    std::csize_t readLen = file.read((void_t *)&usRv.at(0), usRv.size());
    xTEST_EQ(readLen, usRv.size());
    // out
    a_content->swap(usRv);
}
References xl::fs::FileIO::BinReadOnly, xl::fs::FileIO::Error, xl::fs::FileIO::open(), xl::fs::FileIO::read(), xl::fs::FileIO::size(), xCHECK_DO, xTEST_DIFF, xTEST_EQ, and xTEST_PTR.
Referenced by xl::crypt::Crc32::calcFile(), xl::crypt::Blowfish::encryptFileCfb64(), and xl::crypt::Blowfish::setFileKey().
write()
void_t xl::fs::FileBin::write (std::custring_t & content, FileIO::cOpenMode mode) const
{
    xTEST_NA(a_content);
    FileIO file(_filePath);
    file.open(a_mode);
    xCHECK_DO(a_content.empty(), return);
    std::csize_t writeLen = file.write((void_t *)&a_content.at(0), a_content.size());
    xTEST_EQ(writeLen, a_content.size());
}
References xl::fs::FileIO::open(), xl::fs::FileIO::write(), xCHECK_DO, xTEST_EQ, and xTEST_NA.
Referenced by xl::crypt::Blowfish::encryptFileCfb64().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileBin.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileBin.cpp