xLib: xl::sync::IpcSemaphore Class Reference
xl::sync::IpcSemaphore Class Reference
semaphore (interprocess)
#include "IpcSemaphore.h"
Public Types
using handle_t = sem_t *
Public Member Functions
long_t valueMax () const
maximum value
const handle_t & handle () const
get handle
void_t create (clong_t initialValue, std::ctstring_t &name)
create
void_t open (std::ctstring_t &name)
open
void_t post () const
release
void_t wait (culong_t timeoutMsec) const
wait
long_t value () const
get value
ctors, dtor
IpcSemaphore ()
virtual ~IpcSemaphore ()
xNO_COPY_ASSIGN (IpcSemaphore)
Detailed Description
semaphore (interprocess)
Member Typedef Documentation
handle_t
using xl::sync::IpcSemaphore::handle_t = sem_t *
Constructor & Destructor Documentation
IpcSemaphore()
xl::sync::IpcSemaphore::IpcSemaphore ()
{
    xTEST(!_isValid());
    _construct_impl();
}
References xTEST.
~IpcSemaphore()
xl::sync::IpcSemaphore::~IpcSemaphore () virtual
{
    xTEST(_isValid());
    _destruct_impl();
}
References xTEST.
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::IpcSemaphore::xNO_COPY_ASSIGN (IpcSemaphore)
valueMax()
long_t xl::sync::IpcSemaphore::valueMax () const
maximum value
{
    return _valueMax_impl();
}
Referenced by create().
handle()
const IpcSemaphore::handle_t & xl::sync::IpcSemaphore::handle () const
get handle
{
    xTEST(_isValid());
    return _handle;
}
References xTEST.
create()
void_t xl::sync::IpcSemaphore::create (clong_t initialValue, std::ctstring_t & name)
create
{
    xTEST(!_isValid());
    xTEST_LESS_EQ(a_name.size(), Path::maxSize());
    xTEST(0L <= a_initialValue && a_initialValue <= valueMax());
    _create_impl(a_initialValue, a_name);
}
References xl::fs::Path::maxSize(), valueMax(), xTEST, and xTEST_LESS_EQ.
open()
void_t xl::sync::IpcSemaphore::open (std::ctstring_t & name)
open
{
    xTEST(_isValid());
    xTEST_NA(a_name);
    _open_impl(a_name);
}
References xTEST, and xTEST_NA.
post()
void_t xl::sync::IpcSemaphore::post () const
release
{
    xTEST(_isValid());
    _post_impl();
}
References xTEST.
wait()
void_t xl::sync::IpcSemaphore::wait (culong_t timeoutMsec) const
wait
{
    xTEST(_isValid());
    xTEST_NA(a_timeoutMsec);
    _wait_impl(a_timeoutMsec);
}
References xTEST, and xTEST_NA.
value()
long_t xl::sync::IpcSemaphore::value () const
get value
{
    xTEST(_isValid());
    return _value_impl();
}
References xTEST.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/IpcSemaphore.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/IpcSemaphore.cpp