xLib: xl::net::DnsClient Class Reference
xl::net::DnsClient Class Reference
DNS client.
#include "DnsClient.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (DnsClient)
xNO_COPY_ASSIGN (DnsClient)
Static Public Member Functions
static void_t hostAddrByName (std::ctstring_t &hostName, std::tstring_t *hostAddr)
get host address by name
static void_t hostNameByAddr (std::ctstring_t &hostAddr, const ISocket::AddressFamily family, std::tstring_t *hostName)
get host name by address
static void_t localHostName (std::tstring_t *hostName)
get local host name
static void_t nameInfo (ISocket::cAddressFamily family, std::ctstring_t &hostAddr, cushort_t hostPort, std::tstring_t *name, std::tstring_t *port)
get name info
static void_t hostAddrInfo (std::ctstring_t &hostName, std::ctstring_t &port, caddrinfo_t *hints, addrinfo_t **addrInfo)
get host addr info
static void_t protocolByName (std::ctstring_t &protocolName, std::tstring_t *name, std::vec_tstring_t *aliases, int_t *number)
get protocol by name
static void_t protocolByNumber (cint_t number, std::tstring_t *name, std::vec_tstring_t *aliases, int_t *number_rv)
get protocol by number
static void_t serviceByName (std::ctstring_t &serviceName, std::ctstring_t &protocolName, std::tstring_t *name, std::vec_tstring_t *aliases, int_t *port, std::tstring_t *protocolName_rv)
get service by name
static void_t serviceByPort (cushort_t port, std::ctstring_t &protocolName, std::tstring_t *name, std::vec_tstring_t *aliases, short_t *port_rv, std::tstring_t *protocolName_rv)
get service by port
static bool_t isOnLan (cuint_t ip)
return true if IP is on this LAN
static bool_t isBroadcast (cuint_t ip)
return true if IP is a (directed) IP-broadcast address
static bool_t isAddressIpv4 (std::ctstring_t &ip)
is address IP v4
static bool_t isAddressIpv6 (std::ctstring_t &ip)
is address IP v6
Detailed Description
DNS client.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::net::DnsClient::xNO_DEFAULT_CONSTRUCT (DnsClient)
xNO_COPY_ASSIGN()
xl::net::DnsClient::xNO_COPY_ASSIGN (DnsClient)
hostAddrByName()
void_t xl::net::DnsClient::hostAddrByName (std::ctstring_t & hostName, std::tstring_t * hostAddr) static
get host address by name
{
    xTEST(!a_hostName.empty());
    xTEST_PTR(out_hostAddr);
    std::tstring_t sRv;
    hostent *host = ::gethostbyname( xT2A(a_hostName).c_str() );
    xTEST_PTR(host);
    xCHECK_DO(host == nullptr, return);
    auto addrList = reinterpret_cast<struct in_addr **>(host->h_addr_list);
    for (std::size_t i = 0; addrList[i] != nullptr; ++ i) {
        sRv = Format::str(xT("{} "), ::inet_ntoa(*addrList[i]));
    }
    sRv = String::trimSpace(sRv);
    xTEST(!sRv.empty());
    if (host->h_name != nullptr) {
        std::cstring_t hostName = host->h_name;
        xTEST(!hostName.empty());
    }
    *out_hostAddr = sRv;
}
References xl::core::FormatT< StreamT >::str(), xl::core::String::trimSpace(), xCHECK_DO, xT, xT2A, xTEST, and xTEST_PTR.
Referenced by xl::package::Ssh2Client::connect(), and xl::package::Ssh2Client::isAlive().
hostNameByAddr()
void_t xl::net::DnsClient::hostNameByAddr (std::ctstring_t & hostAddr, const ISocket::AddressFamily family, std::tstring_t * hostName) static
get host name by address
{
    xTEST(!a_hostAddr.empty());
    xTEST_PTR(out_hostName);
    hostent *host {};
    switch (a_family) {
    case ISocket::AddressFamily::afInet:
        {
            in_addr iaAddr {};
            iaAddr.s_addr = ::inet_addr( xT2A(a_hostAddr).c_str() );
            xTEST_DIFF(iaAddr.s_addr, INADDR_NONE);
            host = ::gethostbyaddr(reinterpret_cast<char *>(&iaAddr), sizeof(iaAddr),
                static_cast<int_t>(ISocket::AddressFamily::afInet));
            xTEST_PTR(host);
        }
        break;
#if (xWINVER >= xOS_WIN_VISTA)
    case ISocket::AddressFamily::afInet6:
        {
        #if xTODO
            IN6_ADDR iaAddr6 {};
            iRv = ::inet_pton(afInet6, a_casHostAddr.c_str(), &iaAddr6);
            xTEST_DIFF(iRv, 0);
            *out_hostName = ::gethostbyaddr(reinterpret_cast<char *>( &iaAddr6 ), 16,
                static_cast<std::size_t>(ISocket::AddressFamily::afInet6));
            xTEST_PTR(host);
        #endif
        }
        break;
#endif
    default:
        {
            *out_hostName = xA2T("");
            return;
        }
        break;
    }
    xCHECK_DO(host == nullptr, return);
    *out_hostName = xA2T(host->h_name);
}
References xl::net::ISocket::afInet, xl::net::ISocket::afInet6, xA2T, xCHECK_DO, xT2A, xTEST, xTEST_DIFF, and xTEST_PTR.
localHostName()
void_t xl::net::DnsClient::localHostName (std::tstring_t * hostName) static
get local host name
{
    xTEST_PTR(out_hostName);
    std::string asRv(xHOST_NAME_MAX, '0');
#if   xENV_WIN
    const auto   hostNameSize = static_cast<int_t>(asRv.size() * sizeof(std::string::value_type));
#elif xENV_UNIX
    std::csize_t hostNameSize = asRv.size() * sizeof(std::string::value_type);
#endif
    int_t iRv = ::gethostname(&asRv.at(0), hostNameSize);
    xTEST_EQ(iRv, 0);
    asRv.assign(asRv.c_str());    // trim '0' from end
    *out_hostName = xA2T(asRv);
}
References xA2T, xHOST_NAME_MAX, xTEST_EQ, and xTEST_PTR.
nameInfo()
void_t xl::net::DnsClient::nameInfo (ISocket::cAddressFamily a_family, std::ctstring_t & a_hostAddr, cushort_t a_hostPort, std::tstring_t * out_name, std::tstring_t * out_port) static
get name info
Parameters
a_family address family
a_hostAddr IP address
a_hostPort port
[out] out_name host name
[out] out_port service name
{
    xTEST_NA(a_family);
    xTEST(!a_hostAddr.empty());
    xTEST_GR(a_hostPort, static_cast<ushort_t>(0));
    xTEST_NA(out_name);
    xTEST_NA(out_port);
    sockaddr_in socketAddr {};
    socketAddr.sin_family      = static_cast<sa_family_t>(a_family);
    socketAddr.sin_addr.s_addr = ::inet_addr( xT2A(a_hostAddr).c_str() );
    socketAddr.sin_port        = htons(a_hostPort);
    tchar_t hostName[NI_MAXHOST + 1] = {0};
    tchar_t hostPort[NI_MAXSERV + 1] = {0};
    int_t iRv = xNAME_INFO_GET(reinterpret_cast<sockaddr *>(&socketAddr), sizeof(socketAddr),
        &hostName[0], NI_MAXHOST, &hostPort[0], NI_MAXSERV, NI_NUMERICSERV);
#if   xENV_WIN
    xTEST_EQ(iRv, 0);
#elif xENV_UNIX
    xTEST_EQ_MSG(iRv, 0, ::gai_strerror(iRv));
#endif
    // [out]
    if (out_name != nullptr) {
        *out_name = hostName;
    }
    if (out_port != nullptr) {
        xTEST_EQ(a_hostPort, (ushort_t)std::atoi(hostPort));
        *out_port = hostPort;
    }
}
References xNAME_INFO_GET, xT2A, xTEST, xTEST_EQ, xTEST_EQ_MSG, xTEST_GR, and xTEST_NA.
hostAddrInfo()
void_t xl::net::DnsClient::hostAddrInfo (std::ctstring_t & a_hostName, std::ctstring_t & a_port, caddrinfo_t * out_hints, addrinfo_t ** out_addrInfo) static
get host addr info
Parameters
a_hostName host name
a_port port
out_hints caddrinfo_t (maybe nullptr)
[out] out_addrInfo caddrinfo_t
{
    xTEST(!a_hostName.empty());
    xTEST(!a_port.empty());
    xTEST_NA(out_hints);
    xTEST_PTR(out_addrInfo);
    int_t iRv = xADDR_INFO_GET(a_hostName.c_str(), a_port.c_str(), out_hints, out_addrInfo);
#if   xENV_WIN
    xTEST_EQ(iRv, 0);
#elif xENV_UNIX
    xTEST_EQ_MSG(iRv, 0, ::gai_strerror(iRv));
#endif
}
References xADDR_INFO_GET, xTEST, xTEST_EQ, xTEST_EQ_MSG, xTEST_NA, and xTEST_PTR.
protocolByName()
void_t xl::net::DnsClient::protocolByName (std::ctstring_t & protocolName, std::tstring_t * name, std::vec_tstring_t * aliases, int_t * number) static
get protocol by name
{
    xTEST(!a_protocolName.empty());
    xTEST_NA(a_name);
    xTEST_NA(out_aliases);
    xTEST_NA(out_number);
    protoent/*PROTOENT*/ *info = ::getprotobyname( xT2A(a_protocolName).c_str() );
    xTEST_PTR(info);
    xCHECK_DO(info == nullptr, return);
    // a_name
    if (a_name != nullptr) {
        *a_name = xA2T(info->p_name);
    }
    // out_aliases
    if (out_aliases != nullptr) {
        out_aliases->clear();
        for (char **s = info->p_aliases; s && *s; ++ s) {
            out_aliases->push_back( xA2T(*s) );
        }
    }
    // a_number
    Utils::ptrAssignT(out_number, *out_number = info->p_proto);
}
References xl::core::Utils::ptrAssignT(), xA2T, xCHECK_DO, xT2A, xTEST, xTEST_NA, and xTEST_PTR.
protocolByNumber()
void_t xl::net::DnsClient::protocolByNumber (cint_t number, std::tstring_t * name, std::vec_tstring_t * aliases, int_t * number_rv) static
get protocol by number
{
    xTEST_NA(a_number);
    xTEST_NA(a_name);
    xTEST_NA(a_aliases);
    xTEST_NA(a_number_rv);
    protoent/*PROTOENT*/ *info = ::getprotobynumber(a_number);
    xTEST_PTR(info);
    xCHECK_DO(info == nullptr, return);
    // a_name
    if (a_name != nullptr) {
        *a_name = xA2T(info->p_name);
    }
    // a_aliases
    if (a_aliases != nullptr) {
        a_aliases->clear();
        for (char **s = info->p_aliases; s && *s; ++ s) {
            a_aliases->push_back( xA2T(*s) );
        }
    }
    // a_number_rv
    Utils::ptrAssignT(a_number_rv, *a_number_rv = info->p_proto);
}
References xl::core::Utils::ptrAssignT(), xA2T, xCHECK_DO, xTEST_NA, and xTEST_PTR.
serviceByName()
void_t xl::net::DnsClient::serviceByName (std::ctstring_t & serviceName, std::ctstring_t & protocolName, std::tstring_t * name, std::vec_tstring_t * aliases, int_t * port, std::tstring_t * protocolName_rv) static
get service by name
{
    xTEST(!a_serviceName.empty());
    xTEST(!a_protocolName.empty());
    xTEST_NA(a_name);
    xTEST_NA(a_aliases);
    xTEST_NA(a_port);
    xTEST_NA(a_protocolName_rv);
    servent *info = ::getservbyname(xT2A(a_serviceName).c_str(), xT2A(a_protocolName).c_str());
    xTEST_PTR(info);
    xCHECK_DO(info == nullptr, return);
    // name
    if (a_name != nullptr) {
       *a_name = xA2T(info->s_name);
    }
    // aliases
    if (a_aliases != nullptr) {
        a_aliases->clear();
        for (char **s = info->s_aliases; s && *s; ++ s) {
            a_aliases->push_back( xA2T(*s) );
        }
    }
    // port
    Utils::ptrAssignT(a_port, *a_port = info->s_port);
    // protocolName_rv
    if (a_protocolName_rv != nullptr) {
        *a_protocolName_rv = xA2T(info->s_proto);
    }
}
References xl::core::Utils::ptrAssignT(), xA2T, xCHECK_DO, xT2A, xTEST, xTEST_NA, and xTEST_PTR.
serviceByPort()
void_t xl::net::DnsClient::serviceByPort (cushort_t port, std::ctstring_t & protocolName, std::tstring_t * name, std::vec_tstring_t * aliases, short_t * port_rv, std::tstring_t * protocolName_rv) static
get service by port
{
    xTEST_GR(a_port, static_cast<ushort_t>(0));
    xTEST(!a_protocolName.empty());
    xTEST_NA(a_name);
    xTEST_NA(a_aliases);
    xTEST_NA(a_port_rv);
    xTEST_NA(a_protocolName_rv);
    servent *info = ::getservbyport(a_port, xT2A(a_protocolName).c_str());
    xTEST_PTR(info);
    xCHECK_DO(info == nullptr, return);
    // name
    if (a_name != nullptr) {
        *a_name = xA2T(info->s_name);
    }
    // aliases
    if (a_aliases != nullptr) {
        a_aliases->clear();
        for (char **s = info->s_aliases; s && *s; ++ s) {
            a_aliases->push_back( xA2T(*s) );
        }
    }
    // port
    Utils::ptrAssignT(a_port_rv, static_cast<short_t>( info->s_port ));
    // protocolName_rv
    if (a_protocolName_rv != nullptr) {
        *a_protocolName_rv = xA2T(info->s_proto);
    }
}
References xl::core::Utils::ptrAssignT(), xA2T, xCHECK_DO, xT2A, xTEST, xTEST_GR, xTEST_NA, and xTEST_PTR.
isOnLan()
bool_t xl::net::DnsClient::isOnLan (cuint_t ip) static
return true if IP is on this LAN
{
    cuint_t localIp = INADDR_ANY;  // IP of local interfaCe (network order)
    cuint_t netMask = INADDR_NONE; // net mask for IP (network order)
    return (((ntohl(a_ip) ^ ntohl(localIp)) & ntohl(netMask)) == 0UL);
}
isBroadcast()
bool_t xl::net::DnsClient::isBroadcast (cuint_t ip) static
return true if IP is a (directed) IP-broadcast address
{
    cuint_t netMask = INADDR_NONE; // net mask for IP (network order)
    return ((~ntohl(a_ip) & ~ntohl(netMask)) == 0UL);
}
isAddressIpv4()
bool_t xl::net::DnsClient::isAddressIpv4 (std::ctstring_t & ip) static
is address IP v4
{
    int_t iRv {};
    sockaddr_in sa {};
    iRv = ::inet_pton(AF_INET, xT2A(a_ip).c_str(), &sa.sin_addr);
    xTEST_DIFF(iRv, -1);
    // xTEST_DIFF_MSG(iRv, 0, Format::str(xT("Invalid IPv4: {}"), a_ip)); - skip
    return (iRv > 0);
}
References xT2A, and xTEST_DIFF.
Referenced by xl::package::Ssh2Client::connect(), and xl::package::Ssh2Client::isAlive().
isAddressIpv6()
bool_t xl::net::DnsClient::isAddressIpv6 (std::ctstring_t & ip) static
is address IP v6
{
    int_t iRv {};
    sockaddr_in6 sa {};
    iRv = ::inet_pton(AF_INET6, xT2A(a_ip).c_str(), &sa.sin6_addr);
    xTEST_DIFF(iRv, -1);
    // xTEST_DIFF_MSG(iRv, 0, Format::str(xT("Invalid IPv6: {}"), a_ip)); - skip
    return (iRv > 0);
}
References xT2A, and xTEST_DIFF.
Referenced by xl::package::Ssh2Client::connect(), and xl::package::Ssh2Client::isAlive().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/DnsClient.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/DnsClient.cpp