xLib: xl::core::Handle< T, typeT > Class Template Reference
xl::core::Handle< T, typeT > Class Template Reference final
handle
#include "Handle.h"
Inherits xl::interface_::IHandle< T >.
Public Member Functions
void_t setCloseOnExec (cbool_t flag)
ctors, dtor
Handle ()
Handle (const T &handle)
Handle (const Handle &handle)
virtual ~Handle ()
operators
Handle & operator= (const T &handle)
Handle & operator= (const Handle &handle)
Overrides
T get () const final
get
void_t set (const T &handle) final
set
T clone () const final
duplicate file descriptors from sub-processes
bool_t isValid () const final
is valid
void_t attach (const T &handle) final
attach
T detach () final
detach
void_t close () final
close
Public Member Functions inherited from xl::interface_::IHandle< T >
IHandle ()=default
virtual ~IHandle ()=default
Static Public Member Functions
static T null ()
get "null" value
static std::size_t openMax ()
maximum open handles
Detailed Description
template<typename T, HandleType typeT>
class xl::core::Handle< T, typeT >
handle
Constructor & Destructor Documentation
Handle() [1/3]
template<typename T , HandleType typeT> xl::core::Handle< T, typeT >::Handle ()
                         :
    _handle( null() )
{
}
Handle() [2/3]
template<typename T , HandleType typeT> xl::core::Handle< T, typeT >::Handle (const T & handle) explicit
  :
    _handle(a_handle)
{
    xTEST_NA(a_handle);
}
References xTEST_NA.
Handle() [3/3]
template<typename T , HandleType typeT> xl::core::Handle< T, typeT >::Handle (const Handle< T, typeT > & handle) explicit
  :
    _handle( null() )
{
    xTEST_NA(a_handle);
    _handle = a_handle.clone();
}
References xl::core::Handle< T, typeT >::clone(), and xTEST_NA.
~Handle()
template<typename T , HandleType typeT> xl::core::Handle< T, typeT >::~Handle () virtual
{
    close();
}
Member Function Documentation
operator=() [1/2]
template<typename T , HandleType typeT> Handle< T, typeT > & xl::core::Handle< T, typeT >::operator= (const T & handle)
TODO: [skynowa] disabled (for remove) - file wasn't close – close();
{
    xTEST_NA(a_handle);
    // Try m_Handle.Attach(other.Detach(), if you got an assertion here.
    xCHECK_RET(_handle == a_handle, *this);
    /// TODO: [skynowa] disabled (for remove) - file wasn't close
    ///-- close();
    _handle = a_handle;
    return *this;
}
operator=() [2/2]
template<typename T , HandleType typeT> Handle< T, typeT > & xl::core::Handle< T, typeT >::operator= (const Handle< T, typeT > & handle)
{
    xTEST_NA(a_handle);
    xCHECK_RET(this == &a_handle, *this);
    close();
    _handle = a_handle.clone();
    xTEST_NA(_handle);
    return *this;
}
get()
template<typename T , HandleType typeT> T xl::core::Handle< T, typeT >::get () const final virtual
get
Implements xl::interface_::IHandle< T >.
{
    return _handle;
}
Referenced by xl::db::mysql::IResult::_fetchLengths(), xl::db::mysql::IResult::_fetchRow(), xl::net::TcpServer::accept(), xl::net::TcpServer::bind(), xl::fs::FileIO::clearError(), xl::db::mysql::Connection::commit(), xl::package::Ssh2Client::connect(), xl::net::TcpClient::connect(), xl::package::curl::Client::escape(), xl::db::mysql::IResult::fetchField(), xl::db::mysql::IResult::fetchFieldDirect(), xl::db::mysql::IResult::fetchFields(), xl::db::mysql::IResult::fields(), xl::fs::FileIO::flush(), xl::fs::FileIO::getNative(), xl::package::curl::Client::info(), xl::net::TcpClient::ioctl(), xl::fs::FileIO::isEof(), xl::fs::FileIO::isError(), xl::net::ISocket::isReadable(), xl::net::TcpClient::isServerAlive(), xl::net::ISocket::isWritable(), xl::db::mysql::Connection::kill(), xl::net::TcpServer::listen(), xl::fs::FileIO::locking(), xl::package::curl::Client::pause(), xl::package::curl::Client::perform(), xl::db::mysql::Connection::ping(), xl::fs::FileIO::position(), xl::fs::FileIO::read(), xl::fs::FileIO::read(), xl::fs::FileIO::readChar(), xl::fs::FileIO::readLine(), xl::package::curl::Client::receive(), xl::net::ISocket::receiveBytes(), xl::net::ISocket::recvAll(), xl::package::curl::Client::reset(), xl::db::mysql::Connection::rollback(), xl::db::mysql::IResult::rows(), xl::fs::FileIO::scanf(), xl::db::mysql::Connection::selectDb(), xl::package::curl::Client::send(), xl::net::ISocket::sendBytes(), xl::db::mysql::Connection::setAutoCommit(), xl::package::curl::Client::setOption(), xl::fs::FileIO::setPosition(), xl::fs::FileIO::setSize(), xl::fs::FileIO::setVBuff(), xl::package::curl::Client::unescape(), xl::fs::FileIO::ungetChar(), xl::fs::File::wipe(), xl::fs::FileIO::write(), xl::fs::FileIO::write(), xl::fs::FileIO::write(), xl::fs::FileIO::writeChar(), xl::fs::FileIO::writeLine(), and xl::fs::FileIO::writeV().
set()
template<typename T , HandleType typeT> void_t xl::core::Handle< T, typeT >::set (const T & handle) final virtual
set
Implements xl::interface_::IHandle< T >.
{
    xTEST_NA(a_handle);
    _handle = a_handle;
}
References xTEST_NA.
clone()
template<typename T , HandleType typeT> T xl::core::Handle< T, typeT >::clone () const final virtual
duplicate file descriptors from sub-processes
Implements xl::interface_::IHandle< T >.
{
    xCHECK_RET(!isValid(), null());
    // Impl
    {
        if      constexpr (typeT == HandleType::Native) {
        #if   xENV_WIN
            T hRv = null();
            BOOL blRes = ::DuplicateHandle(::GetCurrentProcess(), _handle, ::GetCurrentProcess(), &hRv,
                DUPLICATE_SAME_ACCESS, FALSE, DUPLICATE_SAME_ACCESS);
            xTEST_DIFF(blRes, FALSE);
            return hRv;
        #elif xENV_UNIX
            int_t handleDup {};
            int_t iRv = xDUP2(_handle, handleDup);
            xTEST_DIFF(iRv, -1);
            return handleDup;
        #endif
        }
        else if constexpr (typeT == HandleType::NativeInvalid) {
        #if   xENV_WIN
            T hRv = null();
            BOOL blRes = ::DuplicateHandle(::GetCurrentProcess(), _handle, ::GetCurrentProcess(), &hRv,
                DUPLICATE_SAME_ACCESS, FALSE, DUPLICATE_SAME_ACCESS);
            xTEST_DIFF(blRes, FALSE);
            return hRv;
        #elif xENV_UNIX
            int_t handleDup {};
            int_t iRv = xDUP2(_handle, handleDup);
            xTEST_DIFF(iRv, -1);
            return handleDup;
        #endif
        }
        else if constexpr (typeT == HandleType::Dll) {
        #if   xENV_WIN
            // TODO: [skynowa] Dll
            return _handle;
        #elif xENV_UNIX
            // TODO: [skynowa] Dll
            return _handle;
        #endif
        }
        else if constexpr (typeT == HandleType::StdFile) {
            int_t handle = ::fileno(_handle);
            xTEST_DIFF(handle, -1);
            int_t handleDup {};
            int_t iRv = xDUP2(handle, handleDup);
            xTEST_DIFF(iRv, -1);
            return static_cast<T>(xTFDOPEN(handleDup, xT("r+")));  // TODO: [skynowa] clone - open mode
        }
        else if constexpr (typeT == HandleType::MySqlConn) {
            return _handle;
        }
        else if constexpr (typeT == HandleType::MySqlResult) {
            return _handle;
        }
        else if constexpr (typeT == HandleType::Curl) {
            return ::curl_easy_duphandle(_handle);
        }
        else if constexpr (typeT == HandleType::FindDir) {
        #if   xENV_WIN
            // TODO: [skynowa] FindDir
            return _handle;
        #elif xENV_UNIX
            // TODO: [skynowa] FindDir
            return _handle;
        #endif
        }
        else if constexpr (typeT == HandleType::Socket) {
        #if   xENV_WIN
            // TODO: [skynowa] Socket
            return _handle;
        #elif xENV_UNIX
            // TODO: [skynowa] Socket
            return _handle;
        #endif
        }
        else {
            // n/a - as compile-time test
        }
    } // Impl
}
References xl::core::Curl, xl::core::Dll, xl::core::FindDir, xl::core::MySqlConn, xl::core::MySqlResult, xl::core::Native, xl::core::NativeInvalid, xl::core::Socket, xl::core::StdFile, xCHECK_RET, xDUP2, xT, and xTEST_DIFF.
Referenced by xl::core::Handle< T, typeT >::Handle().
isValid()
template<typename T , HandleType typeT> bool_t xl::core::Handle< T, typeT >::isValid () const final virtual
is valid
Implements xl::interface_::IHandle< T >.
{
#if xENV_WIN
    if constexpr (typeT == HandleType::NativeInvalid) {
        // created but not initialised
        cbool_t cond1 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xCDCDCDCD) ));
        // uninitialized locals in VC6 when you compile w/ /GZ
        cbool_t cond2 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xCCCCCCCC) ));
        // indicate an uninitialized variable
        cbool_t cond3 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xBAADF00D) ));
        // no man's land (normally outside of a process)
        cbool_t cond4 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xFDFDFDFD) ));
        // freed memory set by NT's heap manager
        cbool_t cond5 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xFEEEFEEE) ));
        // deleted
        cbool_t cond6 = (_handle != reinterpret_cast<T>( static_cast<intptr_t>(0xDDDDDDDD) ));
        // compare with error handle value
        cbool_t cond7 = (_handle != null());
        return (cond1 && cond2 && cond3 && cond4 && cond5 && cond6 && cond7);
    }
    else if constexpr (typeT == HandleType::Socket) {
        return (_handle >= 0);
    }
    else {
        return (_handle != null());
    }
#elif xENV_UNIX
    return (_handle != null());
#endif
}
References xl::core::NativeInvalid, and xl::core::Socket.
Referenced by xl::db::mysql::IResult::_fetchLengths(), xl::db::mysql::IResult::_fetchRow(), xl::net::TcpServer::accept(), xl::net::TcpServer::bind(), xl::package::curl::Client::Client(), xl::fs::FileIO::close(), xl::net::TcpClient::connect(), xl::net::ISocket::create(), xl::db::mysql::IResult::fetchField(), xl::db::mysql::IResult::fetchFieldDirect(), xl::db::mysql::IResult::fetchFields(), xl::db::mysql::IResult::fetchRow(), xl::db::mysql::IResult::fetchRows(), xl::db::mysql::IResult::fields(), xl::package::curl::HttpClient::getInfos(), xl::fs::FileIO::getNative(), xl::net::ISocket::handle(), xl::net::TcpClient::ioctl(), xl::db::mysql::IResult::IResult(), xl::net::TcpServer::listen(), xl::fs::FsWatcher::openFiles(), xl::net::ISocket::receive(), xl::db::mysql::IResult::rows(), xl::net::ISocket::send(), xl::net::ISocket::sendAll(), xl::package::curl::HttpClient::setOptionsDefault(), xl::db::mysql::StoreResult::StoreResult(), and xl::db::mysql::UseResult::UseResult().
attach()
template<typename T , HandleType typeT> void_t xl::core::Handle< T, typeT >::attach (const T & handle) final virtual
attach
Implements xl::interface_::IHandle< T >.
{
    xTEST_NA(a_handle);
    xCHECK_DO(!isValid(), return);
    close();
    _handle = a_handle;
}
References xCHECK_DO, and xTEST_NA.
detach()
template<typename T , HandleType typeT> T xl::core::Handle< T, typeT >::detach () final virtual
detach
Implements xl::interface_::IHandle< T >.
{
    T hRv = _handle;
    _handle = null();
    return hRv;
}
close()
template<typename T , HandleType typeT> void_t xl::core::Handle< T, typeT >::close () final virtual
close
Implements xl::interface_::IHandle< T >.
{
    if ( !isValid() ) {
        _handle = null();
        return;
    }
    // Impl
    {
        if      constexpr (typeT == HandleType::Native ||
                           typeT == HandleType::NativeInvalid)
        {
        #if   xENV_WIN
            BOOL blRes = ::CloseHandle(_handle);
            xTEST_DIFF(blRes, FALSE);
        #elif xENV_UNIX
            int_t iRv = ::close(_handle);
            xTEST_DIFF(iRv, -1);
        #endif
        }
        else if constexpr (typeT == HandleType::Dll) {
        #if   xENV_WIN
            BOOL blRv = ::FreeLibrary(_handle);
            xTEST_DIFF(blRv, FALSE);
        #elif xENV_UNIX
            int_t iRv = ::dlclose(_handle);
            xTEST_EQ(iRv, 0);
        #endif
        }
        else if constexpr (typeT == HandleType::StdFile) {
            int_t iRv {};
            iRv = std::fflush(_handle);
            xTEST_DIFF(iRv, xTEOF);
            iRv = std::fclose(_handle);
            xTEST_DIFF(iRv, xTEOF);
        }
        else if constexpr (typeT == HandleType::MySqlConn) {
            (void_t)::mysql_close(_handle);
        }
        else if constexpr (typeT == HandleType::MySqlResult) {
            (void_t)::mysql_free_result(_handle);
        }
        else if constexpr (typeT == HandleType::Curl) {
            (void_t)::curl_easy_cleanup(_handle);
        }
        else if constexpr (typeT == HandleType::FindDir) {
        #if   xENV_WIN
            BOOL blRv = ::FindClose(_handle);
            xTEST_DIFF(blRv, FALSE);
        #elif xENV_UNIX
            int_t iRv = ::closedir(_handle);
            xTEST_DIFF(iRv, -1);
        #endif
        }
        else if constexpr (typeT == HandleType::Socket) {
        #if   xENV_WIN
            int_t iRv = ::shutdown(_handle, SD_BOTH);
            xTEST_DIFF(iRv, xSOCKET_ERROR);
            iRv = ::closesocket(_handle);
            xTEST_DIFF(iRv, xSOCKET_ERROR);
        #elif xENV_UNIX
            int_t iRv = ::shutdown(_handle, SHUT_RDWR);
            xTEST_DIFF(iRv, xSOCKET_ERROR);
            iRv = ::close(_handle);
            xTEST_DIFF(iRv, xSOCKET_ERROR);
        #endif
        }
        else {
            // n/a - as compile-time test
        }
    } // Impl
    _handle = null();
}
References xl::core::Curl, xl::core::Dll, xl::core::FindDir, xl::core::MySqlConn, xl::core::MySqlResult, xl::core::Native, xl::core::NativeInvalid, xl::core::Socket, xl::core::StdFile, xSOCKET_ERROR, xTEST_DIFF, and xTEST_EQ.
Referenced by xl::db::mysql::Connection::close(), xl::fs::FileIO::close(), xl::fs::FsWatcher::close(), and xl::net::ISocket::close().
setCloseOnExec()
template<typename T , HandleType typeT> void_t xl::core::Handle< T, typeT >::setCloseOnExec (cbool_t flag)
Dealing with Duplicate file Descriptors from Sub-Processes
https://oroboro.com/file-handle-leaks-server/
When you spawn subprocesses they inherit all the open file descriptors of the parent process unless those descriptors have been specifically flagged as FD_CLOEXEC
This is because the operating system doesnt know which file descriptors will be used by the subprocess for inter-process communication. Or if the subprocess will be the one that will handle an open network socket.
Normally when you spawn subprocesses the only file descriptors that need to stay open are the pipes that are connected to STDIN, STDOUT, and STDERR of the child process. But every subprocess is different.
Right before your server calls fork() or exec(), call showFdInfo() to make sure that all file descriptors are labeled FD_CLOEXEC except for the ones you need to be duplicated.
{
   /**
    * Dealing with Duplicate file Descriptors from Sub-Processes
    *
    * https://oroboro.com/file-handle-leaks-server/
    *
    * When you spawn subprocesses they inherit all the open file descriptors of the parent process
    * unless those descriptors have been specifically flagged as FD_CLOEXEC
    *
    * This is because the operating system doesnt know which file descriptors will be used by the
    * subprocess for inter-process communication. Or if the subprocess will be the one that will
    * handle an open network socket.
    *
    * Normally when you spawn subprocesses the only file descriptors that need to stay open are
    * the pipes that are connected to STDIN, STDOUT, and STDERR of the child process. But every
    * subprocess is different.
    *
    * Right before your server calls fork() or exec(), call showFdInfo() to make sure that all file
    * descriptors are labeled FD_CLOEXEC except for the ones you need to be duplicated.
    */
    _setCloseOnExec_impl(a_flag);
}
null()
template<typename T , HandleType typeT> T xl::core::Handle< T, typeT >::null () static
get "null" value
{
    if      constexpr (typeT == HandleType::Native) {
        return xNATIVE_HANDLE_NULL;
    }
    else if constexpr (typeT == HandleType::NativeInvalid) {
        return xNATIVE_HANDLE_INVALID;
    }
    else if constexpr (typeT == HandleType::Dll) {
        return nullptr;
    }
    else if constexpr (typeT == HandleType::StdFile) {
        return nullptr;
    }
    else if constexpr (typeT == HandleType::MySqlConn) {
        return nullptr;
    }
    else if constexpr (typeT == HandleType::MySqlResult) {
        return nullptr;
    }
    else if constexpr (typeT == HandleType::Curl) {
        return nullptr;
    }
    else if constexpr (typeT == HandleType::FindDir) {
        return xFIND_DIR_HANDLE_NULL;
    }
    else if constexpr (typeT == HandleType::Socket) {
        return xSOCKET_HANDLE_INVALID;
    }
    else {
        // n/a - as compile-time test
    }
}
References xl::core::Curl, xl::core::Dll, xl::core::FindDir, xl::core::MySqlConn, xl::core::MySqlResult, xl::core::Native, xl::core::NativeInvalid, xl::core::Socket, xl::core::StdFile, xFIND_DIR_HANDLE_NULL, xNATIVE_HANDLE_INVALID, xNATIVE_HANDLE_NULL, and xSOCKET_HANDLE_INVALID.
openMax()
template<typename T , HandleType typeT> std::size_t xl::core::Handle< T, typeT >::openMax () static
maximum open handles
show variables like "max_connections"
+--------------—+----—+ | Variable_name | Value | +--------------—+----—+ | max_connections | 100 | +--------------—+----—+
set global max_connections = 200;
{
    if constexpr (typeT == HandleType::Native ||
                  typeT == HandleType::NativeInvalid ||
                  typeT == HandleType::Dll ||
                  typeT == HandleType::StdFile)
    {
    #if   xENV_WIN
        cint_t iRv = _getmaxstdio();
        xTEST_GR(iRv, 0);
        return static_cast<std::size_t>(iRv);
    #elif xENV_UNIX
        rlimit limit {};
        int_t iRv = ::getrlimit(RLIMIT_NOFILE, &limit);
        xTEST_EQ(iRv, 0);
        xTEST_GR(static_cast<std::size_t>(limit.rlim_cur), 0UL);
        return static_cast<std::size_t>( limit.rlim_cur );
    #endif
    }
    else if constexpr (typeT == HandleType::MySqlConn) {
        // TODO: [skynowa] _openMax_impl
       /**
        * show variables like "max_connections"
        *
        * +-----------------+-------+
        * | Variable_name   | Value |
        * +-----------------+-------+
        * | max_connections | 100   |
        * +-----------------+-------+
        *
        * set global max_connections = 200;
        */
        return 0;
    }
    else if constexpr (typeT == HandleType::MySqlResult) {
        // TODO: [skynowa] MySqlResult
        return 0;
    }
    else if constexpr (typeT == HandleType::Curl) {
        return static_cast<std::size_t>(CURLOPT_MAXCONNECTS);
    }
    else if constexpr (typeT == HandleType::FindDir) {
    #if   xENV_WIN
        cint_t iRv = _getmaxstdio();
        xTEST_GR(iRv, 0);
        return static_cast<std::size_t>(iRv);
    #elif xENV_UNIX
        // TODO: [skynowa] FindDir
        return 0;
    #endif
    }
    else if constexpr (typeT == HandleType::Socket) {
    #if   xENV_WIN
        cint_t iRv = _getmaxstdio();
        xTEST_GR(iRv, 0);
        return static_cast<std::size_t>(iRv);
    #elif xENV_UNIX
        // TODO: [skynowa] FindDir
        return 0;
    #endif
    }
    else {
        // n/a - as compile-time test
    }
}
References xl::core::Curl, xl::core::Dll, xl::core::FindDir, xl::core::MySqlConn, xl::core::MySqlResult, xl::core::Native, xl::core::NativeInvalid, xl::core::Socket, xl::core::StdFile, xTEST_EQ, and xTEST_GR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Handle.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Handle.inl