xLib: xl::debug::AutoProfiler Class Reference
xl::debug::AutoProfiler Class Reference
auto profiling code
#include "AutoProfiler.h"
Public Member Functions
ctors, dtor
AutoProfiler (std::ctstring_t &filePath, cptr_ctchar_t comment,...)
virtual ~AutoProfiler ()
xNO_DEFAULT_CONSTRUCT (AutoProfiler)
xNO_COPY_ASSIGN (AutoProfiler)
Detailed Description
auto profiling code
Constructor & Destructor Documentation
AutoProfiler()
xl::debug::AutoProfiler::AutoProfiler (std::ctstring_t & filePath, cptr_ctchar_t comment, ...)
{
    // format comment
    va_list args;
    xVA_START(args, a_comment);
    _comment = FormatC::strV(a_comment, args);
    xVA_END(args);
    // start
    _profiler.setLogPath(a_filePath);
    _profiler.start();
}
References xl::debug::Profiler::setLogPath(), xl::debug::Profiler::start(), and xl::core::FormatC::strV().
~AutoProfiler()
xl::debug::AutoProfiler::~AutoProfiler () virtual
{
    size_t uiRv = _profiler.stop(xT("%s"), _comment.c_str());
    xUNUSED(uiRv);
}
References xl::debug::Profiler::stop(), xT, and xUNUSED.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::debug::AutoProfiler::xNO_DEFAULT_CONSTRUCT (AutoProfiler)
xNO_COPY_ASSIGN()
xl::debug::AutoProfiler::xNO_COPY_ASSIGN (AutoProfiler)
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/AutoProfiler.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/AutoProfiler.cpp