xLib: xl::fs::FsWatcher Class Reference
xl::fs::FsWatcher Class Reference abstract
File system watcher.
#include "FsWatcher.h"
Public Types
enum class Event {
Unknown = 0 ,
Attrib ,
CloseNoWrite ,
CloseWrite ,
Open ,
Read ,
Moved ,
Delete ,
Modify_linux ,
MovedFrom_linux ,
MovedTo_linux ,
Create_linux ,
Delete_linux ,
Delete_bsd ,
Extend_bsd ,
Link_bsd ,
Revoke_bsd ,
Write_bsd
}
Public Member Functions
bool_t openFiles (std::cvec_tstring_t &filePaths, std::cmap_tstring_t &cmds)
bool_t openDirs (std::cvec_tstring_t &dirPaths, std::cmap_tstring_t &cmds)
void_t watch (culong_t timeoutMsec)
void_t close ()
virtual void_t onEvent (std::ctstring_t &fsName, cEvent event)=0
ctors, dtor
FsWatcher (std::cvec_tstring_t &dirPathsDisabled, std::ctstring_t &shellFilter)
virtual ~FsWatcher ()
xNO_DEFAULT_CONSTRUCT (FsWatcher)
xNO_COPY_ASSIGN (FsWatcher)
Detailed Description
File system watcher.
Member Enumeration Documentation
Event
enum class xl::fs::FsWatcher::Event strong
Enumerator
Unknown
Attrib
CloseNoWrite
CloseWrite
Open
Read
Moved
Delete
Modify_linux
MovedFrom_linux
MovedTo_linux
Create_linux
Delete_linux
Delete_bsd
Extend_bsd
Link_bsd
Revoke_bsd
Write_bsd
    {
        Unknown = 0,
        Attrib,
        CloseNoWrite,
        CloseWrite,
        Open,
        Read,
        Moved,
        Delete,
        // Linux
        Modify_linux,
        MovedFrom_linux,
        MovedTo_linux,
        Create_linux,
        Delete_linux,
        // BSD
        Delete_bsd,
        Extend_bsd,
        Link_bsd,
        Revoke_bsd,
        Write_bsd
    };
Constructor & Destructor Documentation
FsWatcher()
xl::fs::FsWatcher::FsWatcher (std::cvec_tstring_t & dirPathsDisabled, std::ctstring_t & shellFilter)
  :
    _dirPathsDisabled(a_dirPathsDisabled),
    _shellFilter     (a_shellFilter)
{
}
~FsWatcher()
xl::fs::FsWatcher::~FsWatcher () virtual
{
    close();
}
References close().
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::FsWatcher::xNO_DEFAULT_CONSTRUCT (FsWatcher)
xNO_COPY_ASSIGN()
xl::fs::FsWatcher::xNO_COPY_ASSIGN (FsWatcher)
openFiles()
bool_t xl::fs::FsWatcher::openFiles (std::cvec_tstring_t & filePaths, std::cmap_tstring_t & cmds)
{
    close();
    // _filePaths
    for (const auto &it_filePath : a_filePaths) {
        FileIO file(it_filePath);
        file.open(FileIO::OpenMode::ReadOnly);
        if ( !file.get().isValid() ) {
            std::tcout << "[FsWatcher] Can't open: " << it_filePath << std::endl;
            continue;
        }
        _filePaths.push_back(it_filePath);
        _fileHandles.push_back( file.getNative() );
        // TODO: FileIO::detach - removed
        // HandleStdFile &handle = file.detach();
        // xUNUSED(handle);
    }
    if ( _filePaths.empty() ) {
        return false;
    }
    // a_cmds
    _cmds = a_cmds;
    return true;
}
References close(), xl::fs::FileIO::get(), xl::fs::FileIO::getNative(), xl::core::Handle< T, typeT >::isValid(), xl::fs::FileIO::open(), and xl::fs::FileIO::ReadOnly.
Referenced by openDirs().
openDirs()
bool_t xl::fs::FsWatcher::openDirs (std::cvec_tstring_t & dirPaths, std::cmap_tstring_t & cmds)
{
    bool_t bRv {};
    close();
    for (const auto &it_dirPath : a_dirPaths) {
        std::vec_tstring_t filePaths;
        Finder::files(it_dirPath, _shellFilter, true, &filePaths);
        std::tcout << "[FsWatcher] Open dir: " << it_dirPath << ", " << filePaths.size() << std::endl;
        if ( filePaths.empty() ) {
            continue;
        }
        bRv = openFiles(filePaths, a_cmds);
        if (!bRv) {
            continue;
        }
    }
    std::tcout << "[FsWatcher] Opened files: " << _filePaths.size() << std::endl;
    return true;
}
References close(), xl::fs::Finder::files(), and openFiles().
watch()
void_t xl::fs::FsWatcher::watch (culong_t timeoutMsec)
{
    _watch_impl();
    Thread::currentSleep(a_timeoutMsec);
}
References xl::sync::Thread::currentSleep().
close()
void_t xl::fs::FsWatcher::close ()
{
    _close_impl();
    for (const auto &it_fileHandle : _fileHandles) {
        // TODO: Close handles
        xUNUSED(it_fileHandle);
    #if 0
        HandleNativeInvalid handle;
        handle = it_fileHandle;
        handle.close();
    #endif
    }
    _fileHandles.clear();
    _filePaths.clear();
    _cmds.clear();
}
References xl::core::Handle< T, typeT >::close(), and xUNUSED.
Referenced by openDirs(), openFiles(), and ~FsWatcher().
onEvent()
virtual void_t xl::fs::FsWatcher::onEvent (std::ctstring_t & fsName, cEvent event) pure virtual
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FsWatcher.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FsWatcher.cpp