xLib: xl::sync::Signal Class Reference
xl::sync::Signal Class Reference
signal
#include "Signal.h"
Public Types
using on_info_t = void_t(*)(int_t sig, siginfo_t *siginfo, void_t *context)
signal info handler type
using on_exit_t = void_t(*)()
exit handler type
Public Member Functions
std::sig_atomic_t state () const
get state flag
void_t setState (const std::sig_atomic_t state)
set state flag
void_t connect (const std::vector< int_t > &signalNums, const sighandler_t onSignals) const
set signal handle
void_t connectAll (const sighandler_t onSignals) const
set all signal handle
void_t connectInfo (const std::vector< int_t > &signalNums, const on_info_t onInfo) const
set signal handle
void_t connectInfoAll (const on_info_t onInfo) const
set all signal handle
void_t connectExit (const on_exit_t onExit) const
set exit handle
void_t connectTerminate (const std::terminate_handler onTerminate) const
set terminate handle (by default, the terminate handler calls abort)
void_t connectUnexpected (const std::unexpected_handler onUnexpected) const
set unexpected handler
void_t raise (cint_t signalNum) const
sends signal to the current executing program
ctors, dtor
Signal ()=default
virtual ~Signal ()=default
xNO_COPY_ASSIGN (Signal)
Static Public Member Functions
static bool_t isValid (cint_t signalNum)
check whether a given signal is valid for the current machine
static std::tstring_t decription (cint_t signalNum)
string describing signal
static std::tstring_t infoDescription (const siginfo_t &info)
string describing signal code
Detailed Description
signal
Member Typedef Documentation
on_info_t
using xl::sync::Signal::on_info_t = void_t (*) (int_t sig, siginfo_t *siginfo, void_t *context)
signal info handler type
on_exit_t
using xl::sync::Signal::on_exit_t = void_t (*) ()
exit handler type
Constructor & Destructor Documentation
Signal()
xl::sync::Signal::Signal () default
~Signal()
virtual xl::sync::Signal::~Signal () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::Signal::xNO_COPY_ASSIGN (Signal)
state()
std::sig_atomic_t xl::sync::Signal::state () const
get state flag
{
    return _state;
}
setState()
void_t xl::sync::Signal::setState (const std::sig_atomic_t state)
set state flag
{
    // ANDROID: SIG_ATOMIC_MIN, SIG_ATOMIC_MAX
#if xTODO_ANDROID
    xTEST(a_state >= SIG_ATOMIC_MIN && a_state <= SIG_ATOMIC_MAX);
#endif
    _state = a_state;
}
References xTEST.
connect()
void_t xl::sync::Signal::connect (const std::vector< int_t > & signalNums, const sighandler_t onSignals) const
set signal handle
FAQ: set handlers
https://gist.github.com/jvranish/4441299
TODO: [xENV_APPLE]
{
   /**
    * FAQ: set handlers
    *
    * https://gist.github.com/jvranish/4441299
    */
    int_t iRv = 0;
    struct sigaction action {};
    {
        action.sa_handler = a_onSignals;
        /// TODO: [xENV_APPLE]
    #if xENV_APPLE
        iRv = sigemptyset(&action.sa_mask);
    #else
        iRv = ::sigemptyset(&action.sa_mask);
    #endif
        xTEST_DIFF(iRv, - 1);
        action.sa_flags = SA_RESTART | SA_SIGINFO;
    }
    for (const auto &it : a_signalNums) {
        switch (it) {
        case SIGKILL:
            Trace() << Format::str(xT("xLib: Signal {} ({}) cannot be caught or ignored"),
                            xLEX_TO_STR(SIGKILL), SIGKILL);
            continue;
        case SIGSTOP:
            Trace() << Format::str(xT("xLib: Signal {} ({}) cannot be caught or ignored"),
                            xLEX_TO_STR(SIGSTOP), SIGSTOP);
            continue;
            break;
        default:
            break;
        }
        iRv = ::sigaction(it, &action, nullptr);
        xTEST_DIFF_MSG(iRv, - 1, Format::str(xT("Signal: {}"), decription(it)));
    }
}
References decription(), xl::core::FormatT< StreamT >::str(), xLEX_TO_STR, xT, xTEST_DIFF, and xTEST_DIFF_MSG.
Referenced by connectAll().
connectAll()
void_t xl::sync::Signal::connectAll (const sighandler_t onSignals) const
set all signal handle
{
    std::vector<int_t> signalNums;
    cint_t signalMin = SIGHUP;
    cint_t signalMax = SIGSYS;
    for (int_t i = signalMin; i <= signalMax; ++ i) {
        // filter signals
        {
            switch (i) {
            case SIGKILL:
            case SIGSTOP:
                // signals cannot be caught or ignored;
                continue;
                break;
            default:
                break;
            }
            // TODO: [skynowa] [ANDROID] SIGCLD
        }
        signalNums.push_back(i);
    }  // for (signalMax)
    connect(signalNums, a_onSignals);
}
References connect().
connectInfo()
void_t xl::sync::Signal::connectInfo (const std::vector< int_t > & signalNums, const on_info_t onInfo) const
set signal handle
FAQ: set handlers
https://gist.github.com/jvranish/4441299
TODO: [xENV_APPLE]
TODO: [xENV_APPLE]
{
   /**
    * FAQ: set handlers
    *
    * https://gist.github.com/jvranish/4441299
    */
    int_t iRv = 0;
    struct sigaction action;
    {
        // Block other terminal-generated signals while handler runs
        sigset_t blockMask;
        {
            /// TODO: [xENV_APPLE]
        #if xENV_APPLE
            iRv = sigemptyset(&blockMask);
        #else
            iRv = ::sigemptyset(&blockMask);
        #endif
            xTEST_DIFF(iRv, - 1);
            for (const auto &it : a_signalNums) {
                if (it == SIGKILL || it == SIGSTOP) {
                    continue;
                }
                /// TODO: [xENV_APPLE]
            #if xENV_APPLE
                iRv = sigaddset(&blockMask, it);
            #else
                iRv = ::sigaddset(&blockMask, it);
            #endif
                xTEST_DIFF(iRv, - 1);
            }
        }
        action.sa_sigaction = a_onInfo;
        action.sa_mask      = blockMask;
        action.sa_flags     = SA_RESTART | SA_SIGINFO;
    }
    for (const auto &it : a_signalNums) {
        switch (it) {
        case SIGKILL:
            Trace() << Format::str(xT("xLib: Signal {} ({}) cannot be caught or ignored"),
                            xLEX_TO_STR(SIGKILL), SIGKILL);
            continue;
        case SIGSTOP:
            Trace() << Format::str(xT("xLib: Signal {} ({}) cannot be caught or ignored"),
                            xLEX_TO_STR(SIGSTOP), SIGSTOP);
            continue;
            break;
        default:
            break;
        }
        iRv = ::sigaction(it, &action, nullptr);
        xTEST_DIFF_MSG(iRv, - 1, Format::str(xT("Signal: {}"), decription(it)));
    }
}
References decription(), xl::core::FormatT< StreamT >::str(), xLEX_TO_STR, xT, xTEST_DIFF, and xTEST_DIFF_MSG.
Referenced by connectInfoAll().
connectInfoAll()
void_t xl::sync::Signal::connectInfoAll (const on_info_t onInfo) const
set all signal handle
{
    std::vector<int_t> signalNums;
    cint_t signalMin = SIGHUP;
    cint_t signalMax = SIGSYS;
    for (int_t i = signalMin; i <= signalMax; ++ i) {
        // filter signals
        {
            switch (i) {
            case SIGKILL:
            case SIGSTOP:
                // signals cannot be caught or ignored;
                continue;
                break;
            default:
                break;
            }
            // TODO: [skynowa] [ANDROID] SIGCLD
        }
        signalNums.push_back(i);
    }  // for (signalMax)
    connectInfo(signalNums, a_onInfo);
}
References connectInfo().
Referenced by xl::package::Application::run().
connectExit()
void_t xl::sync::Signal::connectExit (const on_exit_t onExit) const
set exit handle
{
    xCHECK_DO(a_onExit == nullptr, return);
    int_t iRv = std::atexit(a_onExit);
    xTEST(iRv == 0);
}
References xCHECK_DO, and xTEST.
Referenced by xl::package::Application::run().
connectTerminate()
void_t xl::sync::Signal::connectTerminate (const std::terminate_handler onTerminate) const
set terminate handle (by default, the terminate handler calls abort)
{
    std::terminate_handler handler_old = std::set_terminate(a_onTerminate);
    xUNUSED(handler_old);
}
References xUNUSED.
Referenced by xl::package::Application::run().
connectUnexpected()
void_t xl::sync::Signal::connectUnexpected (const std::unexpected_handler onUnexpected) const
set unexpected handler
{
    std::unexpected_handler handler_old = std::set_unexpected(a_onUnexpected);
    xUNUSED(handler_old);
}
References xUNUSED.
Referenced by xl::package::Application::run().
raise()
void_t xl::sync::Signal::raise (cint_t signalNum) const
sends signal to the current executing program
{
    int_t iRv = std::raise(a_signalNum);
    xTEST(iRv == 0);
}
References xTEST.
isValid()
bool_t xl::sync::Signal::isValid (cint_t a_signalNum) static
check whether a given signal is valid for the current machine
Parameters
a_signalNum signal number
{
    return (::sigaction(a_signalNum, nullptr, nullptr) == 0);
}
decription()
std::tstring_t xl::sync::Signal::decription (cint_t a_signalNum) static
string describing signal
Parameters
a_signalNum signal number
{
    return Format::str(xT("{} - {}"), a_signalNum, _decription_impl(a_signalNum));
}
References xl::core::FormatT< StreamT >::str(), and xT.
Referenced by connect(), connectInfo(), and infoDescription().
infoDescription()
std::tstring_t xl::sync::Signal::infoDescription (const siginfo_t & a_info) static
string describing signal code
Parameters
a_info signal info struct
{
    std::tstring_t sRv;
    cint_t         _KERNEL = - 1;
    constexpr _SignalInfo signalInfos[] =
    {
        // _KERNEL
    #if !xENV_BSD && !xENV_APPLE
        {_KERNEL, SI_ASYNCNL,    xLEX_TO_STR(SI_ASYNCNL),    xT("Sent by asynch name lookup completion")},
        {_KERNEL, SI_TKILL,      xLEX_TO_STR(SI_TKILL),      xT("Sent by tkill")},
        {_KERNEL, SI_SIGIO,      xLEX_TO_STR(SI_SIGIO),      xT("Sent by queued SIGIO")},
    #endif
        {_KERNEL, SI_ASYNCIO,    xLEX_TO_STR(SI_ASYNCIO),    xT("Sent by AIO completion")},
        {_KERNEL, SI_MESGQ,      xLEX_TO_STR(SI_MESGQ),      xT("Sent by real time mesq state change")},
        {_KERNEL, SI_TIMER,      xLEX_TO_STR(SI_TIMER),      xT("Sent by timer expiration")},
        {_KERNEL, SI_QUEUE,      xLEX_TO_STR(SI_QUEUE),      xT("Sent by sigqueue")},
        {_KERNEL, SI_USER,       xLEX_TO_STR(SI_USER),       xT("Sent by kill, sigsend")},
    #if !xENV_APPLE
        {_KERNEL, SI_KERNEL,     xLEX_TO_STR(SI_KERNEL),     xT("Send by kernel")},
    #endif
        // SIGILL
        {SIGILL,  ILL_ILLOPC,    xLEX_TO_STR(ILL_ILLOPC),    xT("Illegal opcode")},
        {SIGILL,  ILL_ILLOPN,    xLEX_TO_STR(ILL_ILLOPN),    xT("Illegal operand")},
        {SIGILL,  ILL_ILLADR,    xLEX_TO_STR(ILL_ILLADR),    xT("Illegal addressing mode")},
        {SIGILL,  ILL_ILLTRP,    xLEX_TO_STR(ILL_ILLTRP),    xT("Illegal trap")},
        {SIGILL,  ILL_PRVOPC,    xLEX_TO_STR(ILL_PRVOPC),    xT("Privileged opcode")},
        {SIGILL,  ILL_PRVREG,    xLEX_TO_STR(ILL_PRVREG),    xT("Privileged register")},
        {SIGILL,  ILL_COPROC,    xLEX_TO_STR(ILL_COPROC),    xT("Coprocessor error")},
        {SIGILL,  ILL_BADSTK,    xLEX_TO_STR(ILL_BADSTK),    xT("Internal stack error")},
        // SIGFPE
        {SIGFPE,  FPE_INTDIV,    xLEX_TO_STR(FPE_INTDIV),    xT("Integer divide by zero")},
        {SIGFPE,  FPE_INTOVF,    xLEX_TO_STR(FPE_INTOVF),    xT("Integer overflow")},
        {SIGFPE,  FPE_FLTDIV,    xLEX_TO_STR(FPE_FLTDIV),    xT("Floating point divide by zero")},
        {SIGFPE,  FPE_FLTOVF,    xLEX_TO_STR(FPE_FLTOVF),    xT("Floating point overflow")},
        {SIGFPE,  FPE_FLTUND,    xLEX_TO_STR(FPE_FLTUND),    xT("Floating point underflow")},
        {SIGFPE,  FPE_FLTRES,    xLEX_TO_STR(FPE_FLTRES),    xT("Floating point inexact result")},
        {SIGFPE,  FPE_FLTINV,    xLEX_TO_STR(FPE_FLTINV),    xT("Floating point invalid operation")},
        {SIGFPE,  FPE_FLTSUB,    xLEX_TO_STR(FPE_FLTSUB),    xT("Subscript out of range")},
        // SIGSEGV
        {SIGSEGV, SEGV_MAPERR,   xLEX_TO_STR(SEGV_MAPERR),   xT("Address not mapped to object")},
        {SIGSEGV, SEGV_ACCERR,   xLEX_TO_STR(SEGV_ACCERR),   xT("Invalid permissions for mapped object")},
        // SIGBUS
        {SIGBUS,  BUS_ADRALN,    xLEX_TO_STR(BUS_ADRALN),    xT("Invalid address alignment")},
        {SIGBUS,  BUS_ADRERR,    xLEX_TO_STR(BUS_ADRERR),    xT("Non-existant physical address")},
        {SIGBUS,  BUS_OBJERR,    xLEX_TO_STR(BUS_OBJERR),    xT("Object specific hardware error")},
    #if !xENV_BSD && !xENV_APPLE
        {SIGBUS,  BUS_MCEERR_AR, xLEX_TO_STR(BUS_MCEERR_AR), xT("Hardware memory error: action required")},
        {SIGBUS,  BUS_MCEERR_AO, xLEX_TO_STR(BUS_MCEERR_AO), xT("Hardware memory error: action optional")},
    #endif
        // SIGTRAP
        {SIGTRAP, TRAP_BRKPT,    xLEX_TO_STR(TRAP_BRKPT),    xT("Process breakpoint")},
        {SIGTRAP, TRAP_TRACE,    xLEX_TO_STR(TRAP_TRACE),    xT("Process trace trap")},
        // SIGCHLD
        {SIGCHLD, CLD_EXITED,    xLEX_TO_STR(CLD_EXITED),    xT("Child has exited")},
        {SIGCHLD, CLD_KILLED,    xLEX_TO_STR(CLD_KILLED),    xT("Child was killed")},
        {SIGCHLD, CLD_DUMPED,    xLEX_TO_STR(CLD_DUMPED),    xT("Child terminated abnormally")},
        {SIGCHLD, CLD_TRAPPED,   xLEX_TO_STR(CLD_TRAPPED),   xT("Traced child has trapped")},
        {SIGCHLD, CLD_STOPPED,   xLEX_TO_STR(CLD_STOPPED),   xT("Child has stopped")},
        {SIGCHLD, CLD_CONTINUED, xLEX_TO_STR(CLD_CONTINUED), xT("Stopped child has continued")}
        // SIGPOLL
    #if !xENV_BSD && !xENV_APPLE
        ,
        {SIGPOLL, POLL_IN,       xLEX_TO_STR(POLL_IN),       xT("Data input available")},
        {SIGPOLL, POLL_OUT,      xLEX_TO_STR(POLL_OUT),      xT("Output buffers available")},
        {SIGPOLL, POLL_MSG,      xLEX_TO_STR(POLL_MSG),      xT("Input message available")},
        {SIGPOLL, POLL_ERR,      xLEX_TO_STR(POLL_ERR),      xT("I/O error")},
        {SIGPOLL, POLL_PRI,      xLEX_TO_STR(POLL_PRI),      xT("High priority input available")},
        {SIGPOLL, POLL_HUP,      xLEX_TO_STR(POLL_HUP),      xT("Device disconnected")}
    #endif
    };
    for (const auto &it_signalInfo : signalInfos) {
        xCHECK_DO(it_signalInfo.num  != a_info.si_signo, continue);
        xCHECK_DO(it_signalInfo.code != a_info.si_code,  continue);
        sRv = Format::str(xT("{}\n{} ({}) - {}\n{}"),
                decription(it_signalInfo.num),
                it_signalInfo.codeStr,
                it_signalInfo.code,
                it_signalInfo.description,
                NativeError::format( static_cast<ulong_t>(a_info.si_errno)) );
        break;
    }
    if ( !sRv.empty() ) {
        return sRv;
    }
    // _KERNEL
    for (const auto &it_signalInfo : signalInfos) {
        xCHECK_DO(it_signalInfo.num  != _KERNEL,        continue);
        xCHECK_DO(it_signalInfo.code != a_info.si_code, continue);
        sRv = Format::str(xT("{}\n{} ({}) - {}\n{}"),
                decription(it_signalInfo.num),
                it_signalInfo.codeStr,
                it_signalInfo.code,
                it_signalInfo.description,
                NativeError::format( static_cast<ulong_t>(a_info.si_errno)) );
        break;
    }
    return sRv;
}
References decription(), xl::debug::NativeError::format(), xl::core::FormatT< StreamT >::str(), xCHECK_DO, xLEX_TO_STR, and xT.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Signal.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Signal.cpp