xLib: xl::core::Duration Class Reference
xl::core::Duration Class Reference
Duration impl.
#include "Duration.h"
Inherits xl::interface_::ICompare< Duration >.
Public Member Functions
Duration plus (const Duration &value) const
Duration minus (const Duration &value) const
Overrides
int_t compare (const Duration &value) const final
Public Member Functions inherited from xl::interface_::ICompare< Duration >
ICompare ()=default
virtual ~ICompare ()=default
bool_t operator== (const Duration &a_value) const
Returns true if "value" is equal to this object.
bool_t operator!= (const Duration &a_value) const
Returns true if "value" is not equal to this object.
bool_t operator< (const Duration &a_value) const
Returns true if "value" is less than this object.
bool_t operator<= (const Duration &a_value) const
Returns true if "value" is less than or equal to this object.
bool_t operator> (const Duration &a_value) const
Returns true if "value" is greater than this object.
bool_t operator>= (const Duration &a_value) const
Returns true if "value" is greater than or equal to this object.
ctors, dtor
Duration (const int64_t totalMsecs)
virtual ~Duration ()
xNO_DEFAULT_CTOR (Duration)
xNO_COPY_ASSIGN (Duration)
int64_t totalMsecs () const
int_t days () const
int_t hours () const
int_t mins () const
int_t secs () const
int_t msecs () const
static Duration days (cint_t days)
static Duration hours (cint_t hours)
static Duration mins (cint_t mins)
static Duration secs (cint_t secs)
static Duration msecs (cint_t msecs)
Additional Inherited Members
Protected Member Functions inherited from xl::interface_::ICompare< Duration >
virtual int_t compare (const Duration &value) const=0
Compare this object to another of the same type.
Detailed Description
Duration impl.
Constructor & Destructor Documentation
Duration()
xl::core::Duration::Duration (const int64_t totalMsecs) explicit
  :
    _totalMsecs{a_totalMsecs}
{
}
~Duration()
xl::core::Duration::~Duration () virtual
{
}
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::core::Duration::xNO_DEFAULT_CTOR (Duration)
xNO_COPY_ASSIGN()
xl::core::Duration::xNO_COPY_ASSIGN (Duration)
days() [1/2]
Duration xl::core::Duration::days (cint_t days) static
{
    return Duration(static_cast<int64_t>(a_days) * 24 * 60 * 60 * 1000);
}
hours() [1/2]
Duration xl::core::Duration::hours (cint_t hours) static
{
    return Duration(static_cast<int64_t>(a_hours) * 60 * 60 * 1000);
}
mins() [1/2]
Duration xl::core::Duration::mins (cint_t mins) static
{
    return Duration(static_cast<int64_t>(a_mins) * 60 * 1000);
}
secs() [1/2]
Duration xl::core::Duration::secs (cint_t secs) static
{
    return Duration(static_cast<int64_t>(a_secs) * 1000);
}
msecs() [1/2]
Duration xl::core::Duration::msecs (cint_t msecs) static
{
    return Duration(a_msecs);
}
totalMsecs()
int64_t xl::core::Duration::totalMsecs () const
{
    return _totalMsecs;
}
Referenced by xl::core::Date::operator+(), xl::core::DateTime::operator+(), xl::core::Time::operator+(), xl::core::Date::operator-(), xl::core::DateTime::operator-(), and xl::core::Time::operator-().
days() [2/2]
int xl::core::Duration::days () const
{
    return static_cast<int>(_totalMsecs / (24LL * 60 * 60 * 1000));
}
hours() [2/2]
int xl::core::Duration::hours () const
{
    return static_cast<int>((_totalMsecs / (60LL * 60 * 1000)) % 24);
}
mins() [2/2]
int xl::core::Duration::mins () const
{
    return static_cast<int>((_totalMsecs / (60LL * 1000)) % 60);
}
secs() [2/2]
int xl::core::Duration::secs () const
{
    return static_cast<int>((_totalMsecs / 1000LL) % 60);
}
msecs() [2/2]
int xl::core::Duration::msecs () const
{
    return static_cast<int>(_totalMsecs % 1000);
}
compare()
int_t xl::core::Duration::compare (const Duration & value) const final
{
    if (_totalMsecs < a_value._totalMsecs) {
        return - 1;
    }
    if (_totalMsecs > a_value._totalMsecs) {
        return 1;
    }
    return 0;
}
plus()
Duration xl::core::Duration::plus (const Duration & value) const
{
    return Duration(_totalMsecs + a_value._totalMsecs);
}
minus()
Duration xl::core::Duration::minus (const Duration & value) const
{
    return Duration(_totalMsecs - a_value._totalMsecs);
}
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Duration.h
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Duration.cpp