xLib: xl::net::TcpServer Class Reference
xl::net::TcpServer Class Reference final
server socket
#include "TcpServer.h"
Inherits xl::net::ISocket.
Public Member Functions
void_t bind (cushort_t &port) const
associates a local address with a socket
void_t listen (cint_t &backlog=xSOCKET_LISTEN_CONNECTIONS_MAX) const
places a socket in a state in which it is listening for an incoming connection
void_t accept (TcpServer *serverSocket, std::tstring_t *fromIp) const
permits an incoming connection attempt on a socket
ctors, dtor
TcpServer ()=default
virtual ~TcpServer ()=default
xNO_COPY_ASSIGN (TcpServer)
Public Member Functions inherited from xl::net::ISocket
void_t create (cAddressFamily family, cType type, cProtocol protocol)
creates a socket that is bound to a specific transport service provider
HandleSocket & handle ()
get handle
bool_t isReadable () const
checking for readability
bool_t isWritable () const
checking for writability
void_t assign (csocket_t &handle)
assign to another handle
void_t close ()
close
std::ssize_t send (cptr_ctchar_t buff, std::csize_t &buffSize, cint_t &flags)
send data
void_t sendAll (std::ctstring_t &buff, cint_t &flags)
send data by blocks
std::ssize_t receive (tchar_t *buff, std::csize_t &buffSize, cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags, std::ctstring_t &delimiter)
receive data to delimiter, includes it
int_t sendBytes (char *buff, std::ssize_t &messageLength)
send bytes
int_t receiveBytes (char *buff, std::ssize_t &stillToReceive)
receive bytes
void_t peerName (std::tstring_t *peerAddr, ushort_t *peerPort)
get address of the peer to which a handle is connected
void_t socketName (std::tstring_t *socketAddr, ushort_t *socketPort)
get local name for a socket
ISocket ()=default
virtual ~ISocket ()=0
xNO_COPY_ASSIGN (ISocket)
Protected Attributes
timeval _timeout {}
timeout
Protected Attributes inherited from xl::net::ISocket
HandleSocket _handle
socket handle
sa_family_t _family {}
family
std::tstring_t _ip
IP.
ushort_t _port {}
port
Additional Inherited Members
Public Types inherited from xl::net::ISocket
enum class AddressFamily {
afUnix = AF_UNIX ,
afLocal = AF_LOCAL ,
afInet = AF_INET ,
afInet6 = AF_INET6 ,
afIpx = AF_IPX ,
afX25 = AF_X25 ,
afAX25 = AF_AX25 ,
afAtmpvc = AF_ATMPVC ,
afAppletalk = AF_APPLETALK ,
afPacket = AF_PACKET
}
address family
enum class Type {
tpStream = SOCK_STREAM ,
tpDgram = SOCK_DGRAM ,
tpRaw = SOCK_RAW ,
tpRdm = SOCK_RDM ,
tpSeqPacket = SOCK_SEQPACKET
}
type
enum class Protocol {
ptIp = IPPROTO_IP ,
ptHopopts = IPPROTO_HOPOPTS ,
ptIcmp = IPPROTO_ICMP ,
ptIgmp = IPPROTO_IGMP ,
ptIpip = IPPROTO_IPIP ,
ptTcp = IPPROTO_TCP ,
ptEgp = IPPROTO_EGP ,
ptPup = IPPROTO_PUP ,
ptUdp = IPPROTO_UDP ,
ptIdp = IPPROTO_IDP ,
ptIpv6 = IPPROTO_IPV6 ,
ptRouting = IPPROTO_ROUTING ,
ptFragment = IPPROTO_FRAGMENT ,
ptRsvp = IPPROTO_RSVP ,
ptGre = IPPROTO_GRE ,
ptEsp = IPPROTO_ESP ,
ptAH = IPPROTO_AH ,
ptICmpv6 = IPPROTO_ICMPV6 ,
ptNone = IPPROTO_NONE ,
ptDstopts = IPPROTO_DSTOPTS ,
ptPim = IPPROTO_PIM ,
ptComp = IPPROTO_COMP ,
ptSctp = IPPROTO_SCTP ,
ptRaw = IPPROTO_RAW ,
ptMax = IPPROTO_MAX
}
protocol
enum Options {
SOCKET_TIMEOUT = 0 ,
SOCKET_BUFF_SIZE = 32768
}
options
Static Public Member Functions inherited from xl::net::ISocket
static int_t select (int_t nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, timeval *timeout)
determines the status of one or more sockets, waiting if necessary, to perform synchronous I/O
static int_t nativeError ()
get error status for the last operation that failed
Detailed Description
server socket
Constructor & Destructor Documentation
TcpServer()
xl::net::TcpServer::TcpServer () default
~TcpServer()
virtual xl::net::TcpServer::~TcpServer () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::net::TcpServer::xNO_COPY_ASSIGN (TcpServer)
bind()
void_t xl::net::TcpServer::bind (cushort_t & port) const
associates a local address with a socket
{
    xTEST(_handle.isValid());
    xTEST_NA(a_port);
    sockaddr_in sockAddr {};
    sockAddr.sin_family      = static_cast<sa_family_t>(_family);
    sockAddr.sin_addr.s_addr = INADDR_ANY;
    sockAddr.sin_port        = htons(a_port);
    int_t iRv = ::bind(_handle.get(), Utils::reinterpretCastT<const sockaddr *>( &sockAddr ),
        sizeof(sockAddr));
    xTEST_DIFF(iRv, xSOCKET_ERROR);
#if 0
    int_t iOpt = 1;
    if (::setsockopt(_handle.get(), SOL_SOCKET, SO_REUSEADDR, (LPSTR)&iOpt, sizeof(iOpt)) < 0) {
        return false;
    }
#endif
}
References xl::net::ISocket::_family, xl::net::ISocket::_handle, bind(), xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xSOCKET_ERROR, xTEST, xTEST_DIFF, and xTEST_NA.
Referenced by bind().
listen()
void_t xl::net::TcpServer::listen (cint_t & backlog = xSOCKET_LISTEN_CONNECTIONS_MAX) const
places a socket in a state in which it is listening for an incoming connection
{
    xTEST(_handle.isValid());
    int_t iRv = ::listen(_handle.get(), a_backlog);
    xTEST_DIFF(iRv, xSOCKET_ERROR);
}
References xl::net::ISocket::_handle, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), listen(), xSOCKET_ERROR, xTEST, and xTEST_DIFF.
Referenced by listen().
accept()
void_t xl::net::TcpServer::accept (TcpServer * serverSocket, std::tstring_t * fromIp) const
permits an incoming connection attempt on a socket
{
    xTEST(_handle.isValid());
    xTEST_PTR(a_serverSocket);
    xTEST_PTR(a_fromIp);
    sockaddr_in     cliaddr {};
    socket_length_t addrlen = sizeof(cliaddr);
    socket_t client = ::accept(_handle.get(), Utils::reinterpretCastT<sockaddr *>( &cliaddr ),
        &addrlen);
    xTEST_DIFF(client, xSOCKET_HANDLE_INVALID);
#if 0
    // TODO: [skynowa] TcpServer::accept()
    scktAcceptSocket.assign(client);
#endif
    a_serverSocket->assign(client);
    std::string fromIp = ::inet_ntoa(cliaddr.sin_addr);
    *a_fromIp = xA2T(fromIp);
}
References xl::net::ISocket::_handle, accept(), xl::net::ISocket::assign(), xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xA2T, xSOCKET_HANDLE_INVALID, xTEST, xTEST_DIFF, and xTEST_PTR.
Referenced by accept().
Member Data Documentation
_timeout
timeval xl::net::TcpServer::_timeout {} protected
timeout
{};  ///< timeout
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/TcpServer.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/TcpServer.cpp