xLib: xl::core::FormatT< StreamT > Class Template Reference
xl::core::FormatT< StreamT > Class Template Reference
format string
#include "Format.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (FormatT)
xNO_COPY_ASSIGN (FormatT)
Static Public Member Functions
template<typename ... ArgsT>
static std::tstring_t str (std::ctstring_view_t fmt, const ArgsT &...args)
Detailed Description
template<typename StreamT>
class xl::core::FormatT< StreamT >
format string
Definition at line 17 of file Format.h.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
template<typename StreamT > xl::core::FormatT< StreamT >::xNO_DEFAULT_CONSTRUCT (FormatT< StreamT >)
xNO_COPY_ASSIGN()
template<typename StreamT > xl::core::FormatT< StreamT >::xNO_COPY_ASSIGN (FormatT< StreamT >)
str()
template<typename StreamT > template<typename ... ArgsT> std::tstring_t xl::core::FormatT< StreamT >::str (std::ctstring_view_t a_fmt, const ArgsT &... a_args) inline static
Parameters
a_fmt format string
a_args argument
Definition at line 29 of file Format.inl.
{
    constexpr std::size_t argsSize {sizeof...(ArgsT)};
    if constexpr (argsSize == 0) {
        return {a_fmt.cbegin(), a_fmt.cend()};
    }
    std::tstring_t sRv;
    std::size_t    specifiersFound {};
    std::size_t    posPrev {};
    // for each args
    (_format(a_fmt, a_args, sRv, specifiersFound, posPrev), ...);
    sRv += a_fmt.substr(posPrev, a_fmt.size() - posPrev);
    if (_isTest) {
        _testFmt(a_fmt, argsSize, specifiersFound);
    }
    return sRv;
}
Referenced by xl::debug::SourceInfo::at(), xl::package::Application::backupDirPath(), xl::debug::BuildInfo::cmake(), xl::debug::BuildInfo::compiler(), xl::package::Application::configDirPath(), xl::package::Application::configPath(), xl::sync::Signal::connect(), xl::sync::Signal::connectInfo(), xl::db::mysql::Db::create(), xl::debug::BuildInfo::datetime(), xl::package::Application::dbDirPath(), xl::package::Application::dbPath(), xl::sync::Signal::decription(), xl::db::mysql::Db::drop(), xl::debug::SourceInfo::expr(), xl::debug::SourceInfo::exprValues(), xl::debug::SourceInfo::format(), xl::debug::NativeError::format(), xl::net::DnsClient::hostAddrByName(), xl::package::curl::Version::info(), xl::package::curl::Client::info(), xl::sync::Signal::infoDescription(), xl::db::mysql::Db::isExists(), xl::fs::FileInfo::isExistsEx(), job(), xl::package::Application::langDirPath(), xl::debug::BuildInfo::langStandart(), xl::package::Application::logDirPath(), xl::package::Application::logPath(), xl::db::mysql::Error::message(), xl::package::xml::Error::message(), xl::system::ConsoleUI::msgBox(), xl::debug::Exception::operator<<(), xl::debug::BuildInfo::os(), xl::system::Console::pause(), xl::package::curl::Client::perform(), xl::debug::BuildInfo::qt(), xl::package::curl::SmtpClient::request(), xl::package::Translate::run(), xl::package::curl::Client::setOption(), xl::db::mysql::Db::show(), xl::debug::BuildInfo::stdLibC(), xl::debug::BuildInfo::stdLibCpp(), xl::interface_::IError< CodeT >::str(), xl::package::Application::tempDirPath(), xl::package::ApplicationInfo::versionFull(), watch(), and xl::debug::BuildInfo::xlibVersion().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Format.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Format.inl