xLib: xl::fs::FileIO Class Reference
xl::fs::FileIO Class Reference
File input/output.
#include "FileIO.h"
Public Types
enum class OpenMode {
ReadOnly ,
Write ,
Append ,
ReadWriteOnly ,
ReadWrite ,
ReadAppend ,
BinReadOnly ,
BinWrite ,
BinAppend ,
BinReadWriteOnly ,
BinReadWrite ,
BinReadAppend
}
Open mode.
enum class PointerPosition {
Error = - 1L ,
Begin = SEEK_SET ,
Curr = SEEK_CUR ,
End = SEEK_END
}
Pointer position.
enum class BufferingMode {
No = _IONBF ,
Line = _IOLBF ,
Full = _IOFBF
}
Buffering mode.
enum class LockingMode {
Lock = F_LOCK ,
TryLock = F_TEST ,
Unlock = F_ULOCK
}
Locking mode.
Public Member Functions
ctors, dtor
FileIO (std::ctstring_t &filePath)
virtual ~FileIO ()
xNO_DEFAULT_CONSTRUCT (FileIO)
xNO_COPY_ASSIGN (FileIO)
open, get
void_t open (cOpenMode mode, cbool_t isBuffering=true)
open
HandleStdFile & get ()
get handle
int_t getNative () const
get native file descriptor associated with a stream
std::tstring_t path () const
get file path
read, write
void_t setVBuff (cBufferingMode mode, char *buff, std::csize_t size) const
change stream buffering
size_t read (void_t *buff, std::csize_t count) const
read block of data
size_t write (cptr_cvoid_t, std::csize_t count) const
write block of data
void_t read (std::ustring_t *buff) const
read to std::ustring_t
void_t write (std::custring_t &buff) const
write from std::ustring_t
void_t read (std::tstring_t *buff) const
read to std::tstring_t
int_t scanf (cptr_ctchar_t format,...) const
read formatted variables (as vfscanf)
int_t write (cptr_ctchar_t format,...) const
write formatted output to stream
int_t writeV (cptr_ctchar_t format, va_list arg) const
write formatted variable argument list to stream
void_t readLine (std::tstring_t *str, std::csize_t maxCount) const
read string to newline or to the end of file
void_t writeLine (std::ctstring_t &str) const
write string and end of line
tchar_t readChar () const
get character
void_t writeChar (ctchar_t ch) const
write character
void_t ungetChar (ctchar_t ch) const
unget character from stream
void_t clear () const
clear content
other
void_t locking (cLockingMode mode, clong_t bytes)
locks or unlocks bytes of a file
void_t setPosition (clong_t offset, cPointerPosition pos) const
set stream position indicator
long_t position () const
get current position in stream
longlong_t size () const
get file size
bool_t isEmpty () const
is empty
void_t setSize (clonglong_t bytes) const
changes the file size
error handling
bool_t isEof () const
check end of file indicator
bool_t isError () const
check error indicator
void_t clearError () const
clear error indicators
closing
void_t flush () const
flush
void_t close ()
close
Detailed Description
File input/output.
Member Enumeration Documentation
OpenMode
enum class xl::fs::FileIO::OpenMode strong
Open mode.
Enumerator
ReadOnly
"r" (no file - error)
Write
"w" (no file - create)
Append
"a" (no file - create)
ReadWriteOnly
"r+" (no file - error)
ReadWrite
"w+" (no file - create)
ReadAppend
"a+" (no file - create)
BinReadOnly
"rb" (no file - error)
BinWrite
"wb" (no file - create)
BinAppend
"ab" (no file - create)
BinReadWriteOnly
"rb+" (no file - error)
BinReadWrite
"wb+" (no file - create)
BinReadAppend
"ab+" (no file - create)
    {
        // Text
        ReadOnly,         ///< "r" (no file - error)
        Write,            ///< "w" (no file - create)
        Append,           ///< "a" (no file - create)
        ReadWriteOnly,    ///< "r+" (no file - error)
        ReadWrite,        ///< "w+" (no file - create)
        ReadAppend,       ///< "a+" (no file - create)
        // Binary
        BinReadOnly,      ///< "rb" (no file - error)
        BinWrite,         ///< "wb" (no file - create)
        BinAppend,        ///< "ab" (no file - create)
        BinReadWriteOnly, ///< "rb+" (no file - error)
        BinReadWrite,     ///< "wb+" (no file - create)
        BinReadAppend     ///< "ab+" (no file - create)
    };
PointerPosition
enum class xl::fs::FileIO::PointerPosition strong
Pointer position.
Enumerator
Error
Begin
Curr
End
    {
        Error = - 1L,
        Begin = SEEK_SET,
        Curr  = SEEK_CUR,
        End   = SEEK_END
    };
BufferingMode
enum class xl::fs::FileIO::BufferingMode strong
Buffering mode.
Enumerator
No
Line
Full
    {
        No   = _IONBF,
        Line = _IOLBF,
        Full = _IOFBF
    };
LockingMode
enum class xl::fs::FileIO::LockingMode strong
Locking mode.
Enumerator
Lock
TryLock
Unlock
    {
    #if   xENV_WIN
        Lock    = LK_NBLCK,
        TryLock = LK_LOCK,
        Unlock  = LK_UNLCK
    #elif xENV_UNIX
        Lock    = F_LOCK,
        TryLock = F_TEST,
        Unlock  = F_ULOCK
    #endif
    };
Constructor & Destructor Documentation
FileIO()
xl::fs::FileIO::FileIO (std::ctstring_t & filePath) explicit
  :
    _filePath(a_filePath)
{
}
~FileIO()
xl::fs::FileIO::~FileIO () virtual
{
    close();
}
References close().
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::FileIO::xNO_DEFAULT_CONSTRUCT (FileIO)
xNO_COPY_ASSIGN()
xl::fs::FileIO::xNO_COPY_ASSIGN (FileIO)
open()
void_t xl::fs::FileIO::open (cOpenMode mode, cbool_t isBuffering = true)
open
{
    xTEST(!_filePath.empty());
    xTEST_NA(a_mode);
    xTEST_NA(a_isBuffering);
    // create dir
    Dir( Path(_filePath).dir() ).pathCreate();
    // create, open file
    {
        std::FILE *file = xTFOPEN(_filePath.c_str(), _openMode(a_mode).c_str());
        xTEST_PTR(file);
        _handle = file;
    }
    // buffering
    _setVBuffDefault(a_isBuffering);
}
References xl::fs::Dir::pathCreate(), xTEST, xTEST_NA, and xTEST_PTR.
Referenced by xl::fs::File::clear(), xl::log::FileLog::clear(), xl::fs::File::copy(), xl::fs::FsWatcher::openFiles(), xl::fs::FileText::read(), xl::fs::FileBin::read(), xl::fs::FileInfo::size(), xl::fs::File::wipe(), xl::log::FileLog::write(), xl::fs::FileText::write(), xl::fs::FileText::write(), and xl::fs::FileBin::write().
get()
HandleStdFile & xl::fs::FileIO::get ()
get handle
{
    return _handle;
}
Referenced by xl::fs::FsWatcher::openFiles(), and xl::fs::File::wipe().
getNative()
int_t xl::fs::FileIO::getNative () const
get native file descriptor associated with a stream
{
    xTEST(_handle.isValid());
    return _nativeHandle( _handle.get() );
}
References xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), and xTEST.
Referenced by xl::fs::FsWatcher::openFiles().
path()
std::tstring_t xl::fs::FileIO::path () const
get file path
{
    xTEST(!_filePath.empty());
    xTEST(FileInfo(_filePath).isExists());
    return _filePath;
}
References xTEST.
setVBuff()
void_t xl::fs::FileIO::setVBuff (cBufferingMode mode, char * buff, std::csize_t size) const
change stream buffering
{
    xTEST_NA(a_mode);
    xTEST_NA(a_buff);
    xTEST_NA(a_size);
    int_t iRv = std::setvbuf(_handle.get(), a_buff, static_cast<int>(a_mode), a_size);
    xTEST_DIFF(iRv, - 1);
}
References xl::core::Handle< T, typeT >::get(), xTEST_DIFF, and xTEST_NA.
read() [1/3]
size_t xl::fs::FileIO::read (void_t * buff, std::csize_t count) const
read block of data
{
    xTEST_PTR(a_buff);
    xTEST_NA(a_count);
    size_t uiRv = std::fread(a_buff, 1, a_count, _handle.get());
    xTEST_GR_EQ(a_count, uiRv);
    return uiRv;
}
References xl::core::Handle< T, typeT >::get(), xTEST_GR_EQ, xTEST_NA, and xTEST_PTR.
Referenced by xl::fs::File::copy(), xl::fs::FileText::read(), and xl::fs::FileBin::read().
write() [1/3]
size_t xl::fs::FileIO::write (cptr_cvoid_t a_buff, std::csize_t count) const
write block of data
{
    xTEST_PTR(a_buff);
    xTEST_NA(a_count);
    size_t uiRv = std::fwrite(a_buff, 1, a_count, _handle.get());
    xTEST_EQ(uiRv, a_count);
    return uiRv;
}
References xl::core::Handle< T, typeT >::get(), xTEST_EQ, xTEST_NA, and xTEST_PTR.
Referenced by xl::fs::File::copy(), xl::log::FileLog::write(), xl::fs::FileText::write(), and xl::fs::FileBin::write().
read() [2/3]
void_t xl::fs::FileIO::read (std::ustring_t * buff) const
read to std::ustring_t
{
    xTEST_PTR(a_buff);
    clonglong_t fileSize = size();
    xTEST_DIFF(fileSize, static_cast<longlong_t>(PointerPosition::Error));
    a_buff->clear();
    a_buff->resize( static_cast<size_t>(fileSize) );
    xCHECK_DO(fileSize == 0LL, return);
    size_t uiRv = std::fread(&a_buff->at(0), 1, a_buff->size() *
        sizeof(std::ustring_t::value_type), _handle.get());
    xTEST_EQ(uiRv, a_buff->size());
}
References Error, xl::core::Handle< T, typeT >::get(), size(), xCHECK_DO, xTEST_DIFF, xTEST_EQ, and xTEST_PTR.
write() [2/3]
void_t xl::fs::FileIO::write (std::custring_t & buff) const
write from std::ustring_t
{
    xTEST_NA(a_buff);
    size_t uiRv = std::fwrite(&a_buff.at(0), 1, a_buff.size() *
        sizeof(std::ustring_t::value_type), _handle.get());
    xTEST_EQ(uiRv, a_buff.size());
}
References xl::core::Handle< T, typeT >::get(), xTEST_EQ, and xTEST_NA.
read() [3/3]
void_t xl::fs::FileIO::read (std::tstring_t * buff) const
read to std::tstring_t
scanf()
int_t xl::fs::FileIO::scanf (cptr_ctchar_t a_format, ...) const
read formatted variables (as vfscanf)
Parameters
a_format string format
[out] ... arguments
{
    int_t iRv {};
    va_list args;
    xVA_START(args, a_format);
    iRv = xTVFSCANF(_handle.get(), a_format, args);
    xTEST_GR(iRv, - 1);
    xVA_END(args);
    return iRv;
}
References xl::core::Handle< T, typeT >::get(), and xTEST_GR.
write() [3/3]
int_t xl::fs::FileIO::write (cptr_ctchar_t format, ...) const
write formatted output to stream
{
    xTEST_PTR(a_format);
    va_list args;
    xVA_START(args, a_format);
    int_t iRv = xTVFPRINTF(_handle.get(), a_format, args);
    xTEST_GR(iRv, - 1);
    xVA_END(args);
    return iRv;
}
References xl::core::Handle< T, typeT >::get(), xTEST_GR, and xTEST_PTR.
writeV()
int_t xl::fs::FileIO::writeV (cptr_ctchar_t format, va_list arg) const
write formatted variable argument list to stream
{
    xTEST_PTR(a_format);
    xTEST_NA(a_args);
    int_t iRv = xTVFPRINTF(_handle.get(), a_format, a_args);
    xTEST_GR(iRv, - 1);
    return iRv;
}
References xl::core::Handle< T, typeT >::get(), xTEST_GR, xTEST_NA, and xTEST_PTR.
readLine()
void_t xl::fs::FileIO::readLine (std::tstring_t * str, std::csize_t maxCount) const
read string to newline or to the end of file
{
    xTEST_PTR(a_str);
    xTEST_NA(a_maxCount);
    std::tstring_t str;
    str.resize(a_maxCount + 1); // + 1 for 0
    tchar_t *pszRv = xTFGETS(&str.at(0), static_cast<int_t>( str.size() ), _handle.get());
    xTEST_PTR(pszRv);
    // trim nullptr's from string, remove EOL
    str = String::removeEol( str.c_str() );
    // [out]
    a_str->swap(str);
}
References xl::core::Handle< T, typeT >::get(), xl::core::String::removeEol(), xTEST_NA, and xTEST_PTR.
writeLine()
void_t xl::fs::FileIO::writeLine (std::ctstring_t & str) const
write string and end of line
{
    xTEST_NA(a_str);
    int_t iRv = xTFPUTS((a_str + Const::eol()).c_str(), _handle.get());
    xTEST_DIFF(iRv, - 1);
}
References xl::core::Const::eol(), xl::core::Handle< T, typeT >::get(), xTEST_DIFF, and xTEST_NA.
Referenced by xl::fs::FileText::write().
readChar()
tchar_t xl::fs::FileIO::readChar () const
get character
{
    twint_t iRv = xTFGETC(_handle.get());
    xTEST_DIFF(iRv, xTEOF);
    return static_cast<tchar_t>(iRv);
}
References xl::core::Handle< T, typeT >::get(), and xTEST_DIFF.
writeChar()
void_t xl::fs::FileIO::writeChar (ctchar_t ch) const
write character
{
    xTEST_NA(a_ch);
    twint_t iRv = xTFPUTC(a_ch, _handle.get());
    xTEST_DIFF(iRv, xTEOF);
    xTEST_EQ(static_cast<tchar_t>(iRv), a_ch);
}
References xl::core::Handle< T, typeT >::get(), xTEST_DIFF, xTEST_EQ, and xTEST_NA.
ungetChar()
void_t xl::fs::FileIO::ungetChar (ctchar_t ch) const
unget character from stream
{
    xTEST_NA(a_ch);
    twint_t iRv = xTUNGETC(a_ch, _handle.get());
    xTEST_DIFF(iRv, xTEOF);
    xTEST_EQ(static_cast<tchar_t>(iRv), a_ch);
}
References xl::core::Handle< T, typeT >::get(), xTEST_DIFF, xTEST_EQ, and xTEST_NA.
clear()
void_t xl::fs::FileIO::clear () const
clear content
{
    setSize(0L);
}
References setSize().
Referenced by xl::fs::File::clear(), xl::log::FileLog::clear(), and xl::fs::File::wipe().
locking()
void_t xl::fs::FileIO::locking (cLockingMode mode, clong_t bytes)
locks or unlocks bytes of a file
{
    xTEST_NA(a_mode);
    xTEST_NA(a_bytes);
#if   xENV_WIN
    clong_t    bytes = a_bytes;
#elif xENV_UNIX
    const auto bytes = static_cast<off_t>(a_bytes);
#endif
    int_t iRv = xLOCKING(_nativeHandle(_handle.get()), static_cast<int>(a_mode), bytes);
    xTEST_DIFF(iRv, - 1);
}
References xl::core::Handle< T, typeT >::get(), xLOCKING, xTEST_DIFF, and xTEST_NA.
setPosition()
void_t xl::fs::FileIO::setPosition (clong_t offset, cPointerPosition pos) const
set stream position indicator
{
    xTEST_NA(a_offset);
    xTEST_NA(a_pos);
    int_t iRv = std::fseek(_handle.get(), a_offset, static_cast<int>(a_pos));
    xTEST_DIFF(iRv, - 1);
}
References xl::core::Handle< T, typeT >::get(), xTEST_DIFF, and xTEST_NA.
Referenced by size(), and xl::fs::File::wipe().
position()
long_t xl::fs::FileIO::position () const
get current position in stream
{
    long_t liRv = std::ftell(_handle.get());
    xTEST_DIFF(liRv, - 1L);
    return liRv;
}
References xl::core::Handle< T, typeT >::get(), and xTEST_DIFF.
Referenced by size().
size()
longlong_t xl::fs::FileIO::size () const
get file size
{
    clong_t currStreamPos = position();
    setPosition(0, PointerPosition::End);
    clong_t streamSize = position();
    setPosition(currStreamPos, PointerPosition::Begin);
    return static_cast<longlong_t>( streamSize );
}
References Begin, End, position(), and setPosition().
Referenced by isEmpty(), xl::fs::FileText::read(), read(), xl::fs::FileBin::read(), setSize(), xl::fs::FileInfo::size(), and xl::fs::File::wipe().
isEmpty()
bool_t xl::fs::FileIO::isEmpty () const
is empty
{
    clonglong_t fileSize = size();
    xTEST_DIFF(fileSize, - 1LL);
    return (fileSize == 0LL);
}
References size(), and xTEST_DIFF.
setSize()
void_t xl::fs::FileIO::setSize (clonglong_t bytes) const
changes the file size
{
    xTEST_NA(a_bytes);
#if   xENV_WIN
    clonglong_t _bytes = a_bytes;
#elif xENV_UNIX
    const auto  _bytes = static_cast<off_t>(a_bytes);
#endif
    int_t iRv = xCHSIZE(_nativeHandle( _handle.get() ), _bytes);
    xTEST_EQ(iRv, 0);
    xTEST_EQ(size(), a_bytes);
}
References xl::core::Handle< T, typeT >::get(), size(), xCHSIZE, xTEST_EQ, and xTEST_NA.
Referenced by clear().
isEof()
bool_t xl::fs::FileIO::isEof () const
check end of file indicator
{
    return static_cast<bool_t>( std::feof(_handle.get()) );
}
References xl::core::Handle< T, typeT >::get().
Referenced by xl::fs::File::copy().
isError()
bool_t xl::fs::FileIO::isError () const
check error indicator
{
    return static_cast<bool_t>( std::ferror(_handle.get()) );
}
References xl::core::Handle< T, typeT >::get().
clearError()
void_t xl::fs::FileIO::clearError () const
clear error indicators
{
    (void_t)std::clearerr( _handle.get() );
}
References xl::core::Handle< T, typeT >::get().
Referenced by close().
flush()
void_t xl::fs::FileIO::flush () const
flush
{
    twint_t iRv = std::fflush( _handle.get() );
    xTEST_DIFF(iRv, xTEOF);
}
References xl::core::Handle< T, typeT >::get(), and xTEST_DIFF.
Referenced by xl::fs::File::wipe().
close()
void_t xl::fs::FileIO::close ()
close
{
    xCHECK_DO(!_handle.isValid(), return);
    clearError();
    _handle.close();
}
References clearError(), xl::core::Handle< T, typeT >::close(), xl::core::Handle< T, typeT >::isValid(), and xCHECK_DO.
Referenced by ~FileIO().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileIO.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileIO.cpp