xLib: xl::sync::ThreadCurrent Class Reference
xl::sync::ThreadCurrent Class Reference
Current thread.
#include "ThreadCurrent.h"
Static Public Member Functions
static bool_t isCurrent (Thread::cid_t id)
is current id
static Thread::id_t id ()
get the thread identifier of the calling thread
static Thread::handle_t handle ()
get pseudo handle for the calling thread
static void_t yield ()
yield
static void_t sleep (culong_t timeoutMsec)
sleep
Detailed Description
Current thread.
Member Function Documentation
isCurrent()
bool_t xl::sync::ThreadCurrent::isCurrent (Thread::cid_t id) static
is current id
{
    return _isCurrent_impl(a_id);
}
Referenced by xl::sync::Thread::create(), and xl::sync::Thread::isCurrent().
id()
Thread::id_t xl::sync::ThreadCurrent::id () static
get the thread identifier of the calling thread
{
    return _id_impl();
}
Referenced by xl::debug::ErrorReport::ErrorReport(), and xl::sync::Thread::isCurrent().
handle()
Thread::handle_t xl::sync::ThreadCurrent::handle () static
get pseudo handle for the calling thread
{
    return _handle_impl();
}
yield()
void_t xl::sync::ThreadCurrent::yield () static
yield
{
    _yield_impl();
}
sleep()
void_t xl::sync::ThreadCurrent::sleep (culong_t timeoutMsec) static
sleep
{
    xCHECK_DO(a_timeoutMsec == 0UL, return);
    _sleep_impl(a_timeoutMsec);
}
References xCHECK_DO.
Referenced by xl::sync::ThreadPool< TaskT >::onRun(), xl::system::Console::pause(), xl::fs::Dir::tryRemove(), xl::fs::File::tryRemove(), and xl::fs::FsWatcher::watch().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Sync/ThreadCurrent.h
/home/runner/work/xLib/xLib/Include/xLib/Sync/ThreadCurrent.cpp