xLib: xl::system::Environments Class Reference
xl::system::Environments Class Reference
system environment variables
#include "Environment.h"
Public Member Functions
void_t setVars (const std::set< std::pair_tstring_t > &vars) const
set or change values
std::vec_tstring_t vars () const
get all values
std::tstring_t findFirstOf (std::cvec_tstring_t &names) const
get first value by names
ctors, dtor
Environments ()=default
virtual ~Environments ()=default
xNO_COPY_ASSIGN (Environments)
Static Public Member Functions
static std::tstring_t expandVars (std::ctstring_t &strWithVars)
expands strings by separator "%"
Detailed Description
system environment variables
Definition at line 69 of file Environment.h.
Constructor & Destructor Documentation
Environments()
xl::system::Environments::Environments () default
~Environments()
virtual xl::system::Environments::~Environments () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::Environments::xNO_COPY_ASSIGN (Environments)
setVars()
void_t xl::system::Environments::setVars (const std::set< std::pair_tstring_t > & a_vars) const
set or change values
Parameters
a_vars vars ({"HOME=/usr/home","LOGNAME=home"})
Definition at line 171 of file Environment.cpp.
{
    for (const auto &[it_name, it_value] : a_vars) {
        Environment env(it_name);
        env.setValue(it_value);
    }
}
References xl::system::Environment::setValue().
vars()
std::vec_tstring_t xl::system::Environments::vars () const
get all values
Definition at line 182 of file Environment.cpp.
{
    return std::move( _vars_impl() );
}
findFirstOf()
std::tstring_t xl::system::Environments::findFirstOf (std::cvec_tstring_t & a_names) const
get first value by names
Parameters
a_names var names
Definition at line 188 of file Environment.cpp.
{
    xCHECK_RET(a_names.empty(), std::tstring_t{});
    for (const auto &it_name : a_names) {
        Environment env(it_name);
        bool_t bRv = env.isExists();
        xCHECK_DO(!bRv, continue);
        return env.value();
    }
    return {};
}
References xl::system::Environment::isExists(), xl::system::Environment::value(), xCHECK_DO, and xCHECK_RET.
Referenced by xl::system::User::name().
expandVars()
std::tstring_t xl::system::Environments::expandVars (std::ctstring_t & strWithVars) static
expands strings by separator "%"
Definition at line 207 of file Environment.cpp.
{
    // Win: Same as ::ExpandEnvironmentStrings()
    std::tstring_t sRv = a_strWithVars;
    // TODO: [unix] "$" as separator: $VAR, ${VAR}
    std::ctstring_t sep = xT("%");
    for ( ; ; ) {
        // find from left two first chars '%'
        std::csize_t startSepPos = sRv.find(sep);
        xCHECK_DO(startSepPos == std::tstring_t::npos, break);
        std::csize_t stopSepPos = sRv.find(sep, startSepPos + sep.size());
        xCHECK_DO(stopSepPos == std::tstring_t::npos, break);
        // copy %var% to temp string
        std::ctstring_t &rawEnvName = String::cut(sRv, startSepPos, stopSepPos + sep.size());
        xTEST(!rawEnvName.empty());
        std::ctstring_t &envName = String::trimChars(rawEnvName, sep);
        // expand var to temp string
        std::ctstring_t &expandedEnvValue = Environment(envName).value();
        // replace envVar(%var%) by expandedEnvVar
        sRv.replace(startSepPos, rawEnvName.size(), expandedEnvValue);
    }
    return sRv;
}
References xl::core::String::cut(), xl::core::String::trimChars(), xl::system::Environment::value(), xCHECK_DO, xT, and xTEST.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Environment.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Environment.cpp