xLib: xl::db::mysql::Connection Class Reference
xl::db::mysql::Connection Class Reference
MySql connection.
#include "Connection.h"
Public Member Functions
cHandleMySqlConn & get () const
get handle
ctors, dtor
Connection (const Options &options)
Read options from Options struct.
Connection (std::ctstring_t &optionsFile)
Read options from the named option file instead of from my.cnf.
xNO_DEFAULT_CONSTRUCT (Connection)
xNO_COPY_ASSIGN (Connection)
Commit
void_t setAutoCommit (cbool_t flag) const
void_t commit ()
commits the current transaction
void_t rollback ()
rolls back the current transaction
Query query (std::ctstring_t &sql) const
get Query object
Connection
void_t connect () const
attempts to establish a connection to a MySql database engine running on host
void_t reconnect ()
reconnect to DB
bool_t ping () const
checks whether the connection to the server is working
void_t selectDb (std::ctstring_t &dbName) const
Causes the DB specified by dbName to become the default (current) DB on the connection.
void_t close ()
closes a previously opened connection
void_t kill (culong_t pid)
Asks the server to kill the thread specified by pid.
Detailed Description
MySql connection.
Definition at line 17 of file Connection.h.
Constructor & Destructor Documentation
Connection() [1/2]
xl::db::mysql::Connection::Connection (const Options & options) explicit
Read options from Options struct.
Definition at line 21 of file Connection.cpp.
  :
    _options{a_options}
{
    xTEST_NA(a_options);
    _init();
}
Connection() [2/2]
xl::db::mysql::Connection::Connection (std::ctstring_t & optionsFile) explicit
Read options from the named option file instead of from my.cnf.
Definition at line 31 of file Connection.cpp.
  :
    _optionsFile{a_optionsFile}
{
    xTEST(FileInfo(a_optionsFile).isExists());
    _init();
}
Member Function Documentation
close()
void_t xl::db::mysql::Connection::close ()
closes a previously opened connection
Definition at line 93 of file Connection.cpp.
{
    xTEST_NA(_conn);
    _conn.close();
}
References xl::core::Handle< T, typeT >::close().
Referenced by reconnect().
commit()
void_t xl::db::mysql::Connection::commit ()
commits the current transaction
Definition at line 112 of file Connection.cpp.
{
    bool_t bRv = ::mysql_commit(_conn.get());
    xTEST_MSG(bRv, Error(*this).str());
}
References xl::core::Handle< T, typeT >::get(), and xl::interface_::IError< CodeT >::str().
connect()
void_t xl::db::mysql::Connection::connect () const
attempts to establish a connection to a MySql database engine running on host
Definition at line 57 of file Connection.cpp.
{
    if ( !_optionsFile.empty() ) {
        _connectByOptionsFile();
    } else {
        _connectByOptions();
    }
}
Referenced by xl::db::mysql::Db::create(), xl::db::mysql::Db::drop(), xl::db::mysql::Db::isExists(), reconnect(), and xl::db::mysql::Db::show().
get()
cHandleMySqlConn & xl::db::mysql::Connection::get () const
get handle
Definition at line 42 of file Connection.cpp.
{
    return _conn;
}
Referenced by xl::db::mysql::EscapeQuoted::EscapeQuoted(), xl::db::mysql::IResult::fields(), xl::db::mysql::EscapeQuoted::forQuote(), xl::db::mysql::IResult::IResult(), xl::db::mysql::IResult::rows(), xl::db::mysql::StoreResult::StoreResult(), and xl::db::mysql::UseResult::UseResult().
kill()
void_t xl::db::mysql::Connection::kill (culong_t pid)
Asks the server to kill the thread specified by pid.
Definition at line 101 of file Connection.cpp.
{
    xTEST_GR(a_pid, 0UL);
    int_t iRv = ::mysql_kill(_conn.get(), a_pid);
    xTEST_EQ_MSG(iRv, 0, Error(*this).str());
}
References xl::core::Handle< T, typeT >::get(), and xl::interface_::IError< CodeT >::str().
ping()
bool_t xl::db::mysql::Connection::ping () const
checks whether the connection to the server is working
Definition at line 75 of file Connection.cpp.
{
    int_t iRv = ::mysql_ping( _conn.get() );
    xTEST_EQ(iRv, 0);
    return (iRv == 0);
}
References xl::core::Handle< T, typeT >::get().
query()
Query xl::db::mysql::Connection::query (std::ctstring_t & sql) const
get Query object
Definition at line 126 of file Connection.cpp.
{
    return Query(*this, a_sql);
}
Referenced by xl::db::mysql::Db::create(), xl::db::mysql::Db::drop(), xl::db::mysql::Db::isExists(), and xl::db::mysql::Db::show().
reconnect()
void_t xl::db::mysql::Connection::reconnect ()
reconnect to DB
Definition at line 67 of file Connection.cpp.
{
    close();
    _init();
    connect();
}
References close(), and connect().
rollback()
void_t xl::db::mysql::Connection::rollback ()
rolls back the current transaction
Definition at line 119 of file Connection.cpp.
{
    bool_t bRv = ::mysql_rollback(_conn.get());
    xTEST_MSG(bRv, Error(*this).str());
}
References xl::core::Handle< T, typeT >::get(), and xl::interface_::IError< CodeT >::str().
selectDb()
void_t xl::db::mysql::Connection::selectDb (std::ctstring_t & a_dbName) const
Causes the DB specified by dbName to become the default (current) DB on the connection.
Parameters
a_dbName DB name
Definition at line 84 of file Connection.cpp.
{
    int_t iRv = ::mysql_select_db(_conn.get(), xT2A(a_dbName).c_str());
    xTEST_EQ_MSG(iRv, 0, Error(*this).str());
}
References xl::core::Handle< T, typeT >::get(), xl::interface_::IError< CodeT >::str(), and xT2A.
setAutoCommit()
void_t xl::db::mysql::Connection::setAutoCommit (cbool_t flag) const
sets autocommit mode on
Note
: Must be called AFTER connect()
Definition at line 48 of file Connection.cpp.
{
    bool_t bRv = ::mysql_autocommit(_conn.get(), a_flag);
    xTEST_MSG(bRv, Error(*this).str());
}
References xl::core::Handle< T, typeT >::get(), and xl::interface_::IError< CodeT >::str().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Connection.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Connection.cpp