xLib: /home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Functions.cpp File Reference
Functions.cpp File Reference
function macroses
#include "Functions.h"
#include <xLib/Core/Core.h>
#include "Platform/Unix/Functions_unix.inl"
Functions
std::string xl::demangleName (const char *nameRaw)
Demangling names.
Detailed Description
function macroses
Definition in file Functions.cpp.
Function Documentation
demangleName()
std::string xl::demangleName (const char * a_nameRaw)
Demangling names.
Definition at line 53 of file Functions.cpp.
{
    if (a_nameRaw == nullptr) {
        return {};
    }
    std::string sRv;
#if   xCOMPILER_MS
    constexpr DWORD buffSize {1024};
    char            buff[buffSize + 1] {};
    const     DWORD flags {UNDNAME_COMPLETE}; // Enable full undecoration
    DWORD dwRv = ::UnDecorateSymbolName(a_nameRaw, buff, buffSize, flags);
    sRv = (dwRv != 0UL) ? a_nameRaw : buff;
#elif xCOMPILER_MINGW || xCOMPILER_GNUC
    int status {- 1};
    char *buff = abi::__cxa_demangle(a_nameRaw, nullptr, nullptr, &status);
    sRv = (buff == nullptr || status != 0) ? a_nameRaw : buff;
    if (buff != nullptr) {
        std::free(buff); buff = nullptr;
    }
#else
    sRv = a_nameRaw;
#endif
    return sRv;
}
References xl::demangleName().
Referenced by xl::demangleName(), and xl::core::Type< T >::nameDemangle().