xLib: xl::package::curl::Version Class Reference
xl::package::curl::Version Class Reference
Client version.
#include "Version.h"
Public Member Functions
CURLversion version () const
std::tstring_t info () const
void_t protocols (std::vec_tstring_t *values) const
ctors, dtor
Version ()=default
~Version ()=default
xNO_COPY_ASSIGN (Version)
Detailed Description
Client version.
Constructor & Destructor Documentation
Version()
xl::package::curl::Version::Version () default
~Version()
xl::package::curl::Version::~Version () default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::package::curl::Version::xNO_COPY_ASSIGN (Version)
version()
CURLversion xl::package::curl::Version::version () const
{
    return _version;
}
Referenced by info(), and protocols().
info()
std::tstring_t xl::package::curl::Version::info () const
{
    std::tstring_t sRv;
    curl_version_info_data *infoData = ::curl_version_info( version() );
    xTEST_PTR(infoData);
    sRv = Format::str(
        xT("age: {}\n"
        "version: {}\n"
        "version_num: {}\n"
        "host: {}\n"
        "features: {}\n"
        "ssl_version: {}\n"
        "ssl_version_num: {}\n"
        "libz_version: {}\n"
        "protocols: {}\n"
        "ares: {}\n"
        "ares_num: {}\n"
        "libidn: {}\n"
        "iconv_ver_num: {}\n"
        "libssh_version: {}"),
        infoData->age,
        infoData->version,
        infoData->version_num,
        infoData->host,
        infoData->features,
        infoData->ssl_version,
        infoData->ssl_version_num,
        infoData->libz_version,
        infoData->protocols,
        infoData->ares,
        infoData->ares_num,
        infoData->libidn,
        infoData->iconv_ver_num,
        infoData->libssh_version);
    return sRv;
}
References xl::core::FormatT< StreamT >::str(), version(), xT, and xTEST_PTR.
protocols()
void_t xl::package::curl::Version::protocols (std::vec_tstring_t * a_values) const
Parameters
[out] a_values
{
    xTEST_PTR(a_values);
    a_values->clear();
    curl_version_info_data *infoData = ::curl_version_info( version() );
    xTEST_PTR(infoData);
    const char *const *const prot = infoData->protocols;
    xTEST_PTR(prot);
    for (std::size_t i = 0; *(prot + i) != nullptr; ++ i) {
        a_values->push_back(*(prot + i));
    }
}
References version(), and xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Version.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Version.cpp