xLib: xl::core::String Class Reference
xl::core::String Class Reference
strings utils
#include "String.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (String)
xNO_COPY_ASSIGN (String)
Static Public Member Functions
template<typename T >
static T castTo (std::ctstring_t &value)
cast to bools, chars, ints, doubles, enums
template<typename T >
static std::tstring_t cast (const T &value)
convert type to std::tstring_t
template<typename T >
static std::tstring_t cast (const T &value, cint_t base)
convert type to std::tstring_t by base (8, 10, 16)
template<typename T >
static T cast (std::ctstring_t &str)
convert std::tstring_t to type
template<typename T >
static T cast (std::ctstring_t &str, cint_t base)
convert std::tstring_t by base (8, 10, 16) to type
static std::string castA (std::cwstring_t &str)
std::wstring in std::string
static std::wstring castW (std::cstring_t &str)
std::string in std::wstring
static std::string castA (std::cwstring_t &str, cuint_t codePage)
std::wstring in std::string
static std::wstring castW (std::cstring_t &str, cuint_t codePage)
std::string in std::wstring
static std::string castA (std::cwstring_t &str, const std::locale &locale)
std::wstring in std::string
static std::wstring castW (std::cstring_t &str, const std::locale &locale)
std::string in std::wstring
static std::string castCodePage (std::cstring_t &str, cuint_t codePageSource, cuint_t codePageDest)
convert codepage
static std::string castToOem (std::ctstring_t &str)
convert char to oem
static std::tstring_t castFromOem (std::cstring_t &str)
convert oem to char
static std::tstring_t castBool (cbool_t value)
bool_t to std::tstring_t
static bool_t castBool (std::ctstring_t &str)
convert std::tstring_t to bool_t
static std::tstring_t toLowerCase (std::ctstring_t &str)
convert to low case
static std::tstring_t toUpperCase (std::ctstring_t &str)
convert to uppercase
static std::tstring_t toLowerCase (std::ctstring_t &str, std::csize_t length)
convert to low case
static std::tstring_t toUpperCase (std::ctstring_t &str, std::csize_t length)
convert to uppercase
static std::tstring_t trimLeftChars (std::ctstring_t &str, std::ctstring_t &chars)
trim left chars
static std::tstring_t trimRightChars (std::ctstring_t &str, std::ctstring_t &chars)
trim left chars
static std::tstring_t trimChars (std::ctstring_t &str, std::ctstring_t &chars)
trim left, right chars
static std::tstring_t trimSpace (std::ctstring_t &str)
trim left, right spaces
static std::tstring_t removeEol (std::ctstring_t &str)
remove end of line from end of string
static std::tstring_t quoted (std::ctstring_t &str, ctchar_t delimiter=xT('\"'), ctchar_t escape = xT('\\'))
quote string
static std::tstring_t replaceAll (std::ctstring_t &str, std::ctstring_t &strOld, std::ctstring_t &strNew)
replace all strings
static std::tstring_t replaceAll (std::ctstring_t &str, ctchar_t &charOld, ctchar_t &charNew)
replace all chars
static std::tstring_t removeAll (std::ctstring_t &str, std::ctstring_t &removeStr)
remove all strings
static void_t split (std::ctstring_t &str, std::ctstring_t &sep, std::vec_tstring_t *rv)
split by separator
template<typename T >
static void_t split (std::ctstring_t &str, std::ctstring_t &sepLine, std::ctstring_t &sepKeyValue, T *map)
split by separator
static std::tstring_t join (std::cvec_tstring_t &vec, ctchar_t &sep)
join with char separator
static std::tstring_t join (std::cvec_tstring_t &vec, std::ctstring_t &sep)
join with string separator
template<typename T >
static std::tstring_t join (const T &map, std::ctstring_t &sepLine, std::ctstring_t &sepKeyValue)
join with string separator
static std::tstring_t cut (std::ctstring_t &str, std::ctstring_t &sepLeft, std::ctstring_t &sepRight)
cut using strings
static std::tstring_t rcut (std::ctstring_t &str, std::ctstring_t &sepLeft, std::ctstring_t &sepRight)
cut using strings
static std::tstring_t cut (std::ctstring_t &str, std::csize_t posBegin, std::csize_t posEnd=std::tstring_t::npos)
cut using string positions
static std::tstring_t minimize (std::ctstring_t &str, std::csize_t maxLength)
minimize
static std::tstring_t formatBytes (culonglong_t &bytes)
format bytes (like Bit(s), Byte(s), MB, GB, TB)
static std::tstring_t formatPercentage (culonglong_t &maxValue, culonglong_t &currentValue)
formatting percentage
static void_t * memoryZeroSecure (void_t *buff, std::csize_t buffSize)
secure zero memory
static bool_t isRepeated (std::ctstring_t &str)
is repeated
Detailed Description
strings utils
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::core::String::xNO_DEFAULT_CONSTRUCT (String)
xNO_COPY_ASSIGN()
xl::core::String::xNO_COPY_ASSIGN (String)
castTo()
template<typename T > T xl::core::String::castTo (std::ctstring_t & value) static
cast to bools, chars, ints, doubles, enums
{
    T rv {};
    try {
        // bool_t
        if      (std::is_same<T, bool_t>::value) {
            rv = static_cast<T>( std::stoul(a_value) );
        }
        // tchar_t
        else if (std::is_same<T, tchar_t>::value ||
                 std::is_same<T, uchar_t>::value)
        {
            if ( a_value.size() > 0) {
                rv = static_cast<T>(a_value[0]);
            }
        }
        // short_t
        else if (std::is_same<T, short_t>::value) {
            rv = static_cast<T>( std::stoi(a_value) );
        }
        else if (std::is_same<T, ushort_t>::value) {
            rv = static_cast<T>( std::stoul(a_value) );
        }
        // int_t
        else if (std::is_same<T, int_t>::value) {
            rv = static_cast<T>( std::stoi(a_value) );
        }
        else if (std::is_same<T, uint_t>::value) {
            rv = static_cast<T>( std::stoul(a_value) );
        }
        // long_t
        else if (std::is_same<T, long_t>::value) {
            rv = static_cast<T>( std::stol(a_value) );
        }
        else if (std::is_same<T, ulong_t>::value) {
            rv = static_cast<T>( std::stoul(a_value) );
        }
        // longlong_t
        else if (std::is_same<T, longlong_t>::value) {
            rv = static_cast<T>( std::stoll(a_value) );
        }
        else if (std::is_same<T, ulonglong_t>::value) {
            rv = static_cast<T>( std::stoull(a_value) );
        }
        // float_t
        else  if (std::is_same<T, float_t>::value) {
            rv = static_cast<T>( std::stof(a_value) );
        }
        else if (std::is_same<T, double_t>::value) {
            rv = static_cast<T>( std::stod(a_value) );
        }
        else if (std::is_same<T, longdouble_t>::value) {
            rv = static_cast<T>( std::stold(a_value) );
        }
        // enum
        else if (std::is_enum<T>::value) {
            rv = static_cast<T>( std::stoll(a_value) );
        }
        // other
        else {
            static_assert(true, "Unknown type");
            xTEST_FAIL_MSG(xT("Unknown type"));
        }
    }
    catch (const std::exception &a_exp) {
        xTEST_FAIL_MSG( std::tstring_t(a_exp.what()) );
        rv = {};
    }
    catch (...) {
        xTEST_FAIL_MSG(xT("Unknown exception"));
        rv = {};
    }
    return rv;
}
References xT, and xTEST_FAIL_MSG.
cast() [1/4]
template<typename T > std::tstring_t xl::core::String::cast (const T & a_value) static
convert type to std::tstring_t
Parameters
a_value source value
{
    xTEST_NA(a_value);
    std::tstring_t sRv;
    try {
        std::tostringstream_t oss;
        oss.exceptions(std::tostringstream_t::failbit | std::tostringstream_t::badbit);
        oss << a_value;
        sRv = oss.str();
    }
    catch (std::ctostringstream_t::failure &) {
        sRv.clear();
    }
    catch (...) {
        sRv.clear();
    }
    return sRv;
}
References xTEST_NA.
Referenced by formatPercentage(), xl::debug::BuildInfo::os(), xl::fs::Config::setValue(), xl::fs::Config::value(), and xl::fs::File::wipe().
cast() [2/4]
template<typename T > std::tstring_t xl::core::String::cast (const T & a_value, cint_t a_base) static
convert type to std::tstring_t by base (8, 10, 16)
Parameters
a_value source value
a_base valid values: 8, 10, 16
{
    xTEST_NA(a_value);
    xTEST_NA(a_base);
    std::tstring_t sRv;
    try {
        std::tostringstream_t oss;
        oss.exceptions(std::tostringstream_t::failbit | std::tostringstream_t::badbit);
        oss << std::setbase(a_base) << std::uppercase << a_value;  // std::showbase
        sRv = oss.str();
    }
    catch (std::ctostringstream_t::failure &) {
        sRv.clear();
    }
    catch (...) {
        sRv.clear();
    }
    return sRv;
}
References xTEST_NA.
cast() [3/4]
template<typename T > T xl::core::String::cast (std::ctstring_t & a_str) static
convert std::tstring_t to type
Parameters
a_str source string
{
    xTEST_NA(a_str);
    T rvT;
    try {
        std::tistringstream_t iss(a_str);
        iss.exceptions(std::tistringstream_t::failbit | std::tistringstream_t::badbit);
        iss >> rvT;
    }
    catch (std::ctistringstream_t::failure &) {
        return T();
    }
    catch (...) {
        return T();
    }
    return rvT;
}
References xTEST_NA.
cast() [4/4]
template<typename T > T xl::core::String::cast (std::ctstring_t & a_str, cint_t a_base) static
convert std::tstring_t by base (8, 10, 16) to type
Parameters
a_str source string
a_base valid values: 8, 10, 16
{
    xTEST_NA(a_str);
    xTEST_NA(a_base);
    T rvT;
    try {
        std::tistringstream_t iss(a_str);
        iss.exceptions(std::tistringstream_t::failbit | std::tistringstream_t::badbit);
        iss >> std::setbase(a_base) >> rvT;
    }
    catch (std::ctistringstream_t::failure &) {
        return T();
    }
    catch (...) {
        return T();
    }
    return rvT;
}
References xTEST_NA.
castA() [1/3]
std::string xl::core::String::castA (std::cwstring_t & a_str) static
std::wstring in std::string
Parameters
a_str source string
{
    xTEST_NA(a_str);
    std::string asRv;
    std::transform(a_str.begin(), a_str.end(), std::back_inserter(asRv), Narrow( std::locale() ));
    return asRv;
}
References xTEST_NA.
Referenced by castCodePage().
castW() [1/3]
std::wstring xl::core::String::castW (std::cstring_t & a_str) static
std::string in std::wstring
Parameters
a_str source string
{
    xTEST_NA(a_str);
    std::wstring wsRv;
    std::transform(a_str.begin(), a_str.end(), std::back_inserter(wsRv), Widen( std::locale() ));
    return wsRv;
}
References xTEST_NA.
Referenced by castCodePage().
castA() [2/3]
std::string xl::core::String::castA (std::cwstring_t & a_str, cuint_t a_codePage) static
std::wstring in std::string
Parameters
a_str source string
a_codePage code page
{
    xTEST_NA(a_str);
    xTEST_NA(a_codePage);
    return _castA_impl(a_str, a_codePage);
}
References xTEST_NA.
castW() [2/3]
std::wstring xl::core::String::castW (std::cstring_t & a_str, cuint_t a_codePage) static
std::string in std::wstring
Parameters
a_str source string
a_codePage code page
{
    xTEST_NA(a_str);
    xTEST_NA(a_codePage);
    return _castW_impl(a_str, a_codePage);
}
References xTEST_NA.
castA() [3/3]
std::string xl::core::String::castA (std::cwstring_t & a_str, const std::locale & a_locale) static
std::wstring in std::string
Parameters
a_str source string
a_locale locale
{
    xTEST_NA(a_str);
    xTEST_NA(a_locale);
    xSTD_VERIFY(std::has_facet<std::ctype<wchar_t> >(a_locale));
    xSTD_VERIFY(std::has_facet<std::ctype<char> >(a_locale));
    xCHECK_RET(a_str.empty(),                                   std::string());
    xCHECK_RET(!std::has_facet<std::ctype<wchar_t> >(a_locale), std::string());
    xCHECK_RET(!std::has_facet<std::ctype<char> >(a_locale),    std::string());
    using state_type_t = std::wstring::traits_type::state_type;
    using codecvt_t    = std::codecvt<wchar_t, char, state_type_t>;
    std::string      asRv(a_str.size(), std::wstring::value_type());
    const codecvt_t &codec     = std::use_facet<codecvt_t>( a_locale );
    state_type_t     state {};
    cptr_cwchar_t    itBegin   = &a_str.at(0);
    cptr_cwchar_t    itEnd     = &a_str.at(0) + a_str.size();
    const wchar_t   *itNext    = nullptr;
    char            *itToBegin = &asRv.at(0);
    char            *itToEnd   = &asRv.at(0) + asRv.size();
    char            *itToNext  = nullptr;
    codec.out(state, itBegin, itEnd, itNext, itToBegin, itToEnd, itToNext);
    return asRv;
}
References xCHECK_RET, xSTD_VERIFY, and xTEST_NA.
castW() [3/3]
std::wstring xl::core::String::castW (std::cstring_t & a_str, const std::locale & a_locale) static
std::string in std::wstring
Parameters
a_str source string
a_locale locale
{
    xTEST_NA(a_str);
    xTEST_NA(a_locale);
    xSTD_VERIFY(std::has_facet<std::ctype<std::wstring::value_type>>(a_locale));
    xCHECK_RET(a_str.empty(),                                                   std::wstring());
    xCHECK_RET(!std::has_facet<std::ctype<std::wstring::value_type>>(a_locale), std::wstring());
    std::wstring swRv(a_str.size(), std::wstring::value_type());
    auto itBegin   = a_str.cbegin();
    auto itEnd     = a_str.cend();
    auto itToBegin = swRv.begin();
    for ( ; itBegin != itEnd; ++ itBegin, ++ itToBegin) {
        *itToBegin = std::use_facet<std::ctype<wchar_t>>( a_locale ).widen(*itBegin);
    }
    return swRv;
}
References xCHECK_RET, xSTD_VERIFY, and xTEST_NA.
castCodePage()
std::string xl::core::String::castCodePage (std::cstring_t & a_str, cuint_t a_codePageSource, cuint_t a_codePageDest) static
convert codepage
Parameters
a_str source string
a_codePageSource source code page
a_codePageDest destination code page
{
    xTEST_NA(a_str);
    xTEST_NA(a_codePageSource);
    xTEST_NA(a_codePageDest);
    return castA(castW(a_str, a_codePageSource), a_codePageDest);
}
References castA(), castW(), and xTEST_NA.
castToOem()
std::string xl::core::String::castToOem (std::ctstring_t & a_str) static
convert char to oem
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return _castToOem_impl(a_str);
}
References xTEST_NA.
castFromOem()
std::tstring_t xl::core::String::castFromOem (std::cstring_t & a_str) static
convert oem to char
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return _castFromOem_impl(a_str);
}
References xTEST_NA.
castBool() [1/2]
std::tstring_t xl::core::String::castBool (cbool_t a_value) static
bool_t to std::tstring_t
Parameters
a_value source string
{
    xTEST_NA(a_value);
    return (!a_value) ? xT("false") : xT("true");
}
References xT, and xTEST_NA.
Referenced by xl::fs::Config::setValue(), and xl::fs::Config::value().
castBool() [2/2]
bool_t xl::core::String::castBool (std::ctstring_t & a_str) static
convert std::tstring_t to bool_t
Parameters
a_str source string
{
    xTEST_NA(a_str);
    xCHECK_RET(StringCI::compare(xT("true"),  a_str), true);
    xCHECK_RET(StringCI::compare(xT("false"), a_str), false);
    return false;
}
References xl::core::StringCI::compare(), xCHECK_RET, xT, and xTEST_NA.
toLowerCase() [1/2]
std::tstring_t xl::core::String::toLowerCase (std::ctstring_t & a_str) static
convert to low case
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return toLowerCase(a_str, a_str.size());
}
References toLowerCase(), and xTEST_NA.
Referenced by toLowerCase().
toUpperCase() [1/2]
std::tstring_t xl::core::String::toUpperCase (std::ctstring_t & a_str) static
convert to uppercase
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return toUpperCase(a_str, a_str.size());
}
References toUpperCase(), and xTEST_NA.
Referenced by toUpperCase().
toLowerCase() [2/2]
std::tstring_t xl::core::String::toLowerCase (std::ctstring_t & a_str, std::csize_t a_length) static
convert to low case
Parameters
a_str source string
a_length string size
{
    xTEST_NA(a_str);
    xTEST_NA(a_length);
    size_t length = a_length;
    xCHECK_RET(a_str.empty(),         std::tstring_t());
    xCHECK_DO (a_str.size() < length, length = a_str.size());
    return _toLowerCase_impl(a_str, length);
}
References xCHECK_DO, xCHECK_RET, and xTEST_NA.
toUpperCase() [2/2]
std::tstring_t xl::core::String::toUpperCase (std::ctstring_t & a_str, std::csize_t a_length) static
convert to uppercase
Parameters
a_str source string
a_length string size
{
    xTEST_NA(a_str);
    xTEST_NA(a_length);
    size_t length = a_length;
    xCHECK_RET(a_str.empty(),         std::tstring_t());
    xCHECK_DO (a_str.size() < length, length = a_str.size());
    return _toUpperCase_impl(a_str, length);
}
References xCHECK_DO, xCHECK_RET, and xTEST_NA.
trimLeftChars()
std::tstring_t xl::core::String::trimLeftChars (std::ctstring_t & a_str, std::ctstring_t & a_chars) static
trim left chars
Parameters
a_str source string
a_chars chars for trim
{
    xTEST_NA(a_str);
    xTEST_NA(a_chars);
    std::tstring_t sRv(a_str);
    const std::tstring_t::size_type pos = sRv.find_first_not_of(a_chars);
    if (pos == std::tstring_t::npos) {
        sRv.erase();
        return sRv;
    }
    sRv.erase(0, pos);
    return sRv;
}
References xTEST_NA.
Referenced by trimChars().
trimRightChars()
std::tstring_t xl::core::String::trimRightChars (std::ctstring_t & a_str, std::ctstring_t & a_chars) static
trim left chars
Parameters
a_str source string
a_chars chars for trim
{
    xTEST_NA(a_str);
    xTEST_NA(a_chars);
    std::tstring_t sRv(a_str);
    const std::tstring_t::size_type pos = sRv.find_last_not_of(a_chars);
    if (pos == std::tstring_t::npos) {
        sRv.erase();
        return sRv;
    }
    sRv.erase(pos + 1);
    return sRv;
}
References xTEST_NA.
Referenced by xl::debug::BuildInfo::langStandart(), xl::debug::BuildInfo::os(), xl::fs::FileText::read(), removeEol(), xl::package::Translate::run(), xl::fs::Path::slashAppend(), xl::fs::Path::slashRemove(), and trimChars().
trimChars()
std::tstring_t xl::core::String::trimChars (std::ctstring_t & a_str, std::ctstring_t & a_chars) static
trim left, right chars
Parameters
a_str source string
a_chars chars for trim
{
    xTEST_NA(a_str);
    xTEST_NA(a_chars);
    std::tstring_t sRv(a_str);
    sRv = trimRightChars(sRv, a_chars);
    sRv = trimLeftChars (sRv, a_chars);
    return sRv;
}
References trimLeftChars(), trimRightChars(), and xTEST_NA.
Referenced by xl::system::Envs::expandVars(), and trimSpace().
trimSpace()
std::tstring_t xl::core::String::trimSpace (std::ctstring_t & a_str) static
trim left, right spaces
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return trimChars(a_str, Const::whiteSpaces());
}
References trimChars(), xl::core::Const::whiteSpaces(), and xTEST_NA.
Referenced by xl::package::GitClient::branchName(), xl::package::GitClient::commitsAheadBehind(), xl::debug::BuildInfo::compilerFlags(), xl::net::DnsClient::hostAddrByName(), xl::package::GitClient::localBranchesNum(), xl::package::xml::Error::message(), xl::package::GitClient::modifiedFiles(), xl::package::GitClient::remoteRepoNames(), xl::package::GitClient::repoName(), xl::package::GitClient::repoUrl(), xl::package::GitClient::stashesNum(), and xl::package::GitClient::trackedFiles().
removeEol()
std::tstring_t xl::core::String::removeEol (std::ctstring_t & a_str) static
remove end of line from end of string
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return trimRightChars(a_str, Const::eol());
}
References xl::core::Const::eol(), trimRightChars(), and xTEST_NA.
Referenced by xl::fs::FileIO::readLine().
quoted()
std::tstring_t xl::core::String::quoted (std::ctstring_t & a_str, ctchar_t a_delimiter = xT('\"'), ctchar_t a_escape = xT('\\')) static
quote string
Parameters
a_str source string
a_delimiter delimiter
a_escape escape
{
    std::tstring_t sRv;
    sRv = a_delimiter;
    for (const auto &it : a_str) {
        if (it == a_delimiter ||
            it == a_escape)
        {
            sRv += a_escape;
        }
        sRv += it;
    }
    sRv += a_delimiter;
    return sRv;
}
replaceAll() [1/2]
std::tstring_t xl::core::String::replaceAll (std::ctstring_t & a_str, std::ctstring_t & a_strOld, std::ctstring_t & a_strNew) static
replace all strings
Parameters
a_str source string
a_strOld old string
a_strNew new string
{
    xTEST_NA(a_str);
    xTEST_NA(a_strOld);
    xTEST_NA(a_strNew);
    xCHECK_RET(a_str.empty(),    a_str);
    xCHECK_RET(a_strOld.empty(), a_str);
    std::tstring_t sRv(a_str);
    size_t pos = 0U;
    for ( ; ; ) {
        pos = sRv.find(a_strOld, pos);
        xCHECK_DO(pos == std::tstring_t::npos, break);
        sRv.replace(pos, a_strOld.size(), a_strNew);
        pos += a_strNew.size();
    }
    return sRv;
}
References xCHECK_DO, xCHECK_RET, and xTEST_NA.
Referenced by xl::fs::Path::homeAsBrief(), removeAll(), replaceAll(), xl::fs::Path::toUnix(), and xl::fs::Path::toWin().
replaceAll() [2/2]
std::tstring_t xl::core::String::replaceAll (std::ctstring_t & a_str, ctchar_t & a_charOld, ctchar_t & a_charNew) static
replace all chars
Parameters
a_str source string
a_charOld old char
a_charNew new char
{
    xTEST_NA(a_str);
    xTEST_NA(a_charOld);
    xTEST_NA(a_charNew);
    return replaceAll(a_str, std::tstring_t(1, a_charOld), std::tstring_t(1, a_charNew));
}
References replaceAll(), and xTEST_NA.
removeAll()
std::tstring_t xl::core::String::removeAll (std::ctstring_t & a_str, std::ctstring_t & a_removeStr) static
remove all strings
Parameters
a_str source string
a_removeStr string for remove
{
    xTEST_NA(a_str);
    xTEST_NA(a_removeStr);
    return replaceAll(a_str, a_removeStr, std::tstring_t());
}
References replaceAll(), and xTEST_NA.
split() [1/2]
void_t xl::core::String::split (std::ctstring_t & a_str, std::ctstring_t & a_sep, std::vec_tstring_t * a_rv) static
split by separator
Parameters
a_str source string
a_sep separator
[out] a_rv string vector
{
    xTEST_NA(a_str);
    xTEST_NA(a_sep);
    xTEST_NA(a_rv);
    xCHECK_DO(a_rv != nullptr, a_rv->clear());
    xCHECK_DO(a_str.empty(), return);
    xCHECK_DO(a_sep.empty(), return);
    xTEST_PTR(a_rv);
    std::vec_tstring_t vsRv;
    std::size_t        posPrev = 0U;    // start of string
    for ( ; ; ) {
        std::csize_t pos = a_str.find(a_sep, posPrev);
        xCHECK_DO(pos == std::tstring_t::npos, break);
        vsRv.push_back(a_str.substr(posPrev, pos - posPrev));
        posPrev = pos + a_sep.size();
    }
    vsRv.push_back( a_str.substr(posPrev, a_str.size() - posPrev) );
    // out
    a_rv->swap(vsRv);
}
References xCHECK_DO, xTEST_NA, and xTEST_PTR.
Referenced by xl::package::GitClient::commitsAheadBehind(), xl::debug::BuildInfo::libs(), xl::package::GitClient::localBranchesNum(), xl::package::GitClient::modifiedFiles(), xl::system::ConsoleUI::msgBox(), xl::system::CmdOptions::parse(), xl::fs::FileText::read(), xl::fs::FileText::read(), xl::package::GitClient::remoteRepoNames(), split(), xl::fs::Path::split(), xl::package::GitClient::stashesNum(), xl::package::GitClient::trackedFiles(), xl::system::Env::values(), and xl::system::Envs::vars().
split() [2/2]
template<typename T > void_t xl::core::String::split (std::ctstring_t & a_str, std::ctstring_t & a_sepLine, std::ctstring_t & a_sepKeyValue, T * a_map) static
split by separator
Parameters
a_str string
a_sepLine separator line
a_sepKeyValue separator key value
[out] a_map result
{
    xTEST_NA(a_str);
    xTEST_NA(a_sepLine);
    xTEST_NA(a_sepKeyValue);
    xTEST_NA(a_map);
    xCHECK_DO(a_map != nullptr, a_map->clear());
    xCHECK_DO(a_str.empty(), return);
    xCHECK_DO(a_sepLine.empty(), return);
    xCHECK_DO(a_sepKeyValue.empty(), return);
    xCHECK_DO(a_map == nullptr, return);
    std::vec_tstring_t lines;
    split(a_str, a_sepLine, &lines);
    for (const auto &it_line : lines) {
        xCHECK_DO(it_line.empty(), continue);
        std::csize_t pos = it_line.find(a_sepKeyValue);
        xCHECK_DO(pos == std::tstring_t::npos, continue);
        std::ctstring_t &key   = it_line.substr(0, pos);
        std::ctstring_t &value = it_line.substr(pos + a_sepKeyValue.size(), std::tstring_t::npos);
        // [out]
        a_map->insert( {key, value} );
    }
}
References split(), xCHECK_DO, and xTEST_NA.
join() [1/3]
std::tstring_t xl::core::String::join (std::cvec_tstring_t & a_vec, ctchar_t & a_sep) static
join with char separator
Parameters
a_vec source string vector
a_sep separator
{
    xTEST_NA(a_vec);
    xTEST_NA(a_sep);
    return join(a_vec, std::ctstring_t(1, a_sep));
}
References join(), and xTEST_NA.
Referenced by xl::fs::Path::brief(), join(), xl::package::CsvWriter::saveFile(), xl::package::CsvWriter::saveString(), xl::sync::Process::shellExecute(), and xl::fs::FileText::write().
join() [2/3]
std::tstring_t xl::core::String::join (std::cvec_tstring_t & a_vec, std::ctstring_t & a_sep) static
join with string separator
Parameters
a_vec source string vector
a_sep separator
{
    xTEST_NA(a_vec);
    xTEST_NA(a_sep);
    std::tstring_t sRv;
    for (auto it = a_vec.cbegin(); it != a_vec.cend();  ++ it) {
        sRv.append(*it);
        xCHECK_DO(it < a_vec.end() - 1, sRv.append(a_sep));
    }
    return sRv;
}
References xCHECK_DO, and xTEST_NA.
join() [3/3]
template<typename T > std::tstring_t xl::core::String::join (const T & map, std::ctstring_t & sepLine, std::ctstring_t & sepKeyValue) static
join with string separator
{
    xTEST_NA(a_map);
    xTEST_NA(a_sepLine);
    xTEST_NA(a_sepKeyValue);
    std::tstring_t sRv;
    for (const auto &[key, value] : a_map) {
        sRv += key + a_sepKeyValue + value + a_sepLine;
    }
    return sRv;
}
References xTEST_NA.
cut() [1/2]
std::tstring_t xl::core::String::cut (std::ctstring_t & a_str, std::ctstring_t & a_sepLeft, std::ctstring_t & a_sepRight) static
cut using strings
Parameters
a_str source string
a_sepLeft left separator
a_sepRight right separator
{
    xTEST_NA(a_str);
    xTEST_NA(a_sepLeft);
    xTEST_NA(a_sepRight);
    size_t delimPosStart = a_str.find(a_sepLeft);
    xCHECK_RET(delimPosStart == std::tstring_t::npos, std::tstring_t());
    delimPosStart += a_sepLeft.size();
    size_t delimPosStop = a_str.find(a_sepRight, delimPosStart);
    xCHECK_RET(delimPosStop == std::tstring_t::npos, std::tstring_t());
    xCHECK_RET(delimPosStart >= delimPosStop,        std::tstring_t());
    return a_str.substr(delimPosStart, delimPosStop - delimPosStart);
}
References xCHECK_RET, and xTEST_NA.
Referenced by xl::system::Envs::expandVars(), xl::fs::Path::fileBaseName(), and xl::package::GitClient::repoUrlName().
rcut()
std::tstring_t xl::core::String::rcut (std::ctstring_t & a_str, std::ctstring_t & a_sepLeft, std::ctstring_t & a_sepRight) static
cut using strings
Parameters
a_str source string
a_sepLeft left separator
a_sepRight right separator
{
    xTEST_NA(a_str);
    xTEST_NA(a_sepLeft);
    xTEST_NA(a_sepRight);
    size_t delimPosStart = a_str.find(a_sepLeft);
    xCHECK_RET(delimPosStart == std::tstring_t::npos, std::tstring_t());
    delimPosStart += a_sepLeft.size();
    size_t delimPosStop  = a_str.rfind(a_sepRight);
    xCHECK_RET(delimPosStop == std::tstring_t::npos, std::tstring_t());
    xCHECK_RET(delimPosStart >= delimPosStop,        std::tstring_t());
    return a_str.substr(delimPosStart, delimPosStop - delimPosStart);
}
References xCHECK_RET, and xTEST_NA.
cut() [2/2]
std::tstring_t xl::core::String::cut (std::ctstring_t & a_str, std::csize_t a_posBegin, std::csize_t a_posEnd = std::tstring_t::npos) static
cut using string positions
Parameters
a_str source string
a_posBegin begin position
a_posEnd end position
{
    xTEST_NA(a_str);
    xTEST_NA(a_posBegin);
    xTEST_NA(a_posEnd);
    xCHECK_RET(a_str.empty(),         std::tstring_t());
    xCHECK_RET(a_posBegin > a_posEnd, std::tstring_t());
    size_t size = std::tstring_t::npos;
    if (a_posEnd == std::tstring_t::npos) {
        size = a_posEnd;
    } else {
        size = a_posEnd - a_posBegin;
    }
    return a_str.substr(a_posBegin, size);
}
References xCHECK_RET, and xTEST_NA.
minimize()
std::tstring_t xl::core::String::minimize (std::ctstring_t & a_str, std::csize_t a_maxLength) static
minimize
Parameters
a_str source string
a_maxLength string maximum size
{
    xTEST_NA(a_str);
    xTEST_NA(a_maxLength);
    xCHECK_RET(a_str.empty(),     std::tstring_t());
    xCHECK_RET(a_maxLength == 0U, std::tstring_t());
    std::tstring_t sRv;
    if (a_str.size() > a_maxLength) {
        if (a_maxLength < Const::dot3().size()) {
            sRv = a_str.substr(0U, a_maxLength);
        } else {
            sRv = a_str.substr(0U, a_maxLength - Const::dot3().size()) + Const::dot3();
        }
    } else {
        sRv = a_str;
    }
    return sRv;
}
References xl::core::Const::dot3(), xCHECK_RET, and xTEST_NA.
formatBytes()
std::tstring_t xl::core::String::formatBytes (culonglong_t & a_bytes) static
format bytes (like Bit(s), Byte(s), MB, GB, TB)
Parameters
a_bytes bytes
{
    xTEST_NA(a_bytes);
    std::tstring_t sRv = Const::strUnknown();
    culonglong_t eb   = xEB(1);
    culonglong_t pb   = xPB(1);
    culonglong_t tb   = xTB(1);
    culonglong_t gb   = xGB(1);
    culonglong_t mb   = xMB(1);
    culonglong_t kb   = xKB(1);
    culonglong_t byte = xBYTES(1);
    if (     a_bytes / eb > 0ULL) {
        sRv = FormatC::str(xT("%.2f EB"), static_cast<double>(a_bytes) / static_cast<double>(eb));
    }
    else if (a_bytes / pb > 0ULL) {
        sRv = FormatC::str(xT("%.2f PB"), static_cast<double>(a_bytes) / static_cast<double>(pb));
    }
    else if (a_bytes / tb > 0ULL) {
        sRv = FormatC::str(xT("%.2f TB"), static_cast<double>(a_bytes) / static_cast<double>(tb));
    }
    else if (a_bytes / gb > 0ULL) {
        sRv = FormatC::str(xT("%.2f GB"), static_cast<double>(a_bytes) / static_cast<double>(gb));
    }
    else if (a_bytes / mb > 0ULL) {
        sRv = FormatC::str(xT("%.2f MB"), static_cast<double>(a_bytes) / static_cast<double>(mb));
    }
    else if (a_bytes / kb > 0ULL) {
        sRv = FormatC::str(xT("%.2f KB"), static_cast<double>(a_bytes) / static_cast<double>(kb));
    }
    else if (a_bytes / byte > 0ULL) {
        sRv = FormatC::str(xT("%.2f Byte(s)"), static_cast<double>(a_bytes) / static_cast<double>(byte));
    }
    else {
        sRv = FormatC::str(xT("%.2f Bit(s)"), static_cast<double>(a_bytes));
    }
    return sRv;
}
References xl::core::FormatC::str(), xl::core::Const::strUnknown(), xBYTES, xEB, xGB, xKB, xMB, xPB, xT, xTB, and xTEST_NA.
formatPercentage()
std::tstring_t xl::core::String::formatPercentage (culonglong_t & a_maxValue, culonglong_t & a_currentValue) static
formatting percentage
Parameters
a_maxValue maximum value
a_currentValue current value
{
    xTEST_NA(a_maxValue);
    xTEST_NA(a_currentValue);
    xCHECK_RET(a_maxValue == 0ULL, xT("0%")); // devision by zero
    std::tstring_t sRv;
    sRv = cast( a_currentValue * 100ULL / a_maxValue );
    xCHECK_RET(sRv.empty(), xT("0%"));
    sRv.append(xT("%"));
    return sRv;
}
References cast(), xCHECK_RET, xT, and xTEST_NA.
memoryZeroSecure()
void_t * xl::core::String::memoryZeroSecure (void_t * a_buff, std::csize_t a_buffSize) static
secure zero memory
Parameters
a_buff buffer
a_buffSize buffer size (bytes)
{
    xTEST_NA(a_buff);
    xTEST_NA(a_buffSize);
    size_t buffSize = a_buffSize;
    for (volatile uchar_t *buff = static_cast<volatile uchar_t *>( a_buff );
         a_buff != nullptr && 0 != buffSize;
         ++ buff, -- buffSize)
    {
        *buff = 0;
    }
    return a_buff;
}
References xTEST_NA.
isRepeated()
bool_t xl::core::String::isRepeated (std::ctstring_t & a_str) static
is repeated
Parameters
a_str source string
{
    xTEST_NA(a_str);
    return ( std::tstring_t::npos == a_str.find_first_not_of(a_str.at(0)) );
}
References xTEST_NA.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/String.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/String.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/String.inl