xLib: xl::core::Locale Class Reference
xl::core::Locale Class Reference
locale
#include "Locale.h"
Public Member Functions
std::tstring_t current () const
get current
void_t setCurrent (std::ctstring_t &locale) const
set current
void_t setDefault () const
set default
ctors, dtor
Locale ()=default
virtual ~Locale ()=default
xNO_COPY_ASSIGN (Locale)
Detailed Description
locale
Constructor & Destructor Documentation
Locale()
xl::core::Locale::Locale () default
~Locale()
virtual xl::core::Locale::~Locale () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::core::Locale::xNO_COPY_ASSIGN (Locale)
current()
std::tstring_t xl::core::Locale::current () const
get current
{
    // n/a
    return _current_impl();
}
Referenced by setDefault().
setCurrent()
void_t xl::core::Locale::setCurrent (std::ctstring_t & locale) const
set current
{
    xTEST_NA(a_locale);
    cptr_ctchar_t locale = a_locale.empty() ? nullptr : a_locale.c_str();
    cptr_ctchar_t pcszRv = xTSETLOCALE(LC_ALL, locale);
    xTEST_PTR(pcszRv);
}
References xTEST_NA, and xTEST_PTR.
Referenced by xl::package::Application::Application(), and setDefault().
setDefault()
void_t xl::core::Locale::setDefault () const
set default
{
    setCurrent( current() );
}
References current(), and setCurrent().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Locale.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Locale.cpp