xLib: xl::core::StringCI Class Reference
xl::core::StringCI Class Reference
strings utils (case insensitive)
#include "String.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (StringCI)
xNO_COPY_ASSIGN (StringCI)
Static Public Member Functions
static std::size_t find (std::ctstring_t &str, std::ctstring_t &target, std::csize_t pos=0, const xTLOCALE &locale=xTLOCALE())
no case search
static bool_t contains (std::ctstring_t &str, std::ctstring_t &target, std::csize_t pos=0, const xTLOCALE &locale=xTLOCALE())
no case search
static bool_t compare (std::ctstring_t &str1, std::ctstring_t &str2, const xTLOCALE &locale=xTLOCALE())
no case compare
Detailed Description
strings utils (case insensitive)
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::core::StringCI::xNO_DEFAULT_CONSTRUCT (StringCI)
xNO_COPY_ASSIGN()
xl::core::StringCI::xNO_COPY_ASSIGN (StringCI)
find()
std::size_t xl::core::StringCI::find (std::ctstring_t & a_str, std::ctstring_t & a_target, std::csize_t a_pos = 0, const xTLOCALE & a_locale = xTLOCALE()) static
no case search
Parameters
a_str source string
a_target target string
a_pos start position
a_locale locale
{
    xTEST_NA(a_str);
    xTEST_NA(a_target);
    xTEST_NA(a_pos);
    xCHECK_RET(a_str.empty() && a_target.empty() && a_pos == 0U, 0U);
    xCHECK_RET(a_target.empty(),                                 0U);
    auto cit = std::search(
        a_str.cbegin() + static_cast<std::ssize_t>(a_pos), a_str.cend(),
        a_target.cbegin(), a_target.cend(), CompareCI(a_locale));
    xCHECK_RET(cit != a_str.cend(), static_cast<std::size_t >(cit - a_str.cbegin()));
    return std::tstring_t::npos;
}
References xCHECK_RET, and xTEST_NA.
Referenced by contains().
contains()
bool_t xl::core::StringCI::contains (std::ctstring_t & a_str, std::ctstring_t & a_target, std::csize_t a_pos = 0, const xTLOCALE & a_locale = xTLOCALE()) static
no case search
Parameters
a_str source string
a_target target string
a_pos start position
a_locale locale
{
    return (find(a_str, a_target, a_pos, a_locale) != std::tstring_t::npos);
}
References find().
Referenced by xl::package::GitClient::filesStatuses().
compare()
bool_t xl::core::StringCI::compare (std::ctstring_t & a_str1, std::ctstring_t & a_str2, const xTLOCALE & a_locale = xTLOCALE()) static
no case compare
Parameters
a_str1 source string
a_str2 target string
a_locale locale
{
    xTEST_NA(a_str1);
    xTEST_NA(a_str2);
    xCHECK_RET(a_str1.size() != a_str2.size(), false);
    return _compare_impl(a_str1, a_str2, a_locale);
}
References xCHECK_RET, and xTEST_NA.
Referenced by xl::core::String::castBool(), xl::core::DateTime::monthNum(), xl::core::CompareCI::operator()(), and xl::core::DateTime::weekDayNum().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/String.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/String.cpp