xLib: xl::net::ISocket Class Reference
xl::net::ISocket Class Reference abstract
socket
#include "ISocket.h"
Inherited by xl::net::TcpClient, and xl::net::TcpServer.
Public Types
enum class AddressFamily {
afUnix = AF_UNIX ,
afLocal = AF_LOCAL ,
afInet = AF_INET ,
afInet6 = AF_INET6 ,
afIpx = AF_IPX ,
afX25 = AF_X25 ,
afAX25 = AF_AX25 ,
afAtmpvc = AF_ATMPVC ,
afAppletalk = AF_APPLETALK ,
afPacket = AF_PACKET
}
address family
enum class Type {
tpStream = SOCK_STREAM ,
tpDgram = SOCK_DGRAM ,
tpRaw = SOCK_RAW ,
tpRdm = SOCK_RDM ,
tpSeqPacket = SOCK_SEQPACKET
}
type
enum class Protocol {
ptIp = IPPROTO_IP ,
ptHopopts = IPPROTO_HOPOPTS ,
ptIcmp = IPPROTO_ICMP ,
ptIgmp = IPPROTO_IGMP ,
ptIpip = IPPROTO_IPIP ,
ptTcp = IPPROTO_TCP ,
ptEgp = IPPROTO_EGP ,
ptPup = IPPROTO_PUP ,
ptUdp = IPPROTO_UDP ,
ptIdp = IPPROTO_IDP ,
ptIpv6 = IPPROTO_IPV6 ,
ptRouting = IPPROTO_ROUTING ,
ptFragment = IPPROTO_FRAGMENT ,
ptRsvp = IPPROTO_RSVP ,
ptGre = IPPROTO_GRE ,
ptEsp = IPPROTO_ESP ,
ptAH = IPPROTO_AH ,
ptICmpv6 = IPPROTO_ICMPV6 ,
ptNone = IPPROTO_NONE ,
ptDstopts = IPPROTO_DSTOPTS ,
ptPim = IPPROTO_PIM ,
ptComp = IPPROTO_COMP ,
ptSctp = IPPROTO_SCTP ,
ptRaw = IPPROTO_RAW ,
ptMax = IPPROTO_MAX
}
protocol
enum Options {
SOCKET_TIMEOUT = 0 ,
SOCKET_BUFF_SIZE = 32768
}
options
Public Member Functions
void_t create (cAddressFamily family, cType type, cProtocol protocol)
creates a socket that is bound to a specific transport service provider
HandleSocket & handle ()
get handle
bool_t isReadable () const
checking for readability
bool_t isWritable () const
checking for writability
void_t assign (csocket_t &handle)
assign to another handle
void_t close ()
close
std::ssize_t send (cptr_ctchar_t buff, std::csize_t &buffSize, cint_t &flags)
send data
void_t sendAll (std::ctstring_t &buff, cint_t &flags)
send data by blocks
std::ssize_t receive (tchar_t *buff, std::csize_t &buffSize, cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags, std::ctstring_t &delimiter)
receive data to delimiter, includes it
int_t sendBytes (char *buff, std::ssize_t &messageLength)
send bytes
int_t receiveBytes (char *buff, std::ssize_t &stillToReceive)
receive bytes
void_t peerName (std::tstring_t *peerAddr, ushort_t *peerPort)
get address of the peer to which a handle is connected
void_t socketName (std::tstring_t *socketAddr, ushort_t *socketPort)
get local name for a socket
ctors, dtor
ISocket ()=default
virtual ~ISocket ()=0
xNO_COPY_ASSIGN (ISocket)
Static Public Member Functions
static int_t select (int_t nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, timeval *timeout)
determines the status of one or more sockets, waiting if necessary, to perform synchronous I/O
static int_t nativeError ()
get error status for the last operation that failed
Protected Attributes
HandleSocket _handle
socket handle
sa_family_t _family {}
family
std::tstring_t _ip
IP.
ushort_t _port {}
port
Detailed Description
socket
Member Enumeration Documentation
AddressFamily
enum class xl::net::ISocket::AddressFamily strong
address family
Enumerator
afUnix
afLocal
afInet
afInet6
afIpx
afX25
afNetlink = AF_NETLINK, /// TODO: not in Apple
afAX25
afAtmpvc
afAppletalk
afPacket
    {
    #if   xENV_WIN
        afUnspecified = AF_UNSPEC,
        afInet        = AF_INET,
        afIpx         = AF_IPX,
        afAppletalk   = AF_APPLETALK,
        afNetbios     = AF_NETBIOS,
        afInet6       = AF_INET6,
        afIrdA        = AF_IRDA
        #if !xCOMPILER_MINGW
            ,
            afBluetooth   = AF_BTH
        #endif
    #elif xENV_UNIX
        #if   xENV_LINUX
            afUnix        = AF_UNIX,
            afLocal       = AF_LOCAL,
            afInet        = AF_INET,
            afInet6       = AF_INET6,
            afIpx         = AF_IPX,
            /// afNetlink     = AF_NETLINK, /// TODO: not in Apple
            afX25         = AF_X25,
            afAX25        = AF_AX25,
            afAtmpvc      = AF_ATMPVC,
            afAppletalk   = AF_APPLETALK,
            afPacket      = AF_PACKET
        #elif xENV_BSD
            afLocal     = PF_LOCAL,
            afUnix      = PF_UNIX,
            afInet      = PF_INET,
            afPup       = PF_PUP,
            afAppletalk = PF_APPLETALK,
            afRoute     = PF_ROUTE,
            afLink      = PF_LINK,
            afIpx       = PF_IPX,
            afRtip      = PF_RTIP,
            afPip       = PF_PIP,
            afIsdn      = PF_ISDN,
            afKey       = PF_KEY,
            afInet6     = PF_INET6,
            afNatm      = PF_NATM,
            afAtm       = PF_ATM,
            afNetgraph  = PF_NETGRAPH,
        #elif xENV_APPLE
            afUnix        = AF_UNIX,
            afLocal       = AF_LOCAL,
            afInet        = AF_INET,
            afInet6       = AF_INET6,
            afIpx         = AF_IPX,
            afAppletalk   = AF_APPLETALK
            // TODO: [skynowa] ISocket - add AP-*
        #endif
    #endif
    };
Type
enum class xl::net::ISocket::Type strong
type
Enumerator
tpStream
tpDgram
tpRaw
tpRdm
tpSeqPacket
    {
        tpStream      = SOCK_STREAM,
        tpDgram       = SOCK_DGRAM,
        tpRaw         = SOCK_RAW,
        tpRdm         = SOCK_RDM,
        tpSeqPacket   = SOCK_SEQPACKET
    };
Protocol
enum class xl::net::ISocket::Protocol strong
protocol
Enumerator
ptIp
ptHopopts
ptIcmp
ptIgmp
ptIpip
ptTcp
ptEgp
ptPup
ptUdp
ptIdp
ptIpv6
ptRouting
ptFragment
ptRsvp
ptGre
ptEsp
ptAH
ptICmpv6
ptNone
ptDstopts
ptPim
ptComp
ptSctp
ptRaw
ptMax
    {
    #if xENV_WIN
        ptIp          = IPPROTO_IP,
        ptIcmp        = IPPROTO_ICMP,
        ptIgmp        = IPPROTO_IGMP,
        //// ptRfcomm      = BTHPROTO_RFCOMM,
        ptTcp         = IPPROTO_TCP,
        ptUdp         = IPPROTO_UDP,
        ptIcmpv6      = IPPROTO_ICMPV6,
        //// ptRm          = IPPROTO_RM
    #elif xENV_UNIX
        #if   xENV_LINUX
            ptIp          = IPPROTO_IP,
            ptHopopts     = IPPROTO_HOPOPTS,
            ptIcmp        = IPPROTO_ICMP,
            ptIgmp        = IPPROTO_IGMP,
            ptIpip        = IPPROTO_IPIP,
            ptTcp         = IPPROTO_TCP,
            ptEgp         = IPPROTO_EGP,
            ptPup         = IPPROTO_PUP,
            ptUdp         = IPPROTO_UDP,
            ptIdp         = IPPROTO_IDP,
            //// ptTp          = IPPROTO_TP,
            //// ptDccp        = IPPROTO_DCCP,
            ptIpv6        = IPPROTO_IPV6,
            ptRouting     = IPPROTO_ROUTING,
            ptFragment    = IPPROTO_FRAGMENT,
            ptRsvp        = IPPROTO_RSVP,
            ptGre         = IPPROTO_GRE,
            ptEsp         = IPPROTO_ESP,
            ptAH          = IPPROTO_AH,
            ptICmpv6      = IPPROTO_ICMPV6,
            ptNone        = IPPROTO_NONE,
            ptDstopts     = IPPROTO_DSTOPTS,
            //// ptMtp         = IPPROTO_MTP,
            //// ptEncap       = IPPROTO_ENCAP,
            ptPim         = IPPROTO_PIM,
            ptComp        = IPPROTO_COMP,
            ptSctp        = IPPROTO_SCTP,
            //// ptUdplite     = IPPROTO_UDPLITE,
            ptRaw         = IPPROTO_RAW,
            ptMax         = IPPROTO_MAX
        #elif xENV_BSD
            ptIp          = IPPROTO_IP,
            ptHopopts     = IPPROTO_HOPOPTS,
            ptIcmp        = IPPROTO_ICMP,
            ptIgmp        = IPPROTO_IGMP,
            ptIpip        = IPPROTO_IPIP,
            ptTcp         = IPPROTO_TCP,
            ptEgp         = IPPROTO_EGP,
            ptPup         = IPPROTO_PUP,
            ptUdp         = IPPROTO_UDP,
            ptIdp         = IPPROTO_IDP,
            //// ptTp          = IPPROTO_TP,
            ptIpv6        = IPPROTO_IPV6,
            ptRouting     = IPPROTO_ROUTING,
            ptFragment    = IPPROTO_FRAGMENT,
            ptRsvp        = IPPROTO_RSVP,
            ptGre         = IPPROTO_GRE,
            ptEsp         = IPPROTO_ESP,
            ptAH          = IPPROTO_AH,
            ptICmpv6      = IPPROTO_ICMPV6,
            ptNone        = IPPROTO_NONE,
            ptDstopts     = IPPROTO_DSTOPTS,
            //// ptMtp         = IPPROTO_MTP,
            //// ptEncap       = IPPROTO_ENCAP,
            ptPim         = IPPROTO_PIM,
            ptRaw         = IPPROTO_RAW,
            ptMax         = IPPROTO_MAX
        #elif xENV_APPLE
            ptIp          = IPPROTO_IP,
            ptHopopts     = IPPROTO_HOPOPTS,
            ptIcmp        = IPPROTO_ICMP,
            ptIgmp        = IPPROTO_IGMP,
            ptIpip        = IPPROTO_IPIP,
            ptTcp         = IPPROTO_TCP,
            ptEgp         = IPPROTO_EGP,
            ptPup         = IPPROTO_PUP,
            ptUdp         = IPPROTO_UDP,
            ptIdp         = IPPROTO_IDP,
            //// ptTp          = IPPROTO_TP,
            ptIpv6        = IPPROTO_IPV6,
            ptRouting     = IPPROTO_ROUTING,
            ptFragment    = IPPROTO_FRAGMENT,
            ptRsvp        = IPPROTO_RSVP,
            ptGre         = IPPROTO_GRE,
            ptEsp         = IPPROTO_ESP,
            ptAH          = IPPROTO_AH,
            ptICmpv6      = IPPROTO_ICMPV6,
            ptNone        = IPPROTO_NONE,
            ptDstopts     = IPPROTO_DSTOPTS,
            //// ptMtp         = IPPROTO_MTP,
            //// ptEncap       = IPPROTO_ENCAP,
            ptPim         = IPPROTO_PIM,
            ptSctp        = IPPROTO_SCTP,
            ptRaw         = IPPROTO_RAW,
            ptMax         = IPPROTO_MAX
            // TODO: [skynowa] ISocket - add IPPROTO-*
        #endif
    #endif
    };
Options
enum xl::net::ISocket::Options
options
Enumerator
SOCKET_TIMEOUT
(1000000 / 10)
SOCKET_BUFF_SIZE
32 KB
    {
        SOCKET_TIMEOUT   = 0,       ///< (1000000 / 10)
        SOCKET_BUFF_SIZE = 32768    ///< 32 KB
    };
Constructor & Destructor Documentation
ISocket()
xl::net::ISocket::ISocket () default
~ISocket()
xl::net::ISocket::~ISocket () pure virtual
{
}
Member Function Documentation
xNO_COPY_ASSIGN()
xl::net::ISocket::xNO_COPY_ASSIGN (ISocket)
create()
void_t xl::net::ISocket::create (cAddressFamily family, cType type, cProtocol protocol)
creates a socket that is bound to a specific transport service provider
{
    xTEST(!_handle.isValid());
    _handle = ::socket(static_cast<int_t>(a_family), static_cast<int_t>(a_type),
        static_cast<int_t>(a_protocol));
    xTEST(_handle.isValid());
    _family = static_cast<sa_family_t>(a_family);
}
References _family, _handle, xl::core::Handle< T, typeT >::isValid(), and xTEST.
Referenced by xl::package::Ssh2Client::connect(), and xl::net::TcpClient::isServerAlive().
handle()
HandleSocket & xl::net::ISocket::handle ()
get handle
{
    xTEST(_handle.isValid());
    return _handle;
}
References _handle, xl::core::Handle< T, typeT >::isValid(), and xTEST.
Referenced by xl::package::Ssh2Client::connect(), and xl::net::TcpClient::isServerAlive().
isReadable()
bool_t xl::net::ISocket::isReadable () const
checking for readability
{
    timeval timeoutVal = {1, 0};
    fd_set  fds;         FD_ZERO(&fds);
    FD_SET(_handle.get(), &fds);
    int_t iRv = ::select(0, &fds, nullptr, nullptr, &timeoutVal);
    xCHECK_RET(iRv <= 0 || !FD_ISSET(_handle.get(), &fds), false);
    return true;
}
References _handle, xl::core::Handle< T, typeT >::get(), select(), and xCHECK_RET.
isWritable()
bool_t xl::net::ISocket::isWritable () const
checking for writability
{
    timeval timeoutVal = {1, 0};
    fd_set  fds;         FD_ZERO(&fds);
    FD_SET(_handle.get(), &fds);
    int_t iRv = ::select(0, nullptr, &fds, nullptr, &timeoutVal);
    xCHECK_RET(iRv <= 0 || !FD_ISSET(_handle.get(), &fds), false);
    return true;
}
References _handle, xl::core::Handle< T, typeT >::get(), select(), and xCHECK_RET.
assign()
void_t xl::net::ISocket::assign (csocket_t & handle)
assign to another handle
{
    xTEST_NA(_handle);
    xTEST_NA(a_handle);
    _handle = a_handle;
}
References _handle, and xTEST_NA.
Referenced by xl::net::TcpServer::accept().
close()
void_t xl::net::ISocket::close ()
close
{
    xTESTS_NA;
    _handle.close();
}
References _handle, xl::core::Handle< T, typeT >::close(), and xTESTS_NA.
Referenced by xl::package::Ssh2Client::disconnect().
send()
std::ssize_t xl::net::ISocket::send (cptr_ctchar_t buff, std::csize_t & buffSize, cint_t & flags)
send data
{
    // TODO: [skynowa] ISocket::send() - LINUX: ssize_t send(int_t sockfd, cptr_cvoid_t buf, size_t len, int_t flags);
    xTEST(_handle.isValid());
    xTEST_PTR(a_buff);
    /////xTEST_LESS(0, ::lstrlen(buff));
    return _send_impl(a_buff, a_buffSize, a_flags);
}
References _handle, xl::core::Handle< T, typeT >::isValid(), xTEST, and xTEST_PTR.
Referenced by sendAll(), and sendBytes().
sendAll()
void_t xl::net::ISocket::sendAll (std::ctstring_t & buff, cint_t & flags)
send data by blocks
{
    xTEST(_handle.isValid());
    xTEST(!a_buff.empty());
    xTEST_LESS(size_t(0U), a_buff.size());
    size_t currPos  = 0;
    // TODO: [skynowa] ISocket::send() - overflow ISocket::sendAll()
    size_t leftSize = a_buff.size() * sizeof(tchar_t);
    // if size of data more than size of buffer - sizeof buffer SOCKET_BUFF_SIZE
    size_t buffOutSize  = 0;
    if (leftSize >= Options::SOCKET_BUFF_SIZE) {
        buffOutSize = Options::SOCKET_BUFF_SIZE;
    } else {
        buffOutSize = leftSize;
    }
    for ( ; ; ) {        /* uiLeftSize > 0 */
        std::ssize_t iRv = send(&a_buff.at(0) + currPos, buffOutSize, a_flags);
        xCHECK_DO(iRv == xSOCKET_ERROR, break);
        xCHECK_DO(iRv == 0,             break);
        currPos  += static_cast<std::size_t>(iRv);
        leftSize -= static_cast<std::size_t>(iRv);
        xCHECK_DO(leftSize < buffOutSize, buffOutSize = leftSize);
        // id data is finished - exit from loop
        if (leftSize == 0) {
            xTEST_EQ(a_buff.size() * sizeof(tchar_t), currPos);
            break;
        }
    }
}
References _handle, xl::core::Handle< T, typeT >::isValid(), send(), SOCKET_BUFF_SIZE, xCHECK_DO, xSOCKET_ERROR, xTEST, xTEST_EQ, and xTEST_LESS.
receive()
std::ssize_t xl::net::ISocket::receive (tchar_t * buff, std::csize_t & buffSize, cint_t & flags)
receive data
{
    xTEST(_handle.isValid());
    xTEST_PTR(a_buff);
    xTEST_DIFF(a_buffSize, (size_t)0);
    std::memset(a_buff, 0, a_buffSize * sizeof(tchar_t));
    return _receive_impl(a_buff, a_buffSize, a_flags);
}
References _handle, xl::core::Handle< T, typeT >::isValid(), xTEST, xTEST_DIFF, and xTEST_PTR.
Referenced by recvAll().
recvAll() [1/2]
std::tstring_t xl::net::ISocket::recvAll (cint_t & flags)
receive data
{
    xTEST_NA(a_flags);
    std::tstring_t sRv;
    std::csize_t   buffSize           = 1024 * sizeof(tchar_t);
    tchar_t        buff[buffSize + 1] = {0};
    for ( ; ; ) {
        ulong_t arg = (ulong_t)a_flags;
        int_t iRv = xIOCTLSOCKET(_handle.get(), FIONREAD, &arg);
        xCHECK_DO(iRv != 0,       break);
        xCHECK_DO(arg == 0,       break);
        xCHECK_DO(buffSize < arg, arg = buffSize);
        std::ssize_t uiRv = ::recv(_handle.get(), (char *)&buff[0], arg, 0);
        xCHECK_DO(uiRv <= 0, break);
        sRv.append(buff, static_cast<std::size_t>(uiRv));
    }
    return sRv;
}
References _handle, xl::core::Handle< T, typeT >::get(), xCHECK_DO, xIOCTLSOCKET, and xTEST_NA.
recvAll() [2/2]
std::tstring_t xl::net::ISocket::recvAll (cint_t & flags, std::ctstring_t & delimiter)
receive data to delimiter, includes it
{
    std::tstring_t sRv;
    std::size_t    inSize = Options::SOCKET_BUFF_SIZE * sizeof(tchar_t);
    std::tstring_t in(inSize, xT('\0'));
    // read from socket by blocks, write to string
    for ( ; ; ) {
        std::ssize_t iRv = receive(&in.at(0), inSize, a_flags);
        xCHECK_DO(iRv == xSOCKET_ERROR, break);
        xCHECK_DO(iRv == 0,             break);
        sRv.append(in.cbegin(), in.cbegin() + iRv);
        // if delimiter was find - break
        size_t delimiterPos = sRv.find(a_delimiter); // TODO: [skynowa] ISocket::recvAll() - from unicode ???
        xCHECK_DO(delimiterPos != std::tstring_t::npos, break);
    }
    return sRv;
}
References receive(), SOCKET_BUFF_SIZE, xCHECK_DO, xSOCKET_ERROR, and xT.
sendBytes()
int_t xl::net::ISocket::sendBytes (char * buff, std::ssize_t & messageLength)
send bytes
{
    // TODO: [skynowa] ISocket::sendBytes()
    int_t   iRv                = 0;
    timeval sendTimeout        = {0, 0};
    std::ssize_t messageLength = a_messageLength;
    // setting the timeout
    sendTimeout.tv_sec  = 0;
    sendTimeout.tv_usec = SOCKET_TIMEOUT;
    fd_set fds;    FD_ZERO(&fds);
    FD_SET(_handle.get(), &fds);
    // ..as long_t as we need to send data...
    while (messageLength > 0) {
        iRv = ::select(0, nullptr, &fds, nullptr, &sendTimeout);
        // timed out, return error
        xCHECK_RET(!iRv, xSOCKET_ERROR);
        // An error occurred
        xCHECK_RET(iRv < 0, nativeError());
        // send a few bytes
    #if   xENV_WIN
        const auto buffSize = static_cast<int_t>(messageLength);
    #elif xENV_UNIX
        const auto buffSize = static_cast<std::size_t>(messageLength);
    #endif
        std::ssize_t sendStatus = ::send(_handle.get(), a_buff, buffSize, 0);
        // An error occurred when sending data
        xCHECK_RET(sendStatus < 0, nativeError());
        // update the buffer and the counter
        messageLength -= sendStatus;
        a_buff        += sendStatus;
    }
    return 0;
}
References _handle, xl::core::Handle< T, typeT >::get(), nativeError(), select(), send(), SOCKET_TIMEOUT, xCHECK_RET, and xSOCKET_ERROR.
receiveBytes()
int_t xl::net::ISocket::receiveBytes (char * buff, std::ssize_t & stillToReceive)
receive bytes
{
    int_t   iRv                 = 0;
    timeval receiveTimeout      = {0, 0};
    std::ssize_t stillToReceive = a_stillToReceive;
    // Setting the timeout
    receiveTimeout.tv_sec  = 0;
    receiveTimeout.tv_usec = SOCKET_TIMEOUT;
    fd_set fds;    FD_ZERO(&fds);
    FD_SET(_handle.get(), &fds);
    // Until the data is sent
    while (stillToReceive > 0) {
        iRv = ::select(0, &fds, nullptr, nullptr, &receiveTimeout);
        // return by timeout
        xCHECK_RET(!iRv, xSOCKET_ERROR);
        // An error occurred
        xCHECK_RET(iRv < 0, nativeError());
        // receive a few bytes
    #if   xENV_WIN
        const auto buffSize = static_cast<int_t>(stillToReceive);
    #elif xENV_UNIX
        const auto buffSize = static_cast<std::size_t>(stillToReceive);
    #endif
        std::ssize_t receiveStatus = ::recv(_handle.get(), a_buff, buffSize, 0);
        // An error occurred when the function recv ()
        xCHECK_RET(receiveStatus < 0, nativeError());
        // changed the value of the counter and the buffer
        stillToReceive -= receiveStatus;
        a_buff         += receiveStatus;
    }
    return 0;
}
References _handle, xl::core::Handle< T, typeT >::get(), nativeError(), select(), SOCKET_TIMEOUT, xCHECK_RET, and xSOCKET_ERROR.
peerName()
void_t xl::net::ISocket::peerName (std::tstring_t * peerAddr, ushort_t * peerPort)
get address of the peer to which a handle is connected
{
    xTEST_NA(a_peerAddr);
    xTEST_NA(a_peerPort);
    _peerName_impl(a_peerAddr, a_peerPort);
}
References xTEST_NA.
socketName()
void_t xl::net::ISocket::socketName (std::tstring_t * socketAddr, ushort_t * socketPort)
get local name for a socket
{
    xTEST_NA(a_socketAddr);
    xTEST_NA(a_socketPort);
    _socketName_impl(a_socketAddr, a_socketPort);
}
References xTEST_NA.
select()
int_t xl::net::ISocket::select (int_t nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, timeval * timeout) static
determines the status of one or more sockets, waiting if necessary, to perform synchronous I/O
{
    // nfds
    // pReadfds
    // pWritefds
    // pExceptfds
     int_t iRv = ::select(a_nfds, a_readfds, a_writefds, a_exceptfds, a_timeout);
     xTEST_DIFF(iRv, xSOCKET_ERROR);
     xTEST_DIFF(iRv, 0);  // zero if the time limit expired
     return iRv;
}
References select(), xSOCKET_ERROR, and xTEST_DIFF.
Referenced by isReadable(), isWritable(), receiveBytes(), select(), and sendBytes().
nativeError()
int_t xl::net::ISocket::nativeError () static
get error status for the last operation that failed
{
    // n/a
    return _nativeError_impl();
}
Referenced by receiveBytes(), and sendBytes().
Member Data Documentation
_handle
HandleSocket xl::net::ISocket::_handle protected
socket handle
Referenced by xl::net::TcpServer::accept(), assign(), xl::net::TcpServer::bind(), close(), xl::net::TcpClient::connect(), create(), handle(), xl::net::TcpClient::ioctl(), isReadable(), isWritable(), xl::net::TcpServer::listen(), receive(), receiveBytes(), recvAll(), send(), sendAll(), and sendBytes().
_family
sa_family_t xl::net::ISocket::_family {} protected
family
{};      ///< family
Referenced by xl::net::TcpServer::bind(), xl::net::TcpClient::connect(), and create().
_ip
std::tstring_t xl::net::ISocket::_ip protected
IP.
_port
ushort_t xl::net::ISocket::_port {} protected
port
{};        ///< port
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/ISocket.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/ISocket.cpp