xLib: xl::package::Translate Class Reference
xl::package::Translate Class Reference final
Translate text (by Google API, mobile version)
#include "Translate.h"
Inherits xl::package::IRestClient.
Public Member Functions
void_t run (std::ctstring_t &textFrom, std::tstring_t *textToBrief, std::tstring_t *textToDetail, std::tstring_t *textToRaw, std::tstring_t *langFrom, std::tstring_t *langTo)
translate text
ctors, dtor
Translate ()=default
virtual ~Translate ()=default
xNO_COPY_ASSIGN (Translate)
Public Member Functions inherited from xl::package::IRestClient
IRestClient ()=default
virtual ~IRestClient ()=default
xNO_COPY_ASSIGN (IRestClient)
Additional Inherited Members
Protected Attributes inherited from xl::package::IRestClient
std::size_t _version {}
std::map_tstring_t _credentials
fs::Config _config
log::FileLog _log
std::tstring_t _dirTmp
curl::HttpClient _http {false}
Detailed Description
Translate text (by Google API, mobile version)
Constructor & Destructor Documentation
Translate()
xl::package::Translate::Translate () default
~Translate()
virtual xl::package::Translate::~Translate () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::package::Translate::xNO_COPY_ASSIGN (Translate)
run()
void_t xl::package::Translate::run (std::ctstring_t & a_textFrom, std::tstring_t * out_textToBrief, std::tstring_t * out_textToDetail, std::tstring_t * out_textToRaw, std::tstring_t * out_langFrom, std::tstring_t * out_langTo)
translate text
HTTP POST request:
<form action="/m" class="">
    ...
    <input type="hidden" name="hl" value="ru"/>
    <input type="hidden" name="sl" value="auto"/>
    <input type="hidden" name="tl" value="ru"/>
    <input type="hidden" name="ie" value="UTF-8"/>
    <input type="hidden" name="prev" value="_m"/>
    <input type="text"   name="q" style="width:65%" maxlength="2048" value="волк"/><br>
    <input type="submit" value="Перевести"/>
</form>
Google Translate query params
https://stackoverflow.com/questions/26714426/what-is-the-meaning-of-google-translate-query-params
sl - source language code (auto for autodetection) tl - translation language hl - host language q - source text / word ie - input encoding (a guess) oe - output encoding (a guess) dt - may be included more than once and specifies what to return in the reply
Here are some values for dt. If the value is set, the following data will be returned:
t - translation of source text at - alternate translations rm - transcription / transliteration of source and translated texts bd - dictionary, in case source text is one word (you get translations with articles, reverse translations, etc.) md - definitions of source text, if it's one word ss - synonyms of source text, if it's one word ex - examples rw - See also list dj - Json response with names (dj=1)
Parameters
a_textFrom source text
[out] out_textToBrief target brief translate
[out] out_textToDetail target detail translate
[out] out_textToRaw target raw translate (HTML) (maybe nullptr)
[out] out_langFrom from language ISO code
[out] out_langTo to language ISO code
{
    xTEST(!a_textFrom.empty());
    xTEST_PTR(out_textToBrief);
    xTEST_PTR(out_textToDetail);
    xTEST_NA(out_textToRaw);
    xTEST_PTR(out_langFrom);
    xTEST_PTR(out_langTo);
    bool_t bRv {};
    curl::OptionIn dataIn;
    {
        std::ctstring_t encoding = xT("UTF-8");
       /**
        * HTTP POST request:
        *
        * \code{.html}
        * <form action="/m" class="">
        *     ...
        *     <input type="hidden" name="hl" value="ru"/>
        *     <input type="hidden" name="sl" value="auto"/>
        *     <input type="hidden" name="tl" value="ru"/>
        *     <input type="hidden" name="ie" value="UTF-8"/>
        *     <input type="hidden" name="prev" value="_m"/>
        *     <input type="text"   name="q" style="width:65%" maxlength="2048" value="волк"/><br>
        *     <input type="submit" value="Перевести"/>
        * </form>
        * \endcode
        */
        dataIn.url            = xT("https://translate.google.com/m");
        dataIn.accept         = xT("text/html");
        dataIn.acceptEncoding = xT("gzip, deflate");
        dataIn.acceptLanguage = xT("en-us,en");
        dataIn.acceptCharset  = encoding;
        // TODO: curl::HttpClient::Request::Post
    #if 0
        std::map_tstring_t headers
        {
            {"content-type", "application/x-www-form-urlencoded"}
        };
        dataIn.addHeaders = headers;
    #endif
        // dataIn.request
        {
           /**
            * Google Translate query params
            *
            * https://stackoverflow.com/questions/26714426/what-is-the-meaning-of-google-translate-query-params
            *
            * sl - source language code (auto for autodetection)
            * tl - translation language
            * hl - host language
            * q  - source text / word
            * ie - input encoding (a guess)
            * oe - output encoding (a guess)
            * dt - may be included more than once and specifies what to return in the reply
            *
            * Here are some values for dt. If the value is set, the following data will be returned:
            *
            * t  - translation of source text
            * at - alternate translations
            * rm - transcription / transliteration of source and translated texts
            * bd - dictionary, in case source text is one word (you get translations with articles,
            *      reverse translations, etc.)
            * md - definitions of source text, if it's one word
            * ss - synonyms of source text, if it's one word
            * ex - examples
            * rw - See also list
            * dj - Json response with names (dj=1)
            */
            Language langFrom {};
            Language langTo {};
            _langsDetect(a_textFrom, &langFrom, &langTo);
            std::ctstring_t  sourceLang   = (langFrom == Language::Unknown) ?
                xT("auto") : _langCode(langFrom);
            std::ctstring_t  targetLang   = _langCode(langTo);
            std::ctstring_t  hostLang     = xT("en");
            std::csize_t     querySizeMax = 2048;
            std::ctstring_t &query        = a_textFrom;
            std::ctstring_t  encodingIn   = encoding;
            std::ctstring_t  encodingOut  = encoding;
            xCHECK_DO(query.size() > querySizeMax,
                Cout() << xT("Warning: ") << xTRACE_VAR_2(querySizeMax, query.size()));
            const std::map_tstring_t request
            {
                {xT("sl"), sourceLang},
                {xT("tl"), targetLang},
                {xT("hl"), hostLang},
                {xT("ie"), encodingIn},
                {xT("oe"), encodingOut},
                {xT("q"),  query}
            };
            // Cout() << xTRACE_VAR(request);
            for (const auto &[param, value] : request) {
                dataIn.request += param + xT("=") + _http.escape(value) + xT("&");
            }
            dataIn.request = String::trimRightChars(dataIn.request, xT("&"));
            // [out]
            *out_langFrom = sourceLang;
            *out_langTo   = targetLang;
        }
    }
    // TODO: curl::HttpClient::Request::Post
    curl::OptionOut dataOut;
    bRv = _http.get(dataIn, &dataOut);
    xTEST(bRv);
    if ( !_http.isSuccess(dataOut) ) {
        // Cout() << xTRACE_VAR(dataOut.body);
        *out_textToBrief  = Format::str(xT("Error: {}"), dataOut.responseCode);
        *out_textToDetail = Format::str(xT("Error: {}"), dataOut.responseCode);
        if (out_textToRaw != nullptr) {
            *out_textToRaw = Format::str(xT("Error: {}"), dataOut.responseCode);
        }
        return;
    }
    xTEST(!dataOut.headers.empty());
    xTEST(!dataOut.body.empty());
#if 0
    Cout()
        << xTRACE_VAR(dataIn.request)   << std::endl
        << xT("\n")
        << xTRACE_VAR(dataOut.contentType)  << std::endl
        << xTRACE_VAR(dataOut.effectiveUrl) << std::endl
        << xTRACE_VAR(dataOut.responseCode) << std::endl
        << xTRACE_VAR(dataOut.totalTimeSec) << std::endl
        << xT("\n")
        << xTRACE_VAR(dataOut.headers)      << std::endl
        << xTRACE_VAR(dataOut.body.size())  << std::endl
        << xTRACE_VAR(dataOut.body)         << std::endl;
#endif
     _responseParse(dataOut, out_textToBrief, out_textToDetail, out_textToRaw);
}
References xl::package::IRestClient::_http, xl::package::curl::OptionIn::accept, xl::package::curl::OptionIn::acceptCharset, xl::package::curl::OptionIn::acceptEncoding, xl::package::curl::OptionIn::acceptLanguage, xl::package::curl::OptionIn::addHeaders, xl::package::curl::OptionOut::body, xl::package::curl::OptionOut::contentType, xl::package::curl::OptionOut::effectiveUrl, xl::package::curl::Client::escape(), xl::package::curl::HttpClient::get(), xl::package::curl::OptionOut::headers, xl::package::curl::HttpClient::isSuccess(), xl::package::curl::OptionIn::request, xl::package::curl::OptionOut::responseCode, xl::core::FormatT< StreamT >::str(), xl::package::curl::OptionOut::totalTimeSec, xl::core::String::trimRightChars(), xl::package::curl::OptionIn::url, xCHECK_DO, xT, xTEST, xTEST_NA, xTEST_PTR, xTRACE_VAR, and xTRACE_VAR_2.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Translate.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Translate.cpp