xLib: xl::system::Console Class Reference
xl::system::Console Class Reference
Shell console.
#include "Console.h"
Public Types
enum class Foreground {
Unknown = 0 , Default , Black , Red ,
Green , Yellow , Blue , Magenta ,
Cyan , White , Gray
}
foreground (text) color
enum class Background {
Unknown = 0 , Default , Black , Red ,
Green , Yellow , Blue , Magenta ,
Cyan , White , Gray
}
background color
enum class Attribute {
Unknown = 0 , AllOff , Bold , Dim ,
Underline , Blink , Reverse , Hidden
}
text attribute
Public Member Functions
xUSING_CONST (Foreground)
xUSING_CONST (Background)
xUSING_CONST (Attribute)
std::tstring_t setAttributes (cForeground foreground, cBackground background, cint_t attributes) const
set text color
std::tstring_t clearAttributes () const
reset text color to default
std::tstring_t setAttributesText (cForeground foreground, cBackground background, cint_t attributes, std::ctstring_t &str) const
set text color, text, reset text color to default
std::tstring_t read () const
read
void_t write (std::ctstring_t &str) const
write
void_t writeLine (std::ctstring_t &str={}) const
write line
void_t writeErrLine (std::ctstring_t &str) const
write error message
void_t write (cForeground foreground, cBackground background, cint_t attributes, std::ctstring_t &str) const
write with colors
void_t writeLine (cForeground foreground, cBackground background, cint_t attributes, std::ctstring_t &str) const
write with colors
void_t writeNl () const
write new line (NL)
void_t pause (culong_t &timeoutMsec) const
pause with timeout (msec)
void_t clear () const
clear
void_t setTitle (std::ctstring_t &title) const
set title string
ctors, dtor
Console ()
virtual ~Console ()
options
void setEscapeValues (cbool_t flag)
escaping values (UNIX only)
Private Member Functions
FILE * _getStdStream (std::ctostream_t &stream) const
Since C++ hasn't a true way to extract stream handler from the a given std::ostream
bool_t _isColorized (std::tostream_t &stream=std::cout) const
bool_t _isAtty (std::ctostream_t &stream) const
Test whether a given std::ostream object refers to a terminal.
std::tstring_t _escapeValue (std::ctstring_t &value) const
escape by "\[...\]"
void_t _destruct_impl ()
std::tstring_t _setAttributes_impl (cForeground foreground, cBackground background, cint_t attributes) const
std::tstring_t _clearAttributes_impl () const
std::tstring_t _read_impl () const
void_t _write_impl (std::ctstring_t &str) const
void_t _clear_impl () const
void_t _setTitle_impl (std::ctstring_t &title) const
Private Attributes
bool_t _isColorSupport {}
Say whether a given stream should be colorized or not.
bool_t _isEscapeValues {}
escaping values
xPLATFORM_IMPL __pad0__: void_t _construct_impl()
Detailed Description
Shell console.
Definition at line 19 of file Console.h.
Member Enumeration Documentation
Attribute
enum xl::system::Console::Attribute strong
text attribute
Enumerator
Unknown
Unknown.
AllOff
Reset all attributes.
Bold
Bold/Bright.
Dim
Dim.
Underline
Underlined.
Blink
Blink (not work with most of the terminal emulators)
Reverse
Invert the foreground and background colors.
Hidden
Hidden (useful for passwords)
Definition at line 78 of file Console.h.
     {
         Unknown = 0,
         AllOff,
         Bold,
         Dim,
         Underline,
         Blink,
         Reverse,
         Hidden
     };
Member Function Documentation
_isColorized()
bool_t xl::system::Console::_isColorized (std::tostream_t & stream = std::cout) const private
Say whether a given stream should be colorized or not. It's always true for ATTY streams and may be true for streams marked with colorize flag
Definition at line 248 of file Console.cpp.
 {
     // An index to be used to access a private storage of I/O streams. See
     // colorize / nocolorize I/O manipulators for details.
     static const int colorizeIndex = std::ios_base::xalloc();
     if ( static_cast<bool_t>(a_stream.iword(colorizeIndex)) ) {
         return true;
     }
     if ( _isAtty(a_stream) ) {
         return true;
     }
     return false;
 }
References _isAtty().
_setAttributes_impl()
std::tstring_t xl::system::Console::_setAttributes_impl (cForeground a_foreground, cBackground a_background, cint_t a_attributes) const private
Colors and formatting (ANSI/VT100 Control sequences)
https://misc.flogisoft.com/bash/tip_colors_and_formatting
#define COLOR_BLACK 0 #define COLOR_BLUE 1 #define COLOR_GREEN 2 #define COLOR_AQUA 3 #define COLOR_RED 4 #define COLOR_PURPLE 5 #define COLOR_YELLOW 6 #define COLOR_WHITE 7 #define COLOR_GRAY 8 #define COLOR_LTBLUE 9 #define COLOR_LTGREEN A #define COLOR_LTAQUA B #define COLOR_LTRED C #define COLOR_LTPURPLE D #define COLOR_LTYELLOW E #define COLOR_LTWHITE F
Definition at line 39 of file Console_unix.inl.
 {
     std::tstring_t sRv;
     Foreground foregroundColor {};
     {
         cint_t foregroundColorDefault = 39;
         cint_t foregroundColorBlack   = 30;
         cint_t foregroundColorRed     = 31;
         cint_t foregroundColorBlue    = 34;
         cint_t foregroundColorGreen   = 32;
         cint_t foregroundColorCyan    = 36;
         cint_t foregroundColorMagenta = 35;
         cint_t foregroundColorYellow  = 33;
         cint_t foregroundColorWhite   = 37;
         cint_t foregroundColorGray    = 37;  // TODO: [skynowa] Console::setAttributes() - foregroundColorGray
         int_t iRv {};
         switch (a_foreground) {
         case Foreground::Default:
             iRv = foregroundColorDefault;
             break;
         case Foreground::Black:
             iRv = foregroundColorBlack;
             break;
         case Foreground::Red:
             iRv = foregroundColorRed;
             break;
         case Foreground::Green:
             iRv = foregroundColorGreen;
             break;
         case Foreground::Yellow:
             iRv = foregroundColorYellow;
             break;
         case Foreground::Blue:
             iRv = foregroundColorBlue;
             break;
         case Foreground::Magenta:
             iRv = foregroundColorMagenta;
             break;
         case Foreground::Cyan:
             iRv = foregroundColorCyan;
             break;
         case Foreground::White:
             iRv = foregroundColorWhite;
             break;
         case Foreground::Gray:
             iRv = foregroundColorGray;
             break;
         case Foreground::Unknown:
         default:
             xTEST_FAIL;
             break;
         }
         foregroundColor = static_cast<Foreground>( iRv );
     }
     Background backgroundColor {};
     {
         cint_t backgroundColorDefault = 49;
         cint_t backgroundColorBlack   = 40;
         cint_t backgroundColorRed     = 41;
         cint_t backgroundColorBlue    = 44;
         cint_t backgroundColorGreen   = 42;
         cint_t backgroundColorCyan    = 46;
         cint_t backgroundColorMagenta = 45;
         cint_t backgroundColorYellow  = 43;
         cint_t backgroundColorWhite   = 47;
         cint_t backgroundColorGray    = 47; // TODO: [skynowa] Console::setAttributes() - Unix - backgroundColorGray
         int_t iRv {};
         switch (a_background) {
         case Background::Default:
             iRv = backgroundColorDefault;
             break;
         case Background::Black:
             iRv = backgroundColorBlack;
             break;
         case Background::Red:
             iRv = backgroundColorRed;
             break;
         case Background::Green:
             iRv = backgroundColorGreen;
             break;
         case Background::Yellow:
             iRv = backgroundColorYellow;
             break;
         case Background::Blue:
             iRv = backgroundColorBlue;
             break;
         case Background::Magenta:
             iRv = backgroundColorMagenta;
             break;
         case Background::Cyan:
             iRv = backgroundColorCyan;
             break;
         case Background::White:
             iRv = backgroundColorWhite;
             break;
         case Background::Gray:
             iRv = backgroundColorGray;
             break;
         case Background::Unknown:
         default:
             xTEST_FAIL;
             break;
         }
         backgroundColor = static_cast<Background>( iRv );
     }
     std::tstring_t attrs;
     {
         // Terminals allow attribute combinations.
         // The attributes must be separated by a semicolon (;).
         std::vec_tstring_t values;
         cint_t attributeAllOff    = 0;
         cint_t attributeBold      = 1;
         cint_t attributeDim       = 2;
         cint_t attributeUnderline = 4;
         cint_t attributeBlink     = 5;
         cint_t attributeReverse   = 7;
         cint_t attributeHidden    = 8;
         Bitset bits(a_attributes);
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::AllOff)),    values.push_back( std::to_string(attributeAllOff) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Bold)),      values.push_back( std::to_string(attributeBold) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Dim)),       values.push_back( std::to_string(attributeDim) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Underline)), values.push_back( std::to_string(attributeUnderline) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Blink)),     values.push_back( std::to_string(attributeBlink) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Reverse)),   values.push_back( std::to_string(attributeReverse) ));
         xCHECK_DO(bits.isSetBit(static_cast<int_t>(Attribute::Hidden)),    values.push_back( std::to_string(attributeHidden) ));
         attrs = String::join(values, xT(';'));
     }
     sRv += _escapeValue( Format::str(xT("\033[{};{}m"), attrs, static_cast<int>(foregroundColor)) ); // TODO: [skynowa] StdStreamV2
     sRv += _escapeValue( Format::str(xT("\033[{}m"), static_cast<int>(backgroundColor)) );           // TODO: [skynowa] StdStreamV2
     return sRv;
 }
_setTitle_impl()
void_t xl::system::Console::_setTitle_impl (std::ctstring_t & a_title) const private
Change the title of a terminal
https://www.zachpfeffer.com/single-post/Change-the-title-of-a-terminal-on-Ubuntu-1604
set-title() { ORIG=$PS1 TITLE="\033]2;$@\a" PS1=${ORIG}${TITLE} }
ESC]0;stringBEL - Set icon name and window title to string ESC]1;stringBEL - Set icon name to string ESC]2;stringBEL - Set window title to string
Icons: https://unicode.org/emoji/charts/full-emoji-list.html https://apps.timwhitlock.info/emoji/tables/unicode
Definition at line 242 of file Console_unix.inl.
 {
     write( _escapeValue(Format::str(xT("\033]0;{}\a"), a_title)) );
 }
References _escapeValue(), and write().
Referenced by setTitle().
write()
void_t xl::system::Console::write (cForeground foreground, cBackground background, cint_t attributes, std::ctstring_t & str) const
write with colors
Unix vs Windows implementation
Use sequence of write() methods, instead of concat strings
Definition at line 141 of file Console.cpp.
 {
     write( setAttributes(a_foreground, a_background, a_attributes) );
     write(a_str);
     write( clearAttributes() );
 }
References clearAttributes(), setAttributes(), and write().
The documentation for this class was generated from the following files:
/home/skynowa/Projects/xLib/Include/xLib/System/Console.h
/home/skynowa/Projects/xLib/Include/xLib/System/Console.cpp
/home/skynowa/Projects/xLib/Include/xLib/System/Platform/Unix/Console_unix.inl
/home/skynowa/Projects/xLib/Include/xLib/System/Platform/Win/Console_win.inl