xLib: xl::log::Trace Class Reference
xl::log::Trace Class Reference final
Tracing to debugger, std::cout.
#include "Trace.h"
Inherits xl::log::ILog.
Public Member Functions
ctors, dtor
Trace ()=default
virtual ~Trace ()
operators
template<typename T >
Trace & operator<< (const T &valueT)
Overrides
void_t write (cptr_ctchar_t format,...) const final
write to log
void_t write (cLevel level, cptr_ctchar_t format,...) const final
write to log
Public Member Functions inherited from xl::log::ILog
void_t setEnabled (cbool_t flag)
set enabled
bool_t isEnabled () const
set enabled
ILog ()=default
virtual ~ILog ()=0
xNO_COPY_ASSIGN (ILog)
Additional Inherited Members
Public Types inherited from xl::log::ILog
enum class Level {
Off = 0 ,
Trace = 1 ,
Debug = 2 ,
Info = 3 ,
Warning = 4 ,
Error = 5 ,
Fatal = 6
}
log level
Protected Member Functions inherited from xl::log::ILog
std::tstring_t _levelString (cLevel level) const
Protected Attributes inherited from xl::log::ILog
std::tostringstream_t _oss
string stream
Detailed Description
Tracing to debugger, std::cout.
Constructor & Destructor Documentation
Trace()
xl::log::Trace::Trace () default
~Trace()
xl::log::Trace::~Trace () virtual
{
    write(xT("%s"), _oss.str().c_str());
}
References xl::log::ILog::_oss, write(), and xT.
Member Function Documentation
operator<<()
template<typename T > Trace & xl::log::Trace::operator<< (const T & valueT)
{
    _oss << a_valueT;
    return *this;
}
References xl::log::ILog::_oss.
write() [1/2]
void_t xl::log::Trace::write (cptr_ctchar_t format, ...) const final virtual
write to log
Implements xl::log::ILog.
{
    xCHECK_DO(!isEnabled(),          return);
    xCHECK_DO(a_format == nullptr, return);
    std::tstring_t msg;
    va_list args;
    xVA_START(args, a_format);
    msg = FormatC::strV(a_format, args);
    xVA_END(args);
    write(Level::Trace, xT("%s"), msg.c_str());
}
References xl::log::ILog::isEnabled(), xl::core::FormatC::strV(), xl::log::ILog::Trace, write(), xCHECK_DO, and xT.
Referenced by write(), and ~Trace().
write() [2/2]
void_t xl::log::Trace::write (cLevel level, cptr_ctchar_t format, ...) const final virtual
write to log
Implements xl::log::ILog.
{
    xCHECK_DO(!isEnabled(), return);
    std::tstring_t msg;
    {
        va_list args;
        xVA_START(args, a_format);
        msg = FormatC::strV(a_format, args);
        xVA_END(args);
        if (a_level != Level::Trace) {
            msg = _levelString(a_level) + xT(": ") + msg;
        }
    }
    _write_impl(msg);
}
References xl::log::ILog::_levelString(), xl::log::ILog::isEnabled(), xl::core::FormatC::strV(), xl::log::ILog::Trace, xCHECK_DO, and xT.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/Trace.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/Trace.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Log/Trace.inl