xLib: xl::system::info::Os Class Reference
xl::system::info::Os Class Reference
OS information.
#include "Os.h"
Public Types
enum class Type {
Unknown ,
Windows3 ,
Windows95 ,
Windows98 ,
WindowsNT ,
Windows2000 ,
WindowsXP ,
WindowsXPProx64Edition ,
WindowsServer2003 ,
WindowsHomeServer ,
WindowsServer2003R2 ,
WindowsVista ,
WindowsServer2008 ,
WindowsServer2008R2 ,
Windows7 ,
Linux ,
FreeBSD ,
Mac
}
OS type.
enum class Arch {
Unknown ,
Bit32 ,
Bit64
}
OS architecture.
Public Member Functions
Type os () const
get information about the current OS
std::tstring_t formatOs () const
format OS type
std::tstring_t distro () const
distributive info
Arch arch () const
get OS architecture
std::tstring_t formatArch () const
format get OS architecture
std::tstring_t desktopName () const
desktop environments
ctors, dtor
Os ()=default
virtual ~Os ()=default
xNO_COPY_ASSIGN (Os)
Detailed Description
OS information.
Member Enumeration Documentation
Type
enum class xl::system::info::Os::Type strong
OS type.
Enumerator
Unknown
Windows3
Windows95
Windows98
WindowsNT
Windows2000
WindowsXP
WindowsXPProx64Edition
WindowsServer2003
WindowsHomeServer
WindowsServer2003R2
WindowsVista
WindowsServer2008
WindowsServer2008R2
Windows7
Linux
FreeBSD
Mac
    {
        Unknown,
        // windows family
        Windows3,
        Windows95,
        Windows98,
        WindowsNT,
        Windows2000,
        WindowsXP,
        WindowsXPProx64Edition,
        WindowsServer2003,
        WindowsHomeServer,
        WindowsServer2003R2,
        WindowsVista,
        WindowsServer2008,
        WindowsServer2008R2,
        Windows7,
        // Linux  family
        Linux,
        // BSD family
        FreeBSD,
        // Apple family
        Mac
    };
Arch
enum class xl::system::info::Os::Arch strong
OS architecture.
Enumerator
Unknown
Bit32
Bit64
    {
        Unknown,
        Bit32,
        Bit64
    };
Constructor & Destructor Documentation
Os()
xl::system::info::Os::Os () default
~Os()
virtual xl::system::info::Os::~Os () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::info::Os::xNO_COPY_ASSIGN (Os)
os()
Os::Type xl::system::info::Os::os () const
get information about the current OS
{
    return _os_impl();
}
formatOs()
std::tstring_t xl::system::info::Os::formatOs () const
format OS type
{
    return _formatOs_impl();
}
distro()
std::tstring_t xl::system::info::Os::distro () const
distributive info
{
    return _distro_impl();
}
arch()
Os::Arch xl::system::info::Os::arch () const
get OS architecture
{
    return _arch_impl();
}
Referenced by formatArch().
formatArch()
std::tstring_t xl::system::info::Os::formatArch () const
format get OS architecture
{
    std::tstring_t sRv = Const::strUnknown();
    cArch arch_ = arch();
    switch (arch_) {
    case Arch::Bit32:
        sRv = xT("32-bit");
        break;
    case Arch::Bit64:
        sRv = xT("64-bit");
        break;
    case Arch::Unknown:
        sRv = Const::strUnknown();
        break;
    }
    return sRv;
}
References arch(), Bit32, Bit64, xl::core::Const::strUnknown(), Unknown, and xT.
desktopName()
std::tstring_t xl::system::info::Os::desktopName () const
desktop environments
{
    return _desktopName_impl();
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Info/Os.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Info/Os.cpp