xLib: xl::db::mysql::StoreResult Class Reference
xl::db::mysql::StoreResult Class Reference final
Recordset.
#include "Result.h"
Inherits xl::db::mysql::IResult.
Public Member Functions
ctors, dtor
StoreResult (const Connection &connection)
virtual ~StoreResult ()=default
xNO_DEFAULT_CONSTRUCT (StoreResult)
xNO_COPY_ASSIGN (StoreResult)
Public Member Functions inherited from xl::db::mysql::IResult
HandleMySqlResult & get ()
get handle
std::size_t fields () const
number of columns in a result set / connection
std::uint64_t rows () const
number of rows in the result set / connection
IResult (const Connection &connection)
virtual ~IResult ()=0
xNO_DEFAULT_CONSTRUCT (IResult)
xNO_COPY_ASSIGN (IResult)
MYSQL_FIELD * fetchField () const
The MYSQL_FIELD structure for the current column.
void_t fetchFieldDirect (cuint_t fieldNumber, MYSQL_FIELD *field) const
The MYSQL_FIELD structure for the specified column.
MYSQL_FIELD * fetchFields () const
An array of MYSQL_FIELD structures for all columns of a result set.
void_t fetchRow (row_t *row) const
fetching row
void_t fetchRows (rows_t *rows) const
fetching rows
Additional Inherited Members
Protected Member Functions inherited from xl::db::mysql::IResult
MYSQL_ROW _fetchRow () const
A MYSQL_ROW structure for the next row.
culong_t * _fetchLengths () const
An array of unsigned long_t integers representing the size of each column.
Protected Attributes inherited from xl::db::mysql::IResult
const Connection * _conn {}
pointer to connection object
HandleMySqlResult _result
result of a query that returns row
Detailed Description
Recordset.
Constructor & Destructor Documentation
StoreResult()
xl::db::mysql::StoreResult::StoreResult (const Connection & a_connection) explicit
Retrieves all the rows immediately (small result)
Return NULL if:
There was a malloc() failure (for example, if the result set was too large).
The data could not be read (an error occurred on the connection).
The query returned no data (for example, it was an INSERT, UPDATE, or DELETE).
🔗 See also:
https://dev.mysql.com/doc/c-api/8.0/en/null-mysql-store-result.html https://dev.mysql.com/doc/c-api/8.0/en/mysql-field-count.html
Parameters
a_connection connection
  :
    IResult(a_connection)
{
   /**
    * Retrieves all the rows immediately (small result)
    *
    * Return NULL if:
    *
    * - There was a malloc() failure (for example, if the result set was too large).
    * - The data could not be read (an error occurred on the connection).
    * - The query returned no data (for example, it was an INSERT, UPDATE, or DELETE).
    *
    * \see https://dev.mysql.com/doc/c-api/8.0/en/null-mysql-store-result.html
    *      https://dev.mysql.com/doc/c-api/8.0/en/mysql-field-count.html
    */
    _result = ::mysql_store_result( _conn->get().get() );
    xTEST_MSG(_result.isValid(), Error(*_conn).str());
}
References xl::db::mysql::IResult::_conn, xl::db::mysql::IResult::_result, xl::db::mysql::Connection::get(), xl::core::Handle< T, typeT >::isValid(), xl::interface_::IError< CodeT >::str(), and xTEST_MSG.
~StoreResult()
virtual xl::db::mysql::StoreResult::~StoreResult () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::StoreResult::xNO_DEFAULT_CONSTRUCT (StoreResult)
xNO_COPY_ASSIGN()
xl::db::mysql::StoreResult::xNO_COPY_ASSIGN (StoreResult)
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Result.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Result.cpp