xLib: xl::fs::Config Class Reference
xl::fs::Config Class Reference
config file
#include "Config.h"
Inherits xl::interface_::IGetRef< std::map_tstring_t >.
Public Member Functions
ctors, dtor
Config ()
Config (std::ctstring_t &filePath)
virtual ~Config ()
xNO_COPY_ASSIGN (Config)
Overrides
std::map_tstring_t & get () final
getter
File's
void_t read ()
parse file
void_t write () const
write
void_t writeDefault (std::cmap_tstring_t &content)
write default file
void_t clear ()
clear content
void_t remove ()
delete
Key's
bool_t keyIsExists (std::ctstring_t &key) const
is exists
void_t keyClear (std::ctstring_t &key)
clear value
void_t keyDelete (std::ctstring_t &key)
delete key and value
Get/set values
template<typename T >
T value (std::ctstring_t &key, const T defaultValue)
template<typename T >
void_t setValue (std::ctstring_t &key, const T value)
Public Member Functions inherited from xl::interface_::IGetRef< std::map_tstring_t >
IGetRef ()=default
virtual ~IGetRef ()=default
Detailed Description
config file
Constructor & Destructor Documentation
Config() [1/2]
xl::fs::Config::Config ()
               :
    Config( Path::exe().str() )
{
}
Config() [2/2]
xl::fs::Config::Config (std::ctstring_t & filePath) explicit
  :
    _fileInfo (a_filePath),
    _file     (a_filePath),
    _separator(Const::equal())
{
    xTEST(!a_filePath.empty());
    xTEST(!_separator.empty());
}
References xTEST.
~Config()
xl::fs::Config::~Config () virtual
{
    write();
}
References write().
Member Function Documentation
xNO_COPY_ASSIGN()
xl::fs::Config::xNO_COPY_ASSIGN (Config)
get()
std::map_tstring_t & xl::fs::Config::get () final virtual
getter
Implements xl::interface_::IGetRef< std::map_tstring_t >.
{
    return _config;
}
Referenced by xl::system::Envs::setVars().
read()
void_t xl::fs::Config::read ()
parse file
{
    xCHECK_DO(!_fileInfo.isExists(), return);
    _file.read(_separator, &_config);
    _config.erase(Const::strEmpty());
}
References xl::fs::FileInfo::isExists(), xl::fs::FileText::read(), xl::core::Const::strEmpty(), and xCHECK_DO.
Referenced by xl::db::mysql::Options::Options(), and xl::system::Envs::setVars().
write()
void_t xl::fs::Config::write () const
write
{
    xCHECK_DO(_config.empty(), return);
    _file.write(_separator, _config, FileIO::OpenMode::Write);
}
References xl::fs::FileIO::Write, xl::fs::FileText::write(), and xCHECK_DO.
Referenced by writeDefault(), and ~Config().
writeDefault()
void_t xl::fs::Config::writeDefault (std::cmap_tstring_t & content)
write default file
{
    xTEST_NA(a_content);
    _config = a_content;
    write();
}
References write(), and xTEST_NA.
clear()
void_t xl::fs::Config::clear ()
clear content
{
    _config.clear();
    File file(_fileInfo);
    file.clear();
}
References xl::fs::File::clear().
remove()
void_t xl::fs::Config::remove ()
delete
{
    _config.clear();
    File file(_fileInfo);
    file.remove();
}
References xl::fs::File::remove().
keyIsExists()
bool_t xl::fs::Config::keyIsExists (std::ctstring_t & key) const
is exists
{
    return _config.contains(a_key);
}
keyClear()
void_t xl::fs::Config::keyClear (std::ctstring_t & key)
clear value
{
    xTEST(!a_key.empty());
    setValue(a_key, std::tstring_t());
}
References setValue(), and xTEST.
keyDelete()
void_t xl::fs::Config::keyDelete (std::ctstring_t & key)
delete key and value
{
    xTEST(!a_key.empty());
    _config.erase(a_key);
}
References xTEST.
value()
template<typename T > T xl::fs::Config::value (std::ctstring_t & key, const T defaultValue) inline
{
    xTEST(!a_key.empty());
    xTEST_NA(a_defaultValue);
    const auto it = _config.find(a_key);
    if (it == _config.cend()) {
        return a_defaultValue;
    }
    const auto &value = it->second;
    if      constexpr (std::is_same_v<T, bool_t>) {
        return String::castBool(value);
    }
    else if constexpr (std::is_same_v<T, ctchar_t *>) {
        return value.c_str();
    }
    else if constexpr (std::is_same_v<T, std::tstring_t>) {
        return String::cast<T>(value);
    }
    else if constexpr (std::is_same_v<T, std::ustring_t>) {
        std::ctstring_t hex = String::cast(value, 16);
        return T{hex.cbegin(), hex.cend()};
    }
    else {
        return String::cast<T>(value);
    }
}
References xl::core::String::cast(), xl::core::String::castBool(), value(), xTEST, and xTEST_NA.
Referenced by xl::db::mysql::Options::Options(), setValue(), and value().
setValue()
template<typename T > void_t xl::fs::Config::setValue (std::ctstring_t & key, const T value) inline
{
    xTEST(!a_key.empty());
    xTEST_NA(a_value);
    std::tstring_t value;
    if      constexpr (std::is_integral_v<T>) {
        value = std::to_string(a_value);
    }
    else if constexpr (std::is_same_v<T, bool_t>) {
        value = String::castBool(a_value);
    }
    else if constexpr (std::is_floating_point_v<T>) {
        value = std::to_string(a_value);
    }
    else if constexpr (std::is_same_v<T, ctchar_t *>) {
        value = a_value;
    }
    else if constexpr (std::is_same_v<T, std::tstring_t>) {
        value = a_value;
    }
    else if constexpr (std::is_same_v<T, std::ustring_t>) {
        value = String::cast( std::tstring_t(a_value.cbegin(), a_value.cend()), 16);
    }
    else {
        Cout() << xTRACE_VAR(a_value);
        value = a_value;
    }
    // [out]
    _config[a_key] = value;
}
References xl::core::String::cast(), xl::core::String::castBool(), value(), xTEST, xTEST_NA, and xTRACE_VAR.
Referenced by keyClear().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Config.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Config.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Config.inl