xLib: xl::sync::AutoIpcMutex Class Reference
xl::sync::AutoIpcMutex Class Reference
auto mutex
#include "AutoIpcMutex.h"
Public Member Functions
ctors, dtor
AutoIpcMutex (IpcMutex &mutex, std::ctstring_t &name)
virtual ~AutoIpcMutex ()
xNO_COPY_ASSIGN (AutoIpcMutex)
Detailed Description
auto mutex
Constructor & Destructor Documentation
AutoIpcMutex()
xl::sync::AutoIpcMutex::AutoIpcMutex (IpcMutex & mutex, std::ctstring_t & name)
  :
    _mutex(a_mutex)
{
    _mutex.create(a_name);
    _mutex.lock(xTIMEOUT_INFINITE);
}
References xl::sync::IpcMutex::create(), xl::sync::IpcMutex::lock(), and xTIMEOUT_INFINITE.
~AutoIpcMutex()
xl::sync::AutoIpcMutex::~AutoIpcMutex () virtual
{
    _mutex.unlock();
}
References xl::sync::IpcMutex::unlock().
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::AutoIpcMutex::xNO_COPY_ASSIGN (AutoIpcMutex)
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AutoIpcMutex.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AutoIpcMutex.cpp