xLib: xl::db::mysql::EscapeQuoted Class Reference
xl::db::mysql::EscapeQuoted Class Reference
Escape with quote (Brief Creates a legal SQL string for use in an SQL statement as qouted)
#include "Query.h"
Public Member Functions
std::tstring_t forQuote (std::ctstring_t &forQuote) const
If the ANSI_QUOTES SQL mode is enabled:
std::tstring_t forSqm () const
std::tstring_t forDqm () const
std::tstring_t forGa () const
ctors, dtor
EscapeQuoted (const Connection &conn, std::ctstring_t &sqlValue)
virtual ~EscapeQuoted ()=default
xNO_DEFAULT_CONSTRUCT (EscapeQuoted)
xNO_COPY_ASSIGN (EscapeQuoted)
Detailed Description
Escape with quote (Brief Creates a legal SQL string for use in an SQL statement as qouted)
Constructor & Destructor Documentation
EscapeQuoted()
xl::db::mysql::EscapeQuoted::EscapeQuoted (const Connection & a_conn, std::ctstring_t & a_sqlValue)
Parameters
a_conn connection
a_sqlValue SQL string value
  :
    _conn    {a_conn},
    _sqlValue{a_sqlValue}
{
    xTEST(_conn.get().isValid());
}
References xl::db::mysql::Connection::get(), and xTEST.
~EscapeQuoted()
virtual xl::db::mysql::EscapeQuoted::~EscapeQuoted () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::EscapeQuoted::xNO_DEFAULT_CONSTRUCT (EscapeQuoted)
xNO_COPY_ASSIGN()
xl::db::mysql::EscapeQuoted::xNO_COPY_ASSIGN (EscapeQuoted)
forQuote()
std::tstring_t xl::db::mysql::EscapeQuoted::forQuote (std::ctstring_t & a_quote) const
If the ANSI_QUOTES SQL mode is enabled:
string literals can be quoted only within single quotation marks because a string quoted within double quotation marks is interpreted as an identifier.
🔗 See also:
https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-escape-string-quote.html
If the argument is NULL:
the return value is the word “NULL” without enclosing single quotation marks
< String (char) in which the escaped string is to be placed
Parameters
a_quote Quote str (char)
{
    xTEST(!a_quote.empty());
    if ( _sqlValue.empty() ) {
        return (a_quote + a_quote);
    }
    if (_sqlValue == nullStr) {
       /**
        * If the argument is NULL:
        *
        * the return value is the word “NULL” without enclosing single quotation marks
        */
        return _sqlValue;
    }
    // escape
    std::tstring_t sRv(_sqlValue.size() * 2 + 1, xT('\0'));
    {
        cchar_t forQuote {xT2A(a_quote)[0]};
            ///< String (char) in which the escaped string is to be placed
        culong_t quotedSize = ::mysql_real_escape_string_quote(_conn.get().get(), &sRv[0],
            _sqlValue.data(), static_cast<ulong_t>(_sqlValue.size()), forQuote);
        xTEST_GR_MSG(quotedSize, 0UL, Error(_conn).str());
        sRv.resize(quotedSize * sizeof(std::tstring_t::value_type));
    }
    // quoted
    {
        sRv = a_quote + sRv + a_quote;
    }
    return sRv;
}
References forQuote(), xl::db::mysql::Connection::get(), xl::db::mysql::nullStr, xT, xT2A, xTEST, and xTEST_GR_MSG.
Referenced by forDqm(), forGa(), forQuote(), and forSqm().
forSqm()
std::tstring_t xl::db::mysql::EscapeQuoted::forSqm () const
{
    return forQuote(Const::sqm());
}
References forQuote().
Referenced by xl::db::mysql::Db::create(), xl::db::mysql::Db::drop(), and xl::db::mysql::Db::isExists().
forDqm()
std::tstring_t xl::db::mysql::EscapeQuoted::forDqm () const
{
    return forQuote(Const::dqm());
}
References forQuote().
forGa()
std::tstring_t xl::db::mysql::EscapeQuoted::forGa () const
{
    return forQuote(Const::ga());
}
References forQuote().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Query.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Query.cpp