xLib: xl::net::TcpClient Class Reference
xl::net::TcpClient Class Reference final
client socket
#include "TcpClient.h"
Inherits xl::net::ISocket.
Public Member Functions
void_t connect (std::ctstring_t &ip, cushort_t &port) const
connecting
void_t ioctl (clong_t &command, ulong_t *args) const
controls the i/o mode
void_t setNonBlockingMode (cbool_t flag) const
set nonblocking mode
void_t timeout (long_t *seconds, long_t *microsec) const
get timeout
void_t setTimeout (clong_t &seconds, clong_t &microsec)
set timeout
ctors, dtor
TcpClient ()
virtual ~TcpClient ()=default
xNO_COPY_ASSIGN (TcpClient)
Public Member Functions inherited from xl::net::ISocket
void_t create (cAddressFamily family, cType type, cProtocol protocol)
creates a socket that is bound to a specific transport service provider
HandleSocket & handle ()
get handle
bool_t isReadable () const
checking for readability
bool_t isWritable () const
checking for writability
void_t assign (csocket_t &handle)
assign to another handle
void_t close ()
close
std::ssize_t send (cptr_ctchar_t buff, std::csize_t &buffSize, cint_t &flags)
send data
void_t sendAll (std::ctstring_t &buff, cint_t &flags)
send data by blocks
std::ssize_t receive (tchar_t *buff, std::csize_t &buffSize, cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags)
receive data
std::tstring_t recvAll (cint_t &flags, std::ctstring_t &delimiter)
receive data to delimiter, includes it
int_t sendBytes (char *buff, std::ssize_t &messageLength)
send bytes
int_t receiveBytes (char *buff, std::ssize_t &stillToReceive)
receive bytes
void_t peerName (std::tstring_t *peerAddr, ushort_t *peerPort)
get address of the peer to which a handle is connected
void_t socketName (std::tstring_t *socketAddr, ushort_t *socketPort)
get local name for a socket
ISocket ()=default
virtual ~ISocket ()=0
xNO_COPY_ASSIGN (ISocket)
Static Public Member Functions
static bool_t isServerAlive (std::ctstring_t &ip, cushort_t &port)
is sever socket available
Static Public Member Functions inherited from xl::net::ISocket
static int_t select (int_t nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, timeval *timeout)
determines the status of one or more sockets, waiting if necessary, to perform synchronous I/O
static int_t nativeError ()
get error status for the last operation that failed
Protected Attributes
timeval _timeout {}
timeout
Protected Attributes inherited from xl::net::ISocket
HandleSocket _handle
socket handle
sa_family_t _family {}
family
std::tstring_t _ip
IP.
ushort_t _port {}
port
Additional Inherited Members
Public Types inherited from xl::net::ISocket
enum class AddressFamily {
afUnix = AF_UNIX ,
afLocal = AF_LOCAL ,
afInet = AF_INET ,
afInet6 = AF_INET6 ,
afIpx = AF_IPX ,
afX25 = AF_X25 ,
afAX25 = AF_AX25 ,
afAtmpvc = AF_ATMPVC ,
afAppletalk = AF_APPLETALK ,
afPacket = AF_PACKET
}
address family
enum class Type {
tpStream = SOCK_STREAM ,
tpDgram = SOCK_DGRAM ,
tpRaw = SOCK_RAW ,
tpRdm = SOCK_RDM ,
tpSeqPacket = SOCK_SEQPACKET
}
type
enum class Protocol {
ptIp = IPPROTO_IP ,
ptHopopts = IPPROTO_HOPOPTS ,
ptIcmp = IPPROTO_ICMP ,
ptIgmp = IPPROTO_IGMP ,
ptIpip = IPPROTO_IPIP ,
ptTcp = IPPROTO_TCP ,
ptEgp = IPPROTO_EGP ,
ptPup = IPPROTO_PUP ,
ptUdp = IPPROTO_UDP ,
ptIdp = IPPROTO_IDP ,
ptIpv6 = IPPROTO_IPV6 ,
ptRouting = IPPROTO_ROUTING ,
ptFragment = IPPROTO_FRAGMENT ,
ptRsvp = IPPROTO_RSVP ,
ptGre = IPPROTO_GRE ,
ptEsp = IPPROTO_ESP ,
ptAH = IPPROTO_AH ,
ptICmpv6 = IPPROTO_ICMPV6 ,
ptNone = IPPROTO_NONE ,
ptDstopts = IPPROTO_DSTOPTS ,
ptPim = IPPROTO_PIM ,
ptComp = IPPROTO_COMP ,
ptSctp = IPPROTO_SCTP ,
ptRaw = IPPROTO_RAW ,
ptMax = IPPROTO_MAX
}
protocol
enum Options {
SOCKET_TIMEOUT = 0 ,
SOCKET_BUFF_SIZE = 32768
}
options
Detailed Description
client socket
Constructor & Destructor Documentation
TcpClient()
xl::net::TcpClient::TcpClient ()
{
    setTimeout(0L, Options::SOCKET_TIMEOUT);
}
References setTimeout(), and xl::net::ISocket::SOCKET_TIMEOUT.
~TcpClient()
virtual xl::net::TcpClient::~TcpClient () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::net::TcpClient::xNO_COPY_ASSIGN (TcpClient)
connect()
void_t xl::net::TcpClient::connect (std::ctstring_t & ip, cushort_t & port) const
connecting
{
    xTEST(_handle.isValid());
    xTEST(!a_ip.empty());
    xTEST((65535 > a_port) && (0 < a_port));
    sockaddr_in sockAddr {};
    sockAddr.sin_family      = static_cast<sa_family_t>(_family);
    sockAddr.sin_addr.s_addr = ::inet_addr( xT2A(a_ip).c_str());
    sockAddr.sin_port        = htons(a_port); // TODO: [skynowa] TcpClient::connect() - htons
    int_t iRv = ::connect(_handle.get(), Utils::reinterpretCastT<sockaddr *>( &sockAddr ),
        sizeof(sockAddr));
    xTEST_DIFF(iRv, xSOCKET_ERROR);
}
References xl::net::ISocket::_family, xl::net::ISocket::_handle, connect(), xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xSOCKET_ERROR, xT2A, xTEST, and xTEST_DIFF.
Referenced by xl::package::Ssh2Client::connect(), connect(), and isServerAlive().
ioctl()
void_t xl::net::TcpClient::ioctl (clong_t & command, ulong_t * args) const
controls the i/o mode
{
    xTEST(_handle.isValid());
    int_t iRv = xIOCTLSOCKET(_handle.get(), static_cast<ulong_t>(a_command), a_args);
    xTEST_DIFF(iRv, xSOCKET_ERROR);
}
References xl::net::ISocket::_handle, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xIOCTLSOCKET, xSOCKET_ERROR, xTEST, and xTEST_DIFF.
setNonBlockingMode()
void_t xl::net::TcpClient::setNonBlockingMode (cbool_t flag) const
set nonblocking mode
{
    _setNonBlockingMode_impl(a_flag);
}
timeout()
void_t xl::net::TcpClient::timeout (long_t * seconds, long_t * microsec) const
get timeout
{
    xTEST_NA(a_seconds);
    xTEST_NA(a_microsec);
    Utils::ptrAssignT(a_seconds,  static_cast<long_t>( _timeout.tv_sec  ));
    Utils::ptrAssignT(a_microsec, static_cast<long_t>( _timeout.tv_usec ));
}
References _timeout, xl::core::Utils::ptrAssignT(), and xTEST_NA.
setTimeout()
void_t xl::net::TcpClient::setTimeout (clong_t & seconds, clong_t & microsec)
set timeout
{
    xTEST_NA(a_seconds);
    xTEST_NA(a_microsec);
    _timeout.tv_sec  = a_seconds;
#if xENV_APPLE
    _timeout.tv_usec = static_cast<int_t>(a_microsec);  /// TODO: review
#else
    _timeout.tv_usec = a_microsec;
#endif
}
References _timeout, and xTEST_NA.
Referenced by TcpClient().
isServerAlive()
bool_t xl::net::TcpClient::isServerAlive (std::ctstring_t & ip, cushort_t & port) static
is sever socket available
{
    xTEST(!a_ip.empty());
    xTEST((65535 > a_port) && (0 < a_port));
    TcpClient client;
    client.create(ISocket::AddressFamily::afInet, ISocket::Type::tpStream, ISocket::Protocol::ptIp);
    sockaddr_in sockAddr {};
    sockAddr.sin_family      = static_cast<sa_family_t>(ISocket::AddressFamily::afInet);
    sockAddr.sin_addr.s_addr = ::inet_addr( xT2A(a_ip).c_str());
    sockAddr.sin_port        = htons(a_port); // TODO: [skynowa] TcpClient::isServerAlive() - htons
    int_t iRv = ::connect(client.handle().get(), Utils::reinterpretCastT<sockaddr *>( &sockAddr ),
        sizeof(sockAddr));
    xTEST_NA(iRv);
    xCHECK_RET(iRv != 0, false);
    return true;
}
References xl::net::ISocket::afInet, connect(), xl::net::ISocket::create(), xl::core::Handle< T, typeT >::get(), xl::net::ISocket::handle(), xl::net::ISocket::ptIp, xl::net::ISocket::tpStream, xCHECK_RET, xT2A, xTEST, and xTEST_NA.
Referenced by xl::package::Ssh2Client::isAlive().
Member Data Documentation
_timeout
timeval xl::net::TcpClient::_timeout {} protected
timeout
{};    ///< timeout
Referenced by setTimeout(), and timeout().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/TcpClient.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Net/TcpClient.cpp