xLib: xl::fs::Backup Class Reference
xl::fs::Backup Class Reference
backuper
#include "Backup.h"
Public Types
enum class Period {
Unknown ,
Hourly ,
Daily ,
Weekly ,
Monthly
}
backup period
enum class Error {
Ok = 0 ,
DestFileNotExists = 1 ,
NotEnoughFreeSpace = 2 ,
CopyFail = 3 ,
DestFileAlreadyExists = 4 ,
PeriodUnknown = 5 ,
Unknown = 6
}
errors codes
Public Member Functions
Error fileExec (std::tstring_t *destFilePath) const
execute file backup
ctors, dtor
Backup (std::ctstring_t &filePath, std::ctstring_t &destDirPath, cPeriod period)
virtual ~Backup ()=default
xNO_DEFAULT_CONSTRUCT (Backup)
xNO_COPY_ASSIGN (Backup)
Detailed Description
backuper
Member Enumeration Documentation
Period
enum class xl::fs::Backup::Period strong
backup period
Enumerator
Unknown
Unknown.
Hourly
File name format: Y-m-d_H (2013-12-21_23)
Daily
File name format: Y-m-d (2013-12-21)
Weekly
File name format: Y_U (2013_01)
Monthly
File name format: Y-m (2013-12)
    {
        Unknown, ///< Unknown
        Hourly,  ///< File name format: %Y-%m-%d_%H (2013-12-21_23)
        Daily,   ///< File name format: %Y-%m-%d (2013-12-21)
        Weekly,  ///< File name format: %Y_%U (2013_01)
        Monthly  ///< File name format: %Y-%m (2013-12)
    };
Error
enum class xl::fs::Backup::Error strong
errors codes
Enumerator
Ok
Success.
DestFileNotExists
Destination file not exists.
NotEnoughFreeSpace
Not enough free space.
CopyFail
Copy fail.
DestFileAlreadyExists
Destination file already exists.
PeriodUnknown
Period unknown.
Unknown
Unknown.
    {
        Ok                    = 0, ///< Success
        DestFileNotExists     = 1, ///< Destination file not exists
        NotEnoughFreeSpace    = 2, ///< Not enough free space
        CopyFail              = 3, ///< Copy fail
        DestFileAlreadyExists = 4, ///< Destination file already exists
        PeriodUnknown         = 5, ///< Period unknown
        Unknown               = 6  ///< Unknown
    };
Constructor & Destructor Documentation
Backup()
xl::fs::Backup::Backup (std::ctstring_t & filePath, std::ctstring_t & destDirPath, cPeriod period) explicit
  :
    _filePath(a_filePath),
    _period  (a_period),
    _destDir (a_destDirPath)
{
    xTEST(!a_filePath.empty());
    xTEST(!a_destDirPath.empty());
    xTEST_DIFF((int)a_period, (int)Period::Unknown);
}
References Unknown, xTEST, and xTEST_DIFF.
~Backup()
virtual xl::fs::Backup::~Backup () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::Backup::xNO_DEFAULT_CONSTRUCT (Backup)
xNO_COPY_ASSIGN()
xl::fs::Backup::xNO_COPY_ASSIGN (Backup)
fileExec()
Backup::Error xl::fs::Backup::fileExec (std::tstring_t * a_destFilePath) const
execute file backup
Parameters
[out] a_destFilePath
{
    xTEST_PTR(a_destFilePath);
    bool_t bRv {};
    // prepare
    {
        a_destFilePath->clear();
        bRv = FileInfo(_filePath).isExists();
        xCHECK_RET(!bRv, Error::DestFileNotExists);
        bRv = _destDir.isExists();
        xCHECK_DO(!bRv, _destDir.pathCreate());
    }
    std::tstring_t dateTs;
    {
        const DateTime &dateCurrent = DateTime::current();
        switch (_period) {
        case Period::Hourly:
            dateTs = dateCurrent.format(xT("%Y-%m-%d_%H"), {});
            break;
        case Period::Daily:
            dateTs = dateCurrent.format(xT("%Y-%m-%d"), {});
            break;
        case Period::Weekly:
            dateTs = dateCurrent.format(xT("%Y_%U"), {});
            break;
        case Period::Monthly:
            dateTs = dateCurrent.format(xT("%Y-%m"), {});
            break;
        case Period::Unknown:
            xTEST_FAIL;
            break;
        }
        xCHECK_RET(dateTs.empty(), Error::PeriodUnknown);
    }
    std::ctstring_t &destDirPath = _destDir.str();
    // format file full name
    std::ctstring_t backupFilePath = Path(destDirPath).slashAppend().str() +
        Path(_filePath).fileName() + xT("_[") + dateTs + xT("]") +
        Path::fileDotExt(Path::FileExt::Backup);
    // check for existence source file
    {
        bRv = FileInfo(backupFilePath).isExists();
        if (bRv) {
            // [out]
            *a_destFilePath = backupFilePath;
            return Error::DestFileAlreadyExists;
        }
    }
    // check for enough space
    {
        Volume volume(destDirPath);
        bRv = volume.isSpaceAvailable( static_cast<ulonglong_t>( FileInfo(_filePath).size() ));
        xCHECK_RET(!bRv, Error::NotEnoughFreeSpace);
    }
    // copy
    {
        File file(_filePath);
        cbool_t isFailIfExists{true};
        file.copy(backupFilePath, isFailIfExists);
    }
    // check for a valid backup
    {
        bRv = FileInfo(backupFilePath).isExists();
        xCHECK_RET(!bRv, Error::CopyFail);
        bRv = (FileInfo(_filePath).size() == FileInfo(backupFilePath).size());
        xCHECK_RET(!bRv, Error::CopyFail);
        bRv = (Crc32().calcFile(_filePath) == Crc32().calcFile(backupFilePath));
        xCHECK_RET(!bRv, Error::CopyFail);
    }
    // [out]
    *a_destFilePath = backupFilePath;
    return Error::Ok;
}
References xl::fs::Path::Backup, xl::crypt::Crc32::calcFile(), xl::fs::File::copy(), CopyFail, xl::core::DateTime::current(), Daily, DestFileAlreadyExists, DestFileNotExists, xl::fs::Path::fileDotExt(), xl::fs::Path::fileName(), xl::core::DateTime::format(), Hourly, xl::fs::Dir::isExists(), xl::fs::FileInfo::isExists(), xl::fs::Volume::isSpaceAvailable(), Monthly, NotEnoughFreeSpace, Ok, xl::fs::Dir::pathCreate(), PeriodUnknown, xl::fs::FileInfo::size(), xl::fs::Path::slashAppend(), xl::fs::Dir::str(), xl::fs::Path::str(), Unknown, Weekly, xCHECK_DO, xCHECK_RET, xT, xTEST_FAIL, and xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Backup.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Backup.cpp