xLib: xl::db::mysql::IResult Class Reference
xl::db::mysql::IResult Class Reference abstract
MySql recordset.
#include "Result.h"
Inherited by xl::db::mysql::StoreResult, and xl::db::mysql::UseResult.
Public Member Functions
HandleMySqlResult & get ()
get handle
std::size_t fields () const
number of columns in a result set / connection
std::uint64_t rows () const
number of rows in the result set / connection
ctors, dtor
IResult (const Connection &connection)
virtual ~IResult ()=0
xNO_DEFAULT_CONSTRUCT (IResult)
xNO_COPY_ASSIGN (IResult)
Fetch
MYSQL_FIELD * fetchField () const
The MYSQL_FIELD structure for the current column.
void_t fetchFieldDirect (cuint_t fieldNumber, MYSQL_FIELD *field) const
The MYSQL_FIELD structure for the specified column.
MYSQL_FIELD * fetchFields () const
An array of MYSQL_FIELD structures for all columns of a result set.
void_t fetchRow (row_t *row) const
fetching row
void_t fetchRows (rows_t *rows) const
fetching rows
Protected Member Functions
MYSQL_ROW _fetchRow () const
A MYSQL_ROW structure for the next row.
culong_t * _fetchLengths () const
An array of unsigned long_t integers representing the size of each column.
Protected Attributes
const Connection * _conn {}
pointer to connection object
HandleMySqlResult _result
result of a query that returns row
Detailed Description
MySql recordset.
Constructor & Destructor Documentation
IResult()
xl::db::mysql::IResult::IResult (const Connection & a_connection) explicit
Parameters
a_connection connection
  :
    _conn(&a_connection)
{
    xTEST(!_result.isValid());
    xTEST(_conn->get().isValid());
}
References _conn, _result, xl::db::mysql::Connection::get(), xl::core::Handle< T, typeT >::isValid(), and xTEST.
~IResult()
xl::db::mysql::IResult::~IResult () pure virtual
{
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::IResult::xNO_DEFAULT_CONSTRUCT (IResult)
xNO_COPY_ASSIGN()
xl::db::mysql::IResult::xNO_COPY_ASSIGN (IResult)
get()
HandleMySqlResult & xl::db::mysql::IResult::get ()
get handle
{
    return _result;
}
References _result.
fields()
std::size_t xl::db::mysql::IResult::fields () const
number of columns in a result set / connection
Get the number of columns either from a pointer to a result set or to a connection handler.
You would use the connection handler if mysql_store_result() or mysql_use_result() returned NULL (and thus you have no result set pointer). In this case, you can call mysql_field_count() to determine whether mysql_store_result() should have produced a nonempty result. This enables the client program to take proper action without knowing whether the query was a SELECT (or SELECT-like) statement. The example shown here illustrates how this may be done.
🔗 See also:
https://dev.mysql.com/doc/c-api/8.0/en/mysql-field-count.html
{
    xTEST_NA(_result);
    xTEST_NA(_conn);
    std::size_t uiRv {};
    if      ( _result.isValid() ) {
        uiRv = ::mysql_num_fields( _result.get() );
    }
    else if (_conn->get().isValid() ) {
        uiRv = ::mysql_field_count( _conn->get().get() );
    }
    return uiRv;
}
References _conn, _result, xl::db::mysql::Connection::get(), xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), and xTEST_NA.
Referenced by fetchRow().
rows()
std::uint64_t xl::db::mysql::IResult::rows () const
number of rows in the result set / connection
mysql_num_rows() is intended for use with statements that return a result set, such as SELECT.
For statements such as INSERT, UPDATE, or DELETE, the number of affected rows can be obtained with mysql_affected_rows().
{
    xTEST_NA(_result);
    xTEST_NA(_conn);
    std::uint64_t ullRv {};
    if      ( _result.isValid() ) {
        ullRv = ::mysql_num_rows( _result.get() );
    }
    else if ( _conn->get().isValid() ) {
        ullRv = ::mysql_affected_rows( _conn->get().get() );
        xTEST_DIFF(ullRv, MYSQL_COUNT_ERROR);
    }
    return ullRv;
}
References _conn, _result, xl::db::mysql::Connection::get(), xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xTEST_DIFF, and xTEST_NA.
fetchField()
MYSQL_FIELD * xl::db::mysql::IResult::fetchField () const
The MYSQL_FIELD structure for the current column.
{
    xTEST(_result.isValid());
    MYSQL_FIELD *field = ::mysql_fetch_field( _result.get() );
    xTEST_NA(field);
    return field;
}
References _result, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xTEST, and xTEST_NA.
fetchFieldDirect()
void_t xl::db::mysql::IResult::fetchFieldDirect (cuint_t fieldNumber, MYSQL_FIELD * field) const
The MYSQL_FIELD structure for the specified column.
{
    xTEST(_result.isValid());
    xTEST_NA(a_fieldNumber);
    xTEST_PTR(out_field);
    out_field = ::mysql_fetch_field_direct(_result.get(), a_fieldNumber);
    xTEST_PTR_MSG(out_field, Error(*_conn).str());
}
References _result, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xl::interface_::IError< CodeT >::str(), xTEST, xTEST_NA, xTEST_PTR, and xTEST_PTR_MSG.
fetchFields()
MYSQL_FIELD * xl::db::mysql::IResult::fetchFields () const
An array of MYSQL_FIELD structures for all columns of a result set.
{
    xTEST(_result.isValid());
    MYSQL_FIELD *field = ::mysql_fetch_fields( _result.get() );
    xTEST_NA(field);
    return field;
}
References _result, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xTEST, and xTEST_NA.
Referenced by fetchRow().
fetchRow()
void_t xl::db::mysql::IResult::fetchRow (row_t * out_row) const
fetching row
Parameters
[out] out_row
{
    xTEST(_result.isValid());
    xTEST_PTR(out_row);
    out_row->clear();
    const MYSQL_ROW row = _fetchRow();
    if (row == nullptr) {
        return;
    }
    std::csize_t  fieldsNum    = fields();
    MYSQL_FIELD  *fields       = fetchFields();
    culong_t     *fieldLengths = _fetchLengths();
    for (std::size_t i = 0; i < fieldsNum; ++ i) {
        std::ctstring_t &it_key = fields[i].name;
        std::tstring_t it_value;
        {
            cptr_cchar_t it_field     = (row[i] == nullptr) ? nullStr.c_str() : row[i];
            std::csize_t it_fieldSize = fieldLengths[i];
            std::cstring_t asField(it_field, it_fieldSize);
            it_value = xA2T(asField);
        }
        // [out]
        out_row->insert( {it_key, it_value} );
    }
}
References _fetchLengths(), _fetchRow(), _result, fetchFields(), fields(), xl::core::Handle< T, typeT >::isValid(), xl::db::mysql::nullStr, xA2T, xTEST, and xTEST_PTR.
Referenced by fetchRows().
fetchRows()
void_t xl::db::mysql::IResult::fetchRows (rows_t * out_rows) const
fetching rows
Parameters
[out] out_rows
{
    xTEST(_result.isValid());
    xTEST_PTR(out_rows);
    out_rows->clear();
    row_t row;
    for (fetchRow(&row); !row.empty(); fetchRow(&row)) {
        out_rows->emplace_back(row);
    }
}
References _result, fetchRow(), xl::core::Handle< T, typeT >::isValid(), xTEST, and xTEST_PTR.
Referenced by xl::db::mysql::Db::isExists(), and xl::db::mysql::Db::show().
_fetchRow()
MYSQL_ROW xl::db::mysql::IResult::_fetchRow () const protected
A MYSQL_ROW structure for the next row.
Returns
mysql_store_result() - returns NULL if there are no more rows to retrieve
mysql_use_result() - returns NULL if there are no more rows to retrieve or an error occurred
{
    xTEST(_result.isValid());
    MYSQL_ROW row = ::mysql_fetch_row(_result.get());
    xTEST_NA(row);
    return row;
}
References _result, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xTEST, and xTEST_NA.
Referenced by fetchRow().
_fetchLengths()
culong_t * xl::db::mysql::IResult::_fetchLengths () const protected
An array of unsigned long_t integers representing the size of each column.
Returns
nullptr - length for empty columns and for columns containing NULL values
The length for empty columns and for columns containing NULL values is zero.
🔗 See also:
how to distinguish these two cases, see the description for mysql_fetch_row().
{
    xTEST(_result.isValid());
   /**
    * \return nullptr - length for empty columns and for columns containing NULL values
    *
    * The length for empty columns and for columns containing NULL values is zero.
    * \see how to distinguish these two cases, see the description for mysql_fetch_row().
    */
    culong_t *fieldLengths = ::mysql_fetch_lengths(_result.get());
    xTEST_PTR_MSG(fieldLengths, Error(*_conn).str());
    return fieldLengths;
}
References _result, xl::core::Handle< T, typeT >::get(), xl::core::Handle< T, typeT >::isValid(), xl::interface_::IError< CodeT >::str(), xTEST, and xTEST_PTR_MSG.
Referenced by fetchRow().
Member Data Documentation
_conn
const Connection* xl::db::mysql::IResult::_conn {} protected
pointer to connection object
{};
Referenced by fields(), IResult(), rows(), xl::db::mysql::StoreResult::StoreResult(), and xl::db::mysql::UseResult::UseResult().
_result
HandleMySqlResult xl::db::mysql::IResult::_result protected
result of a query that returns row
Referenced by _fetchLengths(), _fetchRow(), fetchField(), fetchFieldDirect(), fetchFields(), fetchRow(), fetchRows(), fields(), get(), IResult(), rows(), xl::db::mysql::StoreResult::StoreResult(), and xl::db::mysql::UseResult::UseResult().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Result.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Result.cpp