xLib: xl::interface_::IError< CodeT > Class Template Reference
xl::interface_::IError< CodeT > Class Template Reference abstract
last error
#include "IError.h"
Public Member Functions
virtual CodeT code () const =0
Code.
virtual bool_t isOk () const =0
Check for success.
virtual std::tstring_t category () const =0
Category (type)
virtual std::tstring_t message () const =0
Detail message.
bool_t isFail () const
Check for error.
std::tstring_t str () const
Formatted message.
ctors, dtor
IError ()=default
virtual ~IError ()=default
Detailed Description
template<typename CodeT>
class xl::interface_::IError< CodeT >
last error
Constructor & Destructor Documentation
IError()
template<typename CodeT > xl::interface_::IError< CodeT >::IError () default
~IError()
template<typename CodeT > virtual xl::interface_::IError< CodeT >::~IError () virtual default
Member Function Documentation
code()
template<typename CodeT > virtual CodeT xl::interface_::IError< CodeT >::code () const pure virtual
Code.
Implemented in xl::db::mysql::Error, xl::package::curl::Error, and xl::package::xml::Error.
isOk()
template<typename CodeT > virtual bool_t xl::interface_::IError< CodeT >::isOk () const pure virtual
Check for success.
Implemented in xl::db::mysql::Error, xl::package::curl::Error, and xl::package::xml::Error.
category()
template<typename CodeT > virtual std::tstring_t xl::interface_::IError< CodeT >::category () const pure virtual
Category (type)
Implemented in xl::db::mysql::Error, xl::package::curl::Error, and xl::package::xml::Error.
message()
template<typename CodeT > virtual std::tstring_t xl::interface_::IError< CodeT >::message () const pure virtual
Detail message.
Implemented in xl::db::mysql::Error, xl::package::curl::Error, and xl::package::xml::Error.
isFail()
template<typename CodeT > bool_t xl::interface_::IError< CodeT >::isFail () const
Check for error.
{
    return !isOk();
}
str()
template<typename CodeT > std::tstring_t xl::interface_::IError< CodeT >::str () const
Formatted message.
{
    const auto &code_     = code();
    const auto &okStr_    = isOk() ? xT("Success") : xT("Failure");
    const auto &category_ = category();
    const auto &message_  = message();
    return Format::str(xT("[{}] {} ({}) - {}"),  category_, code_, okStr_, message_);
}
References code, xl::core::FormatT< StreamT >::str(), and xT.
Referenced by xl::db::mysql::IResult::_fetchLengths(), xl::db::mysql::Connection::commit(), xl::db::mysql::IResult::fetchFieldDirect(), xl::package::curl::Client::info(), xl::db::mysql::Connection::kill(), xl::package::curl::Client::perform(), xl::db::mysql::Connection::rollback(), xl::db::mysql::Connection::selectDb(), xl::db::mysql::Connection::setAutoCommit(), xl::package::curl::Client::setOption(), xl::db::mysql::StoreResult::StoreResult(), and xl::db::mysql::UseResult::UseResult().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Interface/IError.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Interface/IError.inl