xLib: xl::fs::Volume Class Reference
xl::fs::Volume Class Reference
volume
#include "Volume.h"
Public Types
enum class Type {
Unknown = 0 ,
NoRoot = 1 ,
Removable = 2 ,
Fixed = 3 ,
Remote = 4 ,
CdRom = 5 ,
Ram = 6
}
drive type
Public Member Functions
std::ctstring_t & path () const
path
Type type () const
type
std::tstring_t fileSystem () const
filesystem type
std::tstring_t label () const
get label
bool_t isValid () const
is valid path
bool_t isReady () const
is ready
bool_t isEmpty () const
is empty
void_t mount (std::ctstring_t &destPath) const
mount
void_t unMount (cbool_t isForce) const
unmount
bool_t isSpaceAvailable (culonglong_t needBytes) const
is enough space
ctors, dtor
Volume (std::ctstring_t &path)
virtual ~Volume ()=default
xNO_DEFAULT_CONSTRUCT (Volume)
xNO_COPY_ASSIGN (Volume)
Static Public Member Functions
static void_t space (std::ctstring_t &dirPath, ulonglong_t *totalBytes, ulonglong_t *availableBytes, ulonglong_t *freeBytes)
get free space
static void_t currentSpace (ulonglong_t *totalBytes, ulonglong_t *availableBytes, ulonglong_t *freeBytes)
get free space of current valume
static void_t paths (std::vec_tstring_t *volumePaths)
get paths
Detailed Description
volume
Member Enumeration Documentation
Type
enum class xl::fs::Volume::Type strong
drive type
Enumerator
Unknown
NoRoot
Removable
Fixed
Remote
CdRom
Ram
    {
    #if   xENV_WIN
        Unknown   = DRIVE_UNKNOWN,
        NoRoot    = DRIVE_NO_ROOT_DIR,
        Removable = DRIVE_REMOVABLE,
        Fixed     = DRIVE_FIXED,
        Remote    = DRIVE_REMOTE,
        CdRom     = DRIVE_CDROM,
        Ram       = DRIVE_RAMDISK
    #elif xENV_UNIX
        Unknown   = 0,
        NoRoot    = 1,
        Removable = 2,
        Fixed     = 3,
        Remote    = 4,
        CdRom     = 5,
        Ram       = 6
    #endif
    };
Constructor & Destructor Documentation
Volume()
xl::fs::Volume::Volume (std::ctstring_t & path) explicit
  :
    _path(a_volumePath)
{
    xTEST(!path().empty());
}
References path(), and xTEST.
~Volume()
virtual xl::fs::Volume::~Volume () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::Volume::xNO_DEFAULT_CONSTRUCT (Volume)
xNO_COPY_ASSIGN()
xl::fs::Volume::xNO_COPY_ASSIGN (Volume)
path()
std::ctstring_t & xl::fs::Volume::path () const
path
{
    return _path;
}
Referenced by isEmpty(), isSpaceAvailable(), and Volume().
type()
Volume::Type xl::fs::Volume::type () const
type
{
    return _type_impl();
}
fileSystem()
std::tstring_t xl::fs::Volume::fileSystem () const
filesystem type
{
    return _fileSystem_impl();
}
label()
std::tstring_t xl::fs::Volume::label () const
get label
{
    bool_t bRv = isReady();
    xCHECK_RET(!bRv, std::tstring_t());
    return _label_impl();
}
References isReady(), and xCHECK_RET.
isValid()
bool_t xl::fs::Volume::isValid () const
is valid path
{
    return _isValid_impl();
}
isReady()
bool_t xl::fs::Volume::isReady () const
is ready
{
    return _isReady_impl();
}
Referenced by label().
isEmpty()
bool_t xl::fs::Volume::isEmpty () const
is empty
{
    return Dir( path() ).isEmpty( Const::maskAll() );
}
References xl::fs::Dir::isEmpty(), xl::core::Const::maskAll(), and path().
mount()
void_t xl::fs::Volume::mount (std::ctstring_t & a_destPath) const
mount
Parameters
a_destPath destination path
{
    xTEST(!a_destPath.empty());
    _mount_impl(a_destPath);
}
References xTEST.
unMount()
void_t xl::fs::Volume::unMount (cbool_t a_isForce) const
unmount
Parameters
a_isForce force unmount even if busy
{
    xTEST_NA(a_isForce);
    _unMount_impl(a_isForce);
}
References xTEST_NA.
isSpaceAvailable()
bool_t xl::fs::Volume::isSpaceAvailable (culonglong_t a_needBytes) const
is enough space
Parameters
a_needBytes need space in bytes
{
    xTEST_NA(a_needBytes);
    ulonglong_t availableBytes {};
    space(path(), nullptr, &availableBytes, nullptr);
    xCHECK_RET(a_needBytes >= availableBytes, false);
    return true;
}
References path(), space(), xCHECK_RET, and xTEST_NA.
Referenced by xl::fs::Backup::fileExec().
space()
void_t xl::fs::Volume::space (std::ctstring_t & a_dirPath, ulonglong_t * a_totalBytes, ulonglong_t * a_availableBytes, ulonglong_t * a_freeBytes) static
get free space
Parameters
a_dirPath directory path (if empty - use current volume)
a_totalBytes total space
a_availableBytes available space (for unprivileged users)
a_freeBytes free space
{
    xTEST_NA(a_dirPath);
    xTEST_NA(a_availableBytes);
    xTEST_NA(a_totalBytes);
    xTEST_NA(a_freeBytes);
    // empty dir - use root directory of the current volume
    std::ctstring_t dirPath = a_dirPath.empty() ? Path::exe().dir() : a_dirPath;
    bool_t bRv = Dir(dirPath).isExists();
    xTEST(bRv);
    _space_impl(dirPath, a_totalBytes, a_availableBytes, a_freeBytes);
}
References xl::fs::Path::dir(), xl::fs::Path::exe(), xl::fs::Dir::isExists(), xTEST, and xTEST_NA.
Referenced by currentSpace(), and isSpaceAvailable().
currentSpace()
void_t xl::fs::Volume::currentSpace (ulonglong_t * a_totalBytes, ulonglong_t * a_availableBytes, ulonglong_t * a_freeBytes) static
get free space of current valume
Parameters
a_totalBytes total space
a_availableBytes available space (for unprivileged users)
a_freeBytes free space
{
    space({}, a_totalBytes, a_availableBytes, a_freeBytes);
}
References space().
paths()
void_t xl::fs::Volume::paths (std::vec_tstring_t * a_volumePaths) static
get paths
Parameters
a_volumePaths volume paths
{
    xTEST_PTR(a_volumePaths);
    _paths_impl(a_volumePaths);
}
References xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Volume.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/Volume.cpp