xLib: xl::package::xml::Node Class Reference
xl::package::xml::Node Class Reference
#include "Node.h"
Public Member Functions
std::tstring_t name () const
std::tstring_t text () const
void findNodes (std::cvec_tstring_t &xpaths, std::vector< Node > &values) const
void node (std::ctstring_t &xpath, Node &value) const
void nodes (std::ctstring_t &xpath, std::vector< Node > &values) const
void texts (std::ctstring_t &xpath, std::vec_tstring_t &values) const
std::size_t childSize () const
void childMap (std::ctstring_t &xpath, std::map_tstring_t &values) const
std::tstring_t attribute (std::ctstring_t &name) const
void attributes (std::map_tstring_t &values) const
std::tstring_t dump (cbool_t isFromCurrent=false, cbool_t isFormat=true)
ctors, dtor
Node ()=default
Node (Doc *xmlDoc, xmlNodePtr node)
Node (const Node &xmlNode)
virtual ~Node ()=default
operators
Node & operator= (const Node &xmlNode)
Constructor & Destructor Documentation
Node() [1/3]
xl::package::xml::Node::Node () default
Node() [2/3]
xl::package::xml::Node::Node (Doc * xmlDoc, xmlNodePtr node)
  :
    _xmlDoc(a_xmlDoc),
    _node  (a_node)
{
}
Node() [3/3]
xl::package::xml::Node::Node (const Node & xmlNode)
  :
    _xmlDoc(a_xmlNode._xmlDoc),
    _node  (a_xmlNode._node)
{
}
~Node()
virtual xl::package::xml::Node::~Node () virtual default
Member Function Documentation
operator=()
Node & xl::package::xml::Node::operator= (const Node & xmlNode)
{
    xCHECK_RET(this == &a_xmlNode, *this);
    _xmlDoc = a_xmlNode._xmlDoc;
    _node   = a_xmlNode._node;
    return *this;
}
References xCHECK_RET.
name()
std::tstring_t xl::package::xml::Node::name () const
{
    return _name(_node);
}
Referenced by attributes().
text()
std::tstring_t xl::package::xml::Node::text () const
{
    std::tstring_t sRv;
    _xmlDoc->_iconv.convert(_text(_node), &sRv);
    return sRv;
}
References xl::package::Iconv::convert().
findNodes()
void xl::package::xml::Node::findNodes (std::cvec_tstring_t & a_xpaths, std::vector< Node > & out_values) const
Parameters
a_xpaths XPaths
[out] out_values result
{
    out_values.clear();
    for (const auto &it_xpath : a_xpaths) {
        std::vector<Node> values;
        nodes(it_xpath, values);
        for (const auto &it_value : values) {
            out_values.emplace_back(it_value);
        }
    }
}
References nodes().
node()
void xl::package::xml::Node::node (std::ctstring_t & a_xpath, Node & out_value) const
Parameters
a_xpath XPath
[out] out_value result
{
    std::vector<Node> nodes_;
    nodes(a_xpath, nodes_);
    xCHECK_DO(nodes_.empty(), return);
    out_value = nodes_.front();
}
References nodes(), and xCHECK_DO.
Referenced by dump(), and nodes().
nodes()
void xl::package::xml::Node::nodes (std::ctstring_t & a_xpath, std::vector< Node > & out_res) const
Parameters
a_xpath XPath
[out] out_res results
{
    out_res.clear();
    xpath_ctx_unique_ptr_t xpathCtx(::xmlXPathNewContext(_node->doc), &::xmlXPathFreeContext);
    if (!xpathCtx) {
        xTEST_FAIL;
        return;
    }
    _xmlDoc->_registerNss(xpathCtx.get());
    xpathCtx->node = _node;
    xpath_obj_unique_ptr_t xpathObj(::xmlXPathEvalExpression((const xmlChar *)a_xpath.data(),
        xpathCtx.get()), ::xmlXPathFreeObject);
    if (!xpathObj) {
        xTEST_FAIL;
        return;
    }
    xmlNodeSetPtr nodes = xpathObj->nodesetval;
    if (nodes == nullptr) {
        xTEST_FAIL;
        return;
    }
    for (int i = 0; i < nodes->nodeNr; ++ i) {
        xmlNodePtr it_node = nodes->nodeTab[i];
        if (it_node == nullptr) {
            xTEST_FAIL;
            continue;
        }
        Node node(_xmlDoc, it_node);
        out_res.emplace_back(node);
    }
}
References node(), nodes(), and xTEST_FAIL.
Referenced by findNodes(), node(), nodes(), and texts().
texts()
void xl::package::xml::Node::texts (std::ctstring_t & a_xpath, std::vec_tstring_t & out_values) const
Parameters
a_xpath XPath
[out] out_values results
{
    out_values.clear();
    std::vector<Node> values;
    nodes(a_xpath, values);
    for (const auto &it_value : values) {
        out_values.emplace_back( it_value.text() );
    }
}
References nodes().
childSize()
std::size_t xl::package::xml::Node::childSize () const
{
    return ::xmlChildElementCount(_node);
}
childMap()
void xl::package::xml::Node::childMap (std::ctstring_t & a_xpath, std::map_tstring_t & out_values) const
Parameters
a_xpath XPath
[out] out_values result
{
    out_values.clear();
    for (xmlNodePtr it_node = _node->children; it_node != nullptr; it_node = it_node->next) {
        if (it_node->type != XML_ELEMENT_NODE) {
            continue;
        }
        if (::xmlFirstElementChild(it_node) != nullptr) {
            continue;
        }
        out_values.emplace(_name(it_node), _text(it_node));
    }
}
attribute()
std::tstring_t xl::package::xml::Node::attribute (std::ctstring_t & a_name) const
Parameters
a_name attribute name
{
    if (_node->type != XML_ELEMENT_NODE) {
        return {};
    }
    std::tstring_t sRv;
    char_unique_ptr_t value(::xmlGetProp(_node, (const xmlChar *)a_name.data()), ::xmlFree);
    if (!value) {
        // attribute - not exists
        return {};
    }
    sRv = Utils::c_cast<cptr_ctchar_t>(value.get());
    return sRv;
}
attributes()
void xl::package::xml::Node::attributes (std::map_tstring_t & out_values) const
Parameters
[out] out_values attributes (name -> value)
{
    out_values.clear();
    if (_node->type != XML_ELEMENT_NODE) {
        return;
    }
    for (xmlAttrPtr p = _node->properties; p != nullptr; p = p->next) {
        const xmlChar *name  = p->name;
        xTEST_PTR(name);
        char_unique_ptr_t value(::xmlGetProp(_node, name), ::xmlFree);
        xTEST(!!value);
        out_values.insert( {(cptr_ctchar_t)name, (cptr_ctchar_t)value.get()} );
    }
}
References name(), xTEST, and xTEST_PTR.
dump()
std::tstring_t xl::package::xml::Node::dump (cbool_t isFromCurrent = false, cbool_t isFormat = true)
{
    std::tstring_t sRv;
    int_t          iRv {};
    buff_unique_ptr_t buff(::xmlBufferCreate(), ::xmlBufferFree);
    xTEST_PTR(buff.get());
    xmlNodePtr node   = a_isFromCurrent ? _node : _node->children;
    cint_t     level  = 0;
    cint_t     format = a_isFormat ? 1 : 0;
    iRv = ::xmlNodeDump(buff.get(), _xmlDoc->_doc.get(), node, level, format);
    xTEST_DIFF(iRv,  -1);
    auto content = (cptr_ctchar_t)buff->content;
    if (content == nullptr) {
        xTEST_FAIL;
        return {};
    }
    // [out]
    sRv = content;
    return sRv;
}
References node(), xTEST_DIFF, xTEST_FAIL, and xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Node.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Xml/Node.cpp