xLib: xl::sync::Mutex Class Reference
xl::sync::Mutex Class Reference
critical section
#include "Mutex.h"
Public Types
using handle_t = pthread_mutex_t
Public Member Functions
const handle_t & handle () const
get handle
void_t create ()
create
void_t lock ()
lock
bool_t tryLock ()
try lock
void_t unlock ()
unlock
ctors, dtor
Mutex ()=default
virtual ~Mutex ()
xNO_COPY_ASSIGN (Mutex)
Detailed Description
critical section
Member Typedef Documentation
handle_t
using xl::sync::Mutex::handle_t = pthread_mutex_t
Constructor & Destructor Documentation
Mutex()
xl::sync::Mutex::Mutex () default
~Mutex()
xl::sync::Mutex::~Mutex () virtual
{
    _destruct_impl();
}
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::Mutex::xNO_COPY_ASSIGN (Mutex)
handle()
const Mutex::handle_t & xl::sync::Mutex::handle () const
get handle
{
    return _handle;
}
create()
void_t xl::sync::Mutex::create ()
create
{
    _create_impl();
}
Referenced by xl::sync::AutoMutex::AutoMutex().
lock()
void_t xl::sync::Mutex::lock ()
lock
{
    _lock_impl();
}
Referenced by xl::sync::AutoMutex::AutoMutex().
tryLock()
bool_t xl::sync::Mutex::tryLock ()
try lock
{
    return _tryLock_impl();
}
unlock()
void_t xl::sync::Mutex::unlock ()
unlock
{
    _unlock_impl();
}
Referenced by xl::sync::AutoMutex::~AutoMutex().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Mutex.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/Mutex.cpp