xLib: xl::crypt::Blowfish Class Reference
xl::crypt::Blowfish Class Reference
blowfish
#include "Blowfish.h"
Public Types
enum class Mode {
Unknown = - 1 ,
Encrypt = BF_ENCRYPT ,
Decrypt = BF_DECRYPT
}
crypt mode
Public Member Functions
ctors, dtor
Blowfish (uchar_t *key, cint_t keySize)
Blowfish (std::custring_t &key)
Blowfish (std::ctstring_t &key)
Blowfish (std::filesystem::path &filePath)
virtual ~Blowfish ()=default
xNO_DEFAULT_CTOR (Blowfish)
xNO_COPY_ASSIGN (Blowfish)
ecrypt with cfb64
void_t encryptCfb64 (cMode mode, cuchar_t *in, uchar_t *out, clong_t inSize, int_t *num)
void_t encryptCfb64 (cMode mode, std::custring_t &in, std::ustring_t *out)
void_t encryptFileCfb64 (cMode mode, std::ctstring_t &filePathIn, std::ctstring_t &filePathOut)
Detailed Description
blowfish
Member Enumeration Documentation
Mode
enum class xl::crypt::Blowfish::Mode strong
crypt mode
Enumerator
Unknown
Encrypt
Decrypt
    {
        Unknown = - 1,
        Encrypt = BF_ENCRYPT,
        Decrypt = BF_DECRYPT
    };
Constructor & Destructor Documentation
Blowfish() [1/4]
xl::crypt::Blowfish::Blowfish (uchar_t * key, cint_t keySize)
{
    xTEST_PTR(a_key);
    xTEST_GR_EQ(_keySizeMax(), a_keySize);
    xTEST_LESS(0, a_keySize);
    (void_t)::BF_set_key(&_key, a_keySize, a_key);
}
References xTEST_GR_EQ, xTEST_LESS, and xTEST_PTR.
Blowfish() [2/4]
xl::crypt::Blowfish::Blowfish (std::custring_t & key) explicit
  :
    Blowfish(const_cast<uchar_t *>( a_key.data() ), static_cast<int_t>( a_key.size() ))
{
}
Blowfish() [3/4]
xl::crypt::Blowfish::Blowfish (std::ctstring_t & key) explicit
  :
    Blowfish(std::ustring_t(a_key.cbegin(), a_key.cend()))
{
}
Blowfish() [4/4]
xl::crypt::Blowfish::Blowfish (std::filesystem::path & filePath) explicit
{
    xTEST(!a_filePath.empty());
    std::ustring_t key;
    {
    #if xUNICODE
        std::ctstring_t filePath = xA2T(a_filePath.wstring());
    #else
        std::ctstring_t filePath = xA2T(a_filePath.string());
    #endif
        FileBin file(filePath);
        file.read(&key);
        FileInfo fileInfo(a_filePath);
        xTEST(!fileInfo.isEmpty());
        xTEST_LESS_EQ(fileInfo.size(), _keySizeMax());
    }
    (void_t)::BF_set_key(&_key, key.size(), key.data());
}
References xl::fs::FileInfo::isEmpty(), xl::fs::FileBin::read(), xl::fs::FileInfo::size(), xA2T, xTEST, and xTEST_LESS_EQ.
~Blowfish()
virtual xl::crypt::Blowfish::~Blowfish () virtual default
Member Function Documentation
xNO_DEFAULT_CTOR()
xl::crypt::Blowfish::xNO_DEFAULT_CTOR (Blowfish)
xNO_COPY_ASSIGN()
xl::crypt::Blowfish::xNO_COPY_ASSIGN (Blowfish)
encryptCfb64() [1/2]
void_t xl::crypt::Blowfish::encryptCfb64 (cMode a_mode, cuchar_t * a_in, uchar_t * out_out, clong_t a_inSize, int_t * out_num)
Parameters
a_mode crypt mode
a_in input buffer
[out] out_out output buffer
a_inSize input buffer size
[out] out_num output buffer size
{
    xTEST(a_mode == Blowfish::Mode::Encrypt || a_mode == Blowfish::Mode::Decrypt);
    xTEST_PTR(a_in);
    xTEST_PTR(out_out);
    xTEST_GR_EQ(a_inSize, 0L);
    xTEST_PTR(out_num);
    uchar_t ivec[BF_BLOCK] {};
    _encryptCfb64(a_mode, a_in, out_out, a_inSize, ivec, out_num);
}
References Decrypt, Encrypt, xTEST, xTEST_GR_EQ, and xTEST_PTR.
Referenced by encryptCfb64(), and encryptFileCfb64().
encryptCfb64() [2/2]
void_t xl::crypt::Blowfish::encryptCfb64 (cMode a_mode, std::custring_t & a_in, std::ustring_t * out_out)
Parameters
a_mode crypt mode
a_in input buffer
[out] out_out output buffer
{
    xTEST(!a_in.empty());
    xTEST_PTR(out_out);
    out_out->resize( a_in.size() );
    // this integer must be initialized to zero when ivec is initialized
    int_t num {};
    encryptCfb64(a_mode, &a_in.at(0), &out_out->at(0), static_cast<long_t>( a_in.size() ), &num);
    xTEST_LESS(- 1, num);
}
References encryptCfb64(), num, xTEST, xTEST_LESS, and xTEST_PTR.
encryptFileCfb64()
void_t xl::crypt::Blowfish::encryptFileCfb64 (cMode a_mode, std::ctstring_t & a_filePathIn, std::ctstring_t & a_filePathOut)
Parameters
a_mode crypt mode
a_filePathIn input file path
a_filePathOut output file path
{
    xTEST(!a_filePathIn.empty());
    xTEST(!a_filePathOut.empty());
    // File - read
    std::ustring_t in;
    {
        FileBin file(a_filePathIn);
        file.read(&in);
    }
    std::ustring_t out;
    if (a_mode == Mode::Encrypt) {
        const auto iv = _randomIv();
        std::ustring_t encrypted;
        _encryptCfb64(a_mode, in, std::ustring_t(iv.cbegin(), iv.cend()), &encrypted);
        // MagicLabel + IV + encrypted
        out.reserve(_encryptedMagicLabel.size() + iv.size() + encrypted.size());
        out.insert(out.end(), _encryptedMagicLabel.cbegin(), _encryptedMagicLabel.cend());
        out.insert(out.end(), iv.cbegin(), iv.cend());
        out.insert(out.end(), encrypted.cbegin(), encrypted.cend());
    }
    else if ( _isCfb64Encrypt(in) ) {
        const auto ivOffset   = _encryptedMagicLabel.size();
        const auto dataOffset = ivOffset + BF_BLOCK;
        std::ustring_t iv(in.cbegin() + static_cast<std::ptrdiff_t>(ivOffset),
            in.cbegin() + static_cast<std::ptrdiff_t>(dataOffset));
        std::ustring_t encrypted(in.cbegin() + static_cast<std::ptrdiff_t>(dataOffset), in.cend());
        _encryptCfb64(a_mode, encrypted, iv, &out);
    }
    else {
        encryptCfb64(a_mode, in, &out);
    }
    // File - write
    {
        FileBin file(a_filePathOut);
        file.write(out, FileIO::OpenMode::BinReadWrite);
    }
}
References Encrypt, encryptCfb64(), xl::fs::FileBin::read(), xl::fs::FileBin::write(), and xTEST.
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Crypt/OpenSsl/Blowfish.h
/home/runner/work/xLib/xLib/Include/xLib/Crypt/OpenSsl/Blowfish.cpp