xLib: xl::core::DateTime Class Reference
xl::core::DateTime Class Reference
date, time
#include "DateTime.h"
Public Member Functions
void_t get (int_t *year, int_t *month, int_t *day, int_t *hour, int_t *minute, int_t *second, int_t *msec) const
get datetime data
int_t dayOfWeek () const
get day of week, days since Sunday 0-6
ulonglong_t toMsec () const
convert DateTime to milliseconds
std::tstring_t format (std::ctstring_t &format, std::ctstring_t &formatMsec=xT(".%03d")) const
formatting
ctors, dtor
DateTime ()
DateTime (const DateTime &datetime)
DateTime (culonglong_t msec)
DateTime (cint_t hour, cint_t minute, cint_t second, cint_t msec)
DateTime (cint_t year, cint_t month, cint_t day)
DateTime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec)
virtual ~DateTime ()=default
comparison operators
bool_t operator== (const DateTime &datetime) const
bool_t operator!= (const DateTime &datetime) const
bool_t operator< (const DateTime &datetime) const
bool_t operator<= (const DateTime &datetime) const
bool_t operator> (const DateTime &datetime) const
bool_t operator>= (const DateTime &datetime) const
assignment operators
DateTime & operator= (const DateTime &datetime)
DateTime & operator= (culonglong_t msec)
DateTime operator+ (const DateTime &datetime) const
DateTime operator- (const DateTime &datetime) const
const DateTime & operator+= (const DateTime &datetime)
const DateTime & operator-= (const DateTime &datetime)
Static Public Member Functions
static DateTime current ()
get current datetime
static int_t daysInMonth (cint_t year, cint_t month)
get number days in month
static bool_t isLeapYear (cint_t year)
is leap year
static std::tstring_t monthStr (cint_t month, cbool_t isShortName)
get month string
static int_t monthNum (std::ctstring_t &month, cbool_t isShortName)
get month number by string
static std::tstring_t weekDayStr (cint_t week_day, cbool_t isShortName)
get week day string (days since Sunday)
static int_t weekDayNum (std::ctstring_t &week_day, cbool_t isShortName)
get week day number by string
Friends
class DateTimeValidator
std::tostream_t & operator<< (std::tostream_t &os, const DateTime &dateTime)
Detailed Description
date, time
Constructor & Destructor Documentation
DateTime() [1/6]
xl::core::DateTime::DateTime ()
                   :
    DateTime(::yearMin, ::monthMin, ::dayMin, ::hourMin, ::minuteMin, ::secondMin, ::msecMin)
{
}
Referenced by operator+(), and operator-().
DateTime() [2/6]
xl::core::DateTime::DateTime (const DateTime & datetime) explicit
  :
    DateTime(a_datetime._year, a_datetime._month,  a_datetime._day,
        a_datetime._hour, a_datetime._minute, a_datetime._second, a_datetime._msec)
{
}
DateTime() [3/6]
xl::core::DateTime::DateTime (culonglong_t msec) explicit
{
    _construct(a_msec);
}
DateTime() [4/6]
xl::core::DateTime::DateTime (cint_t hour, cint_t minute, cint_t second, cint_t msec)
  :
    DateTime(0, 0, 0, a_hour, a_minute, a_second, a_msec)
{
}
DateTime() [5/6]
xl::core::DateTime::DateTime (cint_t year, cint_t month, cint_t day)
  :
    DateTime(a_year, a_month, a_day, 0, 0, 0, 0)
{
}
DateTime() [6/6]
xl::core::DateTime::DateTime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec)
  :
    // datetime
    _year    {a_year},
    _month   {a_month},
    _day     {a_day},
    _hour    {a_hour},
    _minute  {a_minute},
    _second  {a_second},
    _msec    {a_msec},
    // REVIEW: datetime msec member (convert to msec)
    _thisMSec{ _toMsec() }
{
#if 0
    xTEST(DateTimeValidator::date(a_year, a_month, a_day));
    xTEST(DateTimeValidator::time(a_hour, a_minute, a_second, a_msec));
#endif
}
References xl::core::DateTimeValidator::date(), xl::core::DateTimeValidator::time(), and xTEST.
~DateTime()
virtual xl::core::DateTime::~DateTime () virtual default
Member Function Documentation
operator==()
bool_t xl::core::DateTime::operator== (const DateTime & datetime) const
{
    return (_thisMSec == a_datetime._thisMSec);
}
operator!=()
bool_t xl::core::DateTime::operator!= (const DateTime & datetime) const
{
    return (_thisMSec != a_datetime._thisMSec);
}
operator<()
bool_t xl::core::DateTime::operator< (const DateTime & datetime) const
{
    return (_thisMSec < a_datetime._thisMSec);
}
operator<=()
bool_t xl::core::DateTime::operator<= (const DateTime & datetime) const
{
    return (_thisMSec <= a_datetime._thisMSec);
}
operator>()
bool_t xl::core::DateTime::operator> (const DateTime & datetime) const
{
    return (_thisMSec > a_datetime._thisMSec);
}
operator>=()
bool_t xl::core::DateTime::operator>= (const DateTime & datetime) const
{
    return (_thisMSec >= a_datetime._thisMSec);
}
operator=() [1/2]
DateTime & xl::core::DateTime::operator= (const DateTime & datetime)
{
    if (this == &a_datetime) {
        return *this;
    }
    // TODO: fix
    _construct(a_datetime._thisMSec);
    return *this;
}
operator=() [2/2]
DateTime & xl::core::DateTime::operator= (culonglong_t msec)
{
    // TODO: fix
    _construct(a_msec);
    return *this;
}
operator+()
DateTime xl::core::DateTime::operator+ (const DateTime & datetime) const
{
    return DateTime(_thisMSec + a_datetime._thisMSec);
}
References DateTime().
operator-()
DateTime xl::core::DateTime::operator- (const DateTime & datetime) const
{
    return DateTime(_thisMSec - a_datetime._thisMSec);
}
References DateTime().
operator+=()
const DateTime & xl::core::DateTime::operator+= (const DateTime & datetime)
{
    _thisMSec += a_datetime._thisMSec;
    // TODO: fix
    _construct(_thisMSec);
    return *this;
}
operator-=()
const DateTime & xl::core::DateTime::operator-= (const DateTime & datetime)
{
    _thisMSec -= a_datetime._thisMSec;
    // TODO: fix
    _construct(_thisMSec);
    return *this;
}
get()
void_t xl::core::DateTime::get (int_t * year, int_t * month, int_t * day, int_t * hour, int_t * minute, int_t * second, int_t * msec) const
get datetime data
{
    xTESTS_NA
    Utils::ptrAssignT(a_year,   _year);
    Utils::ptrAssignT(a_month,  _month);
    Utils::ptrAssignT(a_day,    _day);
    Utils::ptrAssignT(a_hour,   _hour);
    Utils::ptrAssignT(a_minute, _minute);
    Utils::ptrAssignT(a_second, _second);
    Utils::ptrAssignT(a_msec,   _msec);
}
References xl::core::Utils::ptrAssignT(), and xTESTS_NA.
dayOfWeek()
int_t xl::core::DateTime::dayOfWeek () const
get day of week, days since Sunday 0-6
{
    xTEST(DateTimeValidator::datetime(*this));
    std::tm timeInfo {};
    timeInfo.tm_year = _year  - 1900;
    timeInfo.tm_mon  = _month - 1;
    timeInfo.tm_mday = _day;
    const time_t time = std::mktime(&timeInfo);
    xTEST_DIFF(time, static_cast<time_t>(- 1));
    return timeInfo.tm_wday;
}
References xl::core::DateTimeValidator::datetime(), xTEST, and xTEST_DIFF.
toMsec()
ulonglong_t xl::core::DateTime::toMsec () const
convert DateTime to milliseconds
{
    return _thisMSec;
}
format()
std::tstring_t xl::core::DateTime::format (std::ctstring_t & a_format, std::ctstring_t & a_formatMsec = xT(".%03d")) const
formatting
Parameters
a_format datetime format
a_formatMsec milliseconds format
{
    xTESTS_NA
    xTEST(!a_format.empty());
    xTEST_NA(a_formatMsec);
    std::tstring_t sRv;
    std::tm date {};
    date.tm_sec   = _second;
    date.tm_min   = _minute;
    date.tm_hour  = _hour;
    date.tm_mday  = _day;
    date.tm_mon   = _month - 1;
    date.tm_year  = _year  - 1900;
    date.tm_wday  = {};
    date.tm_yday  = {};
    date.tm_isdst = {};
#if 0
    Cout() << date;
    Cout() << xTRACE_VAR(a_format);
    Cout() << xTRACE_VAR(a_formatMsec);
#endif
    tchar_t buff[80 + 1] {};
    std::csize_t buffSize = xSTRFTIME(&buff[0], sizeof(buff) - 1, a_format.c_str(), &date);
    xCHECK_RET(buffSize == 0, std::tstring_t());
    sRv.assign(&buff[0], buffSize);
    if ( !a_formatMsec.empty() ) {
        sRv += FormatC::str(a_formatMsec.c_str(), _msec);
    }
    return sRv;
}
References xl::core::FormatC::str(), xCHECK_RET, xTEST, xTEST_NA, xTESTS_NA, and xTRACE_VAR.
Referenced by xl::fs::Backup::fileExec(), xl::debug::Profiler::stop(), and xl::log::FileLog::write().
current()
DateTime xl::core::DateTime::current () static
get current datetime
{
    return _current_impl();
}
Referenced by xl::fs::Backup::fileExec(), xl::package::FeatureFlag::setStop(), and xl::log::FileLog::write().
daysInMonth()
int_t xl::core::DateTime::daysInMonth (cint_t year, cint_t month) static
get number days in month
{
    xCHECK_RET(a_month == 2 && isLeapYear(a_year), 29);
    const std::array<int_t, ::monthMax + 1> monthsDays =
    {{
        31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
    }};
    return monthsDays[ static_cast<std::size_t>(a_month) ];
}
References isLeapYear(), and xCHECK_RET.
isLeapYear()
bool_t xl::core::DateTime::isLeapYear (cint_t year) static
is leap year
{
    return ((a_year % 4) == 0 && ((a_year % 100) != 0 || (a_year % 400) == 0));
}
Referenced by daysInMonth().
monthStr()
std::tstring_t xl::core::DateTime::monthStr (cint_t month, cbool_t isShortName) static
get month string
{
    xTEST(DateTimeValidator::month(a_month));
    xTEST_NA(a_isShortName);
    std::tstring_t sRv;
    if (!a_isShortName) {
        // months numbering: 1-12
        const std::array<std::tstring_t, ::monthMax + 1> longMonths =
        {{
            xT("January"),
            xT("February"),
            xT("March"),
            xT("April"),
            xT("May"),
            xT("June"),
            xT("July"),
            xT("August"),
            xT("September"),
            xT("October"),
            xT("November"),
            xT("December")
        }};
        sRv = longMonths[static_cast<std::size_t>(a_month) - 1];
    } else {
        // months numbering: 1-12
        const std::array<std::tstring_t, ::monthMax + 1> shortMonths =
        {{
            xT("Jan"),
            xT("Feb"),
            xT("Mar"),
            xT("Apr"),
            xT("May"),
            xT("Jun"),
            xT("Jul"),
            xT("Aug"),
            xT("Sep"),
            xT("Oct"),
            xT("Nov"),
            xT("Dec")
        }};
        sRv = shortMonths[static_cast<std::size_t>(a_month) - 1];
    }
    return sRv;
}
References xl::core::DateTimeValidator::month(), xT, xTEST, and xTEST_NA.
monthNum()
int_t xl::core::DateTime::monthNum (std::ctstring_t & month, cbool_t isShortName) static
get month number by string
{
    xTEST_NA(a_month);
    xTEST_NA(a_isShortName);
    // months numbering: 0-11
    const std::array<std::tstring_t, ::monthMax + 1> longMonths =
    {{
        xT("January"),
        xT("February"),
        xT("March"),
        xT("April"),
        xT("May"),
        xT("June"),
        xT("July"),
        xT("August"),
        xT("September"),
        xT("October"),
        xT("November"),
        xT("December")
    }};
    // months numbering: 0-11
    const std::array<std::tstring_t, ::monthMax + 1> shortMonths =
    {{
        xT("Jan"),
        xT("Feb"),
        xT("Mar"),
        xT("Apr"),
        xT("May"),
        xT("Jun"),
        xT("Jul"),
        xT("Aug"),
        xT("Sep"),
        xT("Oct"),
        xT("Nov"),
        xT("Dec")
    }};
    for (int_t i = 0; i < static_cast<int_t>( longMonths.size() ); ++ i) {
        if (a_isShortName) {
            xCHECK_RET(StringCI::compare(a_month, shortMonths[ static_cast<std::size_t>(i) ]), i);
        } else {
            xCHECK_RET(StringCI::compare(a_month, longMonths[ static_cast<std::size_t>(i) ]),  i);
        }
    }
    return - 1;
}
References xl::core::StringCI::compare(), xCHECK_RET, xT, and xTEST_NA.
weekDayStr()
std::tstring_t xl::core::DateTime::weekDayStr (cint_t week_day, cbool_t isShortName) static
get week day string (days since Sunday)
{
    xTEST(DateTimeValidator::weekDay(a_week_day));
    xTEST_NA(a_isShortName);
    // days since Sunday (0-6)
    std::tstring_t sRv;
    if (!a_isShortName) {
        const std::array<std::tstring_t, ::weekDayMax + 1> longDays =
        {{
            xT("Sunday"),
            xT("Monday"),
            xT("Tuesday"),
            xT("Wednesday"),
            xT("Thursday"),
            xT("Friday"),
            xT("Saturday")
        }};
        sRv = longDays[ static_cast<std::size_t>(a_week_day) ];
    } else {
        const std::array<std::tstring_t, ::weekDayMax + 1> shortDays =
        {{
            xT("Sun"),
            xT("Mon"),
            xT("Tue"),
            xT("Wed"),
            xT("Thu"),
            xT("Fri"),
            xT("Sat")
        }};
        sRv = shortDays[ static_cast<std::size_t>(a_week_day) ];
    }
    return sRv;
}
References xl::core::DateTimeValidator::weekDay(), xT, xTEST, and xTEST_NA.
weekDayNum()
int_t xl::core::DateTime::weekDayNum (std::ctstring_t & week_day, cbool_t isShortName) static
get week day number by string
{
    xTEST_NA(a_week_day);
    xTEST_NA(a_isShortName);
    const std::array<std::tstring_t, ::weekDayMax + 1> longDays =
    {{
        xT("Monday"),
        xT("Tuesday"),
        xT("Wednesday"),
        xT("Thursday"),
        xT("Friday"),
        xT("Saturday"),
        xT("Sunday")
    }};
    const std::array<std::tstring_t, ::weekDayMax + 1> shortDays =
    {{
        xT("Mon"),
        xT("Tue"),
        xT("Wed"),
        xT("Thu"),
        xT("Fri"),
        xT("Sat"),
        xT("Sun")
    }};
    for (int_t i = 0; i < static_cast<int_t>( longDays.size() ); ++ i) {
        xCHECK_RET(!a_isShortName && StringCI::compare(a_week_day, longDays[ static_cast<std::size_t>(i) ]),  i);
        xCHECK_RET( a_isShortName && StringCI::compare(a_week_day, shortDays[ static_cast<std::size_t>(i) ]), i);
    }
    return - 1;
}
References xl::core::StringCI::compare(), xCHECK_RET, xT, and xTEST_NA.
Friends And Related Symbol Documentation
DateTimeValidator
friend class DateTimeValidator friend
operator<<
std::tostream_t & operator<< (std::tostream_t & os, const DateTime & dateTime) friend
{
    a_os << a_dateTime.format(xT("%d-%m-%Y %H:%M:%S"));
    return a_os;
};
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/DateTime.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/DateTime.cpp