xLib: xl::sync::IpcMutex Class Reference
xl::sync::IpcMutex Class Reference
mutex
#include "IpcMutex.h"
Public Types
using handle_t = sem_t *
Public Member Functions
const handle_t & handle () const
get handle
void_t create (std::ctstring_t &name)
create
void_t open (std::ctstring_t &name)
open
void_t lock (culong_t &timeoutMsec) const
unlock by timeout in msec
void_t unlock () const
lock
ctors, dtor
IpcMutex ()=default
virtual ~IpcMutex ()=default
xNO_COPY_ASSIGN (IpcMutex)
Detailed Description
mutex
Member Typedef Documentation
handle_t
using xl::sync::IpcMutex::handle_t = sem_t *
Constructor & Destructor Documentation
IpcMutex()
xl::sync::IpcMutex::IpcMutex () default
~IpcMutex()
virtual xl::sync::IpcMutex::~IpcMutex () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::sync::IpcMutex::xNO_COPY_ASSIGN (IpcMutex)
handle()
const IpcMutex::handle_t & xl::sync::IpcMutex::handle () const
get handle
{
    return _handle;
}
create()
void_t xl::sync::IpcMutex::create (std::ctstring_t & name)
create
xTEST(!_handle.isValid());
{
    /// xTEST(!_handle.isValid());
#if   xENV_WIN
    // name
#elif xENV_UNIX
    xTEST_GR(Path::nameMaxSize() - 4, a_name.size());
#endif
    _create_impl(a_name);
}
References xl::fs::Path::nameMaxSize(), and xTEST_GR.
Referenced by xl::sync::AutoIpcMutex::AutoIpcMutex().
open()
void_t xl::sync::IpcMutex::open (std::ctstring_t & name)
open
{
    _open_impl(a_name);
}
lock()
void_t xl::sync::IpcMutex::lock (culong_t & timeoutMsec) const
unlock by timeout in msec
xTEST(_handle.isValid());
{
    /// xTEST(_handle.isValid());
    xTEST_NA(a_timeoutMsec);
    _lock_impl(a_timeoutMsec);
}
References xTEST_NA.
Referenced by xl::sync::AutoIpcMutex::AutoIpcMutex().
unlock()
void_t xl::sync::IpcMutex::unlock () const
lock
xTEST(_handle.isValid());
{
    /// xTEST(_handle.isValid());
    _unlock_impl();
}
Referenced by xl::sync::AutoIpcMutex::~AutoIpcMutex().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/IpcMutex.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/IpcMutex.cpp