xLib: xl::system::Envs Class Reference
xl::system::Envs Class Reference
system environment variables
#include "Env.h"
Public Member Functions
ctors, dtor
Envs ()
Envs (std::ctstring_t &prefix)
virtual ~Envs ()=default
xNO_COPY_ASSIGN (Envs)
Setters
void_t setVars (std::ctstring_t &envFilePath) const
set or change values from env file (for example ".env")
void_t setVars (const std::map_tstring_t &vars) const
set or change values
Getters
std::map_tstring_t vars () const
get all values
std::tstring_t findFirstOf (std::cvec_tstring_t &names) const
get first value by names
std::tstring_t operator[] (std::ctstring_t &name) const
get value by name
Static Public Member Functions
static std::tstring_t expandVars (std::ctstring_t &strWithVars)
expands strings by separator "%"
Detailed Description
system environment variables
Constructor & Destructor Documentation
Envs() [1/2]
xl::system::Envs::Envs ()
           :
    Envs(xT(""))
{
}
Envs() [2/2]
xl::system::Envs::Envs (std::ctstring_t & a_prefix) explicit
Parameters
a_prefix Like a "namespace" prefix
  :
    _prefix{a_prefix}
{
}
~Envs()
virtual xl::system::Envs::~Envs () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::Envs::xNO_COPY_ASSIGN (Envs)
setVars() [1/2]
void_t xl::system::Envs::setVars (std::ctstring_t & a_envFilePath) const
set or change values from env file (for example ".env")
Parameters
a_envFilePath file with vars ({"HOME=/usr/home","LOGNAME=home"})
{
    Config config(a_envFilePath);
    config.read();
    for (const auto &[it_name, it_value] : config.get() ) {
        Env env(_prefix, it_name);
        env.setValue(it_value);
    }
}
References xl::fs::Config::get(), xl::fs::Config::read(), and xl::system::Env::setValue().
setVars() [2/2]
void_t xl::system::Envs::setVars (const std::map_tstring_t & a_vars) const
set or change values
Parameters
a_vars vars ({"HOME=/usr/home","LOGNAME=home"})
{
    for (const auto &[it_name, it_value] : a_vars) {
        Env env(_prefix, it_name);
        env.setValue(it_value);
    }
}
References xl::system::Env::setValue().
vars()
std::map_tstring_t xl::system::Envs::vars () const
get all values
{
    std::map_tstring_t spRv;
    for (const auto &it_var : _vars_impl()) {
        std::vec_tstring_t items;
        String::split(it_var, Const::equal(), &items);
        xCHECK_DO(items.size() != 2, continue);
        spRv.emplace(items[0], items[1]);
    }
    return std::move(spRv);
}
References xl::core::Const::equal(), xl::core::String::split(), and xCHECK_DO.
findFirstOf()
std::tstring_t xl::system::Envs::findFirstOf (std::cvec_tstring_t & a_names) const
get first value by names
Parameters
a_names var names
{
    xCHECK_RET(a_names.empty(), std::tstring_t{});
    for (const auto &it_name : a_names) {
        Env env(_prefix, it_name);
        if ( env.isExists() ) {
            return env.value();
        }
    }
    return {};
}
References xl::system::Env::isExists(), xl::system::Env::value(), and xCHECK_RET.
Referenced by xl::system::User::name().
operator[]()
std::tstring_t xl::system::Envs::operator[] (std::ctstring_t & a_name) const
get value by name
Parameters
a_name var name
{
    xCHECK_RET(a_name.empty(), std::tstring_t{});
    Env env(_prefix, a_name);
    return env.value();
}
References xl::system::Env::value(), and xCHECK_RET.
expandVars()
std::tstring_t xl::system::Envs::expandVars (std::ctstring_t & strWithVars) static
expands strings by separator "%"
🪟 Windows:
Same as ExpandEnvironmentStrings()
{
    std::tstring_t sRv = a_strWithVars;
    // TODO: [unix] "$" as separator: $VAR, ${VAR}
    std::ctstring_t sep = xT("%");
    for ( ; ; ) {
        // find from left two first chars '%'
        std::csize_t startSepPos = sRv.find(sep);
        xCHECK_DO(startSepPos == std::tstring_t::npos, break);
        std::csize_t stopSepPos = sRv.find(sep, startSepPos + sep.size());
        xCHECK_DO(stopSepPos == std::tstring_t::npos, break);
        // copy %var% to temp string
        std::ctstring_t &rawEnvName = String::cut(sRv, startSepPos, stopSepPos + sep.size());
        xTEST(!rawEnvName.empty());
        std::ctstring_t &envName = String::trimChars(rawEnvName, sep);
        // expand var to temp string
        std::ctstring_t &expandedEnvValue = Env(envName).value();
        // replace envVar(%var%) by expandedEnvVar
        sRv.replace(startSepPos, rawEnvName.size(), expandedEnvValue);
    }
    return sRv;
}
References xl::core::String::cut(), xl::core::String::trimChars(), xl::system::Env::value(), xCHECK_DO, xT, and xTEST.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Env.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Env.cpp