xLib: xl::db::mysql::Error Class Reference
xl::db::mysql::Error Class Reference final
MySql error.
#include "Error.h"
Inherits xl::interface_::IError< uint_t >.
Public Member Functions
ctors, dtor
Error (const Connection &conn)
Error (const Connection &conn, std::ctstring_t &sql)
virtual ~Error ()=default
xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN (Error)
Overrides
uint_t code () const final
Code.
bool_t isOk () const final
Check for success.
std::tstring_t category () const final
Category (type)
std::tstring_t message () const final
Detail message.
Public Member Functions inherited from xl::interface_::IError< uint_t >
bool_t isFail () const
Check for error.
std::tstring_t str () const
Formatted message.
IError ()=default
virtual ~IError ()=default
Detailed Description
MySql error.
Constructor & Destructor Documentation
Error() [1/2]
xl::db::mysql::Error::Error (const Connection & conn) explicit
  :
    _conn{a_conn}
{
}
Error() [2/2]
xl::db::mysql::Error::Error (const Connection & conn, std::ctstring_t & sql)
  :
    _conn{a_conn},
    _sql {a_sql}
{
}
~Error()
virtual xl::db::mysql::Error::~Error () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::Error::xNO_DEFAULT_CONSTRUCT (Error)
xNO_COPY_ASSIGN()
xl::db::mysql::Error::xNO_COPY_ASSIGN (Error)
code()
uint_t xl::db::mysql::Error::code () const final virtual
Code.
Implements xl::interface_::IError< uint_t >.
{
    xTEST(_conn.get().isValid());
    return ::mysql_errno( _conn.get().get() );
}
References xl::db::mysql::Connection::get(), and xTEST.
Referenced by isOk().
isOk()
bool_t xl::db::mysql::Error::isOk () const final virtual
Check for success.
Implements xl::interface_::IError< uint_t >.
{
    return (code() == 0);
}
References code().
Referenced by message().
category()
std::tstring_t xl::db::mysql::Error::category () const final virtual
Category (type)
Implements xl::interface_::IError< uint_t >.
{
    return xT("xl::db::mysql::Error");
}
References xT.
message()
std::tstring_t xl::db::mysql::Error::message () const final virtual
Detail message.
Implements xl::interface_::IError< uint_t >.
{
    xTEST(_conn.get().isValid());
    if ( isOk() ) {
        return {};
    }
    std::tstring_t sRv;
    cptr_cchar_t descr = ::mysql_error(_conn.get().get());
    xTEST_PTR(descr);
    sRv = Format::str(xT("{}, SQL: \"{}\""), descr, _sql);
    return sRv;
}
References xl::db::mysql::Connection::get(), isOk(), xl::core::FormatT< StreamT >::str(), xT, xTEST, and xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Error.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Error.cpp