xLib: xl::system::ConsoleUI Class Reference
xl::system::ConsoleUI Class Reference
Shell console.
#include "ConsoleUI.h"
Public Types
enum class Result {
Abort = 0 ,
Ignore = 1 ,
Retry = 2
}
modal result
Public Member Functions
Result msgBox (std::ctstring_t &title, std::ctstring_t &text) const
show console message dialog
void_t promptBox (std::ctstring_t &title, std::ctstring_t &text, cbool_t isVisible, std::tstring_t *answer) const
show console prompt dialog
ctors, dtor
ConsoleUI ()=default
virtual ~ConsoleUI ()=default
xNO_COPY_ASSIGN (ConsoleUI)
Detailed Description
Shell console.
Member Enumeration Documentation
Result
enum class xl::system::ConsoleUI::Result strong
modal result
Enumerator
Abort
Ignore
Retry
    {
        Abort  = 0,
        Ignore = 1,
        Retry  = 2
    };
Constructor & Destructor Documentation
ConsoleUI()
xl::system::ConsoleUI::ConsoleUI () default
~ConsoleUI()
virtual xl::system::ConsoleUI::~ConsoleUI () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::ConsoleUI::xNO_COPY_ASSIGN (ConsoleUI)
msgBox()
ConsoleUI::Result xl::system::ConsoleUI::msgBox (std::ctstring_t & title, std::ctstring_t & text) const
show console message dialog
{
    xTEST_NA(a_title);
    xTEST_NA(a_text);
    Result rRv {};
    std::csize_t width     {100};
    ctchar_t     cmdAbort  {xT('a')};
    ctchar_t     cmdIgnore {xT('i')};
    ctchar_t     cmdRetry  {xT('r')};
    std::ctstring_t title = _boxLine(a_title, width) + Const::nl();
    std::tstring_t multiText;
    {
        std::vec_tstring_t text;
        String::split(a_text, Const::nl(), &text);
        for (const auto &it : text) {
            multiText += _boxLine(it, width) + Const::nl();
        }
    }
    _console.writeLine();
    _console.writeLine(Format::str(xT("+{}+"), std::tstring_t(width - 2, xT('-'))));
    _console.writeLine(Format::str(xT("|{}|"), std::tstring_t(width - 2, xT(' '))));
    _console.write(title);
    _console.writeLine(Format::str(xT("|{}|"), std::tstring_t(width - 2, xT(' '))));
    _console.write(multiText);
    _console.writeLine(Format::str(xT("|{}|"), std::tstring_t(width - 2, xT(' '))));
    _console.writeLine(Format::str(xT("+{}+"), std::tstring_t(width - 2, xT('-'))));
    _console.writeLine();
    _console.write(Format::str(xT("\nAbort ({}), Ignore ({}), Retry ({}): "),
        cmdAbort, cmdIgnore, cmdRetry));
    const auto consoleCmd = CharT( static_cast<tchar_t>(std::tcin.get()) ).toLower().get();
    std::tcin.ignore();
    switch (consoleCmd) {
    case cmdAbort:
        rRv = Result::Abort;
        _console.writeLine(xT("Abort..."));
        break;
    case cmdIgnore:
        rRv = Result::Ignore;
        _console.writeLine(xT("Ignore..."));
        break;
    case cmdRetry:
        rRv = Result::Retry;
        _console.writeLine(xT("Retry..."));
        break;
    default:
        rRv = Result::Retry;
        _console.writeLine(xT("Retry..."));
        break;
    }
    return rRv;
}
References Abort, Ignore, xl::core::Const::nl(), Retry, xl::core::String::split(), xl::core::FormatT< StreamT >::str(), xl::system::Console::write(), xl::system::Console::writeLine(), xT, and xTEST_NA.
promptBox()
void_t xl::system::ConsoleUI::promptBox (std::ctstring_t & a_title, std::ctstring_t & a_text, cbool_t a_isVisible, std::tstring_t * out_answer) const
show console prompt dialog
Parameters
a_title title
a_text input text
a_isVisible is input text visible
[out] out_answer answer
{
    xTEST_NA(a_title);
    xTEST_NA(a_text);
    xTEST_NA(a_isVisible);
    xTEST_PTR(out_answer);
    // Title
    _console.write(a_title);
    // Text
    _setStdinEcho(a_isVisible);
    ctchar_t keyEnter     {10};
    ctchar_t keyBackspace {0x8};
    for ( ; ; ) {
        _console.write(a_text + xT(": "));
        for ( ; ; ) {
            ctchar_t ch = static_cast<tchar_t>( std::tcin.get() );
            xCHECK_DO(ch == keyEnter, break);
            xCHECK_DO(ch == keyBackspace, out_answer->clear(); continue);
            out_answer->push_back(ch);
        }
        _console.writeLine(Const::strEmpty());
        xCHECK_DO(out_answer->empty(), continue);
        break;
    }
    if ( !a_isVisible ) {
        _setStdinEcho(true);
    }
}
References xl::core::Const::strEmpty(), xl::system::Console::write(), xl::system::Console::writeLine(), xCHECK_DO, xT, xTEST_NA, and xTEST_PTR.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/ConsoleUI.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/ConsoleUI.cpp