xLib: xl::core::Utils Class Reference
xl::core::Utils Class Reference
help utils
#include "Utils.h"
Public Member Functions
template<typename ToT , typename FromT >
ToT implicitCast (const FromT &a_from)
ctors, dtor
xNO_DEFAULT_CONSTRUCT (Utils)
xNO_COPY_ASSIGN (Utils)
Static Public Member Functions
Delete
template<typename T >
static void_t ptrDeleteT (T *&ptr)
delete object by pointer
template<typename T >
static void_t arrayDeleteT (T *&ptr)
delete array by pointer
Etc
template<typename T >
static void_t ptrAssignT (T *&ptr, const T &value)
assign pointer
template<typename T , std::csize_t arraySize>
static constexpr size_t arraySizeT (const T(&)[arraySize])
get array size
Zero
static void_t memoryZero (void_t *ptr, std::csize_t sizeBytes)
zero memory
template<typename T , std::csize_t arraySize>
static void_t arrayZeroT (T(&arrayT)[arraySize])
array zero
Free
template<typename T , typename F , typename N >
static void_t freeT (T *&ptr, F func, N null=nullptr)
free pointer
template<typename T >
static void_t bufferFreeT (T *&ptr)
free buffer memory
Algos
template<typename T >
static const T & maxT (const T &value1, const T &value2)
get max value
template<typename T >
static const T & minT (const T &value1, const T &value2)
get min value
template<typename T >
static void_t swapT (T &value1, T &value2)
swap variables
Cast
template<typename ToT , typename FromT >
static ToT c_cast (const FromT &value)
C-style cast.
template<typename ToT , class FromT >
static ToT reinterpretCastT (const FromT &ptr)
allows any pointer to be converted into any other pointer type
template<typename To , typename From >
static To implicitCast (const From &a_from)
https://www.boost.org/doc/libs/1_64_0/boost/implicit_cast.hpp
Math operations
template<typename T >
static T roundIntT (cdouble_t value)
round double value to long_t
template<typename T >
static T intSafeDiv (const T &value1, const T &value2)
safe division
Enum
template<typename T >
static T enumIncT (const T &value)
increment enumerator
template<typename T >
static T enumDecT (const T &value)
decrement enumerator
Detailed Description
help utils
Definition at line 14 of file Utils.h.
Member Function Documentation
arrayDeleteT()
template<typename T > void_t xl::core::Utils::arrayDeleteT (T *& ptr) inline static
delete array by pointer
Definition at line 40 of file Utils.inl.
{
    T* tmp {};
    std::swap(a_ptr, tmp);
    delete [] tmp; tmp = nullptr;
}
arraySizeT()
template<typename T , std::csize_t arraySize> constexpr size_t xl::core::Utils::arraySizeT (const T(&)[arraySize]) inline static constexpr
get array size
Definition at line 66 of file Utils.inl.
{
    return arraySize;
}
arrayZeroT()
template<typename T , std::csize_t arraySize> void_t xl::core::Utils::arrayZeroT (T(&) arrayT[arraySize]) inline static
array zero
Definition at line 89 of file Utils.inl.
{
    (void_t)std::fill_n(&a_arrayT[0], arraySize, T{});
}
bufferFreeT()
template<typename T > void_t xl::core::Utils::bufferFreeT (T *& ptr) inline static
free buffer memory
Definition at line 114 of file Utils.inl.
{
    freeT(a_ptr, ::free, nullptr);
}
References freeT().
c_cast()
template<typename ToT , typename FromT > ToT xl::core::Utils::c_cast (const FromT & value) inline static
C-style cast.
Definition at line 160 of file Utils.inl.
{
#if 0
    return (ToT)a_value;
#else
    return reinterpretCastT<ToT>(a_value);
#endif
}
enumDecT()
template<typename T > T xl::core::Utils::enumDecT (const T & value) inline static
decrement enumerator
Definition at line 243 of file Utils.inl.
{
    return static_cast<T>( static_cast<longlong_t>( a_value ) - 1 );
}
enumIncT()
template<typename T > T xl::core::Utils::enumIncT (const T & value) inline static
increment enumerator
Definition at line 234 of file Utils.inl.
{
    return static_cast<T>( static_cast<longlong_t>( a_value ) + 1 );
}
freeT()
template<typename T , typename F , typename N > void_t xl::core::Utils::freeT (T *& ptr, F func, N null = nullptr) inline static
free pointer
Definition at line 99 of file Utils.inl.
{
    xCHECK_DO(a_ptr == a_null, return);
    a_func(a_ptr);
    a_ptr = a_null;
}
References xCHECK_DO.
Referenced by bufferFreeT(), and xl::package::xml::Doc::format().
implicitCast()
template<typename ToT , typename FromT > ToT xl::core::Utils::implicitCast (const FromT & a_from) inline
Definition at line 187 of file Utils.inl.
{
    return a_from;
}
intSafeDiv()
template<typename T > T xl::core::Utils::intSafeDiv (const T & value1, const T & value2) inline static
safe division
Definition at line 218 of file Utils.inl.
{
    static_assert(std::is_integral<T>::value, "");
    if (a_value2 == 0) {
        return 0;
    }
    return a_value1 / a_value2;
}
maxT()
template<typename T > const T & xl::core::Utils::maxT (const T & value1, const T & value2) inline static
get max value
Definition at line 124 of file Utils.inl.
{
    return (a_value1 > a_value2) ? a_value1 : a_value2;
}
memoryZero()
void_t xl::core::Utils::memoryZero (void_t * ptr, std::csize_t sizeBytes) inline static
zero memory
Definition at line 75 of file Utils.inl.
{
    xCHECK_DO(a_ptr == nullptr, return);
    void_t *pvRv = std::memset(a_ptr, 0, a_sizeBytes);
    xUNUSED(pvRv);
}
References xCHECK_DO, and xUNUSED.
minT()
template<typename T > const T & xl::core::Utils::minT (const T & value1, const T & value2) inline static
get min value
Definition at line 135 of file Utils.inl.
{
    return (a_value1 < a_value2) ? a_value1 : a_value2;
}
ptrAssignT()
template<typename T > void_t xl::core::Utils::ptrAssignT (T *& ptr, const T & value) inline static
assign pointer
Definition at line 53 of file Utils.inl.
{
    xCHECK_DO(a_ptr == nullptr, return);
    *a_ptr = a_value;
}
References xCHECK_DO.
Referenced by xl::package::GitClient::commitsAheadBehind(), xl::core::DateTime::get(), xl::net::DnsClient::protocolByName(), xl::net::DnsClient::protocolByNumber(), xl::net::DnsClient::serviceByName(), xl::net::DnsClient::serviceByPort(), and xl::net::TcpClient::timeout().
ptrDeleteT()
template<typename T > void_t xl::core::Utils::ptrDeleteT (T *& ptr) inline static
delete object by pointer
Definition at line 27 of file Utils.inl.
{
    T* tmp {};
    std::swap(a_ptr, tmp);
    delete tmp; tmp = nullptr;
}
Referenced by xl::algos::Algos::deleteAll().
reinterpretCastT()
template<typename ToT , class FromT > ToT xl::core::Utils::reinterpretCastT (const FromT & ptr) inline static
allows any pointer to be converted into any other pointer type
Definition at line 174 of file Utils.inl.
{
    auto *pvVoidCast = static_cast<void_t *>(a_ptr);
    auto  resT       = static_cast<ToT>(pvVoidCast);
    return resT;
}
roundIntT()
template<typename T > T xl::core::Utils::roundIntT (cdouble_t value) inline static
round double value to long_t
Definition at line 197 of file Utils.inl.
{
    assert(a_value >= static_cast<double_t>( (std::numeric_limits<T>::min)() ) - 0.5);
    assert(a_value <= static_cast<double_t>( (std::numeric_limits<T>::max)() ) + 0.5);
    T iRv {};
    if (a_value > 0.0) {
        iRv = static_cast<T>( a_value + 0.5 );
    } else {
        iRv = static_cast<T>( a_value - 0.5 );
    }
    return iRv;
}
swapT()
template<typename T > void_t xl::core::Utils::swapT (T & value1, T & value2) inline static
swap variables
Definition at line 146 of file Utils.inl.
{
    T temp = a_value1;
    a_value1 = a_value2;
    a_value2 = temp;
}
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Utils.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Utils.inl