xLib: xl::debug::NativeError Class Reference
xl::debug::NativeError Class Reference final
system last error
#include "NativeError.h"
Inherits xl::interface_::IError< ulong_t >.
Public Member Functions
ctors, dtor
NativeError ()
NativeError (culong_t code)
xNO_COPY_ASSIGN (NativeError)
void_t set (culong_t code)
set the last error code for the calling thread
void_t clear ()
set last error code to success value (0)
Overrides
ulong_t code () const final
Code.
bool_t isOk () const final
Check for success.
std::tstring_t category () const final
Category (type)
std::tstring_t message () const final
Detail message.
Public Member Functions inherited from xl::interface_::IError< ulong_t >
bool_t isFail () const
Check for error.
std::tstring_t str () const
Formatted message.
IError ()=default
virtual ~IError ()=default
Detailed Description
system last error
Constructor & Destructor Documentation
NativeError() [1/2]
xl::debug::NativeError::NativeError ()
                         :
    NativeError( _fetchCode_impl() )
{
}
NativeError() [2/2]
xl::debug::NativeError::NativeError (culong_t code) explicit
  :
    _code{a_code}
{
}
Member Function Documentation
xNO_COPY_ASSIGN()
xl::debug::NativeError::xNO_COPY_ASSIGN (NativeError)
set()
void_t xl::debug::NativeError::set (culong_t code)
set the last error code for the calling thread
{
    _set_impl(a_code);
    _code = a_code;
}
Referenced by clear(), and xl::debug::NativeErrorSaver::~NativeErrorSaver().
clear()
void_t xl::debug::NativeError::clear ()
set last error code to success value (0)
{
    set( _nativeCodeOk() );
}
References set().
code()
ulong_t xl::debug::NativeError::code () const final virtual
Code.
Implements xl::interface_::IError< ulong_t >.
{
    return _code;
}
Referenced by xl::debug::NativeErrorSaver::~NativeErrorSaver().
isOk()
bool_t xl::debug::NativeError::isOk () const final virtual
Check for success.
Implements xl::interface_::IError< ulong_t >.
{
    return (_code == _nativeCodeOk());
}
category()
std::tstring_t xl::debug::NativeError::category () const final virtual
Category (type)
Implements xl::interface_::IError< ulong_t >.
{
    return xT("xl::debug::NativeError");
}
References xT.
message()
std::tstring_t xl::debug::NativeError::message () const final virtual
Detail message.
Implements xl::interface_::IError< ulong_t >.
{
    return _message_impl(_code);
}
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Debug/NativeError.h
/home/runner/work/xLib/xLib/Include/xLib/Debug/NativeError.cpp