xLib: xl::package::GitClient Class Reference
xl::package::GitClient Class Reference
GIT client.
#include "GitClient.h"
Public Member Functions
bool isGitDir () const
check Git directory
ctors, dtor
GitClient ()
virtual ~GitClient ()=default
xNO_COPY_ASSIGN (GitClient)
Repositories
std::tstring_t repoUrl () const
get repo URL
std::tstring_t repoUrlName () const
get repo URL name
std::tstring_t repoName () const
get repository name
void_t remoteRepoNames (std::vec_tstring_t *repoNames) const
get remote repository names
std::tstring_t gitlabRepoGroupName () const
Gitalb: get group repository name.
Branches
std::tstring_t branchName () const
get brach name
std::size_t localBranchesNum () const
number of local branches
Statuses
std::tstring_t filesStatuses () const
get source files statuses
void_t commitsAheadBehind (std::size_t *aheadNum, std::size_t *behindNum) const
get number commits ahead behind
std::size_t stashesNum () const
get stashes number
void_t modifiedFiles (std::cvec_tstring_t &filterFileExts, std::vec_tstring_t *filePathes) const
get modified files
void_t trackedFiles (std::cvec_tstring_t &filterFileExts, std::vec_tstring_t *filePathes) const
get tracked files
void_t modifiedFilesLineFilter () const
get modified lines line filter (JSON)
Detailed Description
GIT client.
Constructor & Destructor Documentation
GitClient()
xl::package::GitClient::GitClient ()
                     :
    _gitPath( _binPath() )
{
}
~GitClient()
virtual xl::package::GitClient::~GitClient () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::package::GitClient::xNO_COPY_ASSIGN (GitClient)
isGitDir()
bool xl::package::GitClient::isGitDir () const
check Git directory
{
    std::cvec_tstring_t params {"rev-parse", "--git-dir"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    xCHECK_RET(!stdError.empty(), false);
    xCHECK_RET((stdOut.find(xT(".git")) == std::tstring_t::npos), false);
    return true;
}
References xCHECK_RET, and xT.
Referenced by branchName(), commitsAheadBehind(), filesStatuses(), gitlabRepoGroupName(), localBranchesNum(), modifiedFiles(), modifiedFilesLineFilter(), remoteRepoNames(), repoName(), repoUrl(), repoUrlName(), stashesNum(), and trackedFiles().
repoUrl()
std::tstring_t xl::package::GitClient::repoUrl () const
get repo URL
HTTP(s)/Git proto.
* - git@bitbucket.org:skynowa/faq.git
* - ssh://git@gitlab.maklai.dev:8999/suppliers/services-sync.git
* - ssh://git@stash.fabrica.net.ua:7999/trav/booked.git
*
* - https://github.com/FIvanO/PocketBookTest
*
* - https://skynowa@git.code.sf.net/p/x-lib/code
*
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::tstring_t sRv;
    std::cvec_tstring_t params {"config", "--get", "remote.origin.url"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    sRv = String::trimSpace(stdOut);
    return sRv;
}
References isGitDir(), xl::core::String::trimSpace(), xCHECK_RET, and xT.
Referenced by gitlabRepoGroupName(), and repoUrlName().
repoUrlName()
std::tstring_t xl::package::GitClient::repoUrlName () const
get repo URL name
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::ctstring_t &url = repoUrl();
    constexpr std::array protos
    {
        xT("git@"),         // without protos
        xT("@git.code."),   // sourceforge.net
        xT("://")           // with protos
    };
    for (const auto &it_proto : protos) {
        xCHECK_DO(url.find(it_proto) == std::tstring_t::npos, continue);
        return String::cut(url, it_proto, xT(".")) ;
    }
    return {};
}
References xl::core::String::cut(), isGitDir(), repoUrl(), xCHECK_DO, xCHECK_RET, and xT.
repoName()
std::tstring_t xl::package::GitClient::repoName () const
get repository name
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::tstring_t sRv;
    std::cvec_tstring_t params {"rev-parse", "--show-toplevel"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    sRv = String::trimSpace( Path(stdOut).fileBaseName() );
    return sRv;
}
References isGitDir(), xl::core::String::trimSpace(), xCHECK_RET, and xT.
remoteRepoNames()
void_t xl::package::GitClient::remoteRepoNames (std::vec_tstring_t * out_repoNames) const
get remote repository names
Parameters
[out] out_repoNames
{
    xCHECK_DO(out_repoNames == nullptr, return);
    xCHECK_DO(!isGitDir(), return);
    out_repoNames->clear();
    std::cvec_tstring_t params {"remote"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    // [out]
    String::split(String::trimSpace(stdOut), Const::nl(), out_repoNames);
}
References isGitDir(), xl::core::Const::nl(), xl::core::String::split(), xl::core::String::trimSpace(), and xCHECK_DO.
gitlabRepoGroupName()
std::tstring_t xl::package::GitClient::gitlabRepoGroupName () const
Gitalb: get group repository name.
URL
ssh://git@gitlab.maklai.dev:8999/tripnet/services.git
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::tstring_t sRv;
   /**
    * URL
    *
    * \code
    * ssh://git@gitlab.maklai.dev:8999/tripnet/services.git
    * \endcode
    */
    std::ctstring_t &url = repoUrl();
    // Cout() << xTRACE_VAR(url);
    constexpr std::array protos
    {
        xT("git@gitlab")    // without protos
    };
    for (const auto &it_proto : protos) {
        xCHECK_DO(url.find(it_proto) == std::tstring_t::npos, continue);
        // Parse
        {
            std::ctstring_t a_str      = url;
            std::ctstring_t a_sepRight = xT("/");
            std::ctstring_t a_sepLeft  = xT("/");
            xTEST_NA(a_str);
            xTEST_NA(a_sepLeft);
            xTEST_NA(a_sepRight);
            size_t delimPosStop = a_str.rfind(a_sepRight);
            // Cout() << xTRACE_VAR(delimPosStop);
            xCHECK_RET(delimPosStop == std::tstring_t::npos, std::tstring_t());
            delimPosStop += a_sepRight.size() - 1;
            size_t delimPosStart  = a_str.rfind(a_sepLeft, delimPosStop - 1);
            // Cout() << xTRACE_VAR(delimPosStart);
            xCHECK_RET(delimPosStart == std::tstring_t::npos, std::tstring_t());
            xCHECK_RET(delimPosStart >= delimPosStop,         std::tstring_t());
            sRv = a_str.substr(delimPosStart + a_sepLeft.size(), delimPosStop - delimPosStart - 1);
            // Cout() << xTRACE_VAR(sRv);
            return sRv;
        }
    }
    return {};
}
References isGitDir(), repoUrl(), xCHECK_DO, xCHECK_RET, xT, and xTEST_NA.
branchName()
std::tstring_t xl::package::GitClient::branchName () const
get brach name
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::tstring_t sRv;
    std::cvec_tstring_t params {"rev-parse", "--abbrev-ref", "HEAD"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    if      ( stdOut.empty() ) {
        sRv = xT("");
    }
    else if (stdOut == xT("HEAD")) {
        sRv = xT("detached");
    }
    else {
        sRv = stdOut;
    }
    sRv = String::trimSpace(sRv);
    return sRv;
}
References isGitDir(), xl::core::String::trimSpace(), xCHECK_RET, and xT.
Referenced by commitsAheadBehind().
localBranchesNum()
std::size_t xl::package::GitClient::localBranchesNum () const
number of local branches
{
    xCHECK_RET(!isGitDir(), 0);
    std::cvec_tstring_t params {"branch"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    std::vec_tstring_t values;
    String::split(String::trimSpace(stdOut), Const::nl(), &values);
    xCHECK_RET(values.empty(), 0);
    // without "master"
    return values.size() - 1;
}
References isGitDir(), xl::core::Const::nl(), xl::core::String::split(), xl::core::String::trimSpace(), and xCHECK_RET.
filesStatuses()
std::tstring_t xl::package::GitClient::filesStatuses () const
get source files statuses
git_states=""
get_git_states()
{
   local status=`git status 2>&1 | tee`
   local nocommit=`echo  "${status}" 2> /dev/null | grep "nothing to commit" &> /dev/null; echo "$?"`
   local dirty=`echo     "${status}" 2> /dev/null | grep "modified:"         &> /dev/null; echo "$?"`
   local untracked=`echo "${status}" 2> /dev/null | grep "Untracked files"   &> /dev/null; echo "$?"`
   local newfile=`echo   "${status}" 2> /dev/null | grep "new file:"         &> /dev/null; echo "$?"`
   local renamed=`echo   "${status}" 2> /dev/null | grep "renamed:"          &> /dev/null; echo "$?"`
   local deleted=`echo   "${status}" 2> /dev/null | grep "deleted:"          &> /dev/null; echo "$?"`
    git_states=""
   if [ "${nocommit}" == "0" ]; then
    git_states=""
   fi
   if [ "${renamed}" == "0" ]; then
    git_states="${git_states}"
   fi
   if [ "${newfile}" == "0" ]; then
    git_states="+${git_states}"
   fi
   if [ "${untracked}" == "0" ]; then
    git_states="${git_states}"
   fi
   if [ "${deleted}" == "0" ]; then
    git_states="${git_states}"
   fi
   if [ "${dirty}" == "0" ]; then
    git_states="${git_states}"
   fi
}
{
    xCHECK_RET(!isGitDir(), xT(""));
    std::cvec_tstring_t params {"status"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    cbool_t isNoCommit  = StringCI::contains(stdOut, xT("nothing to commit"));
    cbool_t isModified  = StringCI::contains(stdOut, xT("modified:"));
    cbool_t isUntracked = StringCI::contains(stdOut, xT("Untracked files"));
    cbool_t isNew       = StringCI::contains(stdOut, xT("new file:"));
    cbool_t isRenamed   = StringCI::contains(stdOut, xT("renamed:"));
    cbool_t isDeleted   = StringCI::contains(stdOut, xT("deleted:"));
    std::tstring_t sRv;
    if (isNoCommit) {
        sRv += xT("");
    }
    if (isRenamed) {
        sRv += xT("");
    }
    if (isNew) {
        sRv += xT("");
    }
    if (isUntracked) {
        sRv += xT("");
    }
    if (isDeleted) {
        sRv += xT("");
    }
    if (isModified) {
        sRv += xT("");
    }
    return sRv;
}
References xl::core::StringCI::contains(), isGitDir(), xCHECK_RET, and xT.
commitsAheadBehind()
void_t xl::package::GitClient::commitsAheadBehind (std::size_t * out_aheadNum, std::size_t * out_behindNum) const
get number commits ahead behind
 find_git_ahead_behind()
 {
    if ! $(is_git); then
        git_ahead_behind=""
        return
    fi
    local status=$(git rev-list --left-right --count origin/master...$branch)
    local aheadRegex="([0-9]+)"
    local behindRegex="\s(\w+)$"
    [[ $status =~ $aheadRegex ]]  && ahead="${BASH_REMATCH[1]}"  || ahead="0"
    [[ $status =~ $behindRegex ]] && behind="${BASH_REMATCH[1]}" || behind="0"
??? [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit, working tree clean" ]] && git_ahead_behind=""
    [[ $ahead != "0" ]]  && git_ahead_behind="${ahead}"
    [[ $behind != "0" ]] && git_ahead_behind="${behind}"
 }
Parameters
[out] out_aheadNum ahead number
[out] out_behindNum behind number
{
    Utils::ptrAssignT(out_aheadNum,  std::size_t{});
    Utils::ptrAssignT(out_behindNum, std::size_t{});
    xCHECK_DO(!isGitDir(), return);
    std::cvec_tstring_t params {"rev-list", "--left-right", "--count", "origin/master..." + branchName()};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    std::vec_tstring_t values;
    String::split(stdOut, Const::ht(), &values);
    if (values.size() != 2) {
        return;
    }
    Utils::ptrAssignT(out_aheadNum,  String::cast<std::size_t>(String::trimSpace(values[0])));
    Utils::ptrAssignT(out_behindNum, String::cast<std::size_t>(String::trimSpace(values[1])));
}
References branchName(), xl::core::Const::ht(), isGitDir(), xl::core::Utils::ptrAssignT(), xl::core::String::split(), xl::core::String::trimSpace(), and xCHECK_DO.
stashesNum()
std::size_t xl::package::GitClient::stashesNum () const
get stashes number
{
    xCHECK_RET(!isGitDir(), 0);
    std::cvec_tstring_t params {"stash", "list"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
    std::vec_tstring_t values;
    String::split(String::trimSpace(stdOut), Const::nl(), &values);
    return values.size();
}
References isGitDir(), xl::core::Const::nl(), xl::core::String::split(), xl::core::String::trimSpace(), and xCHECK_RET.
modifiedFiles()
void_t xl::package::GitClient::modifiedFiles (std::cvec_tstring_t & a_filterFileExts, std::vec_tstring_t * out_filePathes) const
get modified files
Parameters
a_filterFileExts (Maybe empty)
[out] out_filePathes file paths
{
    xCHECK_DO(out_filePathes == nullptr, return);
    xCHECK_DO(!isGitDir(), return);
    out_filePathes->clear();
    bool_t bRv {};
    std::cvec_tstring_t params {"status", "--short"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params, &stdOut, &stdError);
#if 0
    Cout() << xTRACE_VAR(stdOut);
    Cout() << xTRACE_VAR(stdError);
#endif
    std::vec_tstring_t values;
    String::split(String::trimSpace(stdOut), Const::nl(), &values);
    xCHECK_DO(values.empty(), return);
    for (const auto &it_value : values) {
        std::ctstring_t &filePath = String::trimSpace(it_value);
        // Filter
        if ( !a_filterFileExts.empty() ) {
            std::ctstring_t &fileExt = Path(filePath).ext();
            bRv = Algos::isContains(a_filterFileExts, fileExt);
            xCHECK_DO(!bRv, continue);
        }
        out_filePathes->push_back(filePath);
    } // for (values)
}
References xl::fs::Path::ext(), xl::algos::Algos::isContains(), isGitDir(), xl::core::Const::nl(), xl::core::String::split(), xl::core::String::trimSpace(), xCHECK_DO, and xTRACE_VAR.
trackedFiles()
void_t xl::package::GitClient::trackedFiles (std::cvec_tstring_t & a_filterFileExts, std::vec_tstring_t * out_filePathes) const
get tracked files
std::cvec_tstring_t params_commit_diff {"diff", "--name-only", "--cached", "--diff-filter=ACM"}; std::cvec_tstring_t params_master_diff {"diff", "--name-only", "master"};
Parameters
a_filterFileExts filter file extentions
[out] out_filePathes file paths
{
    xCHECK_DO(out_filePathes == nullptr, return);
    xCHECK_DO(!isGitDir(), return);
    out_filePathes->clear();
    bool_t bRv {};
    /// std::cvec_tstring_t params_commit_diff {"diff", "--name-only", "--cached", "--diff-filter=ACM"};
    /// std::cvec_tstring_t params_master_diff {"diff", "--name-only", "master"};
    std::cvec_tstring_t params_master_diff {"diff", "--name-only",
        "--line-prefix=" + Dir::current().str() + "/", "master"};
    std::tstring_t      stdOut;
    std::tstring_t      stdError;
    _gitExecute(params_master_diff, &stdOut, &stdError);
#if 0
    Cout() << xTRACE_VAR(stdOut);
    Cout() << xTRACE_VAR(stdError);
#endif
    std::vec_tstring_t values;
    String::split(String::trimSpace(stdOut), Const::nl(), &values);
    xCHECK_DO(values.empty(), return);
    for (const auto &it_value : values) {
        std::ctstring_t &filePath = String::trimSpace(it_value);
        // Filter
        if ( !a_filterFileExts.empty() ) {
            std::ctstring_t &fileExt = Path(filePath).ext();
            bRv = Algos::isContains(a_filterFileExts, fileExt);
            xCHECK_DO(!bRv, continue);
        }
        out_filePathes->push_back(filePath);
    } // for (values)
}
References xl::fs::Dir::current(), xl::fs::Path::ext(), xl::algos::Algos::isContains(), isGitDir(), xl::core::Const::nl(), xl::core::String::split(), xl::fs::Dir::str(), xl::core::String::trimSpace(), xCHECK_DO, and xTRACE_VAR.
modifiedFilesLineFilter()
void_t xl::package::GitClient::modifiedFilesLineFilter () const
get modified lines line filter (JSON)
def getGitModifiedFilesLineFilter(self):
    "" Get current GIT modified lines line filter (JSON) ""
    # strip the smallest prefix containing P slashes
    p      = 1
    iregex = r'.*\.(h|hh|hpp|inl|cc|cpp|cxx)'
    cmd = "git diff -U0 HEAD".split()
    out = subprocess.Popen(cmd, stdout = subprocess.PIPE, stderr = subprocess.PIPE)
    ## result = stderr.strip().decode("utf8")
    # print("stderr: ", result)
    # extract changed lines for each file
    filename      = None
    lines_by_file = {}
    for it_line in iter(out.stdout.readline, ''):
        line = it_line.decode("utf-8")
        if (not line):
            break
        match = re.search('^\+\+\+\ \"?(.*?/){%s}([^ \t\n\"]*)' % p, line)
        if (match):
            filename = match.group(2)
        if (filename == None):
            continue
        if (not re.match('^%s$' % iregex, filename, re.IGNORECASE)):
            continue
        # print("C++ filename: ", filename)
        match = re.search('^@@.*\+(\d+)(,(\d+))?', line)
        if (match):
            start_line = int(match.group(1))
            line_count = 1
            if (match.group(3)):
                line_count = int(match.group(3))
            if (line_count == 0):
                continue
            end_line = start_line + line_count - 1;
            lines_by_file.setdefault(filename, []).append([start_line, end_line])
    # for (out.stdout)
    if (len(lines_by_file) == 0):
        print("No diffs")
        sys.exit(0)
    line_filter_json = json.dumps(
        [{"name" : name, "lines" : lines_by_file[name]} for name in lines_by_file],
        separators = (',', ':'))
    return line_filter_json
{
    xCHECK_DO(!isGitDir(), return);
   /**
    * \code{.py}
    * def getGitModifiedFilesLineFilter(self):
    *   "" Get current GIT modified lines line filter (JSON) ""
    *
    *   # strip the smallest prefix containing P slashes
    *   p      = 1
    *   iregex = r'.*\.(h|hh|hpp|inl|cc|cpp|cxx)'
    *
    *   cmd = "git diff -U0 HEAD".split()
    *
    *   out = subprocess.Popen(cmd, stdout = subprocess.PIPE, stderr = subprocess.PIPE)
    *
    *   ## result = stderr.strip().decode("utf8")
    *   # print("stderr: ", result)
    *
    *   # extract changed lines for each file
    *   filename      = None
    *   lines_by_file = {}
    *
    *   for it_line in iter(out.stdout.readline, ''):
    *       line = it_line.decode("utf-8")
    *       if (not line):
    *           break
    *
    *       match = re.search('^\+\+\+\ \"?(.*?/){%s}([^ \t\n\"]*)' % p, line)
    *       if (match):
    *           filename = match.group(2)
    *
    *       if (filename == None):
    *           continue
    *
    *       if (not re.match('^%s$' % iregex, filename, re.IGNORECASE)):
    *           continue
    *
    *       # print("C++ filename: ", filename)
    *
    *       match = re.search('^@@.*\+(\d+)(,(\d+))?', line)
    *       if (match):
    *           start_line = int(match.group(1))
    *           line_count = 1
    *
    *           if (match.group(3)):
    *               line_count = int(match.group(3))
    *
    *           if (line_count == 0):
    *               continue
    *
    *           end_line = start_line + line_count - 1;
    *           lines_by_file.setdefault(filename, []).append([start_line, end_line])
    *   # for (out.stdout)
    *
    *   if (len(lines_by_file) == 0):
    *       print("No diffs")
    *       sys.exit(0)
    *
    *   line_filter_json = json.dumps(
    *       [{"name" : name, "lines" : lines_by_file[name]} for name in lines_by_file],
    *       separators = (',', ':'))
    *
    *   return line_filter_json
    * \endcode
    */
}
References isGitDir(), and xCHECK_DO.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/GitClient.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/GitClient.cpp