xLib: xl::core::Const Class Reference
xl::core::Const Class Reference
Method's postfix:
#include "Const.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (Const)
xNO_COPY_ASSIGN (Const)
Static Public Member Functions
static std::cstring_t & strEmptyA ()
static std::cwstring_t & strEmptyW ()
static std::ctstring_t & strEmpty ()
static std::cstring_t & crA ()
static std::cwstring_t & crW ()
static std::ctstring_t & cr ()
static std::cstring_t & nlA ()
static std::cwstring_t & nlW ()
static std::ctstring_t & nl ()
static std::cstring_t & crNlA ()
static std::cwstring_t & crNlW ()
static std::ctstring_t & crNl ()
static std::cstring_t & colonA ()
static std::cwstring_t & colonW ()
static std::ctstring_t & colon ()
static std::cstring_t & winSlashA ()
static std::cwstring_t & winSlashW ()
static std::ctstring_t & winSlash ()
static std::cstring_t & unixSlashA ()
static std::cwstring_t & unixSlashW ()
static std::ctstring_t & unixSlash ()
static std::cstring_t & slashA ()
static std::cwstring_t & slashW ()
static std::ctstring_t & slash ()
static std::cstring_t & eolA ()
static std::cwstring_t & eolW ()
static std::ctstring_t & eol ()
static std::cstring_t & semicolonA ()
static std::cwstring_t & semicolonW ()
static std::ctstring_t & semicolon ()
static std::cstring_t & dotA ()
static std::cwstring_t & dotW ()
static std::ctstring_t & dot ()
static std::cstring_t & dot2A ()
static std::cwstring_t & dot2W ()
static std::ctstring_t & dot2 ()
static std::cstring_t & dot3A ()
static std::cwstring_t & dot3W ()
static std::ctstring_t & dot3 ()
static std::cstring_t & maskAllA ()
static std::cwstring_t & maskAllW ()
static std::ctstring_t & maskAll ()
static std::cstring_t & htA ()
static std::cwstring_t & htW ()
static std::ctstring_t & ht ()
static std::cstring_t & vtA ()
static std::cwstring_t & vtW ()
static std::ctstring_t & vt ()
static std::cstring_t & spaceA ()
static std::cwstring_t & spaceW ()
static std::ctstring_t & space ()
static std::cstring_t & bellA ()
static std::cwstring_t & bellW ()
static std::ctstring_t & bell ()
static std::cstring_t & bsA ()
static std::cwstring_t & bsW ()
static std::ctstring_t & bs ()
static std::cstring_t & ffA ()
static std::cwstring_t & ffW ()
static std::ctstring_t & ff ()
static std::cstring_t & qmA ()
static std::cwstring_t & qmW ()
static std::ctstring_t & qm ()
static std::cstring_t & sqmA ()
static std::cwstring_t & sqmW ()
static std::ctstring_t & sqm ()
static std::cstring_t & dqmA ()
static std::cwstring_t & dqmW ()
static std::ctstring_t & dqm ()
static std::cstring_t & gaA ()
static std::cwstring_t & gaW ()
static std::ctstring_t & ga ()
static std::cstring_t & whiteSpacesA ()
static std::cwstring_t & whiteSpacesW ()
static std::ctstring_t & whiteSpaces ()
static std::cstring_t & equalA ()
static std::cwstring_t & equalW ()
static std::ctstring_t & equal ()
static std::cstring_t & hyphenA ()
static std::cwstring_t & hyphenW ()
static std::ctstring_t & hyphen ()
static std::cstring_t & strUnknownA ()
static std::cwstring_t & strUnknownW ()
static std::ctstring_t & strUnknown ()
Detailed Description
Method's postfix:
"A" - ansi
"W" - unicode
Without - ansi or unicode depends on configs (
🔗 See also:
Macro xUNICODE) Constants
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::core::Const::xNO_DEFAULT_CONSTRUCT (Const)
xNO_COPY_ASSIGN()
xl::core::Const::xNO_COPY_ASSIGN (Const)
strEmptyA()
std::cstring_t & xl::core::Const::strEmptyA () static
{
    static std::cstring_t sRv;
    return sRv;
}
strEmptyW()
std::cwstring_t & xl::core::Const::strEmptyW () static
{
    static std::cwstring_t sRv;
    return sRv;
}
strEmpty()
std::ctstring_t & xl::core::Const::strEmpty () static
{
    static std::ctstring_t sRv;
    return sRv;
}
Referenced by xl::system::ConsoleUI::promptBox(), xl::fs::Config::read(), and xl::fs::FileText::read().
crA()
std::cstring_t & xl::core::Const::crA () static
{
    static std::cstring_t sRv("\r");
    return sRv;
}
Referenced by crNlA(), and whiteSpacesA().
crW()
std::cwstring_t & xl::core::Const::crW () static
{
    static std::cwstring_t sRv(L"\r");
    return sRv;
}
Referenced by crNlW(), and whiteSpacesW().
cr()
std::ctstring_t & xl::core::Const::cr () static
{
    static std::ctstring_t sRv(xT("\r"));
    return sRv;
}
References xT.
Referenced by crNl(), and whiteSpaces().
nlA()
std::cstring_t & xl::core::Const::nlA () static
{
    static std::cstring_t sRv("\n");
    return sRv;
}
Referenced by crNlA(), eolA(), and whiteSpacesA().
nlW()
std::cwstring_t & xl::core::Const::nlW () static
{
    static std::cwstring_t sRv(L"\n");
    return sRv;
}
Referenced by crNlW(), eolW(), and whiteSpacesW().
nl()
std::ctstring_t & xl::core::Const::nl () static
{
    static std::ctstring_t sRv(xT("\n"));
    return sRv;
}
References xT.
Referenced by xl::core::OStream::_printRangeMap(), crNl(), eol(), xl::package::GitClient::localBranchesNum(), xl::package::GitClient::modifiedFiles(), xl::system::ConsoleUI::msgBox(), xl::fs::FileText::read(), xl::package::GitClient::remoteRepoNames(), xl::package::CsvWriter::saveFile(), xl::package::CsvWriter::saveString(), xl::package::GitClient::stashesNum(), xl::package::GitClient::trackedFiles(), whiteSpaces(), xl::fs::FileText::write(), and xl::system::Console::writeNl().
crNlA()
std::cstring_t & xl::core::Const::crNlA () static
{
    static std::cstring_t sRv(crA() + nlA());
    return sRv;
}
References crA(), and nlA().
crNlW()
std::cwstring_t & xl::core::Const::crNlW () static
{
    static std::cwstring_t sRv(crW() + nlW());
    return sRv;
}
References crW(), and nlW().
crNl()
std::ctstring_t & xl::core::Const::crNl () static
{
    static std::ctstring_t sRv(cr() + nl());
    return sRv;
}
References cr(), and nl().
colonA()
std::cstring_t & xl::core::Const::colonA () static
{
    static std::cstring_t sRv(":");
    return sRv;
}
colonW()
std::cwstring_t & xl::core::Const::colonW () static
{
    static std::cwstring_t sRv(L":");
    return sRv;
}
colon()
std::ctstring_t & xl::core::Const::colon () static
{
    static std::ctstring_t sRv(xT(":"));
    return sRv;
}
References xT.
winSlashA()
std::cstring_t & xl::core::Const::winSlashA () static
{
    static std::cstring_t sRv("\\");
    return sRv;
}
winSlashW()
std::cwstring_t & xl::core::Const::winSlashW () static
{
    static std::cwstring_t sRv(L"\\");
    return sRv;
}
winSlash()
std::ctstring_t & xl::core::Const::winSlash () static
{
    static std::ctstring_t sRv(xT("\\"));
    return sRv;
}
References xT.
Referenced by xl::fs::Path::brief(), xl::fs::Path::toUnix(), and xl::fs::Path::toWin().
unixSlashA()
std::cstring_t & xl::core::Const::unixSlashA () static
{
    static std::cstring_t sRv("/");
    return sRv;
}
Referenced by slashA().
unixSlashW()
std::cwstring_t & xl::core::Const::unixSlashW () static
{
    static std::cwstring_t sRv(L"/");
    return sRv;
}
Referenced by slashW().
unixSlash()
std::ctstring_t & xl::core::Const::unixSlash () static
{
    static std::ctstring_t sRv(xT("/"));
    return sRv;
}
References xT.
Referenced by xl::fs::Path::brief(), slash(), xl::fs::Path::slashRemove(), xl::fs::Path::toUnix(), and xl::fs::Path::toWin().
slashA()
std::cstring_t & xl::core::Const::slashA () static
{
    static std::cstring_t sRv(unixSlashA());
    return sRv;
}
References unixSlashA().
slashW()
std::cwstring_t & xl::core::Const::slashW () static
{
    static std::cwstring_t sRv(unixSlashW());
    return sRv;
}
References unixSlashW().
slash()
std::ctstring_t & xl::core::Const::slash () static
{
    static std::ctstring_t sRv(unixSlash());
    return sRv;
}
References unixSlash().
Referenced by xl::fs::Path::brief(), xl::fs::Path::brief(), xl::fs::Path::dir(), xl::fs::Path::dirName(), xl::fs::Path::ext(), xl::fs::Path::fileBaseName(), xl::fs::Path::fileName(), xl::fs::Path::isAbsolute(), xl::fs::FileInfo::isExistsEx(), xl::fs::Dir::pathCreate(), xl::test::Unit::run(), xl::log::FileLog::setFilePath(), xl::fs::Path::slashAppend(), xl::fs::Path::slashRemove(), xl::fs::Path::split(), and xl::fs::File::wipe().
eolA()
std::cstring_t & xl::core::Const::eolA () static
{
    static std::cstring_t sRv(nlA());
    return sRv;
}
References nlA().
eolW()
std::cwstring_t & xl::core::Const::eolW () static
{
    static std::cwstring_t sRv(nlW());
    return sRv;
}
References nlW().
eol()
std::ctstring_t & xl::core::Const::eol () static
{
    static std::ctstring_t sRv(nl());
    return sRv;
}
References nl().
Referenced by xl::fs::FileText::read(), xl::core::String::removeEol(), and xl::fs::FileIO::writeLine().
semicolonA()
std::cstring_t & xl::core::Const::semicolonA () static
{
    static std::cstring_t sRv(";");
    return sRv;
}
semicolonW()
std::cwstring_t & xl::core::Const::semicolonW () static
{
    static std::cwstring_t sRv(L";");
    return sRv;
}
semicolon()
std::ctstring_t & xl::core::Const::semicolon () static
{
    static std::ctstring_t sRv(xT(";"));
    return sRv;
}
References xT.
dotA()
std::cstring_t & xl::core::Const::dotA () static
{
    static std::cstring_t sRv(".");
    return sRv;
}
dotW()
std::cwstring_t & xl::core::Const::dotW () static
{
    static std::cwstring_t sRv(L".");
    return sRv;
}
dot()
std::ctstring_t & xl::core::Const::dot () static
{
    static std::ctstring_t sRv(xT("."));
    return sRv;
}
References xT.
Referenced by xl::fs::Path::brief(), xl::fs::Path::briefName(), xl::fs::Path::ext(), xl::fs::Path::fileBaseName(), xl::fs::Path::fileDotExt(), xl::fs::Finder::isDot(), xl::fs::Dir::isEmpty(), xl::fs::FileInfo::isExistsEx(), xl::fs::Path::removeExt(), xl::fs::Path::removeExtIf(), and xl::fs::Path::setExt().
dot2A()
std::cstring_t & xl::core::Const::dot2A () static
{
    static std::cstring_t sRv("..");
    return sRv;
}
dot2W()
std::cwstring_t & xl::core::Const::dot2W () static
{
    static std::cwstring_t sRv(L"..");
    return sRv;
}
dot2()
std::ctstring_t & xl::core::Const::dot2 () static
{
    static std::ctstring_t sRv(xT(".."));
    return sRv;
}
References xT.
Referenced by xl::fs::Finder::isDot(), and xl::fs::Dir::isEmpty().
dot3A()
std::cstring_t & xl::core::Const::dot3A () static
{
    static std::cstring_t sRv("...");
    return sRv;
}
dot3W()
std::cwstring_t & xl::core::Const::dot3W () static
{
    static std::cwstring_t sRv(L"...");
    return sRv;
}
dot3()
std::ctstring_t & xl::core::Const::dot3 () static
{
    static std::ctstring_t sRv(xT("..."));
    return sRv;
}
References xT.
Referenced by xl::fs::Path::brief(), and xl::core::String::minimize().
maskAllA()
std::cstring_t & xl::core::Const::maskAllA () static
{
    static std::cstring_t sRv("*");
    return sRv;
}
maskAllW()
std::cwstring_t & xl::core::Const::maskAllW () static
{
    static std::cwstring_t sRv(L"*");
    return sRv;
}
maskAll()
std::ctstring_t & xl::core::Const::maskAll () static
{
    static std::ctstring_t sRv(xT("*"));
    return sRv;
}
References xT.
Referenced by xl::fs::Dir::copy(), xl::fs::Finder::files(), xl::fs::Volume::isEmpty(), and xl::fs::Dir::pathClear().
htA()
std::cstring_t & xl::core::Const::htA () static
{
    static std::cstring_t sRv("\t");
    return sRv;
}
Referenced by whiteSpacesA().
htW()
std::cwstring_t & xl::core::Const::htW () static
{
    static std::cwstring_t sRv(L"\t");
    return sRv;
}
Referenced by whiteSpacesW().
ht()
std::ctstring_t & xl::core::Const::ht () static
{
    static std::ctstring_t sRv(xT("\t"));
    return sRv;
}
References xT.
Referenced by xl::package::GitClient::commitsAheadBehind(), and whiteSpaces().
vtA()
std::cstring_t & xl::core::Const::vtA () static
{
    static std::cstring_t sRv("\v");
    return sRv;
}
Referenced by whiteSpacesA().
vtW()
std::cwstring_t & xl::core::Const::vtW () static
{
    static std::cwstring_t sRv(L"\v");
    return sRv;
}
Referenced by whiteSpacesW().
vt()
std::ctstring_t & xl::core::Const::vt () static
{
    static std::ctstring_t sRv(xT("\v"));
    return sRv;
}
References xT.
Referenced by whiteSpaces().
spaceA()
std::cstring_t & xl::core::Const::spaceA () static
{
    static std::cstring_t sRv(" ");
    return sRv;
}
Referenced by whiteSpacesA().
spaceW()
std::cwstring_t & xl::core::Const::spaceW () static
{
    static std::cwstring_t sRv(L" ");
    return sRv;
}
Referenced by whiteSpacesW().
space()
std::ctstring_t & xl::core::Const::space () static
{
    static std::ctstring_t sRv(xT(" "));
    return sRv;
}
References xT.
Referenced by xl::debug::BuildInfo::os(), xl::sync::Process::shellExecute(), and whiteSpaces().
bellA()
std::cstring_t & xl::core::Const::bellA () static
{
    static std::cstring_t sRv("\a");
    return sRv;
}
bellW()
std::cwstring_t & xl::core::Const::bellW () static
{
    static std::cwstring_t sRv(L"\a");
    return sRv;
}
bell()
std::ctstring_t & xl::core::Const::bell () static
{
    static std::ctstring_t sRv(xT("\a"));
    return sRv;
}
References xT.
bsA()
std::cstring_t & xl::core::Const::bsA () static
{
    static std::cstring_t sRv("\b");
    return sRv;
}
bsW()
std::cwstring_t & xl::core::Const::bsW () static
{
    static std::cwstring_t sRv(L"\b");
    return sRv;
}
bs()
std::ctstring_t & xl::core::Const::bs () static
{
    static std::ctstring_t sRv(xT("\b"));
    return sRv;
}
References xT.
ffA()
std::cstring_t & xl::core::Const::ffA () static
{
    static std::cstring_t sRv("\f");
    return sRv;
}
Referenced by whiteSpacesA().
ffW()
std::cwstring_t & xl::core::Const::ffW () static
{
    static std::cwstring_t sRv(L"\f");
    return sRv;
}
Referenced by whiteSpacesW().
ff()
std::ctstring_t & xl::core::Const::ff () static
{
    static std::ctstring_t sRv(xT("\f"));
    return sRv;
}
References xT.
Referenced by whiteSpaces().
qmA()
std::cstring_t & xl::core::Const::qmA () static
{
    static std::cstring_t sRv("\?");
    return sRv;
}
qmW()
std::cwstring_t & xl::core::Const::qmW () static
{
    static std::cwstring_t sRv(L"\?");
    return sRv;
}
qm()
std::ctstring_t & xl::core::Const::qm () static
{
    static std::ctstring_t sRv(xT("\?"));
    return sRv;
}
References xT.
sqmA()
std::cstring_t & xl::core::Const::sqmA () static
{
    static std::cstring_t sRv("\'");
    return sRv;
}
sqmW()
std::cwstring_t & xl::core::Const::sqmW () static
{
    static std::cwstring_t sRv(L"\'");
    return sRv;
}
sqm()
std::ctstring_t & xl::core::Const::sqm () static
{
    static std::ctstring_t sRv(xT("\'"));
    return sRv;
}
References xT.
dqmA()
std::cstring_t & xl::core::Const::dqmA () static
{
    static std::cstring_t sRv("\"");
    return sRv;
}
dqmW()
std::cwstring_t & xl::core::Const::dqmW () static
{
    static std::cwstring_t sRv(L"\"");
    return sRv;
}
dqm()
std::ctstring_t & xl::core::Const::dqm () static
{
    static std::ctstring_t sRv(xT("\""));
    return sRv;
}
References xT.
gaA()
std::cstring_t & xl::core::Const::gaA () static
{
    static std::cstring_t sRv("`");
    return sRv;
}
gaW()
std::cwstring_t & xl::core::Const::gaW () static
{
    static std::cwstring_t sRv(L"`");
    return sRv;
}
ga()
std::ctstring_t & xl::core::Const::ga () static
{
    static std::ctstring_t sRv(xT("`"));
    return sRv;
}
References xT.
whiteSpacesA()
std::cstring_t & xl::core::Const::whiteSpacesA () static
{
    static std::cstring_t sRv(Const::crA() + Const::spaceA() + Const::htA() +
        Const::nlA() + Const::vtA() + Const::ffA());
    return sRv;
}
References crA(), ffA(), htA(), nlA(), spaceA(), and vtA().
whiteSpacesW()
std::cwstring_t & xl::core::Const::whiteSpacesW () static
{
    static std::cwstring_t sRv(Const::crW() + Const::spaceW() + Const::htW() +
        Const::nlW() + Const::vtW() + Const::ffW());
    return sRv;
}
References crW(), ffW(), htW(), nlW(), spaceW(), and vtW().
whiteSpaces()
std::ctstring_t & xl::core::Const::whiteSpaces () static
{
    static std::ctstring_t sRv(Const::cr() + Const::space() + Const::ht() +
        Const::nl() + Const::vt() + Const::ff());
    return sRv;
}
References cr(), ff(), ht(), nl(), space(), and vt().
Referenced by xl::core::String::trimSpace().
equalA()
std::cstring_t & xl::core::Const::equalA () static
{
    static std::cstring_t sRv("=");
    return sRv;
}
equalW()
std::cwstring_t & xl::core::Const::equalW () static
{
    static std::cwstring_t sRv(L"=");
    return sRv;
}
equal()
std::ctstring_t & xl::core::Const::equal () static
{
    static std::ctstring_t sRv(xT("="));
    return sRv;
}
References xT.
Referenced by xl::system::Env::str(), and xl::system::Envs::vars().
hyphenA()
std::cstring_t & xl::core::Const::hyphenA () static
{
    static std::cstring_t sRv("-");
    return sRv;
}
hyphenW()
std::cwstring_t & xl::core::Const::hyphenW () static
{
    static std::cwstring_t sRv(L"-");
    return sRv;
}
hyphen()
std::ctstring_t & xl::core::Const::hyphen () static
{
    static std::ctstring_t sRv(xT("-"));
    return sRv;
}
References xT.
strUnknownA()
std::cstring_t & xl::core::Const::strUnknownA () static
{
    static std::cstring_t sRv("[unknown]");
    return sRv;
}
strUnknownW()
std::cwstring_t & xl::core::Const::strUnknownW () static
{
    static std::cwstring_t sRv(L"[unknown]");
    return sRv;
}
strUnknown()
std::ctstring_t & xl::core::Const::strUnknown () static
{
    static std::ctstring_t sRv(xT("[unknown]"));
    return sRv;
}
References xT.
Referenced by xl::debug::BuildInfo::cmake(), xl::system::info::Os::formatArch(), xl::core::String::formatBytes(), xl::package::curl::Error::message(), xl::debug::BuildInfo::os(), xl::debug::BuildInfo::qt(), and xl::debug::StackTrace::str().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Const.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/Const.cpp