xLib: xl::core::Time Class Reference
xl::core::Time Class Reference
Time impl.
#include "Time.h"
Inherits xl::interface_::ICompare< Time >, xl::interface_::IStr, and xl::interface_::IPrinter< std::tostream_t >.
Public Member Functions
Overrides
int_t compare (const Time &value) const final
std::tstring_t str () const final
Get as string.
void_t print (std::tostream_t &stream) const final
Ops
Time operator+ (const Duration &delta) const
Time operator- (const Duration &delta) const
Converters
int64_t toTotalMsec () const
std::time_t toPosixOffset () const
Format
std::tstring_t format (std::ctstring_t &format, std::ctstring_t &formatMsec=xT(".%03d")) const
Public Member Functions inherited from xl::interface_::ICompare< Time >
ICompare ()=default
virtual ~ICompare ()=default
bool_t operator== (const Time &a_value) const
Returns true if "value" is equal to this object.
bool_t operator!= (const Time &a_value) const
Returns true if "value" is not equal to this object.
bool_t operator< (const Time &a_value) const
Returns true if "value" is less than this object.
bool_t operator<= (const Time &a_value) const
Returns true if "value" is less than or equal to this object.
bool_t operator> (const Time &a_value) const
Returns true if "value" is greater than this object.
bool_t operator>= (const Time &a_value) const
Returns true if "value" is greater than or equal to this object.
Public Member Functions inherited from xl::interface_::IStr
IStr ()=default
virtual ~IStr ()=default
Public Member Functions inherited from xl::interface_::IPrinter< std::tostream_t >
IPrinter ()=default
virtual ~IPrinter ()=default
ctors, dtor
Time ()
Time (cint_t hour, cint_t minute, cint_t second, cint_t msec)
Time (const std::tm &t, cint_t msec)
virtual ~Time ()
xDEF_COPY_ASSIGN (Time)
int_t hour () const
int_t minute () const
int_t second () const
int_t msec () const
static Time currentLocal ()
🕓 local
static Time currentUTC ()
🌍 UTC
static Time fromTotalMsec (const int64_t totalMsec)
🌍 UTC
static Time fromPosix (const std::time_t posixTime, cint_t msec)
🌍 UTC
Additional Inherited Members
Protected Member Functions inherited from xl::interface_::ICompare< Time >
virtual int_t compare (const Time &value) const=0
Compare this object to another of the same type.
Detailed Description
Time impl.
Constructor & Destructor Documentation
Time() [1/3]
xl::core::Time::Time ()
{
}
Referenced by currentLocal(), currentUTC(), fromPosix(), fromTotalMsec(), and operator+().
Time() [2/3]
xl::core::Time::Time (cint_t hour, cint_t minute, cint_t second, cint_t msec)
  :
    _hour  (a_hour),
    _minute(a_minute),
    _second(a_second),
    _msec  (a_msec)
{
    // LogCout() << xTRACE_VAR_4(_hour, _minute, _second, _msec);
}
Time() [3/3]
xl::core::Time::Time (const std::tm & t, cint_t msec)
  :
    Time(a_t.tm_hour, a_t.tm_min, a_t.tm_sec, a_msec)
{
}
~Time()
xl::core::Time::~Time () virtual
{
}
Member Function Documentation
xDEF_COPY_ASSIGN()
xl::core::Time::xDEF_COPY_ASSIGN (Time)
currentLocal()
Time xl::core::Time::currentLocal () static
🕓 local
{
    const auto &[t, msec] = DtUtils::currentTm(false);
    return Time(t, msec);
}
References xl::core::DtUtils::currentTm(), msec(), and Time().
currentUTC()
Time xl::core::Time::currentUTC () static
🌍 UTC
{
    const auto &[t, msec] = DtUtils::currentTm(true);
    return Time(t, msec);
}
References xl::core::DtUtils::currentTm(), msec(), and Time().
fromTotalMsec()
Time xl::core::Time::fromTotalMsec (const int64_t totalMsec) static
🌍 UTC
{
    const auto [sec, msec] = DtUtils::totalMsecToTime_t(a_totalMsec);
    const std::tm t = *std::gmtime(&sec); // UTC
    return Time(t, msec);
}
References msec(), Time(), and xl::core::DtUtils::totalMsecToTime_t().
fromPosix()
Time xl::core::Time::fromPosix (const std::time_t posixTime, cint_t msec) static
🌍 UTC
{
    if (a_msec < 0 || a_msec > 999) {
        return {};
    }
    const std::tm t = *std::gmtime(&a_posixTime);
    return Time(t, a_msec);
}
References Time().
hour()
int_t xl::core::Time::hour () const
{
    return _hour;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
minute()
int_t xl::core::Time::minute () const
{
    return _minute;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
second()
int_t xl::core::Time::second () const
{
    return _second;
}
Referenced by xl::core::DateTime::format(), and xl::core::DateTime::toPosixTime().
msec()
int xl::core::Time::msec () const
{
    return _msec;
}
Referenced by currentLocal(), currentUTC(), xl::core::DateTime::format(), and fromTotalMsec().
compare()
int_t xl::core::Time::compare (const Time & value) const final
TODO: C++20
{
    /// TODO: C++20
    if (_hour < a_value._hour) return -1;
    if (_hour > a_value._hour) return 1;
    if (_minute < a_value._minute) return -1;
    if (_minute > a_value._minute) return 1;
    if (_second < a_value._second) return -1;
    if (_second > a_value._second) return 1;
    if (_msec < a_value._msec) return -1;
    if (_msec > a_value._msec) return 1;
    return 0;
}
Referenced by xl::core::DateTime::compare().
str()
std::tstring_t xl::core::Time::str () const final virtual
Get as string.
Implements xl::interface_::IStr.
{
    std::ctstring_t fmt = xT("%H:%M:%S");
    return format(fmt);
}
References format(), and xT.
print()
void_t xl::core::Time::print (std::tostream_t & stream) const final virtual
Implements xl::interface_::IPrinter< std::tostream_t >.
{
    out_stream << str();
}
operator+()
Time xl::core::Time::operator+ (const Duration & delta) const
{
    int64_t totalMsec =
        static_cast<int64_t>(_hour)   * 3600000 +
        static_cast<int64_t>(_minute) * 60000 +
        static_cast<int64_t>(_second) * 1000 +
        static_cast<int64_t>(_msec);
    totalMsec += a_delta.totalMsecs();
    // Wrap around 24 hours
    const int64_t millis_per_day = 24LL * 60 * 60 * 1000;
    totalMsec = (totalMsec % millis_per_day + millis_per_day) % millis_per_day;
    const auto h  = static_cast<int>(totalMsec / 3600000);
    const auto m  = static_cast<int>((totalMsec / 60000) % 60);
    const auto s  = static_cast<int>((totalMsec / 1000) % 60);
    const auto ms = static_cast<int>(totalMsec % 1000);
    return Time(h, m, s, ms);
}
References Time(), and xl::core::Duration::totalMsecs().
operator-()
Time xl::core::Time::operator- (const Duration & delta) const
{
    return *this + Duration(- a_delta.totalMsecs());
}
References xl::core::Duration::totalMsecs().
toTotalMsec()
int64_t xl::core::Time::toTotalMsec () const
{
    return
        static_cast<int64_t>(_hour)   * 3600000 +
        static_cast<int64_t>(_minute) * 60000 +
        static_cast<int64_t>(_second) * 1000 +
        static_cast<int64_t>(_msec);
}
Referenced by xl::core::DateTime::toMsec().
toPosixOffset()
std::time_t xl::core::Time::toPosixOffset () const
{
    return _hour * 3600 + _minute * 60 + _second;
}
format()
std::tstring_t xl::core::Time::format (std::ctstring_t & a_format, std::ctstring_t & a_formatMsec = xT(".%03d")) const
Parameters
a_format datetime format
a_formatMsec milliseconds format
{
    std::tstring_t sRv;
    std::tm date {};
    date.tm_year  = 0 - 1900;
    date.tm_mon   = 0 - 1;
    date.tm_mday  = 0;
    date.tm_hour  = _hour;
    date.tm_min   = _minute;
    date.tm_sec   = _second;
    date.tm_wday  = {};
    date.tm_yday  = {};
    date.tm_isdst = {};
    // LogCout() << date;
    tchar_t buff[80 + 1] {};
    std::csize_t buffSize = xSTRFTIME(&buff[0], sizeof(buff) - 1, a_format.c_str(), &date);
    xCHECK_RET(buffSize == 0, std::tstring_t());
    sRv.assign(&buff[0], buffSize);
    if ( !a_formatMsec.empty() ) {
        sRv += FormatC::str(a_formatMsec.c_str(), _msec);
    }
    return sRv;
}
References xl::core::FormatC::str(), and xCHECK_RET.
Referenced by xl::core::DateTime::format2(), and str().
The documentation for this class was generated from the following files:
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Time.h
/home/runner/work/xLib/xLib/Include/xLib/Core/Date/Time.cpp