xLib: xl::system::CmdOptions Class Reference
xl::system::CmdOptions Class Reference
Command-line options parser.
#include "CmdOptions.h"
Public Member Functions
void_t parse (cint_t argsNum, cptr_ctchar_t argv[], const std::vector< CmdOptionsUsage > &usage)
parse cmd options (to std::map)
void_t parse (std::cvec_tstring_t &args, const std::vector< CmdOptionsUsage > &usage)
parse cmd options (to std::map)
ctors, dtor
CmdOptions ()=default
virtual ~CmdOptions ()=default
xNO_COPY_ASSIGN (CmdOptions)
Detailed Description
Command-line options parser.
Constructor & Destructor Documentation
CmdOptions()
xl::system::CmdOptions::CmdOptions () default
~CmdOptions()
virtual xl::system::CmdOptions::~CmdOptions () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::CmdOptions::xNO_COPY_ASSIGN (CmdOptions)
parse() [1/2]
void_t xl::system::CmdOptions::parse (cint_t argsNum, cptr_ctchar_t argv[], const std::vector< CmdOptionsUsage > & usage)
parse cmd options (to std::map)
{
    std::vec_tstring_t args;
    ProcessInfo::commandLine(a_argsNum, a_argv, &args);
    parse(args, a_usage);
}
References xl::system::ProcessInfo::commandLine(), and parse().
Referenced by parse().
parse() [2/2]
void_t xl::system::CmdOptions::parse (std::cvec_tstring_t & args, const std::vector< CmdOptionsUsage > & usage)
parse cmd options (to std::map)
{
    xCHECK_DO(a_args.empty(), return);
    // TODO: a_usage - impl
    xUNUSED(a_usage);
    // a_args: {host-name=0, date=0, time=1, test, =}
    // Cout() << xTRACE_VAR(a_args);
    std::cstring_t delimiter = xT("=");
    for (const auto &it_arg : a_args) {
        std::vec_tstring_t items;
        String::split(it_arg, delimiter, &items);
        switch ( items.size() ) {
        case 0:
            continue;
            break;
        case 1:
            {
                auto &key = items[0];
                xCHECK_DO(key.empty(), continue);
                _params.insert( {key, {}} );
            }
            break;
        case 2:
        default:
            {
                auto &key = items[0];
                xCHECK_DO(key.empty(), continue);
                _params.insert( {key, items[1]} );
            }
            break;
        }
    } // for (a_args)
    // Cout() << xTRACE_VAR(_params);
}
References xl::core::String::split(), xCHECK_DO, xT, and xUNUSED.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/CmdOptions.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/CmdOptions.cpp