xLib: xl::sync::AtomicLongInt Class Reference
xl::sync::AtomicLongInt Class Reference
atomic operations with long_t
#include "AtomicLongInt.h"
Public Member Functions
long_t value () const
ctors, dtor
AtomicLongInt ()=default
AtomicLongInt (const AtomicLongInt &value)
virtual ~AtomicLongInt ()=default
operators
AtomicLongInt & operator+= (const AtomicLongInt &value)
AtomicLongInt & operator+= (clong_t &right)
AtomicLongInt & operator-= (const AtomicLongInt &value)
AtomicLongInt & operator-= (clong_t &right)
AtomicLongInt & operator= (const AtomicLongInt &value)
AtomicLongInt & operator= (clong_t &right)
bool_t operator== (const AtomicLongInt &value) const
bool_t operator== (clong_t &right) const
bool_t operator!= (const AtomicLongInt &value) const
bool_t operator!= (clong_t &right) const
bool_t operator< (clong_t &value) const
bool_t operator< (const AtomicLongInt &value) const
bool_t operator<= (clong_t &value) const
bool_t operator<= (const AtomicLongInt &value) const
bool_t operator> (clong_t &value) const
bool_t operator> (const AtomicLongInt &value) const
bool_t operator>= (clong_t &value) const
bool_t operator>= (const AtomicLongInt &value) const
AtomicLongInt & operator++ (cint_t value)
AtomicLongInt & operator-- (cint_t value)
Detailed Description
atomic operations with long_t
Constructor & Destructor Documentation
AtomicLongInt() [1/2]
xl::sync::AtomicLongInt::AtomicLongInt () default
AtomicLongInt() [2/2]
xl::sync::AtomicLongInt::AtomicLongInt (const AtomicLongInt & value)
{
    _value = a_value._value;
}
~AtomicLongInt()
virtual xl::sync::AtomicLongInt::~AtomicLongInt () virtual default
Member Function Documentation
operator+=() [1/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator+= (const AtomicLongInt & value)
{
    return _addAssign_impl(a_value);
}
operator+=() [2/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator+= (clong_t & right)
{
    return _addAssign_impl(a_value);
}
operator-=() [1/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator-= (const AtomicLongInt & value)
{
    return _subtractAssign_impl(a_value);
}
operator-=() [2/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator-= (clong_t & right)
{
    return _subtractAssign_impl(a_value);
}
operator=() [1/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator= (const AtomicLongInt & value)
{
    return _assign_impl(a_value);
}
operator=() [2/2]
AtomicLongInt & xl::sync::AtomicLongInt::operator= (clong_t & right)
{
    return _assign_impl(a_value);
}
operator==() [1/2]
bool_t xl::sync::AtomicLongInt::operator== (const AtomicLongInt & value) const
{
    return (_value == a_value._value);
}
operator==() [2/2]
bool_t xl::sync::AtomicLongInt::operator== (clong_t & right) const
{
    return (_value == a_value);
}
operator!=() [1/2]
bool_t xl::sync::AtomicLongInt::operator!= (const AtomicLongInt & value) const
{
    return (_value != a_value._value);
}
operator!=() [2/2]
bool_t xl::sync::AtomicLongInt::operator!= (clong_t & right) const
{
    return (_value != a_value);
}
operator<() [1/2]
bool_t xl::sync::AtomicLongInt::operator< (clong_t & value) const
{
    return (_value < a_value);
}
operator<() [2/2]
bool_t xl::sync::AtomicLongInt::operator< (const AtomicLongInt & value) const
{
    return (_value < a_value.value());
}
References value().
operator<=() [1/2]
bool_t xl::sync::AtomicLongInt::operator<= (clong_t & value) const
{
    return (_value <= a_value);
}
operator<=() [2/2]
bool_t xl::sync::AtomicLongInt::operator<= (const AtomicLongInt & value) const
{
    return (_value <= a_value.value());
}
References value().
operator>() [1/2]
bool_t xl::sync::AtomicLongInt::operator> (clong_t & value) const
{
    return (_value > a_value);
}
operator>() [2/2]
bool_t xl::sync::AtomicLongInt::operator> (const AtomicLongInt & value) const
{
    return (_value > a_value.value());
}
References value().
operator>=() [1/2]
bool_t xl::sync::AtomicLongInt::operator>= (clong_t & value) const
{
    return (_value >= a_value);
}
operator>=() [2/2]
bool_t xl::sync::AtomicLongInt::operator>= (const AtomicLongInt & value) const
{
    return (_value >= a_value.value());
}
References value().
operator++()
AtomicLongInt & xl::sync::AtomicLongInt::operator++ (cint_t value)
{
    return _inc_impl(a_value);
}
operator--()
AtomicLongInt & xl::sync::AtomicLongInt::operator-- (cint_t value)
{
    return _decr_impl(a_value);
}
value()
long_t xl::sync::AtomicLongInt::value () const
{
    return _value_impl();
}
Referenced by operator<(), operator<=(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AtomicLongInt.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Sync/AtomicLongInt.cpp