xLib: xl::fs::FileType Class Reference
xl::fs::FileType Class Reference
file attribute
#include "FileType.h"
Public Types
enum class Type : types_t {
Unknown = static_cast<types_t>(-1) ,
RegularFile = S_IFREG ,
Directory = S_IFDIR ,
CharacterDevice = S_IFCHR ,
BlockDevice = S_IFBLK ,
Device = (CharacterDevice | BlockDevice) ,
Fifo = S_IFIFO ,
SymbolicLink = S_IFLNK ,
Socket = S_IFSOCK
}
all types
using types_t = mode_t
Public Member Functions
std::ctstring_t & filePath () const
file path
bool_t isExists (cType value) const
is exists
types_t get () const
get
void_t set (ctypes_t values) const
set
void_t add (cType value) const
add
void_t remove (cType value) const
remove
void_t modify (cType valueRemove, cType valueAdd) const
modify
void_t clear () const
clear (set normal attributes, only for Windows)
bool_t isFile () const
check for file
bool_t isDir () const
check for dir
bool_t isExecutable () const
is executable
bool_t isDevice () const
is device
ctors, dtor
FileType (std::ctstring_t &filePath)
virtual ~FileType ()=default
xNO_DEFAULT_CONSTRUCT (FileType)
xNO_COPY_ASSIGN (FileType)
Detailed Description
file attribute
Member Typedef Documentation
types_t
using xl::fs::FileType::types_t = mode_t
Member Enumeration Documentation
Type
enum class xl::fs::FileType::Type : types_t strong
all types
Enumerator
Unknown
Status cannot be determined.
RegularFile
Directory
CharacterDevice
BlockDevice
Device
Fifo
SymbolicLink
Socket
    {
    #if   xENV_WIN
        Unknown           = INVALID_FILE_ATTRIBUTES,
        RegularFile       = FILE_ATTRIBUTE_NORMAL,
        Directory         = FILE_ATTRIBUTE_DIRECTORY,
        Device            = FILE_ATTRIBUTE_DEVICE,
        ReadOnly          = FILE_ATTRIBUTE_READONLY,
        Hidden            = FILE_ATTRIBUTE_HIDDEN,
        System            = FILE_ATTRIBUTE_SYSTEM,
        Archive           = FILE_ATTRIBUTE_ARCHIVE,
        Temporary         = FILE_ATTRIBUTE_TEMPORARY,
        SparseFile        = FILE_ATTRIBUTE_SPARSE_FILE,
        ReparsePoint      = FILE_ATTRIBUTE_REPARSE_POINT,
        Compressed        = FILE_ATTRIBUTE_COMPRESSED,
        Offline           = FILE_ATTRIBUTE_OFFLINE,
        NotContentIndexed = FILE_ATTRIBUTE_NOT_CONTENT_INDEXED,
        Encrypted         = FILE_ATTRIBUTE_ENCRYPTED
    #elif xENV_UNIX
        Unknown           = static_cast<types_t>(-1),   ///< Status cannot be determined
        RegularFile       = S_IFREG,                    ///<
        Directory         = S_IFDIR,                    ///<
        CharacterDevice   = S_IFCHR,                    ///<
        BlockDevice       = S_IFBLK,                    ///<
        Device            = (CharacterDevice | BlockDevice), ///<
        Fifo              = S_IFIFO,                    ///<
        SymbolicLink      = S_IFLNK,                    ///<
        Socket            = S_IFSOCK                    ///<
    #endif
    };
Constructor & Destructor Documentation
FileType()
xl::fs::FileType::FileType (std::ctstring_t & filePath) explicit
  :
    _filePath(a_filePath)
{
    xTEST(!a_filePath.empty());
}
References xTEST.
~FileType()
virtual xl::fs::FileType::~FileType () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::FileType::xNO_DEFAULT_CONSTRUCT (FileType)
xNO_COPY_ASSIGN()
xl::fs::FileType::xNO_COPY_ASSIGN (FileType)
filePath()
std::ctstring_t & xl::fs::FileType::filePath () const
file path
{
    return _filePath;
}
isExists()
bool_t xl::fs::FileType::isExists (cType value) const
is exists
{
    xTEST_NA(a_value);
    xCHECK_RET(a_value == static_cast<Type>(get() & static_cast<FileType::types_t>(a_value)), true);
    return false;
}
References get(), xCHECK_RET, and xTEST_NA.
Referenced by isDevice(), isDir(), xl::fs::Dir::isExists(), and isFile().
get()
FileType::types_t xl::fs::FileType::get () const
get
{
    return _get_impl();
}
Referenced by xl::fs::Dir::isExists(), isExists(), isFile(), and modify().
set()
void_t xl::fs::FileType::set (ctypes_t values) const
set
{
    xTEST_NA(a_values);
    _set_impl(a_values);
}
References xTEST_NA.
Referenced by modify().
add()
void_t xl::fs::FileType::add (cType value) const
add
{
    xTEST_NA(a_value);
    modify(static_cast<Type>(0), a_value);
}
References modify(), and xTEST_NA.
remove()
void_t xl::fs::FileType::remove (cType value) const
remove
{
    xTEST_NA(a_value);
    modify(a_value, static_cast<Type>(0));
}
References modify(), and xTEST_NA.
modify()
void_t xl::fs::FileType::modify (cType valueRemove, cType valueAdd) const
modify
{
    xTEST_NA(a_valueRemove);
    xTEST_NA(a_valueAdd);
    // get current attributes
    ctypes_t valueRemove = static_cast<types_t>(a_valueRemove);
    ctypes_t valueAdd    = static_cast<types_t>(a_valueAdd);
    types_t  values      = get();
    // change bits
    values &= ~valueRemove;
    values |= valueAdd;
    // change the attributes
    set(values);
}
References get(), set(), and xTEST_NA.
Referenced by add(), and remove().
clear()
void_t xl::fs::FileType::clear () const
clear (set normal attributes, only for Windows)
{
    _clear_impl();
}
Referenced by xl::fs::Dir::copy(), xl::fs::Dir::remove(), xl::fs::Dir::tryRemove(), and xl::fs::File::wipe().
isFile()
bool_t xl::fs::FileType::isFile () const
check for file
{
    xCHECK_RET(get() == static_cast<FileType::types_t>(FileType::Type::Unknown), false);
    bool_t bRv {};
#if   xENV_WIN
    bRv = isExists(FileType::Type::Directory);
    xCHECK_RET(bRv, false);
    bRv = isExists(FileType::Type::Device);
    xCHECK_RET(bRv, false);
    bRv = isExists(FileType::Type::ReparsePoint);
    xCHECK_RET(bRv, false);
    bRv = isExists(FileType::Type::Offline);
    xCHECK_RET(bRv, false);
#elif xENV_UNIX
    bRv = isExists(FileType::Type::RegularFile);
    xCHECK_RET(!bRv, false);
#endif
    return true;
}
References Device, Directory, get(), isExists(), RegularFile, Unknown, and xCHECK_RET.
Referenced by isExecutable().
isDir()
bool_t xl::fs::FileType::isDir () const
check for dir
{
    return isExists(FileType::Type::Directory);
}
References Directory, and isExists().
isExecutable()
bool_t xl::fs::FileType::isExecutable () const
is executable
{
    xCHECK_RET(!isFile(), false);
    return _isExecutable_impl();
}
References isFile(), and xCHECK_RET.
isDevice()
bool_t xl::fs::FileType::isDevice () const
is device
{
    return isExists(FileType::Type::Device);
}
References Device, and isExists().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileType.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileType.cpp