xLib: xl::core::FormatC Class Reference
xl::core::FormatC Class Reference
format string in C style
#include "FormatC.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (FormatC)
xNO_COPY_ASSIGN (FormatC)
Static Public Member Functions
static std::tstring_t str (cptr_ctchar_t format,...)
static std::tstring_t strV (cptr_ctchar_t format, va_list args)
Detailed Description
format string in C style
Definition at line 15 of file FormatC.h.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::core::FormatC::xNO_DEFAULT_CONSTRUCT (FormatC)
xNO_COPY_ASSIGN()
xl::core::FormatC::xNO_COPY_ASSIGN (FormatC)
str()
std::tstring_t xl::core::FormatC::str (cptr_ctchar_t a_format, ...) static
Parameters
a_format string format
... arguments
Definition at line 25 of file FormatC.cpp.
{
    xTEST_NA(a_format);
    xCHECK_RET(a_format == nullptr, std::tstring_t());
    std::tstring_t sRv;
    va_list args;
    xVA_START(args, a_format);
    sRv = strV(a_format, args);
    xVA_END(args);
    return sRv;
}
References strV(), xCHECK_RET, and xTEST_NA.
Referenced by xl::core::DateTime::format(), xl::core::String::formatBytes(), xl::crypt::Crc32::formatHex(), and xl::crypt::Guid::str().
strV()
std::tstring_t xl::core::FormatC::strV (cptr_ctchar_t a_format, va_list a_args) static
Parameters
a_format string format
a_args arguments
Definition at line 46 of file FormatC.cpp.
{
    xTEST_NA(a_format);
    xTEST_NA(a_args);
    xCHECK_RET(a_format == nullptr, std::tstring_t());
    std::size_t buffSize {};
    {
        va_list args;
        xVA_COPY(args, a_args);
        cint_t iRv = xTVSNPRINTF(nullptr, 0, a_format, args);
        xVA_END(args);
        xSTD_VERIFY(iRv != - 1);
        xSTD_VERIFY(iRv > - 1);
        if (iRv <= - 1) {
            buffSize = 0;
        } else {
            buffSize = static_cast<std::size_t>(iRv) + 1;  // + 1 for '\0'
        }
        // std::tcout << xTRACE_VAR(buffSize) << std::endl;
        xCHECK_RET(buffSize == 0, std::tstring_t());
    }
    // write to buffer
    std::tstring_t buff(buffSize, xT('\0'));
    {
        va_list args;
        xVA_COPY(args, a_args);
        cint_t iRv = xTVSNPRINTF(&buff.at(0), buffSize, a_format, args);
        xVA_END(args);
        xSTD_VERIFY(iRv != - 1);
        xSTD_VERIFY(iRv > - 1);
        xSTD_VERIFY(iRv == static_cast<int_t>(buffSize) - 1);
        buff.resize( static_cast<std::size_t>(iRv) );
    }
    return buff;
}
References xCHECK_RET, xSTD_VERIFY, xT, xTEST_NA, and xVA_COPY.
Referenced by xl::debug::AutoProfiler::AutoProfiler(), xl::debug::Profiler::restart(), xl::debug::Profiler::stop(), str(), xl::log::FileLog::write(), xl::log::SystemLog::write(), xl::log::Trace::write(), xl::log::FileLog::write(), xl::log::SystemLog::write(), and xl::log::Trace::write().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/FormatC.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/FormatC.cpp