xLib: xl::package::Application Class Reference
xl::package::Application Class Reference abstract
application
#include "Application.h"
Public Types
enum ExitCode {
Failure = EXIT_FAILURE ,
Success = EXIT_SUCCESS
}
Public Member Functions
void_t setDevel (cbool_t flag)
set devel
bool_t isDevel () const
is devel
void_t args (cbool_t withoutFirstArg, std::vec_tstring_t *args) const
command line arguments
const Signal & signal () const
signal
bool_t isRunAsAdmin () const
check for running as admin
bool_t isRunnig () const
check if application already running
void_t dirsCreate ()
create all application directories
bool_t selfCheck () const
self check
ExitCode run ()
run
virtual ExitCode onRun ()=0
run handle
ctors, dtor
Application (std::ctstring_t &appGuid, std::ctstring_t &locale)
virtual ~Application ()=default
xNO_DEFAULT_CONSTRUCT (Application)
xNO_COPY_ASSIGN (Application)
Static Public Member Functions
static void_t exit (cExitCode status)
terminates the process normally, performing the regular cleanup, objects with automatic storage are not destroyed
static void_t exitFailure ()
static void_t exitSuccess ()
static void_t terminate ()
calls the current terminate handler
static void_t abort ()
aborts the current process, producing an abnormal program termination
static std::tstring_t filePath ()
application file path
static std::tstring_t configPath ()
config file
static std::tstring_t logPath ()
log file
static std::tstring_t dbPath ()
database file
static std::tstring_t dirPath ()
application directory
static std::tstring_t configDirPath ()
config directory
static std::tstring_t logDirPath ()
log directory
static std::tstring_t dbDirPath ()
database directory
static std::tstring_t backupDirPath ()
database backup directory
static std::tstring_t tempDirPath ()
temporary directory
static std::tstring_t langDirPath ()
language translation directory
static const BuildInfo & buildInfo ()
build information
Protected Attributes
bool_t _isDevel {}
application information
std::ctstring_t _appGuid
Detailed Description
application
Member Enumeration Documentation
ExitCode
enum xl::package::Application::ExitCode
Enumerator
Failure
Success
    {
        Failure = EXIT_FAILURE,
        Success = EXIT_SUCCESS
    };
Constructor & Destructor Documentation
Application()
xl::package::Application::Application (std::ctstring_t & a_appGuid, std::ctstring_t & a_locale)
Parameters
a_appGuid application GUID
a_locale locale, empty value for current locale
  :
    _isDevel{::isDevel},
    _appGuid{a_appGuid}
{
    xTEST(!a_appGuid.empty());
    xTEST_NA(a_locale);
    Locale locale;
    locale.setCurrent(a_locale);
}
References xl::core::Locale::setCurrent(), xTEST, and xTEST_NA.
~Application()
virtual xl::package::Application::~Application () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::Application::xNO_DEFAULT_CONSTRUCT (Application)
xNO_COPY_ASSIGN()
xl::package::Application::xNO_COPY_ASSIGN (Application)
setDevel()
void_t xl::package::Application::setDevel (cbool_t flag)
set devel
{
    _isDevel = a_flag;
}
References _isDevel.
isDevel()
bool_t xl::package::Application::isDevel () const
is devel
{
    return _isDevel;
}
References _isDevel.
args()
void_t xl::package::Application::args (cbool_t a_withoutFirstArg, std::vec_tstring_t * a_args) const
command line arguments
Parameters
a_withoutFirstArg erase first argument
[out] a_args command line arguments
{
    ProcessInfo info( Process::currentId() );
    info.commandLine(a_args);
    if (a_withoutFirstArg) {
        a_args->erase(a_args->cbegin(), a_args->cbegin() + 1);
    }
}
References xl::system::ProcessInfo::commandLine(), and xl::sync::Process::currentId().
signal()
const Signal & xl::package::Application::signal () const
signal
{
    static Signal signal;
    return signal;
}
References signal().
Referenced by run(), and signal().
isRunAsAdmin()
bool_t xl::package::Application::isRunAsAdmin () const
check for running as admin
{
    User user;
    return user.isAdmin();
}
References xl::system::User::isAdmin().
isRunnig()
bool_t xl::package::Application::isRunnig () const
check if application already running
{
    xUNUSED(_appGuid);
    // TODO: [skynowa] Application::isRunnig()
    return false;
}
References _appGuid, and xUNUSED.
dirsCreate()
void_t xl::package::Application::dirsCreate ()
create all application directories
{
    Dir( configDirPath() ).pathCreate();
    Dir( logDirPath() ).pathCreate();
    Dir( dbDirPath() ).pathCreate();
    Dir( backupDirPath() ).pathCreate();
    Dir( tempDirPath() ).pathCreate();
    Dir( langDirPath() ).pathCreate();
}
References backupDirPath(), configDirPath(), dbDirPath(), langDirPath(), logDirPath(), xl::fs::Dir::pathCreate(), and tempDirPath().
selfCheck()
bool_t xl::package::Application::selfCheck () const
self check
{
#if xLIB_QT
    bool_t bRv {};
    bRv = std::tstring_t(QT_VERSION_STR) == std::tstring_t( qVersion() );
    if (!bRv) {
        std::wcerr
            << "QtLib/Application: "
            << "Qt compile version \"" << QT_VERSION_STR << "\" and "
            << "Qt runtime version \"" << qVersion()     << "\" mismatch" << std::endl;
        return false;
    }
#endif
    // TODO: check configs
    return true;
}
run()
Application::ExitCode xl::package::Application::run ()
run
{
    cbool_t opt_useException {false};
    ExitCode iRv {};
#if xENV_UNIX
#if 0
    signal().connectInfoAll(internal::CrashCallback::onInfo);
#endif
#if 0
    signal().connectExit(internal::CrashCallback::onExit);
    signal().connectTerminate(internal::CrashCallback::onTerminate);
    signal().connectUnexpected(internal::CrashCallback::onUnexpected);
#else
    signal().connectExit(nullptr);
    signal().connectTerminate(nullptr);
    signal().connectUnexpected(nullptr);
#endif
#endif
    if (opt_useException) {
        try {
            iRv = onRun();
        }
        catch (const Exception &a_ex) {
            xTEST_FAIL_MSG(a_ex.what());
        }
        catch (const std::exception &a_ex) {
            std::string msg = a_ex.what();
            xTEST_FAIL_MSG(xA2T(msg));
        }
        catch (...) {
            xTEST_FAIL_MSG(xT("unknown error"));
        }
    } else {
        iRv = onRun();
    }
    return iRv;
}
References xl::sync::Signal::connectExit(), xl::sync::Signal::connectInfoAll(), xl::sync::Signal::connectTerminate(), xl::sync::Signal::connectUnexpected(), onRun(), signal(), xl::debug::Exception::what(), xA2T, xT, and xTEST_FAIL_MSG.
onRun()
Application::ExitCode xl::package::Application::onRun () pure virtual
run handle
{
    xTEST(false);
    return ExitCode::Failure;
}
References Failure, and xTEST.
Referenced by run().
exit()
void_t xl::package::Application::exit (cExitCode status) static
terminates the process normally, performing the regular cleanup, objects with automatic storage are not destroyed
{
    (void_t)std::exit(a_status);
}
Referenced by exitFailure(), and exitSuccess().
exitFailure()
void_t xl::package::Application::exitFailure () static
{
    exit(ExitCode::Failure);
}
References exit(), and Failure.
exitSuccess()
void_t xl::package::Application::exitSuccess () static
{
    exit(ExitCode::Success);
}
References exit(), and Success.
terminate()
void_t xl::package::Application::terminate () static
calls the current terminate handler
{
    (void_t)std::terminate();
}
abort()
void_t xl::package::Application::abort () static
aborts the current process, producing an abnormal program termination
{
    (void_t)std::abort();
}
filePath()
std::tstring_t xl::package::Application::filePath () static
application file path
{
    return Path::exe().str();
}
References xl::fs::Path::exe(), and xl::fs::Path::str().
Referenced by configPath(), dbPath(), and logPath().
configPath()
std::tstring_t xl::package::Application::configPath () static
config file
{
    std::ctstring_t basename = Path( filePath() ).fileBaseName();
    std::ctstring_t ext      = Path::fileDotExt(Path::FileExt::Config);
    return Format::str(xT("{}/{}{}"), configDirPath(), basename, ext);
}
References configDirPath(), xl::fs::Path::fileBaseName(), xl::fs::Path::fileDotExt(), filePath(), xl::core::FormatT< StreamT >::str(), and xT.
logPath()
std::tstring_t xl::package::Application::logPath () static
log file
{
    std::ctstring_t basename = Path( filePath() ).fileBaseName();
    std::ctstring_t ext      = Path::fileDotExt(Path::FileExt::Log);
    return Format::str(xT("{}/{}{}"), logDirPath(), basename, ext);
}
References xl::fs::Path::fileBaseName(), xl::fs::Path::fileDotExt(), filePath(), logDirPath(), xl::core::FormatT< StreamT >::str(), and xT.
dbPath()
std::tstring_t xl::package::Application::dbPath () static
database file
{
    std::ctstring_t basename = Path( filePath() ).fileBaseName();
    std::ctstring_t ext      = Path::fileDotExt(Path::FileExt::Db);
    return Format::str(xT("{}/{}{}"), dbDirPath(), basename, ext);
}
References dbDirPath(), xl::fs::Path::fileBaseName(), xl::fs::Path::fileDotExt(), filePath(), xl::core::FormatT< StreamT >::str(), and xT.
dirPath()
std::tstring_t xl::package::Application::dirPath () static
application directory
{
#if xOS_ANDROID
    return Dir::current().str();
#else
    return Path::exe().dir();
#endif
}
References xl::fs::Dir::current(), xl::fs::Path::dir(), xl::fs::Path::exe(), and xl::fs::Dir::str().
Referenced by backupDirPath(), configDirPath(), dbDirPath(), langDirPath(), logDirPath(), and tempDirPath().
configDirPath()
std::tstring_t xl::package::Application::configDirPath () static
config directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::configDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by configPath(), and dirsCreate().
logDirPath()
std::tstring_t xl::package::Application::logDirPath () static
log directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::logDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by dirsCreate(), and logPath().
dbDirPath()
std::tstring_t xl::package::Application::dbDirPath () static
database directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::dbDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by dbPath(), and dirsCreate().
backupDirPath()
std::tstring_t xl::package::Application::backupDirPath () static
database backup directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::backupDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by dirsCreate().
tempDirPath()
std::tstring_t xl::package::Application::tempDirPath () static
temporary directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::tempDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by dirsCreate().
langDirPath()
std::tstring_t xl::package::Application::langDirPath () static
language translation directory
{
    return Format::str(xT("{}/{}"), dirPath(), ::langDirName);
}
References dirPath(), xl::core::FormatT< StreamT >::str(), and xT.
Referenced by dirsCreate().
buildInfo()
const BuildInfo & xl::package::Application::buildInfo () static
build information
{
    static BuildInfo info;
    return info;
}
Member Data Documentation
_isDevel
bool_t xl::package::Application::_isDevel {} protected
application information
{};
Referenced by isDevel(), and setDevel().
_appGuid
std::ctstring_t xl::package::Application::_appGuid protected
Referenced by isRunnig().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Application.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Application.cpp