xLib: xl::debug::Debugger Class Reference
xl::debug::Debugger Class Reference
debugger
#include "Debugger.h"
Public Member Functions
bool_t isEnabled () const
is debugging enabled
void_t setEnabled (cbool_t flag)
set debugging mode on/off
bool_t isActive () const
is OS debugger presents
void_t coreDumpsEnable (cbool_t flag)
core dumps
void_t breakPoint () const
attach to OS debugger
void_t setLogPath (std::ctstring_t &filePath)
set log file path
std::tstring_t logPath () const
get log file path
void_t reportMake (const ErrorReport &report) const
make report
ctors, dtor
Debugger ()=default
virtual ~Debugger ()=default
xNO_COPY_ASSIGN (Debugger)
Detailed Description
debugger
Constructor & Destructor Documentation
Debugger()
xl::debug::Debugger::Debugger () default
~Debugger()
virtual xl::debug::Debugger::~Debugger () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::debug::Debugger::xNO_COPY_ASSIGN (Debugger)
isEnabled()
bool_t xl::debug::Debugger::isEnabled () const
is debugging enabled
{
    return _isEnabled;
}
Referenced by breakPoint().
setEnabled()
void_t xl::debug::Debugger::setEnabled (cbool_t flag)
set debugging mode on/off
{
    _isEnabled = a_flag;
}
isActive()
bool_t xl::debug::Debugger::isActive () const
is OS debugger presents
{
    return _isActive_impl();
}
coreDumpsEnable()
void_t xl::debug::Debugger::coreDumpsEnable (cbool_t flag)
core dumps
{
    xTEST_NA(a_flag);
    bool_t isEnable {};
    _coreDumpsEnable_impl(a_flag, &isEnable);
    xCHECK_DO(!isEnable, Trace() << xT("xLib: Debugger::coreDumpsEnable() - n/a"));
}
References xCHECK_DO, xT, and xTEST_NA.
breakPoint()
void_t xl::debug::Debugger::breakPoint () const
attach to OS debugger
{
    xCHECK_DO(!isEnabled(), return);
    _breakPoint_impl();
}
References isEnabled(), and xCHECK_DO.
setLogPath()
void_t xl::debug::Debugger::setLogPath (std::ctstring_t & filePath)
set log file path
{
    _logPath = a_filePath;
}
logPath()
std::tstring_t xl::debug::Debugger::logPath () const
get log file path
{
    return _logPath;
}
reportMake()
void_t xl::debug::Debugger::reportMake (const ErrorReport & report) const
make report
{
    // never corrupt last error value
    culong_t nativeError = NativeError::get();
    switch ( a_report.type() ) {
    case ErrorReport::Type::Stdout:
        _stdoutPlain(a_report);
        break;
    case ErrorReport::Type::Log:
        _loggingPlain(a_report);
        break;
    case ErrorReport::Type::StdoutLog:
        _stdoutPlain(a_report);
        _loggingPlain(a_report);
        break;
    case ErrorReport::Type::Exception:
        throw Exception() << a_report.str();
        break;
    default:
        _stdoutPlain(a_report);
        break;
    }
    // never corrupt last error value
    NativeError::set(nativeError);
}
References xl::debug::ErrorReport::Exception, xl::debug::NativeError::get(), xl::debug::ErrorReport::Log, xl::debug::NativeError::set(), xl::debug::ErrorReport::Stdout, xl::debug::ErrorReport::StdoutLog, xl::debug::ErrorReport::str(), and xl::debug::ErrorReport::type().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Debugger.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Debug/Debugger.cpp