xLib: xl::core::DateTimeValidator Class Reference
xl::core::DateTimeValidator Class Reference
DateTime validator.
#include "DateTime.h"
Public Member Functions
ctors, dtor
xNO_DEFAULT_CONSTRUCT (DateTimeValidator)
xNO_COPY_ASSIGN (DateTimeValidator)
Static Public Member Functions
static bool_t year (cint_t year)
static bool_t month (cint_t month)
static bool_t day (cint_t day)
static bool_t hour (cint_t hour)
static bool_t minute (cint_t minute)
static bool_t second (cint_t second)
static bool_t msec (cint_t msec)
static bool_t weekDay (cint_t weekDay)
static bool_t time (cint_t hour, cint_t minute, cint_t second, cint_t msec)
static bool_t date (cint_t year, cint_t month, cint_t day)
static bool_t datetime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec)
static bool_t datetime (const DateTime &datetime)
static bool_t dateOrTime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec)
Detailed Description
DateTime validator.
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::core::DateTimeValidator::xNO_DEFAULT_CONSTRUCT (DateTimeValidator)
xNO_COPY_ASSIGN()
xl::core::DateTimeValidator::xNO_COPY_ASSIGN (DateTimeValidator)
year()
bool_t xl::core::DateTimeValidator::year (cint_t year) static
{
    return (a_year >= ::yearMin && a_year <= ::yearMax);
}
Referenced by date().
month()
bool_t xl::core::DateTimeValidator::month (cint_t month) static
{
    return (a_month >= ::monthMin && a_month <= ::monthMax);
}
Referenced by date(), and xl::core::DateTime::monthStr().
day()
bool_t xl::core::DateTimeValidator::day (cint_t day) static
{
    return (a_day >= ::dayMin && a_day <= ::dayMax);
}
Referenced by date().
hour()
bool_t xl::core::DateTimeValidator::hour (cint_t hour) static
{
    return (a_hour >= ::hourMin && a_hour <= ::hourMax);
}
Referenced by time().
minute()
bool_t xl::core::DateTimeValidator::minute (cint_t minute) static
{
    return (a_minute >= ::minuteMin && a_minute <= ::minuteMax);
}
Referenced by time().
second()
bool_t xl::core::DateTimeValidator::second (cint_t second) static
{
    return (a_second >= ::secondMin && a_second <= ::secondMax);
}
Referenced by time().
msec()
bool_t xl::core::DateTimeValidator::msec (cint_t msec) static
{
    return (a_msec >= ::msecMin && a_msec <= ::msecMax);
}
Referenced by time().
weekDay()
bool_t xl::core::DateTimeValidator::weekDay (cint_t weekDay) static
{
    return (a_weekDay >= ::weekDayMin && a_weekDay <= ::weekDayMax);
}
Referenced by xl::core::DateTime::weekDayStr().
time()
bool_t xl::core::DateTimeValidator::time (cint_t hour, cint_t minute, cint_t second, cint_t msec) static
{
    return (hour(a_hour) && minute(a_minute) && second(a_second) && msec(a_msec));
}
References hour(), minute(), msec(), and second().
Referenced by dateOrTime(), datetime(), xl::core::DateTime::DateTime(), and datetime().
date()
bool_t xl::core::DateTimeValidator::date (cint_t year, cint_t month, cint_t day) static
{
    return (year(a_year) && month(a_month) && day(a_day));
}
References day(), month(), and year().
Referenced by dateOrTime(), datetime(), xl::core::DateTime::DateTime(), and datetime().
datetime() [1/2]
bool_t xl::core::DateTimeValidator::datetime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec) static
{
    return (date(a_year, a_month, a_day) && time(a_hour, a_minute, a_second, a_msec));
}
References date(), and time().
Referenced by xl::core::DateTime::dayOfWeek().
datetime() [2/2]
bool_t xl::core::DateTimeValidator::datetime (const DateTime & datetime) static
{
    return (date(a_datetime._year, a_datetime._month, a_datetime._day) &&
            time(a_datetime._hour, a_datetime._minute, a_datetime._second, a_datetime._msec));
}
References date(), and time().
dateOrTime()
bool_t xl::core::DateTimeValidator::dateOrTime (cint_t year, cint_t month, cint_t day, cint_t hour, cint_t minute, cint_t second, cint_t msec) static
{
    return (date(a_year, a_month, a_day) || time(a_hour, a_minute, a_second, a_msec));
}
References date(), and time().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/DateTime.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Core/DateTime.cpp