xLib: xl::package::curl::Client Class Reference
xl::package::curl::Client Class Reference
Client.
#include "Client.h"
Inherited by xl::package::curl::HttpClient, and xl::package::curl::SmtpClient.
Classes
struct ReadData
struct SlistDeleter
Public Member Functions
HandleCurl & get ()
void_t reset ()
template<typename T >
void_t setOption (cCURLoption option, const T &value)
void_t perform ()
void_t pause (cint_t bitMask)
template<typename T >
void_t info (cCURLINFO info, const T &value)
void_t receive (void_t *buff, std::csize_t buffSize, std::size_t *items)
void_t send (cvoid_t *buff, std::csize_t buffSize, std::size_t *items)
std::tstring_t escape (std::ctstring_t &str) const
std::tstring_t unescape (std::ctstring_t &str) const
Ctors, dtor
Client (cbool_t isDebug)
virtual ~Client ()
xNO_DEFAULT_CONSTRUCT (Client)
xNO_COPY_ASSIGN (Client)
Static Public Member Functions
static std::tstring_t escapeUrl (std::ctstring_t &str)
static std::tstring_t unescapeUrl (std::ctstring_t &str)
Protected Types
Types
using slist_unique_ptr_t = std::unique_ptr< curl_slist, SlistDeleter >
Protected Attributes
cbool_t _isDebug {}
HandleCurl _handle
ReadData _readData {}
slist_unique_ptr_t _headers
Callbacks
static std::size_t onWriteHeader (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onWriteData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
static std::size_t onReadData (void_t *buff, std::csize_t size, std::csize_t items, void_t *userData)
Detailed Description
Client.
Member Typedef Documentation
slist_unique_ptr_t
using xl::package::curl::Client::slist_unique_ptr_t = std::unique_ptr<curl_slist, SlistDeleter> protected
Constructor & Destructor Documentation
Client()
xl::package::curl::Client::Client (cbool_t isDebug) explicit
  :
    _isDebug{a_isDebug}
{
    Error err = ::curl_global_init(CURL_GLOBAL_ALL);
    xTEST(err.isOk());
    _handle = ::curl_easy_init();
    xTEST(_handle.isValid());
    setOption(CURLOPT_ERRORBUFFER, &_errorBuff[0]);
    if (_isDebug) {
        setOption(CURLOPT_VERBOSE,        1L);
        setOption(CURLOPT_DEBUGFUNCTION,  _onDebugOption);
        setOption(CURLOPT_DEBUGDATA,     &_debugData);
    }
}
References _handle, _isDebug, xl::package::curl::Error::isOk(), xl::core::Handle< T, typeT >::isValid(), setOption(), and xTEST.
~Client()
xl::package::curl::Client::~Client () virtual
{
    (void_t)::curl_global_cleanup();
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::package::curl::Client::xNO_DEFAULT_CONSTRUCT (Client)
xNO_COPY_ASSIGN()
xl::package::curl::Client::xNO_COPY_ASSIGN (Client)
References info().
get()
HandleCurl & xl::package::curl::Client::get ()
{
    return _handle;
}
References _handle.
reset()
void_t xl::package::curl::Client::reset ()
{
    (void_t)::curl_easy_reset( _handle.get() );
}
References _handle, and xl::core::Handle< T, typeT >::get().
setOption()
template<typename T > void_t xl::package::curl::Client::setOption (cCURLoption option, const T & value) inline
{
    Error err = ::curl_easy_setopt(_handle.get(), a_option, a_value);
    xTEST_MSG(err.isOk(), Format::str(xT("Option: {} - {}"), a_option, err.str()));
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), xl::interface_::IError< CodeT >::str(), xl::core::FormatT< StreamT >::str(), xT, and xTEST_MSG.
Referenced by Client(), xl::package::curl::SmtpClient::request(), and xl::package::curl::HttpClient::setOptionsDefault().
perform()
void_t xl::package::curl::Client::perform ()
{
    Error err = ::curl_easy_perform( _handle.get() );
    xTEST_MSG(err.isOk(), Format::str(xT("perform: {}"), err.str()));
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), xl::interface_::IError< CodeT >::str(), xl::core::FormatT< StreamT >::str(), xT, and xTEST_MSG.
Referenced by xl::package::curl::SmtpClient::request().
pause()
void_t xl::package::curl::Client::pause (cint_t bitMask)
{
    Error err = ::curl_easy_pause(_handle.get(), a_bitMask);
    xTEST(err.isOk());
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), and xTEST.
info()
template<typename T > void_t xl::package::curl::Client::info (cCURLINFO info, const T & value) inline
{
    Error err = ::curl_easy_getinfo(_handle.get(), a_info, a_value);
    xTEST_MSG(err.isOk(), Format::str(xT("Info: {} - {}"), a_info, err.str()));
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), xl::interface_::IError< CodeT >::str(), xl::core::FormatT< StreamT >::str(), xT, and xTEST_MSG.
Referenced by xl::package::curl::HttpClient::getInfos(), xl::package::curl::SmtpClient::request(), and xNO_COPY_ASSIGN().
receive()
void_t xl::package::curl::Client::receive (void_t * buff, std::csize_t buffSize, std::size_t * items)
{
    Error err = ::curl_easy_recv(_handle.get(), a_buff, a_buffSize, a_items);
    xTEST(err.isOk());
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), and xTEST.
send()
void_t xl::package::curl::Client::send (cvoid_t * buff, std::csize_t buffSize, std::size_t * items)
{
    Error err = ::curl_easy_send(_handle.get(), a_buff, a_buffSize, a_items);
    xTEST(err.isOk());
}
References _handle, xl::core::Handle< T, typeT >::get(), xl::package::curl::Error::isOk(), and xTEST.
escape()
std::tstring_t xl::package::curl::Client::escape (std::ctstring_t & str) const
{
    std::tstring_t sRv;
    char *pszRv = ::curl_easy_escape(_handle.get(), a_str.c_str(), static_cast<int>( a_str.size() ));
    xTEST_PTR(pszRv);
    sRv.assign(pszRv);
    Utils::freeT(pszRv, ::curl_free, nullptr);
    return sRv;
}
References _handle, xl::core::Utils::freeT(), xl::core::Handle< T, typeT >::get(), and xTEST_PTR.
Referenced by xl::package::Translate::run().
unescape()
std::tstring_t xl::package::curl::Client::unescape (std::ctstring_t & str) const
{
    std::tstring_t sRv;
    int sizeOut {};
    char *pszRv = ::curl_easy_unescape(_handle.get(), a_str.c_str(),
        static_cast<int>( a_str.size() ), &sizeOut);
    xTEST_PTR(pszRv);
    sRv.assign(pszRv, static_cast<std::size_t>(sizeOut));
    Utils::freeT(pszRv, ::curl_free, nullptr);
    return sRv;
}
References _handle, xl::core::Utils::freeT(), xl::core::Handle< T, typeT >::get(), and xTEST_PTR.
escapeUrl()
std::tstring_t xl::package::curl::Client::escapeUrl (std::ctstring_t & str) static
{
    std::tstring_t sRv;
    char *pszRv = ::curl_escape(a_str.c_str(), static_cast<int>( a_str.size() ));
    xTEST_PTR(pszRv);
    sRv.assign(pszRv);
    Utils::freeT(pszRv, ::curl_free, nullptr);
    return sRv;
}
References xl::core::Utils::freeT(), and xTEST_PTR.
unescapeUrl()
std::tstring_t xl::package::curl::Client::unescapeUrl (std::ctstring_t & str) static
{
    std::tstring_t sRv;
    char *pszRv = ::curl_unescape(a_str.c_str(), static_cast<int>( a_str.size() ));
    xTEST_PTR(pszRv);
    sRv.assign(pszRv);
    Utils::freeT(pszRv, ::curl_free, nullptr);
    return sRv;
}
References xl::core::Utils::freeT(), and xTEST_PTR.
onWriteHeader()
std::size_t xl::package::curl::Client::onWriteHeader (void_t * a_buff, std::csize_t a_size, std::csize_t a_items, void_t * out_userData) static
Parameters
a_buff buffer
a_size buffer size
a_items items number
[in,out] out_userData result
{
    xTEST_PTR(a_buff);
    xTEST_DIFF(a_size,  std::size_t{0});
    xTEST_DIFF(a_items, std::size_t{0});
    xTEST_PTR(out_userData);
    auto *data = static_cast<std::tstring_t *>(out_userData);
    xTEST_PTR(data);
    std::csize_t buffSize = a_items * a_size;
    data->append(static_cast<char *>(a_buff), buffSize);
    return buffSize;
}
References xTEST_DIFF, and xTEST_PTR.
Referenced by xl::package::curl::HttpClient::setOptionsDefault().
onWriteData()
std::size_t xl::package::curl::Client::onWriteData (void_t * a_buff, std::csize_t a_size, std::csize_t a_items, void_t * out_userData) static
Parameters
a_buff buffer
a_size buffer size
a_items items number
[in,out] out_userData result
{
    xTEST_PTR(a_buff);
    xTEST_DIFF(a_size,  std::size_t{0});
    xTEST_DIFF(a_items, std::size_t{0});
    xTEST_PTR(out_userData);
    auto *data = static_cast<std::tstring_t *>(out_userData);
    xTEST_PTR(data);
    std::csize_t buffSize = a_items * a_size;
    data->append(static_cast<char *>(a_buff), buffSize);
    return buffSize;
}
References xTEST_DIFF, and xTEST_PTR.
Referenced by xl::package::curl::HttpClient::setOptionsDefault().
onReadData()
std::size_t xl::package::curl::Client::onReadData (void_t * out_buff, std::csize_t a_size, std::csize_t a_items, void_t * out_userData) static
Parameters
[out] out_buff buffer
a_size buffer size
a_items items number
[in,out] out_userData
{
    xTEST_PTR(out_buff);
    xTEST_DIFF(a_size,  std::size_t{0});
    xTEST_DIFF(a_items, std::size_t{0});
    xTEST_PTR(out_userData);
    auto *data = static_cast<struct ReadData *>(out_userData);
    xTEST_PTR(data);
    std::ctstring_t buff = data->buff.substr(data->bytes);
    if ( buff.empty() ) {
        return 0;
    }
    std::csize_t buffSizeMax = a_size * a_items;
    std::size_t  buffSize    = buff.size();
    if (buffSizeMax < buffSize) {
        buffSize = buffSizeMax;
    }
    std::memcpy(out_buff, buff.data(), buffSize);
    data->bytes += buffSize;
    return buffSize;
}
References xTEST_DIFF, and xTEST_PTR.
Referenced by xl::package::curl::SmtpClient::request(), and xl::package::curl::HttpClient::setOptionsDefault().
Member Data Documentation
_isDebug
cbool_t xl::package::curl::Client::_isDebug {} protected
{};
Referenced by Client().
_handle
HandleCurl xl::package::curl::Client::_handle protected
Referenced by Client(), escape(), get(), xl::package::curl::HttpClient::getInfos(), info(), pause(), perform(), receive(), reset(), send(), setOption(), xl::package::curl::HttpClient::setOptionsDefault(), and unescape().
_readData
ReadData xl::package::curl::Client::_readData {} protected
{};
Referenced by xl::package::curl::SmtpClient::request(), and xl::package::curl::HttpClient::setOptionsDefault().
_headers
slist_unique_ptr_t xl::package::curl::Client::_headers protected
Referenced by xl::package::curl::HttpClient::setOptionsDefault().
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Client.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Client.cpp
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Package/Curl/Client.inl