####################################################################################################
# \file  deploy-docs.yml
# \brief Deploy xLib Doxygen docs
#
# \see   https://github.com/peaceiris/actions-gh-pages
#
####################################################################################################


name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure that the GitHub Actions bot has write access to the repository.

    steps:
    - name: Doxygen - Install
      run: sudo apt install doxygen -y && doxygen --version

    - name: Main repository-  Checkout
      uses: actions/checkout@v2

    - name: GitHub Pages - Create clean branch gh-pages
      run:  git checkout -b gh-pages

    - name: xLib - Checkout
      uses: actions/checkout@v2
      with:
        repository: skynowa/xLib
        path: ../xLib

    - name: Docs - Generate
      run: cd ../xLib/Docs && doxygen ./Doxyfile && cd -

    - name: Docs - Move to root dir
      run: mv ../xLib/Docs/html/* . && cd ..

    - name: Logs
      run: echo $(pwd) && echo $(ls -la)

    # - name: GitHub Pages - Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./Docs/html
    #     publish_branch: gh-pages


    - name: Docs - Commit
      run:  |
        git config --global user.email "skynowa@gmail.com"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"

        git add .
        git commit -am "Doxygen docs - update"

    - name: GitHub Pages - Push
      run:  git push -f origin gh-pages:gh-pages

    # steps:

    #   - name: Git Checkout
    #     uses: actions/checkout@v2

    #   - name: Create clean gh-pages branch
    #     run:  git checkout -b gh-pages

    #   - name: Generate autodocs for libyui base lib
    #     run:  make -C libyui -f Makefile.repo doc

    #   - name: Move generated autodocs to target directory
    #     run:  mv libyui/build/doc/html api-doc

    #   - name: Add generated autodocs to Git repo in the gh-pages branch
    #     run:  |
    #       git config --global user.email "libyui-github-bot@suse.com"
    #       git config --global user.name  "$GITHUB_WORKFLOW GitHub action"
    #       git add api-doc
    #       git commit -am "Generated API doc"

    #   - name: Publish autodocs as GitHub pages
    #     run:  git push -f origin gh-pages:gh-pages

    #   - name: Result URLs
    #     run:  |
    #       REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
    #       REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
    #       echo "Formatted API docs:  https://$REPO_OWNER.github.io/$REPO_NAME/api-doc"
    #       echo ""
    #       echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages"
