name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose another runner if needed

    permissions:
      contents: write  # Ensure that the GitHub Actions bot has write access to the repository

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: skynowa/xLib  # Clone the specific repository

    # Step 2: Set up Doxygen
    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    # Step 3: List files in the Docs directory to confirm Doxyfile location
    - name: List files in xLib/Docs/
      run: ls -la Docs/

    # Step 4: Generate documentation using Doxygen
    - name: Generate documentation
      run: cd ./Docs && doxygen ./Doxyfile  # Run Doxygen with your Doxyfile

    # Step 5: Deploy to GitHub Pages
    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        # publish_dir: ./skynowa.github.io/Docs  # Ensure this points to the correct directory
        publish_dir: ./html
        publish_branch: gh-pages  # The branch where docs will be deployed.

    #----------------------------------
    # Step 6:
    - name: List files in Docs/
      run: pwd && ls -la ../../

    # Step 6:
    - name: List files in Docs/
      run: pwd && ls -la ../

    # Step 6:
    - name: List files in Docs/
      run: pwd && ls -la .

    # Step 6:
    - name: List files in Docs/
      run: pwd && ls -la Docs/
