name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure that the GitHub Actions bot has write access to the repository

    steps:
    - name: xLib - Checkout
      uses: actions/checkout@v2
      with:
        repository: skynowa/xLib

    - name: Doxygen - install
      run: sudo apt-get install -y doxygen

    # Logs
    - name: List files in xLib/Docs/
      run: ls -la Docs/

    # Logs
    - name: Docs - Generate
      run: cd ./Docs && doxygen ./Doxyfile

    # Logs
    - name: GitHub Pages - Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # publish_dir: ./skynowa.github.io/Docs  # Ensure this points to the correct directory
        publish_dir: .
        publish_branch: gh-pages

    #----------------------------------
    # Logs
    - name: List files in Docs/
      run: pwd && ls -la ../../

    # Logs
    - name: List files in Docs/
      run: pwd && ls -la ../

    # Logs
    - name: List files in Docs/
      run: pwd && ls -la .

    # Logs
    - name: List files in Docs/
      run: pwd && ls -la Docs/
