####################################################################################################
# \file  deploy-docs.yml
# \brief Deploy xLib Doxygen docs
#
# \see   https://github.com/peaceiris/actions-gh-pages
#
# .
####################################################################################################


name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure that the GitHub Actions bot has write access to the repository.

    steps:
    - name: Doxygen - Install
      run: |
        sudo apt install doxygen -y
        echo "Version: $(doxygen --version)"

    - name: Main repository-  Checkout
      uses: actions/checkout@v2

    - name: GitHub Pages - Create clean branch gh-pages
      run:  git checkout -b gh-pages

    - name: xLib - Checkout
      uses: actions/checkout@v2
      with:
        repository: skynowa/xLib
        path: xLib

    - name: Docs - Generate
      run: cd ./xLib/Docs && doxygen ./Doxyfile

    - name: Docs - Move to root dir
      run: |
        mv ./xLib/Docs/html/* .

        echo "xLib - remove"
        rm -rf ./xLib

    - name: Logs
      run: |
        pwd
        ls -la

    - name: Docs - Commit
      run:  |
        git config --global user.email "skynowa@gmail.com"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"

        git add .
        git commit -am "Doxygen docs - update"

    - name: GitHub Pages - Push
      run:  git push -f origin gh-pages:gh-pages
      github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Result URLs
      run:  |
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Doxygen doc:  https://$REPO_OWNER.github.io/$REPO_NAME/doc"
        echo ""
        echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages"
