xLib: xl::db::mysql::Db Class Reference
xl::db::mysql::Db Class Reference
MySql DB.
#include "Db.h"
Public Member Functions
void_t show (std::ctstring_t &sqlLike, std::vec_tstring_t *dbNames) const
list DB names
void_t show (std::vec_tstring_t *dbNames) const
list DB names
bool_t isExists () const
check connection
void_t create () const
create DB
void_t drop () const
drop DB
ctors, dtor
Db (const Options &options)
virtual ~Db ()=default
xNO_DEFAULT_CONSTRUCT (Db)
xNO_COPY_ASSIGN (Db)
Detailed Description
MySql DB.
Constructor & Destructor Documentation
Db()
xl::db::mysql::Db::Db (const Options & options) explicit
  :
    _options{a_options}
{
}
~Db()
virtual xl::db::mysql::Db::~Db () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::db::mysql::Db::xNO_DEFAULT_CONSTRUCT (Db)
xNO_COPY_ASSIGN()
xl::db::mysql::Db::xNO_COPY_ASSIGN (Db)
show() [1/2]
void_t xl::db::mysql::Db::show (std::ctstring_t & a_sqlLike, std::vec_tstring_t * out_dbNames) const
list DB names
Parameters
a_sqlLike simple regular expression (SQL LIKE)
[out] out_dbNames
{
    xTEST_NA(a_sqlLike);
    xTEST_PTR(out_dbNames);
    out_dbNames->clear();
    // Connection
    Connection conn(_options);
    conn.connect();
    // Query
    std::tstring_t sql = xT("SHOW DATABASES");
    if ( !a_sqlLike.empty() ) {
        sql += Format::str(xT(" LIKE {}"), EscapeQuoted(conn, a_sqlLike).forSqm());
    }
    // Result
    {
        StoreResult result = conn.query(sql).store();
        rows_t rows;
        result.fetchRows(&rows);
        // [out]
        for (const auto &it_row : rows) {
            xTEST_EQ(it_row.size(), static_cast<std::size_t>(1));
            const auto &value = it_row.begin()->second;
            out_dbNames->emplace_back(value);
        }
    }
}
References xl::db::mysql::Connection::connect(), xl::db::mysql::IResult::fetchRows(), xl::db::mysql::Connection::query(), xl::db::mysql::Query::store(), xl::core::FormatT< StreamT >::str(), xT, xTEST_EQ, xTEST_NA, and xTEST_PTR.
Referenced by show().
show() [2/2]
void_t xl::db::mysql::Db::show (std::vec_tstring_t * out_dbNames) const
list DB names
Parameters
[out] out_dbNames
{
    std::ctstring_t wildcard;
    return show(wildcard, out_dbNames);
}
References show().
isExists()
bool_t xl::db::mysql::Db::isExists () const
check connection
🔗 See also:
https://stackoverflow.com/questions/275314/mysql-row-and-row0-to-string-type
{
    // Connection
    Connection conn(_options);
    conn.connect();
    // Query
    std::ctstring_t sql = Format::str(
        xT("SELECT count(*) as dbCount FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = {}"),
        EscapeQuoted(conn, _options.db).forSqm());
    // Result
    {
        StoreResult result = conn.query(sql).store();
        rows_t rows;
        result.fetchRows(&rows);
        xTEST_EQ(rows.size(), static_cast<size_t>(1));
        xCHECK_RET(rows[0]["dbCount"] == xT("0"), false);
        xTEST_EQ(rows[0]["dbCount"], "1");
    }
    return true;
}
References xl::db::mysql::Connection::connect(), xl::db::mysql::Options::db, xl::db::mysql::IResult::fetchRows(), xl::db::mysql::EscapeQuoted::forSqm(), xl::db::mysql::Connection::query(), xl::db::mysql::Query::store(), xl::core::FormatT< StreamT >::str(), xCHECK_RET, xT, and xTEST_EQ.
create()
void_t xl::db::mysql::Db::create () const
create DB
Warning
Only admin rights
{
    if ( !User().isAdmin() ) {
        xTEST_FAIL_MSG(xT("Only admin rights. Stop"));
        return;
    }
    std::ctstring_t db = _options.db;
    Options options = _options;
    options.db = {};
    // Connection
    Connection conn(options);
    conn.connect();
    // Query
    std::ctstring_t sql = Format::str(xT("CREATE DATABASE IF NOT EXISTS {} CHARACTER SET {}"),
        db,
        EscapeQuoted(conn, _options.charset).forSqm());
    conn.query(sql).exec();
}
References xl::db::mysql::Options::charset, xl::db::mysql::Connection::connect(), xl::db::mysql::Options::db, xl::db::mysql::Query::exec(), xl::db::mysql::EscapeQuoted::forSqm(), xl::db::mysql::Connection::query(), xl::core::FormatT< StreamT >::str(), xT, and xTEST_FAIL_MSG.
drop()
void_t xl::db::mysql::Db::drop () const
drop DB
Warning
Only admin rights
{
    if ( !User().isAdmin() ) {
        xTEST_FAIL_MSG(xT("Only admin rights. Stop"));
        return;
    }
    Options options = _options;
    options.db = {};
    Connection conn(options);
    conn.connect();
    std::ctstring_t sql = Format::str(xT("DROP DATABASE IF EXISTS `{}`"),
        EscapeQuoted(conn, _options.db).forSqm());
    conn.query(sql).exec();
}
References xl::db::mysql::Connection::connect(), xl::db::mysql::Options::db, xl::db::mysql::Query::exec(), xl::db::mysql::EscapeQuoted::forSqm(), xl::db::mysql::Connection::query(), xl::core::FormatT< StreamT >::str(), xT, and xTEST_FAIL_MSG.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Db.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Db/MySql/Db.cpp