xLib: xl::test::Unit Class Reference
xl::test::Unit Class Reference abstract
testing
#include "Unit.h"
Public Member Functions
bool_t isGithubCI () const
check Github CI
bool_t isVpnActive () const
void_t cfg (std::map_tstring_t *values) const
config with test data/credentials
bool_t run ()
run cases
virtual bool_t unit ()=0
unit
ctors, dtor
Unit (const UnitOption &option)
virtual ~Unit ()=0
xNO_DEFAULT_CONSTRUCT (Unit)
xNO_COPY_ASSIGN (Unit)
const UnitOption & option () const
Public Attributes
For global use
void_t * m_pvRv {}
tchar_t m_chRv {}
uchar_t m_ucRv {}
bool_t m_bRv {}
int_t m_iRv {}
short_t m_siRv {}
ushort_t m_usiRv {}
uint_t m_uiRv {}
std::size_t m_stRv {}
std::ssize_t m_sstRv {}
long_t m_liRv {}
ulong_t m_ulRv {}
longlong_t m_llRv {}
ulonglong_t m_ullRv {}
float_t m_fRv {}
double_t m_dRv {}
longdouble_t m_ldRv {}
std::tstring_t m_sRv
std::ustring_t m_usRv
std::vec_tchar_t m_vchRv
std::vec_tstring_t m_vsRv
std::map_tstring_t m_msRv
std::mmap_tstring_t m_mmsRv
std::unmap_tstring_t m_unmsRv
native_handle_t m_hRv {}
Detailed Description
testing
Constructor & Destructor Documentation
Unit()
xl::test::Unit::Unit (const UnitOption & option)
  :
    _option{a_option}
{
}
~Unit()
xl::test::Unit::~Unit () pure virtual
{
}
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::test::Unit::xNO_DEFAULT_CONSTRUCT (Unit)
xNO_COPY_ASSIGN()
xl::test::Unit::xNO_COPY_ASSIGN (Unit)
option()
const UnitOption & xl::test::Unit::option () const
{
   return _option;
}
isGithubCI()
bool_t xl::test::Unit::isGithubCI () const
check Github CI
{
    return Env(xT("GITHUB_WORKSPACE")).isExists();
}
References xl::system::Env::isExists(), and xT.
isVpnActive()
bool_t xl::test::Unit::isVpnActive () const
{
    info::Net net;
    return net.isVpnActive();
}
References xl::system::info::Net::isVpnActive().
cfg()
void_t xl::test::Unit::cfg (std::map_tstring_t * values) const
config with test data/credentials
{
    xCHECK_DO(out_values == nullptr, return);
    std::ctstring_t cfgPath = Path::homeDir().str() + xT("/xlib.cfg");
    Config cfg(cfgPath);
    cfg.read();
    auto &values = cfg.get();
    xTEST(!values.empty());
    // [out]
    *out_values = values;
}
References cfg(), xl::fs::Path::homeDir(), xl::fs::Path::str(), xCHECK_DO, xT, and xTEST.
Referenced by cfg().
run()
bool_t xl::test::Unit::run ()
run cases
{
    // temp dir
    std::ctstring_t tempDirPath = Path::exe().dir() + Const::slash() + _option.name;
    cbool_t isRandomPostfix {true};
    cbool_t isAutoDelete    {true};
    DirTemp dirTemp(tempDirPath, isRandomPostfix, isAutoDelete);
    dirTemp.create();
    _option.tempDirPath = dirTemp.dir().str();
    // run unit
    bool_t isPassed {true};
    bool_t bRv {};
    for (std::size_t i = 0; i < _option.unitLoops; ++ i) {
        try {
            bRv = unit();
            xCHECK_DO(!bRv, isPassed = false);
        }
        catch (const Exception &a_xlibException) {
            xTEST_FAIL_MSG(_option.name + xT(": ") + a_xlibException.what());
            bRv = false;
        }
        catch (const std::exception &a_stdException) {
            std::cstring_t msg = a_stdException.what();
            xTEST_FAIL_MSG(_option.name + xT(": ") + xA2T(msg));
            bRv = false;
        }
        catch (...) {
            xTEST_FAIL_MSG(_option.name + xT(": Unknown error"));
            bRv = false;
        }
        xCHECK_DO(!bRv, isPassed = false);
    } // for (_option.unitLoops)
    return isPassed;
}
References xl::fs::DirTemp::create(), xl::fs::DirTemp::dir(), xl::fs::Path::dir(), xl::fs::Path::exe(), xl::test::UnitOption::name, xl::core::Const::slash(), xl::fs::Dir::str(), xl::test::UnitOption::tempDirPath, unit(), xl::test::UnitOption::unitLoops, xl::debug::Exception::what(), xA2T, xCHECK_DO, xT, and xTEST_FAIL_MSG.
unit()
bool_t xl::test::Unit::unit () pure virtual
unit
Sample
xTEST_CASE("CaseName")
{
    std::ctstring_t testData[][2]
    {
        {xT("TEST_STRING_1"), xT("MUST_BE_1")},
        {xT("TEST_STRING_2"), xT("MUST_BE_2")},
        {xT("TEST_STRING_3"), xT("MUST_BE_3")},
        {xT("TEST_STRING_4"), xT("MUST_BE_4")}
    };
    for (size_t i = 0; i < xARRAY_SIZE(testData); ++ i) {
    }
}
{
   /**
    * Sample
    *
    * \code{.cpp}
    * xTEST_CASE("CaseName")
    * {
    *     std::ctstring_t testData[][2]
    *     {
    *         {xT("TEST_STRING_1"), xT("MUST_BE_1")},
    *         {xT("TEST_STRING_2"), xT("MUST_BE_2")},
    *         {xT("TEST_STRING_3"), xT("MUST_BE_3")},
    *         {xT("TEST_STRING_4"), xT("MUST_BE_4")}
    *     };
    *
    *     for (size_t i = 0; i < xARRAY_SIZE(testData); ++ i) {
    *
    *     }
    * }
    * \endcode
    */
    return true;
}
Referenced by run().
Member Data Documentation
m_pvRv
void_t* xl::test::Unit::m_pvRv {}
{};
m_chRv
tchar_t xl::test::Unit::m_chRv {}
{};
m_ucRv
uchar_t xl::test::Unit::m_ucRv {}
{};
m_bRv
bool_t xl::test::Unit::m_bRv {}
{};
m_iRv
int_t xl::test::Unit::m_iRv {}
{};
m_siRv
short_t xl::test::Unit::m_siRv {}
{};
m_usiRv
ushort_t xl::test::Unit::m_usiRv {}
{};
m_uiRv
uint_t xl::test::Unit::m_uiRv {}
{};
m_stRv
std::size_t xl::test::Unit::m_stRv {}
{};
m_sstRv
std::ssize_t xl::test::Unit::m_sstRv {}
{};
m_liRv
long_t xl::test::Unit::m_liRv {}
{};
m_ulRv
ulong_t xl::test::Unit::m_ulRv {}
{};
m_llRv
longlong_t xl::test::Unit::m_llRv {}
{};
m_ullRv
ulonglong_t xl::test::Unit::m_ullRv {}
{};
m_fRv
float_t xl::test::Unit::m_fRv {}
{};
m_dRv
double_t xl::test::Unit::m_dRv {}
{};
m_ldRv
longdouble_t xl::test::Unit::m_ldRv {}
{};
m_sRv
std::tstring_t xl::test::Unit::m_sRv
m_usRv
std::ustring_t xl::test::Unit::m_usRv
m_vchRv
std::vec_tchar_t xl::test::Unit::m_vchRv
m_vsRv
std::vec_tstring_t xl::test::Unit::m_vsRv
m_msRv
std::map_tstring_t xl::test::Unit::m_msRv
m_mmsRv
std::mmap_tstring_t xl::test::Unit::m_mmsRv
m_unmsRv
std::unmap_tstring_t xl::test::Unit::m_unmsRv
m_hRv
native_handle_t xl::test::Unit::m_hRv {}
{};
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Test/Unit.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Test/Unit.cpp