xLib: xl::system::info::PowerSupply Class Reference
xl::system::info::PowerSupply Class Reference
Power supply information.
#include "PowerSupply.h"
Public Types
enum class Status {
Unknown = 0 ,
Discharging = 1 ,
Charging = 2 ,
Full = 3
}
Status.
Public Member Functions
bool_t isExists () const
Check existance.
std::size_t level () const
get level (pct)
Status status () const
get status
ctors, dtor
PowerSupply ()=default
virtual ~PowerSupply ()=default
xNO_COPY_ASSIGN (PowerSupply)
Detailed Description
Power supply information.
Member Enumeration Documentation
Status
enum class xl::system::info::PowerSupply::Status strong
Status.
Enumerator
Unknown
Unknown.
Discharging
Discharging.
Charging
Charging.
Full
Full.
    {
        Unknown     = 0, ///< Unknown
        Discharging = 1, ///< Discharging
        Charging    = 2, ///< Charging
        Full        = 3  ///< Full
    };
Constructor & Destructor Documentation
PowerSupply()
xl::system::info::PowerSupply::PowerSupply () default
~PowerSupply()
virtual xl::system::info::PowerSupply::~PowerSupply () virtual default
Member Function Documentation
xNO_COPY_ASSIGN()
xl::system::info::PowerSupply::xNO_COPY_ASSIGN (PowerSupply)
isExists()
bool_t xl::system::info::PowerSupply::isExists () const
Check existance.
{
    return _isExists_impl();
}
Referenced by level(), and status().
level()
std::size_t xl::system::info::PowerSupply::level () const
get level (pct)
{
    xCHECK_RET(!isExists(), 0);
    return _level_impl();
}
References isExists(), and xCHECK_RET.
status()
PowerSupply::Status xl::system::info::PowerSupply::status () const
get status
{
    xCHECK_RET(!isExists(), Status::Unknown);
    return _status_impl();
}
References isExists(), Unknown, and xCHECK_RET.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Info/PowerSupply.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/System/Info/PowerSupply.cpp