xLib: xl::fs::FileText Class Reference
xl::fs::FileText Class Reference
Text file.
#include "FileText.h"
Public Member Functions
void_t read (std::tstring_t *content) const
void_t read (std::vec_tstring_t *content) const
void_t read (std::ctstring_t &separator, std::map_tstring_t *content) const
void_t write (std::ctstring_t &content, FileIO::cOpenMode mode) const
void_t write (std::cvec_tstring_t &content, FileIO::cOpenMode mode) const
void_t write (std::ctstring_t &separator, std::cmap_tstring_t &content, FileIO::cOpenMode mode) const
ctors, dtor
FileText (std::ctstring_t &filePath)
virtual ~FileText ()=default
xNO_DEFAULT_CONSTRUCT (FileText)
xNO_COPY_ASSIGN (FileText)
Detailed Description
Text file.
Constructor & Destructor Documentation
FileText()
xl::fs::FileText::FileText (std::ctstring_t & filePath) explicit
  :
    _filePath(a_filePath)
{
}
~FileText()
virtual xl::fs::FileText::~FileText () virtual default
Member Function Documentation
xNO_DEFAULT_CONSTRUCT()
xl::fs::FileText::xNO_DEFAULT_CONSTRUCT (FileText)
xNO_COPY_ASSIGN()
xl::fs::FileText::xNO_COPY_ASSIGN (FileText)
read() [1/3]
void_t xl::fs::FileText::read (std::tstring_t * content) const
{
    xTEST_PTR(a_content);
    a_content->clear();
    std::tstring_t sRv;
    FileIO file(_filePath);
    file.open(FileIO::OpenMode::BinReadOnly);
    clonglong_t fileSize = file.size();
    xTEST_DIFF(fileSize, static_cast<longlong_t>(FileIO::PointerPosition::Error));
    xCHECK_DO(fileSize == 0LL, a_content->clear(); return);
    sRv.resize( static_cast<size_t>(fileSize) );
    std::csize_t readLen = file.read((void_t *)&sRv.at(0), sRv.size());
    xTEST_EQ(readLen, sRv.size());
    // out
    a_content->swap(sRv);
}
References xl::fs::FileIO::BinReadOnly, xl::fs::FileIO::Error, xl::fs::FileIO::open(), xl::fs::FileIO::read(), xl::fs::FileIO::size(), xCHECK_DO, xTEST_DIFF, xTEST_EQ, and xTEST_PTR.
Referenced by xl::fs::Config::read(), and read().
read() [2/3]
void_t xl::fs::FileText::read (std::vec_tstring_t * content) const
{
    xTEST(FileInfo(_filePath).isExists());
    xTEST_PTR(a_content);
    a_content->clear();
    std::tstring_t content;
    read(&content);
    std::vec_tstring_t vsRv;
    String::split(content, Const::nl(), &vsRv);
    // out
    a_content->swap(vsRv);
}
References xl::core::Const::nl(), read(), xl::core::String::split(), xTEST, and xTEST_PTR.
read() [3/3]
void_t xl::fs::FileText::read (std::ctstring_t & separator, std::map_tstring_t * content) const
{
    xTEST(FileInfo(_filePath).isExists());
    xTEST_PTR(a_content);
    a_content->clear();
    // if file empty
    xCHECK_DO(FileInfo(_filePath).size() == 0L, a_content->clear(); return);
    std::locale::global( std::locale() );
    std::tifstream_t ifs(_filePath);
    xTEST(!! ifs);
    xTEST(!ifs.fail());
    xTEST(ifs.good());
    xTEST(ifs.is_open());
    xTEST(!ifs.eof());
    std::map_tstring_t msRv;
    std::tstring_t     line;
    std::vec_tstring_t lines;
    for (size_t i = 0; !ifs.eof(); ++ i) {
        std::getline(ifs, line);
        line = String::trimRightChars(line, Const::eol());
        if ( line.empty() ) {
            auto prRv = msRv.insert( {Const::strEmpty(), Const::strEmpty()} );
            xTEST_NA(prRv);
        } else {
            String::split(line, a_separator, &lines);
            xTEST_EQ(lines.size(), size_t(2));
            auto prRv = msRv.insert( {lines.at(0), lines.at(1)} );
            xTEST_NA(prRv);
        }
    }
    // out
    a_content->swap(msRv);
#if xTODO
    bool_t             bRv {};
    std::map_tstring_t msRv;
    std::vec_tstring_t vsRv;
    bRv = textRead(filePath, &vsRv);
    xTEST(bRv);
    for (const auto it = vsRv.cbegin(); it != vsRv.cend(); ++ it) {
        std::vec_tstring_t lines;
        String::split(vsRv.at(0), separator, &lines);
        msRv.insert( {lines.at(0), lines.at(1)} );
    }
    // out
    content.swap(msRv);
#endif
}
References xl::core::Const::eol(), xl::core::String::split(), xl::core::Const::strEmpty(), xl::core::String::trimRightChars(), xCHECK_DO, xTEST, xTEST_EQ, xTEST_NA, and xTEST_PTR.
write() [1/3]
void_t xl::fs::FileText::write (std::ctstring_t & content, FileIO::cOpenMode mode) const
{
    xTEST_NA(a_content);
    xTEST_NA(a_mode);
    FileIO file(_filePath);
    file.open(a_mode);
    xCHECK_DO(a_content.empty(), return);
    std::csize_t writeLen = file.write((void_t *)&a_content.at(0), a_content.size());
    xTEST_EQ(writeLen, a_content.size());
}
References xl::fs::FileIO::open(), xl::fs::FileIO::write(), xCHECK_DO, xTEST_EQ, and xTEST_NA.
Referenced by xl::package::CsvWriter::saveFile(), xl::fs::Config::write(), and write().
write() [2/3]
void_t xl::fs::FileText::write (std::cvec_tstring_t & content, FileIO::cOpenMode mode) const
{
    xTEST_NA(a_content);
    xTEST_NA(a_mode);
    std::ctstring_t &content = String::join(a_content, Const::nl());
    write(content, a_mode);
}
References xl::core::String::join(), xl::core::Const::nl(), write(), and xTEST_NA.
write() [3/3]
void_t xl::fs::FileText::write (std::ctstring_t & separator, std::cmap_tstring_t & content, FileIO::cOpenMode mode) const
{
    xTEST(!_filePath.empty());
    xTEST(!a_separator.empty());
    xTEST_NA(a_content);
    xTEST_NA(a_mode);
    FileIO file(_filePath);
    file.open(a_mode);
    xCHECK_DO(a_content.empty(), return);
    for (const auto &[key, value] : a_content) {
        file.writeLine(key + a_separator + value);
    }
}
References xl::fs::FileIO::open(), xl::fs::FileIO::writeLine(), xCHECK_DO, xTEST, and xTEST_NA.
The documentation for this class was generated from the following files:
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileText.h
/home/runner/work/skynowa.github.io/skynowa.github.io/xLib/Include/xLib/Fs/FileText.cpp